### ISSUE TITLE
Open file doesn't work with Release 1.4 on Windows 10 1803

### ISSUE THREAD

**Issue by frederich** [WerWolv/ImHex#10]
The File Open dialog does not show up, no matter if ImHex was started as admin or normal user.

**Comment by WerWolv** [comment]
Hi. This bug was fixed after the release of 1.4 and will be in the next version. For now, the work around is to go under View and open the Hex View first. After that the Open File Dialog will show up.

**Comment by Kein** [comment]
Reproducible in 1.6.0
