### ISSUE TITLE
Issues with encoding/decoding columns.

### ISSUE THREAD

**Issue by paxcut** [WerWolv/ImHex#1005]
I am not sure if this should be filed under bugs or features request since i think it has a bit of both. I like the way we can choose special encodings on top of the standard ones but there  are some problems with their use and i think that addressing them  could improve user experience a little bit. I'll start by requesting a feature and end by exposing what i believe is a bug. 

Right now there are settings to turn on and off the two encoding/decoding columns. The problem with how it works is that if you turn off the standard decoding column and turn on the special decoding column it leaves a huge empty space between the data and the  column which cannot be filled. In this case I believe and request that the special decoding column should be moved to take the place of the standard.

Another problem is that the setting doesn't turn off the special column. If you import a special encoding and display it by checking the box in the settings  there is no way I can find to turn it off. I looked at the code and it seems to only check if a special encoding was chosen in order to decide if the special column should be displayed.  I think that clearing the checkbox i mentioned should also erase the column.

As a general rule one expects that upon starting the app the user interface looks like it did when you last exited and any feature that breaks this should be considered bogus. As it stands, the app seems to completely forget about which special encoding was selected when you exited the app, so if you are using the special column you have to reload it every time you start the app.

that's it. None of these issues is particularly important by itself, but taken as a whole they may turn some people off  and I like this app too much to let that happen.

**Comment by paxcut** [comment]
thank you for that. i tested it on my local build and now the the empty column is replaced by the custom column when it is turned off.
 There is still the issue with turning the custom encoding on and off using the checkbox under settings labeled

> Display the advanced decoding column

 which doesn't seem to work. Is the custom encoding not referring to  what is displayed in the advanced decoding column?

**Comment by WerWolv** [comment]
Sorry, I forgot to commit this. Everything should work now as expected :)

**Comment by paxcut** [comment]
it really does I tested both columns and either or and it all works well. Also the chosen custom encoding is remembered with the project which is fantastic.. To top it all my local builds seem to now update and run properly, I'm in Imhex bliss!
You help is very much appreciated.
