### ISSUE TITLE
[Bug] RISC-V missing from disassembler

### ISSUE THREAD

**Issue by gareth-anthony-hulse** [WerWolv/ImHex#1010]
### Operating System

Linux

### What's the issue you encountered?

RISC-V missing from disassembler when upgrading from version 2.7.1.

### How can the issue be reproduced?

Upgrade to 2.8.0, go to Disassembler->Settings->Architecture. RISC-V isn't there.

### ImHex Version

2.8.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Arch Linux yay package manager and AppImage

### Additional context?

**Specs:** https://linux-hardware.org/?probe=b5740f3323

**Comment by WerWolv** [comment]
Thanks for the report! Capstone 5 features have accidentially been disabled even if ImHex was compiled with Capstone 5. The latest commit should correct this.

**Comment by gareth-anthony-hulse** [comment]
doesn't work with compressed instructions:
![Screenshot_20230405_002916](https://user-images.githubusercontent.com/107568353/229944447-97892737-8710-44fb-a3ef-b7cdf46e1c2c.png)

in 2.7.1:
![Screenshot_20230405_003024](https://user-images.githubusercontent.com/107568353/229944593-c67ba442-6411-460e-a954-a5b56182abeb.png)

**Comment by gareth-anthony-hulse** [comment]
Thanks for the fast response so far. Didn't expect to get help so quickly.

**Comment by WerWolv** [comment]
Should be fixed now. The names in the list were switched around

**Comment by gareth-anthony-hulse** [comment]
Now when I press Disassemble, nothing appears in the disassembly table:
![Screenshot_20230405_113055](https://user-images.githubusercontent.com/107568353/230056167-cd77ec45-906a-4c96-ac67-8178bac6aa87.png)

Other architectures work without issue as far I can tell. Tried with a random ELF file:
![Screenshot_20230405_113800](https://user-images.githubusercontent.com/107568353/230057453-1f1e7c6d-3adf-4165-a6b8-a1fb3daea9cd.png)

**Comment by WerWolv** [comment]
God damn I completely messed this up. Latest commit should now actually correct this all. Thank you!

**Comment by gareth-anthony-hulse** [comment]
Working now, thanks.
