### ISSUE TITLE
[Bug] Pattern files missing one line when multifile  project is loaded

### ISSUE THREAD

**Issue by paxcut** [WerWolv/ImHex#1012]
### Operating System

Windows

### What's the issue you encountered?

If there are multiple files with multiple patterns in a project the patterns will be missing one line when project is saved and loaded.

### How can the issue be reproduced?

1) Start imhex   and from the test>pattern>test data folder load bmp.hexpat.bmp. When imhex asks if you want to load and run the bmp pattern click yes.
2) From same folder open json.hexpat.bin a second copy of the bmp pattern should be loaded along with the input file.
3) Save project and call it test. Quit imhex.
4) start imhex and load the project called test. When imhex asks if you want to load and run the bmp pattern say yes. Once pattern has run switch to the .bin input and scroll to the end of the patter file. Note that on the first pattern file the last line is a blank line and in the second pattern file the line is missing.

5) repeat above steps to see more lines deleted. If project fails to load or save try once again and it should work.

### ImHex Version

1.28.0

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

msi

**Comment by paxcut** [comment]
Additional information.

I looked a bit into this problem and I learned that the project file is a tarred file of all the files that make up the project with a different extension. if i create a copy of a project file and make its extension tar, I can use winrar or any tar compatible extractor and extract all the files. When I do that the pattern files inside the project are not truncated, they are not missing any lines which leads me to believe that the problem must occur after imhex untars the project files. If the untar process was incorrect  then there would be problems with all the files stored and right now it seems only pattern files are affected.

**Comment by paxcut** [comment]
The observed behavior was created by this line of code (line 807 of view_pattern_editor.cpp)
```cpp
             lines.pop_back();
  ```
  Removing this line fixes the problem. if you prefer to use pull requests in cases like this I'll happily submit one for review. If  you prefer to make the changes yourself let me know and I wont submit anything.

**Comment by WerWolv** [comment]
I can do it real quick, sorry I completely missed this issue

**Comment by paxcut** [comment]
dont apologize. you do great work and this kind of thing has to be low priority.
