### ISSUE TITLE
[Bug] Windows Pattern - Closing Application

### ISSUE THREAD

**Issue by ArtVandelayExpImp** [WerWolv/ImHex#1013]
### Operating System

Windows

### What's the issue you encountered?

Application will be promptly closed after the import of an custom pattern, when this pattern is placed by right mouse click > Place pattern > Custom Type > PATTERN_STRUCT_DESC

Happens also on the portable Non-GPU Version.

Tested on 2 Windows-PC.

### How can the issue be reproduced?

Load a pattern, place them and then, the app is closing with no further messages.

### ImHex Version

1.28.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI / WinGet

### Additional context?

Windows 10 / 21H2 / Build 19044.2728

**Comment by WerWolv** [comment]
Thanks for the report! Latest commit fixes this
