### ISSUE TITLE
[Bug] Crash on selection place pattern

### ISSUE THREAD

**Issue by lrademacher** [WerWolv/ImHex#1016]
### Operating System

Windows

### What's the issue you encountered?

When using right-click on a selection and selecting "Place pattern... -> Built-in Type -> Single -> u32", the application immediately crashes. This seems to apply to all types (also for Single/Array) and for all kinds of selected bytes.

### How can the issue be reproduced?

1. selecting a range of bytes. E.g.:
00 00 00 00
2. right click and selecting "Place pattern... -> Built-in Type -> Single -> u32"

### ImHex Version

1.28.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by WerWolv** [comment]
Thanks for the report! This has been fixed a few commits ago, check #1013
