### ISSUE TITLE
[Bug] Colours Missing

### ISSUE THREAD

**Issue by reben-f5** [WerWolv/ImHex#1017]
### Operating System

Windows

### What's the issue you encountered?

I can't see colours to highlight information like the image you published it. Can you please provide the instruction on how to add colours into section of information, or should I expected by default, or even a particular type of installer will do?

### How can the issue be reproduced?

n/a

### ImHex Version

1.28.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

imhex-1.28.0-Windows-Portable-NoGPU-x86_64

**Comment by WerWolv** [comment]
Hey
The colorful highlighting is provided by the patterns written in the pattern language. Basically a set of rules that tells ImHex how to highlight and decode the binary data you loaded. There are pre-made patterns available for many common file types, most of these are also bundled into the release builds.
The easiest way to test this is by loading e.g a PNG file into ImHex and then going to `File -> Import... -> Pattern` and choose the `png.hexpat` file there. That will highlight the content of your file.
Alternatively if there isn't a pattern available for your file type yet, you can write your own through the Pattern Editor view (you can open it through the `View` menu if it's not already open). To learn more about how to do that, you can consult the documentation: https://docs.werwolv.net

**Comment by reben-f5** [comment]
Thanks SO much for your time for providing those examples were very helpful !!! 
Now I can locate them easily and apply them based on the file types.
