### ISSUE TITLE
[Bug] Custom patterns from content store not working

### ISSUE THREAD

**Issue by gareth-anthony-hulse** [WerWolv/ImHex#1019]
### Operating System

Linux

### What's the issue you encountered?

Patterns from the content store do not appear in ImHex:
![Screenshot_20230406_204434](https://user-images.githubusercontent.com/107568353/230481249-ca01ad5b-4571-4f01-90d2-f6b76c2ce05c.png)

### How can the issue be reproduced?

Download patterns such as Elf, Intel Hex,  Flac, Uefi, etc. from the content store. Next, right click somewhere in the hex editor view. Then, goto: Place pattern... -> Custom Type. You will see that it is empty.

### ImHex Version

248b93f41a66d055b830ae3f68959a38eea19610

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Git

### Additional context?

**Specs:** https://linux-hardware.org/?probe=a0584206ea

**Comment by WerWolv** [comment]
Hey
I think this might be a misunderstanding of how this feature works. The Custom Types field only lists types that have been parsed from the pattern editor view. So any types you defined yourself or types that you included using `#include`. It does now however list any of the types that are simply available in the libraries but haven't been included.
I agree however that the UX is a bit weird and the menu item should just be disabled if there's no types to place in it.

**Comment by WerWolv** [comment]
Latest commit now makes sure that this menu item correctly gets disabled

**Comment by gareth-anthony-hulse** [comment]
I figured out how to use the patterns. Went to the pattern editor and typed in `#include <elf.hexpat>`, ticked 'Auto evaluate' at the bottom of the view and everything appears to be working. I was thinking you could just right click and add the 3rd party patterns. Had to look in `$XDG_DATA_HOME/imhex/patterns/` to get the file names to include as there is no suggestions or auto completion.
