### ISSUE TITLE
[Bug] The topmost row of pixels does nothing rather than activating menu

### ISSUE THREAD

**Issue by Mercury13** [WerWolv/ImHex#1020]
### Operating System

Windows

### What's the issue you encountered?

Remember Fitts’ law? Edge pixels are an area of infinite size.

### How can the issue be reproduced?

1. Maximize window.
2. Move mouse to the top of the screen, just above menu.
3. Click.

SHOULD: activate menu
NOW: does nothing. Moreover, double click restores window.

### ImHex Version

1.28.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by WerWolv** [comment]
Thanks for the report! I think this might actually be an ImGui issue. I was able to work around it partially so I hope this is alright for now. I think you should report this to the main ImGui repository
