### ISSUE TITLE
build failed on osx 

### ISSUE THREAD

**Issue by newlife** [WerWolv/ImHex#103]
`
/Users/nnnn/ImHex/source/views/view_help.cpp:32:60: error: use of undeclared identifier 'IMHEX_VERSION'
            ImGui::Text("ImHex Hex Editor v%s by WerWolv", IMHEX_VERSION);`

any help is appreciate

**Comment by NicholeMattera** [comment]
Make sure to specify a build type when building: `cmake -DCMAKE_BUILD_TYPE=Release`

**Comment by newlife** [comment]
Thanks , It works!!!!

maybe we can add this to readme ,I didnot find this at first

**Comment by Thog** [comment]
> 
> 
> Thanks , It works!!!!
> 
> maybe we can add this to readme ,I didnot find this at first

Going to do that later yeah, @WerWolv changed some stuffs some days ago, sorry about that ^^'
