### ISSUE TITLE
[Bug] Only one color in hex editor for a bitfield composed of an array of other bitfields

### ISSUE THREAD

**Issue by tushkanchik239** [WerWolv/ImHex#1030]
### Operating System

Windows

### What's the issue you encountered?

When pattern is a bitfield composed of an array of other bitfields highlighting works incorrectly: in "Pattern Data" all fields have different colors, but in hex editor whole the outer-most bitfield (all small fields of all array elements) have the same color. Moreover, all hints in hex editor show the whole bitfield array instead of small fields (a struct composed of an array of structs works correctly). If I use the same array of bitfields directly (without outer bitfield), I have all the colors different both in "Pattern Data" and in hex editor and hints work correctly. But there is another issue: in "Pattern Data" both this configurations have the same values and the same "Offset", but different "Size" (size of an array is greater). I don't completely understand, how alignment rules apply to an array of bitfields without outer bitfield (is there any difference or not), but here we have inconsistency: data and offset are the same, but total size differs.   

![bitfield_bug](https://user-images.githubusercontent.com/70626668/231474952-5dd54a03-91d3-4a6f-9529-888dbe1d244d.jpg)

### How can the issue be reproduced?

[bitfield_bug.txt](https://github.com/WerWolv/ImHex/files/11212018/bitfield_bug.txt)

### ImHex Version

1.28.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by WerWolv** [comment]
Thanks for the report! The latest commit should fix this issue
