### ISSUE TITLE
[Bug] Elements of bitfield array are not ordered in "Pattern Data" when array size is 100.

### ISSUE THREAD

**Issue by tushkanchik239** [WerWolv/ImHex#1037]
### Operating System

Windows

### What's the issue you encountered?

When pattern is a bitfield composed of an array of other bitfields and array size is 100 (for 10 elements it works correctly) in "Pattern Data" array elements are not ordered.

![bitfield_order_bug](https://user-images.githubusercontent.com/70626668/233152399-47208779-45be-4fd7-8121-bda23c0eed83.jpg)

### How can the issue be reproduced?

bitfield bf
{
    b1 : 11;
    b2 : 21;
    b3 : 31;
};

bitfield abf
{
    bf vals[100];
};

abf a @ 0;

### ImHex Version

bb8b4af

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

built using msys

**Comment by WerWolv** [comment]
Hey
It looks like you accidentally clicked on the "Color" column so now it's sorting all these fields by color (indicated by the small triangle next to the column header). Try clicking on the "Offset" column to sort it by offsets, that's probably what you want

**Comment by tushkanchik239** [comment]
Yes, it works! Thanks a lot. But now I wonder why it looks like all "bits" in "Offset" fields are modulo 317?

![bitfield_bits_bug](https://user-images.githubusercontent.com/70626668/233307021-2fed1023-efc3-44ae-b89b-ba68f222749f.jpg)

**Comment by WerWolv** [comment]
It was modulo 256 actually due to an overflow. Latest commit should fix it
