### ISSUE TITLE
[Bug] Failed to run Imhex on Arch Linux

### ISSUE THREAD

**Issue by Integral-Tech** [WerWolv/ImHex#1039]
### Operating System

Linux

### What's the issue you encountered?

After the recent upgrade of the "yara" package on Arch Linux, Imhex failed to run:
```
imhex: error while loading shared libraries: libyara.so.9: cannot open shared object file: No such file or directory
```

### How can the issue be reproduced?

Upgrade Arch Linux to the latest, then run Imhex.

### ImHex Version

1.28.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Arch Linux packag (*.tar.zst)

**Comment by folfgirl** [comment]
I also just got this now, I have the libyara.so.10 instead of libyara.so.9 
![2023-04-20_22-22](https://user-images.githubusercontent.com/79891947/233533411-cc3e4448-e7cc-460a-91aa-54cb660d0550.png)

**Comment by folfgirl** [comment]
I am assuming you're using arch.

**Comment by Integral-Tech** [comment]
> I also just got this now, I have the libyara.so.10 instead of libyara.so.9 ![2023-04-20_22-22](https://user-images.githubusercontent.com/79891947/233533411-cc3e4448-e7cc-460a-91aa-54cb660d0550.png)

archlinuxcn/imhex works for me now.

**Comment by folfgirl** [comment]
could you elaborate more mine is still not working?

**Comment by Integral-Tech** [comment]
> could you elaborate more mine is still not working?

Have you added the archlinuxcn repository to /etc/pacman.conf?

**Comment by folfgirl** [comment]
oh I have a better solution  aur/imhex compile it, it work too I also don't trust archlinuxcn but that is me.

**Comment by folfgirl** [comment]
I am assuming that aur/imhex-bin is compiled with libyara.so.9 and not  libyara.so.10 so using aur/imhex just compiles imhex and I compile it with  libyara.so.10 so that is my fix.

**Comment by WerWolv** [comment]
Yeah if your distro uses non-archlinux repositories things will probably not work well. Installing imhex-bin or imhex-git from the AUR should generally work though. Those packages are also maintained by us

**Comment by folfgirl** [comment]
aur/imhex-git is version 1.25.0 not 1.28.0 whitch aur/imhex is 1.28.0 just like aur/imhex-bin just not compiled yet.

**Comment by Necklaces** [comment]
@WerWolv I'm experiencing this same bug on plain Arch with [imhex-bin](https://aur.archlinux.org/packages/imhex-bin) installed (version 1.28.0-1):

```
imhex: error while loading shared libraries: libyara.so.9: cannot open shared object file: No such file or directory
```

To fix it, either a new build for Archlinux with libyara.so.10 has to be built, or the existing one has to be patched with something like patchelf (could be done in the PKGBUILD).

As it stands now, the `imhex-bin` AUR package is broken.

**Comment by WerWolv** [comment]
@Necklaces We're aware of the issue yeah, thanks. @iTrooz who maintains the AUR package will upload a recompiled version of the release soon

**Comment by iTrooz** [comment]
Actually, I updated the package like 10 seconds ago ! :D `imhex-bin` should be working now

**Comment by folfgirl** [comment]
I am still getting the error.

**Comment by Necklaces** [comment]
@folfgirl - Unfortunately @iTrooz forgot to increase the `pkgrel` variable when updating, so you have to uninstall the package and also remove it from any caches (depends on your AUR helper, mine was also in /var/cache/pacman/pkg/).

**Comment by iTrooz** [comment]
Oops, fixed it

**Comment by folfgirl** [comment]
thanks
