### ISSUE TITLE
Build on MAC OSX11.1 Big Sur have error

### ISSUE THREAD

**Issue by LeeHDsniper** [WerWolv/ImHex#104]
I have got this：

`
/usr/local/Cellar/cmake/3.19.2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a1288.dir/link.txt --verbose=1
    /usr/local/opt/llvm/bin/clang  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_a1288.dir/testCCompiler.c.o -o cmTC_a1288 
    ld: library not found for -lSystem
    clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_a1288] Error 1
    make: *** [cmTC_a1288/fast] Error 2
`
<img width="906" alt="image" src="https://user-images.githubusercontent.com/13035589/103118144-85501480-46a8-11eb-8cbd-7a0f6a75c297.png">

**Comment by WerWolv** [comment]
Looks like something's wrong as well with your setup. It can't find some "System" library which it needs. Make sure you have a proper compile evironment working before trying to compile ImHex

**Comment by LeeHDsniper** [comment]
OK,I find something interesting.
This is my Macbook info:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/13035589/103258094-c741c900-49ce-11eb-8aa4-fd6e1f4a31e7.png">
To build imhex successfully,I did some operation below:
1. DO NOT INSTALL llvm,if you do,uninstall it.
2. INSTALL pkg-config by homebrew.
3. use this `CC=/usr/local/bin/gcc-10 CXX=/usr/local/bin/g++-10 PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig":"$(brew --prefix)/lib/pkgconfig" cmake   ..` to build
Finally,I got a executable file,BUT,it Look wired ,the same as #93 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/13035589/103258373-a4fc7b00-49cf-11eb-86bf-30a8c4f3c63b.png">

**Comment by Dids** [comment]
This actually seems to happen on a fresh install of macOS Big Sur and Xcode, but only when trying to compile with LLVM from Homebrew. Additionally, the `brew bundle` step could technically install newer and incompatible versions of dependencies, including LLVM, since no specific version is specified (and brew's version support is a bit messy).

I'll keep digging, but this definitely seems to require a very specific environment, which I haven't been able to reproduce on new, fresh installs.

**Comment by LeeHDsniper** [comment]
Exactly right！
I builded it on a fresh install of macOS BigSur and didn't install Xcode(Although it didn't work after installing Xcode).
This is content of build/CMakeFiles/CMakeError.log:
···
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/local/bin/gcc-10 
Build flags: 
Id flags:  

The output was:
1
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/local/bin/g++-10 
Build flags: 
Id flags:  

The output was:
1
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
···

**Comment by Dids** [comment]
Another quick update on this. Less than a month ago, the brew formula for `llvm` was updated from v10 to v11, and for some reason they no longer supply a symlink or binary called `clang`, but instead append the version to it, so it's `$(brew --prefix llvm)/bin/clang-11`. Big Sur and Xcode (or command line utilities) ship with Apple's fork of LLVM 12.

This only fixes a part of the problem however, as by default, CMake still can't find the correct macOS libraries/frameworks. Still working on that, so might have an update on that soon.
