### ISSUE TITLE
[Bug] Cannot launch ImHex-1.28.0 due to mbedtls lookup errors

### ISSUE THREAD

**Issue by xoores** [WerWolv/ImHex#1044]
### Operating System

Linux

### What's the issue you encountered?

ImHex is using (probably deprecated) functions from mbedtls:
`imhex: symbol lookup error: imhex: undefined symbol: mbedtls_md4_ret`

See: https://github.com/Mbed-TLS/mbedtls/issues/4280

### How can the issue be reproduced?

Run imhex on a system with new mbedtls (net-libs/mbedtls-2.28.1)

### ImHex Version

1.28.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

DEB

**Comment by WerWolv** [comment]
Hm interesting. Those functions are only used by libcurl where we use the latest release. 
What Linux distro are you using? The .deb file we provide exklusively supports Ubuntu 22.04, everything else will not work due to similar version issues.

**Comment by xoores** [comment]
Gentoo - I grabbed the *.deb because I initially tried to create an ebuild for imhex but unfortunately it tries to pull something from GIT during build 🤷 That fails due to the Gentoo system creating no-network sandbox for building.

After that I opted out for creating a "bin" ebuild (for pre-built package). Should I rather use RPM for this?

**Comment by WerWolv** [comment]
The RPMs are for various versions of Fedora and Red Hat so they will probably not work for you either.

You can try making an ebuild again though but with the `IMHEX_OFFLINE_BUILD` cmake option set to ON. That will disable all network access during the build process.
Alternatively the AppImage and Flatpak version of ImHex should generally run on all platforms.

**Comment by xoores** [comment]
As long as Fedora/RH uses (relatively) recent packages, it may just work. But of course it's not the best solution.

Neat, I will try that and report back 🙂 I tried to extract some variables and look for configuring cmake but I failed miserably 😁

**Comment by xoores** [comment]
Worked like a charm!

This can be closed, attached is an ebuild file for the most recent version (original from GURU overlay, tweaked so it can be compiled). Just remove the .txt - added because GitHub would not allow me to upload .ebuild directly 🙂 This ebuild should work as long as you keep naming schemes intact by simply renaming it to correct version. 

[imhex-1.28.0.ebuild.txt](https://github.com/WerWolv/ImHex/files/11302235/imhex-1.28.0.ebuild.txt)

Thanks for your quick reaction!
Jan
