### ISSUE TITLE
CMake Error:

### ISSUE THREAD

**Issue by melonwool** [WerWolv/ImHex#105]
system: macOS bigsur

CMake Error at /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/CMakeDetermineCCompiler.cmake:49 (message):
  Could not find compiler set in environment variable CC:

  /usr/local/Cellar/llvm/10.0.1_2/bin/clang.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by WerWolv** [comment]
Looks like something's wrong with your build environment. It can't even find your compilers. Make sure you got everything installed properly
