### ISSUE TITLE
[Bug] Hex editor doesn't update and other odd behaviour when file is modified externally

### ISSUE THREAD

**Issue by gareth-anthony-hulse** [WerWolv/ImHex#1058]
### Operating System

Linux

### What's the issue you encountered?

The hex editor doesn't show any change when the current open file is modified by an external application, such as an assembler or another editor.

With the disassembler it gets a bit odd. Only tested it with the RISC-V architecture: on first the run after a external modification it shows the change in the disassembly table. Running the disassembler again after that gives inconsistent results: it will not always show the most recent change and may instead present with previous alterations, the original unmodified data or show no change at all.

### How can the issue be reproduced?

**Hex editor:** Modify the file externally with another application, while it is open in Imhex.

**Disassembler:** The bug is most obvious when rapidly pressing the disassemble button with a file that has been externally modified multiple times while it is open in ImHex.

### ImHex Version

https://github.com/WerWolv/ImHex/commit/5680b90549dc940772daf3d31c72afd62f28b38f

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Git

### Additional context?

https://linux-hardware.org/?probe=64aa7fb49b

**Comment by iTrooz** [comment]
(Can confirm this issue)

**Comment by paxcut** [comment]
If this gets resolved maybe also close the two other issues that mention problems with files modified externally. #947 and #498 ( the second  is a feature request about detecting files modified externally).
