### ISSUE TITLE
[Bug] Build fails with clang 16 and gcc 12.2 on Mingw

### ISSUE THREAD

**Issue by roflcopter4** [WerWolv/ImHex#1063]
### Operating System

Windows

### What's the issue you encountered?

Clang 16 fails in a couple of places, some of which could have been in third party libraries. I didn't record which after seeing previous issues in which the developers indicated they don't intend to write portable code. I recall that one file used the C++ 23 feature `std::unexpected`, which is hidden behind an ifdef in GNU libstdc++ that happens to exclude clang. The build also fails if compiled with LLVM libc++. At least one file fails to include mandatory headers which just happen to be included in other headers in GNU libstdc++, but such inclusion is non-standard (namely <iterator>). The code also uses `std::jthread` which is not implemented in libc++ yet. This is the case for the most recent release of that library rather than an outdated one as stated by the developers elsewhere.

Additionally the CMake files add various compiler flags which clang does not support, failing the build instantly. At least these are an easy fix. Unfortunately, it does imply that the developers are apparently not aware of which flags are compiler specific.

GCC comes closer to success, but the very same flags that cause clang to fail trip it up too. The warning `stringop-overflow` is triggered 12 times when compiling libimhex with LTO enabled. Because `-Werror` is also enabled, this fails the build. Or, that would be the case if not for the fact that linking the library fails instantly because someone hard-coded the library `dl` to be linked as well. This library does not exist outside of glibc on Linux.

Edited: Slightly less rude.

### How can the issue be reproduced?

Build with clang or GCC on Mingw64, on Windows. GCC build with the `-flto` compiler flag.

### ImHex Version

5a6e5d22557715d1207599b727b1555fea2f161d

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

source

### Additional context?

<details>
<summary>GCC error report</summary>
Some leading paths removed.

```
In member function 'load',
    inlined from '__conv_op ' at <atomic>:87:26,
    inlined from 'isFinished' at ImHex/lib/libimhex/source/api/task.cpp:75:22,
    inlined from 'isRunning' at ImHex/lib/libimhex/source/api/task.cpp:133:33,
    inlined from 'isRunning' at ImHex/lib/libimhex/source/api/task.cpp:128:10:
<bits/atomic_base.h>:488:31: error: '__atomic_load_1' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  488 |         return __atomic_load_n(&_M_i, int(__m));
      |                               ^
<bits/atomic_base.h>:488:31: error: '__atomic_load_1' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
In member function 'load',
    inlined from '__conv_op ' at <atomic>:87:26,
    inlined from 'hadException' at ImHex/lib/libimhex/source/api/task.cpp:79:22,
    inlined from 'hadException' at ImHex/lib/libimhex/source/api/task.cpp:141:35,
    inlined from 'hadException' at ImHex/lib/libimhex/source/api/task.cpp:136:10:
<bits/atomic_base.h>:488:31: error: '__atomic_load_1' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  488 |         return __atomic_load_n(&_M_i, int(__m));
      |                               ^
<bits/atomic_base.h>:488:31: error: '__atomic_load_1' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
In member function 'load',
    inlined from '__conv_op ' at <atomic>:87:26,
    inlined from 'shouldInterrupt' at ImHex/lib/libimhex/source/api/task.cpp:83:22,
    inlined from 'shouldInterrupt' at ImHex/lib/libimhex/source/api/task.cpp:149:38,
    inlined from 'shouldInterrupt' at ImHex/lib/libimhex/source/api/task.cpp:144:10:
<bits/atomic_base.h>:488:31: error: '__atomic_load_1' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  488 |         return __atomic_load_n(&_M_i, int(__m));
      |                               ^
<bits/atomic_base.h>:488:31: error: '__atomic_load_1' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
In member function 'load',
    inlined from '__conv_op ' at <atomic>:87:26,
    inlined from 'wasInterrupted' at ImHex/lib/libimhex/source/api/task.cpp:87:22,
    inlined from 'wasInterrupted' at ImHex/lib/libimhex/source/api/task.cpp:157:37,
    inlined from 'wasInterrupted' at ImHex/lib/libimhex/source/api/task.cpp:152:10:
<bits/atomic_base.h>:488:31: error: '__atomic_load_1' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  488 |         return __atomic_load_n(&_M_i, int(__m));
      |                               ^
<bits/atomic_base.h>:488:31: error: '__atomic_load_1' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
In member function 'store',
    inlined from 'operator=' at <bits/atomic_base.h>:356:7,
    inlined from 'operator=' at <atomic>:80:31,
    inlined from 'interrupt' at ImHex/lib/libimhex/source/api/task.cpp:60:33,
    inlined from 'interrupt' at ImHex/lib/libimhex/source/api/task.cpp:165:24:
<bits/atomic_base.h>:464:25: error: '__atomic_store_1' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  464 |         __atomic_store_n(&_M_i, __i, int(__m));
      |                         ^
<bits/atomic_base.h>:464:25: error: '__atomic_store_1' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
In member function 'load',
    inlined from '__conv_op ' at <bits/atomic_base.h>:348:20,
    inlined from 'getValue' at ImHex/lib/libimhex/source/api/task.cpp:105:22,
    inlined from 'getProgress' at ImHex/lib/libimhex/source/api/task.cpp:173:37,
    inlined from 'getProgress' at ImHex/lib/libimhex/source/api/task.cpp:168:9:
<bits/atomic_base.h>:488:31: error: '__atomic_load_8' writing 8 bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  488 |         return __atomic_load_n(&_M_i, int(__m));
      |                               ^
In member function 'load',
    inlined from '__conv_op ' at <bits/atomic_base.h>:348:20,
    inlined from 'getMaxValue' at ImHex/lib/libimhex/source/api/task.cpp:109:22,
    inlined from 'getProgress' at ImHex/lib/libimhex/source/api/task.cpp:173:66,
    inlined from 'getProgress' at ImHex/lib/libimhex/source/api/task.cpp:168:9:
<bits/atomic_base.h>:488:31: error: '__atomic_load_8' writing 8 bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  488 |         return __atomic_load_n(&_M_i, int(__m));
```

</details>

**Comment by WerWolv** [comment]
Hey, I can't speak about clang really as I haven't used it in a while but I've been compiling ImHex using GCC 12.2 just fine and recently upgraded to GCC 13.1.

> don't intend to write portable code
All of my code is compiled with `-Wall -Wextra -Wpedantic -Werror`. That's pretty much as portable as you'll get it.

> stringop-overflow
This warning is explicitly disabled in the cmake script because it causes tons of false positives (or I'm too stupid to figure out where the problem lies). I spent many hours trying to fix these warnings when they got introduced into GCC but couldn't, they basically always pointed at code somewhere in the standard library.

> LTO
Does it build for you without LTO? LTO had issues for me in the past too but because of other reasons. I wouldn't be surprised if things were still broken there as it obviously ignores set compiler flags.

**Comment by iTrooz** [comment]
Hey, I think WerWolv's explanations are enough to close this issue, feel free to ping me if there's anything else wrong
