### ISSUE TITLE
[Bug] In the popup, elements of bitfield are not shown as defined order in the pattern

### ISSUE THREAD

**Issue by SundaresanSelvaraj** [WerWolv/ImHex#1069]
### Operating System

Windows

### What's the issue you encountered?

In the popup, elements of bitfield are shown in a different order than the defined order in the pattern

### How can the issue be reproduced?

Add bitfield pattern as defined below and place this pattern more than two times

```
bitfield BitField {
  a : 2;
  b : 10;
  c : 4;
  d : 4;
  e : 4;
  f : 8;
  g : 8;
  h : 8;
  i : 8;
  j : 4;
  k : 4;
};
```

In some places, bitfield elements are displayed in the correct order as defined.
<img width="952" alt="imhex_V74HnnLnK9" src="https://github.com/WerWolv/ImHex/assets/58017919/84eeb3b4-1902-40c6-8ad4-a89ad8dafa00">

Whereas in most of the places, bitfield elements order is changed
<img width="960" alt="imhex_7P4fGmBaAx" src="https://github.com/WerWolv/ImHex/assets/58017919/ed574678-014f-4c22-beab-5908ca2f70c2">

### ImHex Version

v1.26.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by paxcut** [comment]
you are using an old version. current is 1.28.0. When I try the bitfield only the bits in the byte the cursor is hovering are shown.

**Comment by SundaresanSelvaraj** [comment]
@paxcut when I apply structure pattern in v1.28.0, ImHex is crashing. I have seen that crashing issue reported in #1046. So, I reported the issue based on v1.26.2

**Comment by paxcut** [comment]
that crash is on linux ubuntu and you are in windows like me. I ran the exact same bit-field as you can see in the image using a local build using latest source. grab a nightly build from https://imhex.werwolv.net/ at the bottom. report crashes here

**Comment by paxcut** [comment]
I tried running on nightly portable and it doesn't crash, but hangs instead.

**Comment by paxcut** [comment]
I also tried the latest release and ran your bit-field without ImHex hanging and the error you reported is not there either.

**Comment by WerWolv** [comment]
The freezes have been fixed in the latest commit now

**Comment by WerWolv** [comment]
And also the way bitfields are being displayed in the editor has fundamentally changed with v1.28.0 and above. Please update to the latest nightly if you depend on the "Place Pattern" feature

**Comment by SundaresanSelvaraj** [comment]
Hi @WerWolv, Is it possible to reconsider the old-style popup for bitfields? It was helpful than the current style as all data can be seen in single popup.

**Comment by WerWolv** [comment]
The old style isn't really possible anymore for technical reasons. However, you can add the `[[sealed]]` attribute to your bitfields to get a similar but more compact view of the data again

**Comment by SundaresanSelvaraj** [comment]
@WerWolv I tried it already. With sealed attribute, all members are not displayed in popup. Is it possible to enhance sealed attribute popup to show all members in upcoming releases?

**Comment by WerWolv** [comment]
Latest commit makes sure now that fields with value zero are properly displayed in the popup as long as the field uses two or more bits.

![image](https://github.com/WerWolv/ImHex/assets/10835354/01c0bf2d-c326-44be-a30d-f2e192beca87)
This here is really as good as it will get. I'm sorry if you don't like it

**Comment by SundaresanSelvaraj** [comment]
@WerWolv Thanks for your reply
