### ISSUE TITLE
[Bug] Bitfields cannot be edited in Pattern Data view

### ISSUE THREAD

**Issue by Nintynuts** [WerWolv/ImHex#1076]
### Operating System

Windows

### What's the issue you encountered?

Unlike most other data types, bitfield can't be edited in the Pattern Data view. Ideally, for single bits it should be a checkbox.

### How can the issue be reproduced?

Use this example, and try to edit the values in the pattern data panel.

test pattern:
```
bitfield Test{
    a0:1;
    a1:1;
    a2:1;
    a3:1;
    a4:1;
    a5:1;
    a6:1;
    a7:1;
};

Test test[35] @ 0x0;
```

test hex:
```
01 02 04 08 10 20 40 80 03 05 09 11 21 41 81 06 0A 12 22 42 82 0C 14 24 84 18 28 48 88 30 50 90 60 A0 C0
```

### ImHex Version

1.28.0

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

MSI

**Comment by Nintynuts** [comment]
I just tried this on nightly, and I still can't edit bitfields in the Pattern data view.

**Comment by WerWolv** [comment]
Closed the wrong issue, sorry

**Comment by WerWolv** [comment]
Latest commit implements this now
