### ISSUE TITLE
Hex Editor View freezes ImHex when pattern has large number of records

### ISSUE THREAD

**Issue by caseyem** [WerWolv/ImHex#108]
Thanks for the creating/developing ImHex - it is great to see a tool that can apply structured patterns to binary data.

In my exploration of the tool, I think I've come across a bug. I didn't see it listed as a known bug, but apologies if this is a known limitation. 

When using the Pattern feature with a large number of records, the Hex Editor view is freezing up the application.

File Contents: 16 byte header followed by N records
Num Records: ~16,000 (the exact number of records is expected to be "(File Size - 16) / record size"
File Size: ~10 MB
Record Size: 0x0198
OS: Windows
ImHex Version: 1.5.0

When I try to create a pattern struct that is the 16 byte header followed up a subset of N records, the application starts lagging if N > 32 and becomes unusable when N > ~100-1000 records. In all my tests, N is less than the total number of records in the file.

This appears to only affect the Hex Editor View; if I remove it from my Window, the freezing does not occur. I am able to look at all the record data in the Pattern Record View when Hex Editor View is not loaded without any lagging or freezing. The main freezing seems to occur right away but becomes unbearable if I try to use a record to jump to a location in the Hex Editor View or try to scroll the Hex Editor View.

Don't hesitate to ask if you need additional information.

**Comment by WerWolv** [comment]
Hi!
Yeah another user reported this to me before and I started looking into it. It indeed has to do with the hex editor highlighting but I couldn't pin-point it just yet. I'm working on it though

**Comment by caseyem** [comment]
Sounds good - thanks for the quick response! I had a feeling it might be a known issue. If this is a duplicate issue, please feel free to close this.

**Comment by WerWolv** [comment]
This should be fixed with the latest commit. I'm still working on a way to properly clip the list entries in the Pattern Data window but at least scrolling down in the hex editor will now longer cause the framerate to drop drastically.
