### ISSUE TITLE
compilation error / window.hpp

### ISSUE THREAD

**Issue by diehard88** [WerWolv/ImHex#110]
xpto@xpto-linux:~/ImHex/build$ make
[  2%] Building CXX object CMakeFiles/ImHex.dir/source/main.cpp.o
In file included from /home/xpto/ImHex/source/main.cpp:1:
/home/xpto/ImHex/include/window.hpp:3:10: fatal error: concepts: No such file or directory
    3 | #include <concepts>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/ImHex.dir/build.make:63: CMakeFiles/ImHex.dir/source/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:77: CMakeFiles/ImHex.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

![image](https://user-images.githubusercontent.com/25366502/103435061-abf5da00-4bd7-11eb-98c6-54e241ba675e.png)

**Comment by WerWolv** [comment]
Get a up to date compiler that supports C++20 and concepts. For example GCC 10.2.
