### ISSUE TITLE
[Bug] error[E0007]: Limit error. Evaluation depth exceeded set limit of '32'. hint: If this is intended, try increasing the limit using '#pragma eval_depth <new_limit>'.

### ISSUE THREAD

**Issue by sagasm** [WerWolv/ImHex#1113]
### Operating System

Windows

### What's the issue you encountered?

trying to write a parser using structure as parameter.

### How can the issue be reproduced?

Use the provided files as input and pattern. Try to run the pattern and when it finishes scroll down the console output window to see the error.
[test.zip](https://github.com/WerWolv/ImHex/files/11583212/test.zip)

### ImHex Version

1.29

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Portable

**Comment by paxcut** [comment]
This code produces an infinite loop because the struct and the function depend on each other. I am not sure what output this is expected to have and it is not clear what the intended usage is from the code alone.

**Comment by paxcut** [comment]
Can this be closed? Are there more issues?
