### ISSUE TITLE
[Bug] Changes made in the "Theme manager" are not saved

### ISSUE THREAD

**Issue by Traveller23** [WerWolv/ImHex#1123]
### Operating System

Windows

### What's the issue you encountered?

Today is my first time using this software.
After I changed some colors in the "Theme manager" and exported them, I closed the program and opened it again and found that the previous changes were lost.
Another problem is that I can't find where to import themes in the "Theme manager".

### How can the issue be reproduced?

See above.

### ImHex Version

1.29.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by WerWolv** [comment]
Hey!
Sorry this might not be super clearly documented. The Theme Manager currently is only there to make custom themes and export them. The colors you set in there aren't saved by default.
If you want to reuse the saved theme, move it to `%localappdata%/imhex/themes`

**Comment by Traveller23** [comment]
Thanks for the quick reply, I'll try it right away!

**Comment by Traveller23** [comment]
I totally get it, thanks a lot!
