### ISSUE TITLE
[Bug] Patten Data window always repeat the first element value in an array

### ISSUE THREAD

**Issue by Demonese** [WerWolv/ImHex#1136]
### Operating System

Windows

### What's the issue you encountered?

![2023-06-14 140732](https://github.com/WerWolv/ImHex/assets/57629614/b1b8fdf9-d68b-4270-927f-e023e3ec02b0)

### How can the issue be reproduced?

![image](https://github.com/WerWolv/ImHex/assets/57629614/c5822c19-77ae-4d09-8d59-b377f89fd8cd)

### ImHex Version

1.29.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by WerWolv** [comment]
Hi! This is currently a bug in the latest release of ImHex, sorry. Please download the nightly build here: https://imhex.download/#nightly. That should fix the problem
