### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by shaeinst** [WerWolv/ImHex#114]
**Environment : Arch LInux**
log:
```
/usr/bin/ld: /usr/local/lib/libpython3.9.a(thread.o): undefined reference to symbol 'pthread_condattr_setclock@@GLIBC_2.3.3'
/usr/bin/ld: /usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/imhex.dir/build.make:500: imhex] Error 1
make[1]: *** [CMakeFiles/Makefile2:179: CMakeFiles/imhex.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

```

**Comment by Corfucinas** [comment]
The same error happened to me on issue #113 (env: Ubuntu 20.04)

**Comment by Terr** [comment]
I got the same error. After adding `-lpthread` to the linker flags I got undefined references to `openpty` and `forkpty` so I also added `-lutil`, and then it linked successfully.

```
export LDFLAGS='-lpthread -lutil'
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j
```

System: Linux with GCC 10.2.0, Python 3.9.0 built from source

**Comment by Corfucinas** [comment]
Tried that and now got this new error

```
/usr/bin/ld: /home/the-box/.pyenv/versions/3.9.1/lib/libpython3.9.a(thread.o): undefined reference to symbol 'pthread_condattr_setclock@@GLIBC_2.3.3'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libpthread.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/imhex.dir/build.make:496: imhex] Error 1
make[1]: *** [CMakeFiles/Makefile2:160: CMakeFiles/imhex.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by shaeinst** [comment]
### compiled successfully but now i'm getting runtime error
```
Glfw Error 65544: Wayland: Failed to connect to display
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to initialize GLFW!
[1]    197722 abort (core dumped)  ./imhex
```

**Comment by Terr** [comment]
@Corfucinas That's almost the same error. Did you try deleting the `build/` directory to do a clean build?

@shaeinst Try looking into running other OpenGL applications in your environment. I don't know enough about Wayland, but it's possible that this error isn't specific to ImHex.

**Comment by WerWolv** [comment]
Wayland has quite a few issues with glfw and ImGui so it will be buggy either way.
However, that issue can come from you installing glfw3-wayland instead of glfw3-x11 by accident. There's both in the Pacman repo and wayland is the default one

**Comment by shaeinst** [comment]
@WerWolv thank you very much, replacing **glfw3-wayland** with **glfw3-x11** solved problem for me

**Comment by Corfucinas** [comment]
> @Corfucinas That's almost the same error. Did you try deleting the `build/` directory to do a clean build?
> 
> @shaeinst Try looking into running other OpenGL applications in your environment. I don't know enough about Wayland, but it's possible that this error isn't specific to ImHex.

Yes, deleted the /build folder, still can't compile it (same error).
