### ISSUE TITLE
[Bug] Arch Linux package fails to launch due to mbedtls

### ISSUE THREAD

**Issue by InvalidUsernameException** [WerWolv/ImHex#1143]
### Operating System

Linux

### What's the issue you encountered?

I've installed the `imhex-bin` AUR package that you provide. When I tried to launch it today it failed because of a missing library dependency (used to work in the past):
```
imhex: error while loading shared libraries: libmbedtls.so.14: cannot open shared object file: No such file or directory
```

This seems to be caused by the fact that the AUR packages references [`mbedtls`](https://archlinux.org/packages/extra/x86_64/mbedtls/) in it's dependencies. This package got a [major version jump from 2.x to 3.x](https://gitlab.archlinux.org/archlinux/packaging/packages/mbedtls/-/commit/311b627161d66ea85cced655dbb6a697ab1039d7) on April 19, 2023. At the same time the Arch package maintainers introduced a new package [`mbedtls2`](https://archlinux.org/packages/extra/x86_64/mbedtls2/) for [backward compatibility](https://gitlab.archlinux.org/archlinux/packaging/packages/mbedtls2/-/commits/main). This v2 package seems to provide the necessary library versions that the ImHex binary needs. Installing it manually makes InHex work again.

Since the AUR package was updated well after the v2 to v3 switch on `mbedtls` happened, I presume that something needs to be done on your side and that this is not just a temporary issue that will resolve itself on the next build.

### How can the issue be reproduced?

Start ImHex installed on Arch Linux from the AUR package. Make sure that `mbedtls2` is not installed on the system.

### ImHex Version

1.29.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Arch Linux AUR package

**Comment by WerWolv** [comment]
Hey, thanks for letting us know!

@iTrooz could you take care of this when you have time?

**Comment by iTrooz** [comment]
Indeed, I think we need to change the dependencies of the imhex-bin package on our side. I'm going to try that.

Thanks for the detailed report !

**Comment by iTrooz** [comment]
Okay so the problem isn't so much about `mbedtls2`. Just rebuilding the package on our side with updated ArchLinux should work. The current nightly builds work fine, for example.

I'm going to upload a new file to the release and update the AUR package when I get time

This kind of problem seem to happen often, maybe we should make a script for this in the future

**Comment by InvalidUsernameException** [comment]
Looks like you're right. With the binary from the new release it works out of the box.
