### ISSUE TITLE
[Bug] Copy/Paste does not work in nightly build

### ISSUE THREAD

**Issue by cryptax** [WerWolv/ImHex#1154]
### Operating System

Linux

### What's the issue you encountered?

I was unable to copy text from the pattern editor or the console to an editor outside ImHex.
The copy just looks as if it doesn't work and does not copy anything in the clipboard.
Then, the paste doesn't work of course.

Important: there is no issue with the Release 1.29.0 version (the bug does not occur in that version). **This bug only affects the nightly version** I downloaded yesterday night.

sha256 `21860ba179d6980ab5043ad1abaf972ef64b7d1759855eb73f0fc03256b03780`
`imhex-1.29.0-x86_64.AppImage`
`master@ae06954` which points to https://github.com/WerWolv/ImHex/commit/ae06954771098a8b54e2dfc85767a94d38bf5b3e

### How can the issue be reproduced?

- Open ImHex
- Open a pattern
- Select a portion of your pattern
- Type Ctrl-C or whatever shortcut you normally use to copy to the clipboard.
- Open an editor outside ImHex. For example: Emacs, or Discord.
- Try to paste with Ctrl-V (or your expected shortcut).

### ImHex Version

1.29.0

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

AppImage

### Additional context?

Affected version:

- sha256 `21860ba179d6980ab5043ad1abaf972ef64b7d1759855eb73f0fc03256b03780`
- filename: `imhex-1.29.0-x86_64.AppImage`
- git : `master@ae06954` which points to https://github.com/WerWolv/ImHex/commit/ae06954771098a8b54e2dfc85767a94d38bf5b3e
- I am running Linux Mint 21.1 with Cinnamon Window Manager. Linux Mint is close to Ubuntu/Debian.

**Comment by paxcut** [comment]
This works ok on windows (at least for me) so seeing how the bug is reported on linux this may mean it is  os dependent.
