### ISSUE TITLE
chinese(or other language) error

### ISSUE THREAD

**Issue by niedabao1** [WerWolv/ImHex#116]
can't open file which the file name include Chinese(BIG5) or file path include Chinese
![error](https://raw.githubusercontent.com/niedabao1/error_/master/pic/ScreenRecorderProject4.gif)

**Comment by Frain-Breeze** [comment]
what is the full path of the file you're trying to load? to replicate the issue

**Comment by niedabao1** [comment]
> what is the full path of the file you're trying to load? to replicate the issue

path: D:\测试\测试用例.exe

system:  Windows10 家庭版
