### ISSUE TITLE
[Bug] Cannot save settings on Windows (tries to save to ProgramData instead of appdata on chocolatey build)

### ISSUE THREAD

**Issue by Poikilos** [WerWolv/ImHex#1166]
### Operating System

Windows

### What's the issue you encountered?

Settings are using the program's directory.
- on the portable build: can save settings (I can see that the portable install creates imgui.ini)
- on the chocolatey install: cannot save settings (and I can't find it since it isn't in Program Files)
  - :edit: The exe itself is at `C:\ProgramData\chocolatey\bin\imhex.exe` (according to `where imhex.exe` in Command Prompt) but I'm not sure where it is trying to save imgui.ini
    - :edit: See workaround at bottom of this initial post to see where it is saved

Expected behavior:
- Configuration files should be saved in APPDATA--something like:
```C++
namespace fs = std::filesystem; // requires C++17
// namespace fs = boost::filesystem; // ok for C++14 or below with boost
std::string get_data_path() {
    fs::path data_path = ".";
    std::string configs_base_var = "HOME";

    #if defined(WIN32) || defined(_WIN32) || defined(__WIN32) && !defined(__CYGWIN__)
    // ^ See <https://stackoverflow.com/a/3213261>
    configs_base_var = "APPDATA";
    char const* configs_cstr = getenv(configs_base_var);
    // APPDATA variable yields the same as "%USERPROFILE%\AppData\Roaming" usually (may differ based on network policies etc).
    // LOCALAPPDATA (such as for computer-specific or large datasets) yields the same as "%USERPROFILE%\AppData\Local" usually
    if (datas_cstr == nullptr) {
        // An error is shown further down if data_path is untouched.
    } else {
        std::string datas_str(datas_cstr);
        // The '/' operator is overloaded in fs:path as the path join operator:
        data_path = datas_str / "ImHex";
    }
    #else
    char const* profile_cstr = getenv(configs_base_var);
    if (profile_cstr == nullptr) {
        // An error is shown further down if data_path is untouched.
    } else {
        std::string datas_str(datas_cstr);
        data_path = datas_str;
        // The '/' operator is overloaded in fs:path as the path join operator:
        data_path /= ".config";
        data_path /= "imhex";
    }
    #endif
    // configs_cstr and profile_cstr are different variables
    //   since profile_cstr doesn't directly contain program config dirs,
    //   so instead check the state of data_path
    //   as a better way to see if getenv failed:
    if (data_path == ".") {
        std::cerr << "Error: The " << configs_base_var
             << " variable was not available in the environment"
             << " so \"" << fs::absolute(data_path)
             << "\" will be used to store configuration files." std::endl;
    }
    return data_path;
}
```

This code was not tested.

### How can the issue be reproduced?

- doesn't remember data sharing answer
- doesn't remember Tip of the Day "Don't show again" answer
- settings aren't saved if the options are changed manually in the Settings menu (Tried to uncheck "Upload crash reports")
- "Show tips on startup" setting is off in settings, but tips are still shown (because it is never actually saved--It is only off during runtime if you have checked "Don't show again" on the startup Tip of the Day screen of that run)
- even though "Enable update checks and usage statistics" is unchecked, the program pauses during each startup and says "Checking for updates..."

### ImHex Version

1.30.1

### ImHex Build Typeinstead of bytes

- [ ] Nightly or built from sources

### Installation type

chocolatey

### Additional context?

Maybe a PORTABLE environment variable should be set by the build process only when making a portable build (not for chocolatey or other installers that place the program in a read-only directory). Then you could continue saving it in the same folder as the exe (or current directory if that is the way it is being determined--though that isn't as trustworthy) and bypass the suggested code above in that case.

:edit: Workaround: Give full control of current user to `C:\ProgramData\chocolatey\lib\imhex\tools` directory
- Changing settings then generates two files in `C:\ProgramData\chocolatey\lib\imhex\tools\config`: "interface.ini", "settings.json"
- Allows user to mess up the install though.

**Comment by TankedThomas** [comment]
This is also happening to me, so I tried the Windows installer (not portable) and by default, it's saving `imgui.ini` to the Desktop, so it seems to affect more than the Chocolatey install. 

This seems to be following #467 (same behaviour, with Desktop being the default folder), so I'm wondering if that bug was never fixed properly (or perhaps reintroduced).

**Comment by WerWolv** [comment]
Hi, thanks for the reports
I think I figured out why there's an imgui.ini file created on the Desktop but it not being able to save settings at all is weird.
Normally ImHex just tries to write to each of the registered config paths in order until one works. By default on Windows it will try first try to save it to `%localappdata%/imhex/config` and if that fails it tries to save it next to the executable. 

Could it be that there's something preventing it from accessing the LocalAppData folder? If it can't save anything there and ImHex is installed using the installer, Chocolatey or anything similar it also won't be able to store data next to the executable either so nothing will get saved.
One workaround could be to just temporarily launch ImHex as admin so it can create the folders and write to them if it's some permissions error.

**Comment by WerWolv** [comment]
Also, CC "PORTABLE environment variable"
The only difference between the installed and the portable version is a single file called `PORTABLE` that's next to the executable. Does the Chocolatey installation have that as well? If yes, that's a bug that should be reported to the person maintaining the Chocolatey package as it's not maintained by us.

**Comment by Poikilos** [comment]
Thanks! `C:\ProgramData\chocolatey\lib\imhex\tools\PORTABLE` is present, and deleting the file as Administrator solves the issue (and settings are saved in `%LOCALAPPDATA%\imhex` after that) so I informed the packager: https://community.chocolatey.org/packages/imhex#discussion

**Comment by Poikilos** [comment]
I commented on the chocolatey package page a year ago but didn't hear back, so I have contacted them today via https://community.chocolatey.org/packages/imhex

**Comment by Poikilos** [comment]
@WerWolv I didn't hear from the maintainer Jarcho. You are also listed on there as a maintainer. Do you know where the chocolatey packaging metadata is, or if it is even in a repo? I can help out but if I don't have to package it from scratch that would help me get to it.

**Comment by WerWolv** [comment]
@Poikilos It can be found here I believe: https://github.com/Jarcho/chocolatey-packages/tree/master/imhex/
The reason I'm maintainer is because I requested it ages ago just in case but I never touched any of the source code
