### ISSUE TITLE
Kaitai support

### ISSUE THREAD

**Issue by tamas-boczan** [WerWolv/ImHex#118]
[Kaitai struct](https://kaitai.io/) is a pattern language that serves a similar purpose to the custom pattern language included in the project.
The language is mature and widely used. Adding support for it would allow:
1. importing the users' already existing data structure definitions to ImHex,
2. re-using definitions created with the help of ImHex in different projects, such as the user's own scripts.

**Comment by Frain-Breeze** [comment]
I'm 99% sure there was already an issue on this, but I sadly can't find it atm.

**Comment by WerWolv** [comment]
See #61 
I'm open for PRs that add import options that turn other formats into Pattern Language code and export options that turn Pattern Langauge code back into other formats. However I want ImHex to always use the Pattern Language inside. It's the main reason this project exists for me.
