### ISSUE TITLE
[Bug] Build step for imhex_patterns failed: 2

### ISSUE THREAD

**Issue by sagasm** [WerWolv/ImHex#1182]
### Operating System

Windows

### What's the issue you encountered?

Reload CMake Project Failed.

### How can the issue be reproduced?

After Reload CMake Project , VisualGDB Gives error:
![image](https://github.com/WerWolv/ImHex/assets/14829950/92d1c4be-a759-48f9-98a9-dc7fd7a53a67)

IDE: VS2022 with VisualGDB 5.6R9

### ImHex Version

1.30.1

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Portable

**Comment by paxcut** [comment]
for instructions on compiling for windows  please check (https://github.com/WerWolv/ImHex/blob/master/dist/compiling/windows.md) currently visual studio/visual gdb are not supported.

**Comment by sagasm** [comment]
Funny, I used to build imhex 1.29 with vissualgdb with success.

**Comment by paxcut** [comment]
i am not saying it wont work, but only way to guarantee it will work is with gcc in mingw

**Comment by WerWolv** [comment]
Using Visual Studio as an IDE is fine as long as you're not using MSVC to compile ImHex.

**Comment by sagasm** [comment]
I try to make a symlink from VisualGDB\CMake\bin\cmake.exe to mingw64\bin\cmake.exe, Now cmake configuration succeeded.

**Comment by WerWolv** [comment]
Do you know what version of cmake is bundled with VisualGDB? I currently use 3.25.2.

I find it weird that it crashes when printing something. Could you try doing what I suggested here? https://github.com/WerWolv/ImHex/issues/1182#issuecomment-1618205077

**Comment by sagasm** [comment]
version of cmake is bundled with VisualGDB is 3.20.3.2

**Comment by sagasm** [comment]
@WerWolv I tried remove the message function from the cmake/build_helpers.cmake, reeload CMake Project still Failed when use  cmake.exe bundled with VisualGDB.

**Comment by sagasm** [comment]
I have found two ways to solve this problem:
1. make a symlink from visualgdb cmake.exe to mingw cmake.exe
Or:
2. modify CMake commdand to mingw cmake.xe at CMake Build Settings, modify "Use pre-build Cmake for local builds" to false at vs2022->options->VIsiualGDB->Cmake.

**Comment by paxcut** [comment]
please close all the issues opened that are considered resolved.
