### ISSUE TITLE
[Bug] Loop iterations exceeded set limit of 4096 vs #pragma array_limit 

### ISSUE THREAD

**Issue by RomanNagornyi** [WerWolv/ImHex#1184]
### Operating System

Windows

### What's the issue you encountered?

I am trying to implement a data inspector to get different CRCs and sums while selecting data.
For short selections, it works well, but for bigger I got this error 
"error[E0007]:Limit error. Loop iterations exceeded set limit of 4096"

#pragma array_limit 0xFFFFFF - didn't help

### How can the issue be reproduced?

this is my simple code
```c
#pragma once
#pragma array_limit 0xFFFFFF
#pragma pattern_limit 0xFFFFFF
#pragma eval_depth 0xFFFFFF

#include <hex/impl/imhex_check.pat>
#include <std/io.pat>
#include <std/mem.pat>
#include <std/string.pat>

namespace hex::core {

    struct Selection {
        bool valid;
        u64 address, size;
    };
    fn get_selection() {
        u128 result = builtin::hex::core::get_selection();

        Selection result1;
        if (result == u128(-1)) {
            result.valid    = false;
            result.address  = 0x00;
            result.size     = 0x00;
        } else {
            result1.valid    = true;
            result1.address  = result >> 64;
            result1.size     = result & u64(-1);
        }
        std::print(std::string::to_string(result));
        std::print(std::string::to_string(result1.size));
        return result1;
    };
}
struct MyCustomInspector {} [[format_read("custom_inspector_formatter")]];
fn custom_inspector_formatter(MyCustomInspector customInspector) {
    return  getRange();
};
MyCustomInspector customInspector @ $ [[name("Custom Inspector Name")]];

fn getRange(){
    hex::core::Selection sel= hex::core::get_selection();
    u8 data[sel.size] @ sel.address;
    return std::format("8bit {0:02X}", getSum8(sel));
};

fn getSum8(hex::core::Selection sel){
    u8 data[sel.size] @ sel.address;
    u8 gg;
    for (u8 i = 0, i < sizeof(data), i += 1) {
        gg = gg+data[i];
    }
    return gg;
};
```

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

portable windows

**Comment by paxcut** [comment]
if the size of your data is bigger than 4096 then you are exceeding the loop_limit that can be updated in a pragma. Besides the code you should also supply some input file so that the issue can be reproduced.

**Comment by RomanNagornyi** [comment]
> if the size of your data is bigger than 4096 then you are exceeding the loop_limit that can be updated in a pragma. Besides the code you should also supply some input file so that the issue can be reproduced.

[EEPROM_ST95640_8U0959655A_5WK44779_CRASH_CH341.zip](https://github.com/WerWolv/ImHex/files/11971814/EEPROM_ST95640_8U0959655A_5WK44779_CRASH_CH341.zip)

thanks for your reply. There is a bin file inside the zip. With loop_limit above 5000 - imhex has long evaluation and crashes. Maybe my code is not well-optimized or even wrong to get selection.

**Comment by paxcut** [comment]
i set loop_limit to 0xFFFFFF and selected 6768 first bytes and got no error or crash. how big selection are you using?

**Comment by RomanNagornyi** [comment]
![0 - 147 address crash](https://github.com/WerWolv/ImHex/assets/11340059/fd18a80a-ad7e-4ce7-9682-a8c916e99d4e)

from 0 to 147. Maybe because of portable installation I have this error



> i set loop_limit to 0xFFFFFF and selected 6768 first bytes and got no error or crash. how big selection are you using?

**Comment by paxcut** [comment]
this is using 1.30.1 but the msi installed and it runs quickly band result shows in inspector.
![image](https://github.com/WerWolv/ImHex/assets/53811119/d4454241-f748-4e93-a031-247bc7a754b6)

**Comment by RomanNagornyi** [comment]
> this is using 1.30.1 but the msi installed and it runs quickly and result shows in inspector. ![image](https://user-images.githubusercontent.com/53811119/251570201-d4454241-f748-4e93-a031-247bc7a754b6.png)

MSI installation didn't help.. In inspector after the first calculation do changes occur after ? My data inspector stuck and no calculation after for other selections.

**Comment by RomanNagornyi** [comment]
and I can't close the program as there is some process running in background

**Comment by paxcut** [comment]
i see, inspector wont update and can't quit either. but nothing crashed and no error message is given.

**Comment by paxcut** [comment]
I'm not sure how to debug a data inspector script. can this be turned into a pattern that accepts some selection limits so it can be more easily debugged?

**Comment by RomanNagornyi** [comment]
> I'm not sure how to debug a data inspector script. can this be turned into a pattern that accepts some selection limits so it can be more easily debugged?

![2023-07-07 00_02_50-](https://github.com/WerWolv/ImHex/assets/11340059/9b14d767-0349-4bc8-a206-83832068cef2)

here I have disabled loop_limit  and debug on. I use Pattern editor window, here error is shown.

**Comment by paxcut** [comment]
i am confused. are you running the code by saving it into the inspector's folder or are you running it as a pattern? (using green play button) one will run when selection is made but no data pattern will be created. the other will show data pattern result but has no way to receive selection limits.

**Comment by RomanNagornyi** [comment]
> i am confused. are you running the code by saving it into the inspector's folder or are you running it as a pattern? (using green play button) one will run when selection is made but no data pattern will be created. the other will show data pattern result but has no way to receive selection limits.

I try to run in inspector folder and in Pattern editor :) 
![2023-07-07 00_28_47-](https://github.com/WerWolv/ImHex/assets/11340059/7c1133b3-ff8a-462f-8208-52e9be286ff8)

I figured out that error comes from this simple For loop with no data modifications inside

**Comment by paxcut** [comment]
pragma debug has no effect in inspector script. running the pattern you posted doesnt produce any output. error is definitely in loop since thats what error says.

**Comment by paxcut** [comment]
to get an output you have to place a variable in the data but the pattern posted doesnt do that

**Comment by RomanNagornyi** [comment]
For this simple function - the result for any selection is 0

```c
fn getSum8(hex::core::Selection sel){
    u8 gg;
    for (u8 i = 0, i < 100, i += 1) {
    }
    return gg;
};
```

but with i == 300 loop crashed

```c
fn getSum8(hex::core::Selection sel){
    u8 gg;
    for (u8 i = 0, i < 300, i += 1) {
    }
    return gg;
};
```

I think issue with loop

**Comment by paxcut** [comment]
i doesnt crash for me

**Comment by RomanNagornyi** [comment]
> i doesnt crash for me

strange. Thank you a lot for your time and patience

**Comment by RomanNagornyi** [comment]
I changed this

```c
    for (u8 i = 0, i < sizeof(data), i += 1) {
        gg = gg+data[i];
    }
```

to 
```c
    for (u128 i = 0, i < sizeof(data), i += 1) {
        gg = gg+data[i];
    }
```

And works well :)

**Comment by paxcut** [comment]
dont worry. i would like to help you but i can't unless you give me detailed explanations of what you are doing. The fact it doesnt crash for me is because no variables are placed in data in the code you posted so pattern never runs. if you modified the pattern to place data you need to explain what type of data was place and where it was placed

**Comment by paxcut** [comment]
u8 is form 0 to 255 so first loop can never run past that

**Comment by RomanNagornyi** [comment]
[hex pat file.zip](https://github.com/WerWolv/ImHex/files/11972813/hex.pat.file.zip)

This is my example (for folder \scripts\inspectors), for sum8, 16 and 32 with dynamic calculation. Works like a charm. Thank you for this excellent project.
