### ISSUE TITLE
[Bug] Incorrect return type in formatter causes segfault

### ISSUE THREAD

**Issue by CodingKoopa** [WerWolv/ImHex#1196]
### Operating System

Linux, Win11

### What's the issue you encountered?

If the user makes the mistake of defining a formatter which outputs the original value as-is, ImHex will crash.

### How can the issue be reproduced?

Execute the following pattern on any file:
```c
struct T {
} [[format("fmt")]];

fn fmt(T t) {
    return t;
};

T t @ 0;
```

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

`imhex` from Arch User Repository

### Additional context?

Discussed on Discord [around this message](https://discord.com/channels/789833418631675954/789838296376803358/1120847483250147420). This kind of crash does not seem to allow ImHex to provide a backup of what you were working on.

**Comment by paxcut** [comment]
The error here is not on the recursive nature of the formatter. a format function must return a string and you are returning a T variable and that make it crash. Try the following code which works fine
```cpp
#include "std/string.pat"

struct T {
   char temp[3];
} [[format("fmt")]];

fn fmt(T t) {
    // try either one or the other lines
    // the one now produces the correct error
    // the one just below runs as it should
    
    //return t.temp;
    return std::format("{}",t);
};

T t @ 0;
```
so the recursion is handled properly. There is a bug in the sense that imhex shouldn't crash  but  the issue title should be changed to "incorrect return type in formatter causes segfault"
