### ISSUE TITLE
Cannot run on VMware Windows 10 20H2 guest

### ISSUE THREAD

**Issue by nmantani** [WerWolv/ImHex#12]
Hi,

When I tried to run ImHex 1.4.0 on VMware Windows 10 20H2 guest, it exited immediately with the following error message:

```
Glfw Error 65542: WGL: The driver does not appear to support OpenGL
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to create window!
```

It can run on Windows 10 20H2 host and it seems useful!

**Comment by WerWolv** [comment]
Make sure you have enabled hardware acceleration in your VM's settings. ImHex depends on OpenGL
