### ISSUE TITLE
[Bug] can't download extra content files when file path includes multi byte characters.

### ISSUE THREAD

**Issue by dismoty** [WerWolv/ImHex#1201]
### Operating System

Windows

### What's the issue you encountered?

Hi, thank you for developing this quite useful tool.
When I tried to download extra contents from content store, the attempt was failed with the below error message.

> Failed to download file! Destination folder does not exist.

At that time, I recognized that I executed ImHex in the folder which includes multi-byte characters. (Japanese)
After moved the folder which does not contain any multi-byte characters, the download feature works well.
So I guess the problem comes from such folder path which contains multi-byte characters.

I believe it's not a critical issue, so I hope the problem will be solved someday.

Thank you.

### How can the issue be reproduced?

Try to download extra content when ImHex is working in the folder which contains multi-byte characters.

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

zip archive

**Comment by WerWolv** [comment]
Thanks for the report! The latest commit should fix this issue
