### ISSUE TITLE
[Bug] Sound visualiser does not fail gracefully on weird inputs

### ISSUE THREAD

**Issue by EnronEvolved** [WerWolv/ImHex#1208]
### Operating System

Linux

### What's the issue you encountered?

I'm using ImHex to poke around in the audio data files of an old MS-DOS game (Xargon), and I'm trying to use the built-in sound visualiser to play back the PCM data stored therein.

The file is structured with a fixed number of entries, not all of which have sound data associated with them (zero length, zero playback frequency, no associated `soundData` variable in the associated `SoundEntry`). When I attempt to open the visualiser associated with the one of these empty entries, ImHex hangs when the it appears and I have to forcibly quit the program.

### How can the issue be reproduced?

1. Open the file "AUDIO.XR1" from the Xargon registered version in ImHex. It can be found [here](https://www.classicdosgames.com/game/Xargon.html). I'd just attach the file but GitHub complained about the file type. 
2. Run the following pattern over the file:
```
#pragma endian little

fn field(u64 addr, u64 zero, u64 scale, s64 offset) {
    return (addr-zero)/scale + zero + offset;
};

struct SoundEntry {
    u64 lengthOffset = field($, 0x0, 2, 200);
    u64 rateOffset = field($, 0x0, 2, 300);
    u32 offset;
    u16 length @ lengthOffset;
    u16 rate @ rateOffset;
    s8 soundData[length] @ offset;
} [[hex::visualize("sound", soundData, 1, rate)]];

SoundEntry soundEntries[50] @ 0x0;
```
3. Open the visualiser of the zeroth entry in the the resulting list (`soundEntries`), and observe the unintended behaviour.

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Flatpak

**Comment by WerWolv** [comment]
Thanks for the report! The latest commit fixes this.
The issue was that the first entry had a sampling rate of zero which caused a division by zero error. With the latest commit these inputs are now properly checked.
