### ISSUE TITLE
[Feature] [please vote] Automatically resize the file when needing

### ISSUE THREAD

**Issue by iTrooz** [WerWolv/ImHex#1213]
Right now, ImHex will not resize the file automatically (e.g. when writing past the end of the file, or when using Ctrl+V), because we do not want people to accidentally change their file size (which can often be a problem, with dealing with binary formats)

That said, we have received some demands about making ImHex automatically resize file size.

So I'm opening this issue, to get an estimation of how much people want this feature. If it is added, it will probably be in the form of a off-by-default checkbox in the settings that enables this behaviour

So, if you want this, please add a :+1: reaction
If you're ready to make a PR for this, please comment here

**Comment by frkami123** [comment]
This would be useful. But with a prompt dialog that ask so users can can make decision to proceed.
