### ISSUE TITLE
[Bug] Anchored struct variables do not show up in result of `[[format(...)]]`

### ISSUE THREAD

**Issue by Nintynuts** [WerWolv/ImHex#1218]
### Operating System

Windows

### What's the issue you encountered?

My data has an offset to a string elsewhere in the file, and I want to see that string in the result of my format method, but nothing shows up. Is this because it's not been resolved before format is called?

### How can the issue be reproduced?

example data:
> 70 00 C5 00 22 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 56 61 72 69 61 62 6C 65 20 31 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 56 61 72 69 61 62 6C 65 20 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 56 61 72 69 61 62 6C 65 20 33 00 00 00 00

pattern:
```cpp
struct Name {
    u16 offset;
    char name[] @ offset;
} [[format("format_Name")]];

fn format_Name(auto name){
    return name.name;
};

struct Data {
    Name names[3];
} [[inline]];

Data data @ 0x0;
```

### ImHex Version

1.30.1

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Nightly msi

**Comment by WerWolv** [comment]
Hey. The issue is that your format function tries to create a copy of the struct's data which fails because of the placed variable. If you take the variable in as a `ref auto` parameter instead, it should work as expected

**Comment by Nintynuts** [comment]
Thanks, I forgot about ref. Is there a reason `auto` isn't `ref` by default for structs?

**Comment by WerWolv** [comment]
Because sometimes you don't want them to be references. It's only a few cases where you absolutely need a reference. In many cases it works without and if you want to modify some of the values in the struct before formatting them, you absolutely need to create a copy.

`auto` in general really just means "Disable type checks and allow any type to be passed in as this parameter"
