### ISSUE TITLE
[Bug] Standard path has double `imhex` in it on MacOS

### ISSUE THREAD

**Issue by ershov** [WerWolv/ImHex#1221]
### Operating System

MacOS

### What's the issue you encountered?

![image](https://github.com/WerWolv/ImHex/assets/449936/1ecd2d65-952b-435a-b8dd-33fde602d357)

Strictly speaking, it's not a big issue, just an inconsistency. One `imhex` in the path would be enough.

### How can the issue be reproduced?

1. Install ImHex.

### ImHex Version

1.30.1

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

DMG

### Additional context?

User settings are untouched.

**Comment by WerWolv** [comment]
Thanks. Latest commit should fix this. Could you download the latest nightly once it becomes available and verify that it's correct now?

**Comment by ershov** [comment]
@WerWolv Thank you for fixing this so quickly.

What will happen to existing installations? Will they loose all user files because the path has changed?

**Comment by ershov** [comment]
I can acknowledge that the current "nightly" has only one `imhex` in its paths. (MacOS)
