### ISSUE TITLE
[Bug] "Standard Magic" is not shipped with the app.

### ISSUE THREAD

**Issue by ershov** [WerWolv/ImHex#1223]
### Operating System

MacOS

### What's the issue you encountered?

Because "Standard Magic" is not included in the app installation, the patterns are not automatically loaded when a file is opened. "Importing" the pattern is not straightforward and hard to find.

At the same time, magics for Nintendo Switch and Portable Executable are included.

<img width="601" alt="image" src="https://github.com/WerWolv/ImHex/assets/449936/56b615d3-692b-4879-8c60-cd40c5780bdd">

The patterns is one of the main features of the app, it'd be great if it worked out-of-the-box as advertised.

### How can the issue be reproduced?

1. Remove any existing installation
    ```
    rm -rf \
        /Applications/imhex.app \
        ~/Applications/imhex.app \
        ~/Library/Application\ Support/imhex \
        ~/Library/Preferences/net.WerWolv.ImHex.plist \
        ~/Library/Saved\ Application\ State/net.WerWolv.ImHex.savedState
    ```
2. Install a fresh ImHex

### ImHex Version

1.30.1

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

DMG

**Comment by paxcut** [comment]
As you clearly are aware the file can be obtained from the content store. I think it is designed that way to ensure you have the latest version even if you download an old version of imhex

**Comment by ershov** [comment]
Is there any particular reason for not including a basic functionality in the app itself? How is it useful?

**Comment by fabifont** [comment]
Hi @WerWolv , I am on ImHex 1.33.1 and it's completely missing the standard magic entry. Is there a way to fix it and download all magic files?
![image](https://github.com/WerWolv/ImHex/assets/38903806/019ee409-f1dd-4709-9b87-08c10f0b9e38)

**Comment by WerWolv** [comment]
Hey @fabifont
Having the standard magic database as a downloadable thing caused a huge amount of problems, that's why it's now bundled in with the builtin plugin's romfs and extracted from there instead.

**Comment by fabifont** [comment]
> Hey @fabifont Having the standard magic database as a downloadable thing caused a huge amount of problems, that's why it's now bundled in with the builtin plugin's romfs and extracted from there instead.

So where are magic files stored? Because patterns are not auto-recognized and I cannot apply the pattern manually either.

**Comment by WerWolv** [comment]
That depends on your OS. On Windows, they're under `%localappdata%/imhex/magic`.
And what do you mean with "cannot apply the pattern manually either"? You should always be able to import them through `File -> Import -> Pattern`

**Comment by fabifont** [comment]
> That depends on your OS. On Windows, they're under `%localappdata%/imhex/magic`. And what do you mean with "cannot apply the pattern manually either"? You should always be able to import them through `File -> Import -> Pattern`

With the flatpak version or on Windows, If I import a file like a `.bmp` it automatically loads the default pattern for it (or you can right click and apply it manually). On the Arch Linux version which is shipped from AUR this doesn't work. I cannot see any builtin pattern. I also tried building it locally but I had the same problem.

**Comment by WerWolv** [comment]
I think most versions of ImHex that you get from package repositories don't actually ship with all the patterns pre-installed. The packagers usually make another package that only installs the patterns/includes/etc so you might need to look for that.
Alternately, go to `Extras -> Content Store` and install all the patterns and libraries you want from there.

**Comment by fabifont** [comment]
> I think most versions of ImHex that you get from package repositories don't actually ship with all the patterns pre-installed. The packagers usually make another package that only installs the patterns/includes/etc so you might need to look for that. Alternately, go to `Extras -> Content Store` and install all the patterns and libraries you want from there.

They are installed.
![image](https://github.com/WerWolv/ImHex/assets/38903806/69b54e0a-a49b-434a-a57f-868da635b77f)

**Comment by fabifont** [comment]
@WerWolv sorry to bother you. I've seen that there have been some commits on the main branch. Is there a new upcoming release that fixes my problem?

**Comment by fabifont** [comment]
I temporarily switched to the Flatpak version which works fine and patterns are present.

**Comment by Devenec** [comment]
I have the same issue on Windows, with ImHex 1.35.1, with both the portable version (the GPU version) and the version installed from the MSI: patterns are not automatically loaded. I tried with 7z, JPEG, PNG, ZIP and exe (Windows PE) files, but the pattern editor stays empty. Manual importing via _File_ > _Import..._ > _Pattern File_ works.

I checked the log file for something related to the issue, but the only error I could find was:
```
[19:55:37] [ERROR] [Script | Init Tasks]       You must install or update .NET to run this application.

App: D:\ImHex\imhex-gui.exe
Architecture: x64
[19:55:37] [ERROR] [Script | Init Tasks]       Framework: 'Microsoft.NETCore.App', version '8.0.6' (x64)
[19:55:37] [ERROR] [Script | Init Tasks]       .NET location: C:\Program Files\dotnet\

[19:55:37] [ERROR] [Script | Init Tasks]       The following frameworks were found:
[19:55:37] [ERROR] [Script | Init Tasks]         5.0.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
[19:55:37] [ERROR] [Script | Init Tasks]         6.0.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
[19:55:37] [ERROR] [Script | Init Tasks]       
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.6&arch=x64&rid=win10-x64
[19:55:37] [ERROR] [Script | Init Tasks]       Error when initializing script loader: Failed to initialize command line 0x80008096
```
Installing .NET runtime 8.0 made the error to disappear, but didn't resolve the issue, and didn't seem to affect the behaviour of the application.

I also noticed with the MSI version that the content store showed _Download_ next to all patterns, although most were already installed with the application. The portable version correctly showed _Remove_ next to the already installed patterns.

**Comment by WerWolv** [comment]
Thank you for bringing it up again, the latest commit should fix this now
