### ISSUE TITLE
[Bug] "Remove" button in Content Store doesn't do the job [MacOS]

### ISSUE THREAD

**Issue by ershov** [WerWolv/ImHex#1224]
### Operating System

MacOS

### What's the issue you encountered?

In Content Store there button "Remove" doesn't actually remove the thing.

### How can the issue be reproduced?

1. Make a fresh installation of ImHex.
2. In "Content Store" download the "Standard Magic" by "Download" button.
3. "Remove" button appears.
4. Press the "Remove" button.

The downloaded files are still there and "standard magic" works.

### ImHex Version

1.30.1

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

DMG

**Comment by paxcut** [comment]
I tested this on windows using latest nightly portable and when i delete pe magic the file is no longer in the magic folder of portable

**Comment by iTrooz** [comment]
I can reproduce this bug, the other files get removed, but the *.mgc files stay there

**Comment by paxcut** [comment]
I deleted standard magic and there was no trace left of anything that was downloaded when I first installed it. Maybe thats only for standard magic.

**Comment by iTrooz** [comment]
I just talking with WerWolv, and apparently its only an issue for Linux (and MacOS I guess)

In short, libmagic isn't consistent across platforms, and our hack (https://github.com/WerWolv/ImHex/pull/1212) doesn't put the .mgc files where it should (they should be in the `standard_magic` folder)

**Comment by paxcut** [comment]
I guess I dont quite understand the implications with respect to this issue. I just tested and for the other two magic files there are both a .magic and a .mgc and they are both on the magic folder. Deleting either on on the content store deletes only the .magic file on windows. Is this part of the bug or should these two also have their own folders? When I install standard magic it creates a standard_magic folder where a lot of mgc and extensionless files are written. Is the bug then only that on linux this folder is never created?

**Comment by ershov** [comment]
On MacOS, it doesn't create a `standard_magic` subdirectory - the files are all in the `magic` dir.

**Comment by ershov** [comment]
I honestly don't think it's a high priority bug. I hardly can imagine why anyone would delete anything.
