### ISSUE TITLE
[Bug] current master doesn't build on Mac

### ISSUE THREAD

**Issue by ckoehler** [WerWolv/ImHex#1226]
### Operating System

MacOS

### What's the issue you encountered?

```
CMake Error at lib/libimhex/CMakeLists.txt:79 (target_link_libraries):
  Target "plcli" of type EXECUTABLE may not be linked into another target.
  One may link only to INTERFACE, OBJECT, STATIC or SHARED libraries, or to
  executables with the ENABLE_EXPORTS property set.
```

I think it's this commit (it works before this one, not with this one):
https://github.com/WerWolv/ImHex/commit/a83ca3c228b593c52cb09fdd2c82239c0333ff09

This variable `LIBPL_BUILD_CLI_AS_EXECUTABLE` suggests that `plcli` won't be built as executable, but I don't see it used anywhere else.

### How can the issue be reproduced?

follow the macos.md compile instructions

### ImHex Version

2082781cf57febb1ce7becca547e687919038a7a

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

N/A

### Additional context?

cmake version 3.27.1

**Comment by ckoehler** [comment]
Leaving this for posterity: make sure you update the submodules... 
`git pull --recurse-submodules`

**Comment by rvanlaar** [comment]
Might be worth it to document https://www.git-scm.com/docs/git-config#Documentation/git-config.txt-fetchrecurseSubmodules in the readme.
