### ISSUE TITLE
[feature request] throwing errors / asserts

### ISSUE THREAD

**Issue by Frain-Breeze** [WerWolv/ImHex#123]
I think it would be very handy to throw errors and/or warnings when a specific conditional evaluates to true. For example, we have an unknown image format, which seems to have a byte with the type of image data in it. Let's name this byte x. In all files we have seen so far, x has only ever been 0, 1 or 2. We have also implemented the proper structs for 0, 1 and 2. but what if x is not 0, 1 or 2? we would want to be alerted of that. So, here we could then assert that x < 3.
This would allow for much more robust patterns, as this has essentially just implemented error checking on the file in question. This not only helps catch errors, it also warns you of possibly unimplemented parts of the filetype.

**Comment by WerWolv** [comment]
That is a very cool idea that does require some extra work around how functions work and are used throughout the language. I'll definitely look into it though!

**Comment by WerWolv** [comment]
Got some extra features implemented :)
![](https://i.imgur.com/eu3PBD5.png)
