### ISSUE TITLE
[Bug] Unable to start imhex on Arch Linux due to missing libfmt.so.9

### ISSUE THREAD

**Issue by frkami123** [WerWolv/ImHex#1234]
### Operating System

Linux

### What's the issue you encountered?

Unable to start imhex-bin (AUR) on Arch Linux.
Error message: `imhex: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory`

### How can the issue be reproduced?

On Arch Linux distribution, enter terminal commands:
1. Update to the latest packages: `sudo pacman -Syu`
2. Install `imhex-bin` via `yay`: `yay -Syu imhex-bin`
3. Launch `imhex` executable: `imhex`
4. Observe imhex error message: `imhex: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory`

### ImHex Version

1.30.1-1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

AUR via yay

### Additional context?

Seem like the fmt package on Arch Linux has been upgraded to version 10.
Arch Linux: 2023/08/04 (August 4)
imhex-bin (AUR): 1.30.1-1
fmt: 10.0.0-1

Installation using `imhex-1.30.1-ArchLinux-x86_64.pkg.tar.zst` also run into this problem.

**Comment by WerWolv** [comment]
My god why does Arch not keep old packages around when they are updated in the repo...

@iTrooz could you update the AUR release again?

**Comment by iTrooz** [comment]
Sure !

I wonder if specifying the major versions of packages in the PKGBUILD would help

**Comment by tuanthien** [comment]
Look like the issue has been fixed with AUR imhex-bin 1.30.1-2. Thanks.

**Comment by iTrooz** [comment]
Oh yeah, I forgot to say it here sorry, but I updated the package

**Comment by mastercaution** [comment]
Arch updated `fmt` to version 11 last week, so the current binaries (v. 1.35.4) referencing `libfmt.so.10` don't run anymore.

**Comment by mastercaution** [comment]
> I wonder if specifying the major versions of dependencies in the PKGBUILD would help

@iTrooz you could add the .so version (like below) to the `PKGBUILD`, which will prevent upgrading fmt to a newer major version until the ImHex package is updated.

```diff
diff --git a/PKGBUILD b/PKGBUILD
index fcea9ec..77d6189 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -8,7 +8,7 @@ pkgdesc="A Hex Editor for Reverse Engineers, Programmers and people who value th
 arch=("x86_64")
 url="https://github.com/WerWolv/ImHex"
 license=('GPL2')
-depends=(glfw mbedtls freetype2 libglvnd dbus gtk3 curl fmt yara nlohmann-json zlib bzip2 xz zstd)
+depends=(glfw mbedtls freetype2 libglvnd dbus gtk3 curl libfmt.so=10 yara nlohmann-json zlib bzip2 xz zstd)
 makedepends=(git)
 provides=(imhex)
 conflicts=(imhex)
```

Unfortunately, due to pacman reasons I don't understand, this will also prevent _any_ system upgrade and likely people will complain to you about failing `pacman -Syu`. I don't know if this is a worthwhile trade-off :sweat_smile:

```
$ pacman -Syu                                                    
:: Synchronizing package databases...
 core is up to date
 extra is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing fmt (11.0.2-1) breaks dependency 'fmt=10.2.0' required by imhex-bin
```

**Comment by iTrooz** [comment]
>  you could add the .so version (see diff below) to the PKGBUILD, which will prevent upgrading fmt to a newer major version until the ImHex package is updated.

Good idea, but I don't think I can determine what version of libfmt we are using. ImHex just uses whatever version is in the environment, we don't have a variable saying `libfmt_version=10`

>  I don't know if this is a worthwhile trade-off 😅

Pretty sure people will absolutely hate it, and spam us for quicker upgrades ;) so let's not do it

**Comment by ameuret** [comment]
When I build a minimal test app that uses (default, system) {fmt} it's resolved to v11 (dixit `ldd`). But for some reason, when I build ImHex using the current `PKGBUILD` it links to v10. Which has been removed recently in favour of v11. I've check both fmt hierarchies that are fetched through git submodules by ImHex and they're both `FMT_VERSION 110002`. :man_shrugging:

**Comment by nikelborm** [comment]
faced the same error. reinstalling imhex from aur with cleanBuild helped
