### ISSUE TITLE
[Bug] Saving a memory provider doesn't transform it into a file provider (?)

### ISSUE THREAD

**Issue by LennardF1989** [WerWolv/ImHex#1238]
### Operating System

Windows

### What's the issue you encountered?

I have been using ImHex pretty intensly past few days. Really liking the tool and especially the pattern editor (coming from 010 Editor myself)! However, I have been running into a lot of crashes and nuisances as I was/am reversing a file. I will make a bunch of issues to cover those, this being the first.

If you make a new file, add some stuff in the pattern editor, and then save the file. All the contents of the pattern editor will be lost.

After saving, the Pattern editor is now empty.

### How can the issue be reproduced?

1. File > New File...
2. Type something in Pattern editor
3. File > Save

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

### Additional context?

Continuation of https://github.com/WerWolv/ImHex-Patterns/issues/148

**Comment by paxcut** [comment]
There are two cases. For both cases follow these steps.

1.Start a new ImHex and create a new file. Resize it and fill some values but don't save it.
2. Type some pattern code in the pattern editor

Now the two cases separate.
case A. Save the input file by doing a Save As. The file will save but the Imhex file remains uninitialized . The pattern code is intact. To get to a normal state load the newly create file, transfer the pattern code and close the uninitialized file.
Case B. Save input file using Save. Now the input file is updated but the pattern code disappears.

**Comment by paxcut** [comment]
A video of second case

https://github.com/WerWolv/ImHex/assets/53811119/589e8cbf-df54-48e0-b001-f9a953ada56b

**Comment by paxcut** [comment]
the first case.

https://github.com/WerWolv/ImHex/assets/53811119/0a1a38b8-a1b2-40e7-961d-d347bcdfdd9c

**Comment by paxcut** [comment]
This is fixed now. Please check a nightly build and if there are no further issues close this one.

**Comment by iTrooz** [comment]
If this is closed, could you open a new issue for case A ? Alternatively keep this one open

**Comment by paxcut** [comment]
I was under the impression that case A was already doing the intended behavior. The reason I posted about case A was because I thought it would behave as the usual Save as do in most places, but apparently thats not the case for ImHex. To be sure I expected the file name that was saved to take over the unnamed file but Save As in ImHex is supposed to leave everything as it was.

**Comment by iTrooz** [comment]
> I was under the impression that case A was already doing the intended behavior. 

Yeah, but we talked about that on discord, and WerWolv is okay with changing this behavior
