### ISSUE TITLE
Periodically save content in Pattern Editor

### ISSUE THREAD

**Issue by Foxboron** [WerWolv/ImHex#124]
I try starting writing up the UEFI structs but then I hit the an edge case while hitting some keycombo and `imhex` segfaults. When I start it again the content of the editor is gone.

The work around is to just save the content of the editor every time I make progress but it feels brittle and there are no keybind for "Save Project" yet. It would be great to have some way to load up the past content or at least have it dumped to some file so it's easier to reproduce the crash and not loose all the work.

**Comment by Frain-Breeze** [comment]
This would be a great feature. Something I’d like to add to this: It would be very nice if ImHex could edit a pattern file, instead of only loading from it. Saving would then write back the changes to the file it was loaded from.

**Comment by WerWolv** [comment]
This is definitely an issue that needs improvement. Both having a key binding for saving the patterns as well as creation of periodic backups that can be loaded again if necessary. I'll look into it.

**Comment by WerWolv** [comment]
We still don't have a periodic backup feature, however if ImHex crashes it will now create an auto backup
