### ISSUE TITLE
[Bug/Feature] "Save project as..." doesn't update window title properly

### ISSUE THREAD

**Issue by LennardF1989** [WerWolv/ImHex#1243]
### Operating System

Windows

### What's the issue you encountered?

Tagging this as bug/feature, as there is a bug involved, but I also feel that from a UX perspective, it could be better.

Say you open ImHex, drag/drop a file and start editor the pattern. The circle on the tab will light up there is data to be saved. If you now switch to the file, there is no way to "just save" the project. You will have to go "File > Save Project As..." (ALT+SHIFT+S).

This will then save the project and immediately set it as active too. However, the title is not updated to reflect that.

BUG: Saving a new project makes it seem like it's not loaded, while it is.
FEATURE: ALT+S (Save project) should just perform the same action in this scenario, as "Save Project As" basically means "Save project and set as active project", saving something that doesn't exist yet, kind of should do the same.

### How can the issue be reproduced?

1. I start a new ImHex instance
2. Drag/drop a file, start editing pattern. 
3. Light circle pops up in tab that there is data to save. Switch to it.
4. Hit CTRL+SHIFT+S to save project somewhere.
5. Title of Window is not updated to reflect you are now in an active project.
6. Close ImHex and restart
7. Load project
8. Title is now properly updated.

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by Nowilltolife** [comment]
Fixed in 2059ad82c3da163b003ea1561fa51ba672332a57
