### ISSUE TITLE
[Bug/Feature] Opening a project when another is opened throws error message

### ISSUE THREAD

**Issue by LennardF1989** [WerWolv/ImHex#1244]
### Operating System

Windows

### What's the issue you encountered?

Again, kind of a bug/feature thing.

BUG: If you have a project opened, and then try to load another project, you will get a warning stating "Some providers failed to load: filename: Failed to open file filename: No such file or directory.

If you however restart ImHex and then open the project, everything is fine.

FEATURE: There is actually no way to "properly" close a project in ImHex. You can prevent the above bug without restarting, by closing all tabs first until you see the home screen again, and then open the project.

### How can the issue be reproduced?

1. Start ImHex
2. Drag/drop any file
3. "File > Save project as"
4. "File > Open project" on the file you just saved - you will now get one or more errors.
5. Close all tabs until you see the home screen (if 4 failed badly, you probably already see the home screen)
6. "File > Open project" on the file you saved earlier, now it will load just fine.

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by iTrooz** [comment]
I could reproduce this on the latest release, but not the latest nightly. Closing as completed
