### ISSUE TITLE
[Bug] Can't get cmake to build project on Windows

### ISSUE THREAD

**Issue by LennardF1989** [WerWolv/ImHex#1246]
### Operating System

Windows

### What's the issue you encountered?

I simply cannot get the project to compile at all on Windows 11...

I've followed the instructions outlined here: https://github.com/WerWolv/ImHex/blob/master/dist/compiling/windows.md

1. I've installed the latest MSYS2 that's available now.
2. Cloned the project and submodule
3. Ran the script to download dependencies from the MinGW x64 shell

Additionally I had to run `pacman -S mingw-w64-{i686,x86_64}-make`, otherwise I would not have `mingw32-make`.

I then played around with the commandline because:
- for some reason the shell can't find the gcc, g++ and make program (even after adding it to the PATH and restarting)
- the instructions that I have to run from the "build" directory are also incorrect, since cmake won't be able to find the CMakeList.txt (EDIT: The `..` in the documentation got dropped, so you can ignore this - but still doesn't fix the problem).
- I had to force skipping the compiler check because it would insist on mixing forward/backwards slashes during try compile steps (generating an invalid path with escaped characters).
- Turn on `IMHEX_IGNORE_BAD_COMPILER`, most likely because of the above. 
```
cmake -G "MinGW Makefiles"                \
  -DCMAKE_MAKE_PROGRAM=mingw32-make       \
  -DCMAKE_C_COMPILER=gcc                  \
  -DCMAKE_C_COMPILER_FORCED=TRUE          \
  -DCMAKE_CXX_COMPILER=g++                \
  -DCMAKE_CXX_COMPILER_FORCED=TRUE        \
  -DCMAKE_BUILD_TYPE=Release              \
  -DCMAKE_INSTALL_PREFIX="$PWD/install"   \
  -DCMAKE_C_COMPILER_LAUNCHER=ccache      \
  -DCMAKE_CXX_COMPILER_LAUNCHER=ccache    \
  -DCMAKE_C_FLAGS="-fuse-ld=lld"          \
  -DCMAKE_CXX_FLAGS="-fuse-ld=lld"        \
  -DCMAKE_OBJC_COMPILER_LAUNCHER=ccache   \
  -DCMAKE_OBJCXX_COMPILER_LAUNCHER=ccache \
  -DRUST_PATH="$USERPROFILE/.cargo/bin/"  \
  -B build
```

The end result is it will simply say "-- Configuring incomplete, errors occurred!" with nothing else to go on. I've been at this for at least 2 hours by now, solving one problem after the other.

Has anyone here a working setup on Windows that can help me out...

### How can the issue be reproduced?

See above.

### ImHex Version

n/a

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

n/a

**Comment by WerWolv** [comment]
Hey, I'm developing on Windows all the time and it works perfectly fine for me. 

Make sure to run the cmake commands through the mingw64 terminal and not through your normal command line. Otherwise various env vars won't be set correctly.
Additionally, I recommend using Ninja instead of make since it drastically speeds up the build.

**Comment by LennardF1989** [comment]
I am using the mingw64 terminal, which is the odd thing!

> Ninja
I'll see if that perhaps makes any difference. I'll report back!

**Comment by LennardF1989** [comment]
Unfortunately, that didn't fix it for. However, I did manage to compile now.

I loaded the project up in VSCode and it sugggested to install the "CMake Tools" extension. This immediately offered to use my installed mingw64 setup. So I removed the build directory, reverted all changes, ran the "CMake: Install" command from VSCode and it just started compiling like nothing was ever wrong...

You are correct though that using the standard make program is atrociously slow! A fresh build took 9 minutes, while I can compile the full UE5 engine from scratch within a hour on this machine...

Unfurtunately ninja doesn't want to compile, I get an error saying:
```
[cmake] ninja: error: Makefile:5: expected '=', got ':'
[cmake] default_target: all
[cmake]               ^ near here
```

**Comment by WerWolv** [comment]
I think you need to delete your build folder and re-run cmake with the `-G "Ninja"` flag set. It somehow tries to run the Makefile using ninja which obviously won't work.

Besides that, you might want to use the new `-DIMHEX_USE_DEFAULT_BUILD_SETTINGS=ON` option which will use the recommended tools to build everything. (e.g llvm-binutils instead of regular ones, ld.lld instead of gold, etc). Using these settings, I can compile ImHex in about 3 minutes from zero on my machine. And in maybe 5 to 10 seconds when just making changes to a few files

**Comment by LennardF1989** [comment]
There we go! Thank you, that brought it down to less than 2 minutes :)

For reference to others, what I did was:
- Make sure you have cloned the full Git repository, including the submodules, **recursively**!
- Install MSYS2
   - Optional: I added my MINGW64 bin-folder to my PATH variable.
- Open the MINGW64 terminal and execute the `dist\get_deps_msys2.sh` script.
- Additionally, install ninja through `pacman -S mingw-w64-x86_64-ninja`
- Close the terminal
- Open folder in "VS Code" and install the "CMake Tools" extension.
- When asked to setup your compiler, select MINGW64.
- Save the folder as a workspace
- Open up the created `.vscode/settings.json` and add the following contents:
```json
{
    "cmake.configureOnOpen": true,
    "cmake.configureSettings": {
        "CMAKE_MAKE_PROGRAM": "ninja"
    },
    "cmake.generator": "Ninja",
    "cmake.configureArgs": [
        "-DIMHEX_USE_DEFAULT_BUILD_SETTINGS=ON"
    ]
}
```
- If it already got created, remove the `build` directory.
- Run "CMake: Configure" and let it prepare.
- Run "CMake: Install", wait a bit and done! You now have a imhex.exe in your build directory :)
