### ISSUE TITLE
MacOS v1.6.0 is v1.5.0

### ISSUE THREAD

**Issue by scemino** [WerWolv/ImHex#125]
Hi,

I downloaded this: https://github.com/WerWolv/ImHex/releases/download/v1.6.0/ImHex_1.6.0_MacOS.zip
I installed ImHex with **imhex.dmg** and when I launch the application, I had DPI issues, and I discovered in the about box this:
<img width="766" alt="Capture d’écran 2021-01-09 à 20 26 25" src="https://user-images.githubusercontent.com/643384/104106945-49789a00-52b9-11eb-970f-931e3866b2b3.png">
This is not v1.6.0.

**Comment by Frain-Breeze** [comment]
It is actually 1.6.0, werwolv just forgot to change the version number in cmake

**Comment by scemino** [comment]
Ah OK.
Too bad... it means I have DPI scaling issues even with v1.6.0.

**Comment by WerWolv** [comment]
Yeah sorry about that, I'll replace the release when I have time.

The issue about DPI is that devices with retina displays report wrong values to glfw. I gladly accept PRs fixing the issue as myself I have absolutely no way of debugging it without a mac.
