### ISSUE TITLE
[Bug] Windows blending to their backgroud

### ISSUE THREAD

**Issue by unrealsecurity** [WerWolv/ImHex#1256]
### Operating System

Windows

### What's the issue you encountered?

Installed the latest release and now every window seems to be blending to their background. 

![Screenshot 1](https://github.com/WerWolv/ImHex/assets/33143283/5dafb4bb-99ad-4653-9f95-5b500b3c7671) 
![Screenshot 1](https://github.com/WerWolv/ImHex/assets/33143283/338eabce-80b9-496c-94b9-d0b45b4063c8)

### How can the issue be reproduced?

Install ImHex on Windows

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by WerWolv** [comment]
Hey! Is there a possibility that you have old themes installed from the content store?
It looks like something set the alpha style setting to basically 0. Try deleting the `%localappdata%/imhex` folder, things should go back to normal again then

**Comment by unrealsecurity** [comment]
No I'm using the default dark theme. I also tested fresh install on a machine that never had ImHex before.

**Comment by paxcut** [comment]
Maybe it is because you are running on test mode. Are you using customized drivers? Try turning test mode off and see if that helps.

**Comment by unrealsecurity** [comment]
It might be more than just alpha value below 1 because it looks like some color blend mode. 

If I set the window background color to white this happens... 
![Screenshot](https://github.com/WerWolv/ImHex/assets/33143283/9254e599-b246-48e6-b8b8-de813275dd7d)

**Comment by unrealsecurity** [comment]
@paxcut Test mode isn't the problem. No weird drivers.

**Comment by WerWolv** [comment]
If you check the Theme Manager, the two interesting settings are under Styles. 
imgui -> alpha which should be 1.0 and imhex -> window-blur which should be 0.0

At least on Windows 11 it works without any issues but I'm setting up a Windows 10 VM right now to check if I can reproduce it there

**Comment by unrealsecurity** [comment]
I have those values correct.

**Comment by paxcut** [comment]
i am on windows 10 and I don't have that issue and never had it before. rename the config folder and restart imhex to use default settings.

**Comment by unrealsecurity** [comment]
Did that too. I want to clarify that I had ImHex on this same machine and it was definitely not looking like this.

**Comment by unrealsecurity** [comment]
I wanted to add that I updated from 1.29.0 release.

**Comment by paxcut** [comment]
on theme manager under imgui colors check the last entry windows background. Alpha should be 255

**Comment by unrealsecurity** [comment]
If you check the second screenshot, you see that my `window-background` property has an alpha value of 255.

**Comment by Christian720** [comment]
Unsubscribe please

**Comment by paxcut** [comment]
sorry, i didnt realize you posted image showing window background color.  If you switch back to older version does the issue go away? Maybe try a portable version of the older release.

**Comment by WerWolv** [comment]
I'd assume the issue is me enabling `GLFW_TRANSPARENT_FRAMEBUFFER` on the main window now. Previously I only used it on the startup splash screen. 

From what I can tell, it doesn't happen to most people so it must be some driver incompatibility with your system. What GPU are you using? 
The best I can probably do is provide a setting that you can manually enable in the settings file to disable this flag from being set

**Comment by unrealsecurity** [comment]
I'll try the NoGPU version in a sec!

**Comment by unrealsecurity** [comment]
It appears the portable NoGPU version works and doesn't have this weird behavior. I should've mentioned earlier that I upgraded ImHex on a VMware Workstation VM. It's very likely that the `GLFW_TRANSPARENT_FRAMEBUFFER` is the culprit there. It might be a good idea to set defaults that work everywhere and give user an option to enable additional features.

**Comment by WerWolv** [comment]
So far you're the only person reporting this issue. Since it only happens in VMs and we have the NoGPU versions available, I think I'll leave the current behaviour for now. 
I'll see though if I can maybe detect if this setting is properly supported by the GPU driver and disable it if it's not supported. In general, I'd like to keep it enabled if possible at all

**Comment by unrealsecurity** [comment]
Sounds good to me. I'll use the NoGPU version in VM if it works well enough performance wise. Latest release works on host without any issues.

**Comment by rwperrott** [comment]
On Linux Mint 22.1 Xfce 64-bit, with no Xfce window transparency, after deleting ~/.config/imhex directory,
only the window frame is visible on a White background, and the content is only fully visible on a completely Black background. I tried checking the colours, but all looked OK, as 255 alpha, so the alpha is probably being ignored and assumed to be 50%.

I just retried imhex-1.35.4-Ubuntu-24.04-x86_64.deb to imhex-1.36.2-Ubuntu-24.04-x86_64.deb, with the ~/.config/imhex directory before each re-install, and all are effectively unusable, so BS on this being closed as completed!

How about providing a setting switch to completely disable all alpha transparency.

**Comment by rwperrott** [comment]
I just tried imhex-1.37.1-Ubuntu-24.04-x86_64.deb and alpha is still about 50%, whatever I set theme values set to, so still broken!
Styles -> imgui -> alpha is 1.0, but behaves like it is 0.5 or less, after `apt purge imhex`, then reinstall!

**Comment by rwperrott** [comment]
Still broken the same in v1.37.4 ...

**Comment by rwperrott** [comment]
It looks like imhex is probably misusing a Linux full-screen "game" display API, because this issue disappears when:
 
- XFCE/Setting/Desktop Setting -> Window Manager
    -  is {manager}
    - not {manager} + Compositing
- or XFCE/Setting/Windows Manager Tweaks -> Compositor/Enable display compositing
    - is disabled

Typically Window Compositing should be disabled for full-screen games, because it isn't needed and can cause rendering issues, however this should not be assumed for windowed apps!
