### ISSUE TITLE
[Bug] Restarting after setting changes does not work

### ISSUE THREAD

**Issue by RunDevelopment** [WerWolv/ImHex#1262]
### Operating System

Windows

### What's the issue you encountered?

After changing a setting (e.g. fonts), ImHex wants to restart, so I clicked the restart button. The program closes and never restarts. I have to start it manually. (Settings are changed correctly.)

### How can the issue be reproduced?

1. Fresh MSI install on windows 10.
2. Start the application and change a setting that requires a restart.
3. Click "Restart".
4. See as nothing happens.

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by Nemoumbra** [comment]
ImHex does the expected thing in the latest Nightly build.
