### ISSUE TITLE
[Bug] Can't open any disk or partition

### ISSUE THREAD

**Issue by zorone** [WerWolv/ImHex#1265]
### Operating System

Windows

### What's the issue you encountered?

I can't open any disk or partition at all. It shows weird dialog screen with unreadable text. And I can't click out from it at all. I have to close and open it again to interact with them.

![Screenshot (4696)](https://github.com/WerWolv/ImHex/assets/60736083/49e92b67-ac9f-4c3d-8ea5-f3729aa5592c)

### How can the issue be reproduced?

I don't remember it that clearly. I couldn't even remember if the program that I copied from was able to use this feature or not. But I remember a bit that I copied this portable program, that I already installed everything from content store.  (Which has been used from another computer before.) And I ran it. Everything seems to work as a first glance. Then I updated everything I could be able to update in content store. When I tried to use it, it happened. I tried to remove and reinstall but it still did not work.

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable, then remove and use MSI.

### Additional context?

I can still open files from it, but not for disk and volume.
Also, can you improve searching speed? It is painfully slow to be able to bear.

**Comment by WerWolv** [comment]
Hey
That's a very weird issue, it works fine on my machine. That popup is set to always auto resize so it should always display all the content in it. Could you try deleting `%localappdata%/imhex/config/interface.ini`?

About the search speed, could you give some more context? Searching is reasonably fast for me too. Even in a debug build, it searches through a 120MB file in about 10 seconds

**Comment by zorone** [comment]
Wow, you were right. It just solved my issue completely. I am too amazed that it turns out like that.
![Screenshot (4698)](https://github.com/WerWolv/ImHex/assets/60736083/3c026de3-4912-4dcc-8d72-a48eefd95fda)

For your info, I also put interface.ini here too.
[https://pastebin.com/KGFysmyT](https://pastebin.com/KGFysmyT)

I assume it might be caused by wrongly set from different system. And it didn't handle it properly to adapt to new system, I guess?

About file searching speed, maybe I might be too biased in that manner. I just feel like HxD is faster. I don't really have any evidence though. Maybe I could try to set a timer and count for that later. And also open new issue, I supposed?

I don't know if I should close this issuse or not, because we didn't do anything and it just fixed itself before my eyes. It could still happen later too. You can close this issue if you want, though.

**Comment by zorone** [comment]
Wait, it happened again...
![Screenshot (4699)](https://github.com/WerWolv/ImHex/assets/60736083/f4069578-a222-4abf-bce4-7839c6b24d06)

It just happens after I close drive G: from tabs because in Windows Explorer, it shows Access is denied.  And although I close drive G: tab, I still can't access drive G. When I try to use disk provider again, it just happens like before... I want to cry now.

**Comment by zorone** [comment]
I will reproduce it again.

Removing interface.ini, then launch ImHex as admin. Nothing was created.
![Screenshot (4709)](https://github.com/WerWolv/ImHex/assets/60736083/3200b7db-1d49-4834-af31-4fe9f5d91674)

Open drive G, Open successfully; nothing was created.
![Screenshot (4711)](https://github.com/WerWolv/ImHex/assets/60736083/90f0bfea-04cc-4ce2-8639-27f0b1a6d501)

Click on drive G: in Windows Explorer, access is denied.
![Screenshot (4712)](https://github.com/WerWolv/ImHex/assets/60736083/3185a394-89e0-49f2-8e0c-3d2bba17b685)

close Hex Editor tab, G: drive is still not accessible.
![Screenshot (4713)](https://github.com/WerWolv/ImHex/assets/60736083/d8209ac5-3b67-4aac-b05b-e284cc8a13d0)

reopen G: drive in ImHex, get weird dialog. Nothing was created.
![Screenshot (4714)](https://github.com/WerWolv/ImHex/assets/60736083/bc7ec2af-e48f-4504-904e-63c87543cd3d)

Close ImHex, interface.ini have been created.
![Screenshot (4715)](https://github.com/WerWolv/ImHex/assets/60736083/f455945a-cb6d-4a82-87e0-1cab73a4f28b)

interface.ini at this stage. Not the same as 3 files prior.
[https://pastebin.com/Z98UTEvw](https://pastebin.com/Z98UTEvw)


I hope this help. And I hope what I did is not overwhelm you.

**Comment by zorone** [comment]
3rd times reproduction.

remove interface.ini and reopen it. Nothing was created.
![Screenshot (4716)](https://github.com/WerWolv/ImHex/assets/60736083/289fa7ba-3639-4289-9f60-f9a44a4baef6)

Open G: drive. It shows this screen. Nothing was generated.
![Screenshot (4718)](https://github.com/WerWolv/ImHex/assets/60736083/e915bbc4-3689-42d2-ac5e-9bc2d19d86a8)

Open Hex editor page. Nothing was generated.
![Screenshot (4719)](https://github.com/WerWolv/ImHex/assets/60736083/bd626d02-2c23-4830-bb81-a341f50bc8bb)

close at G: tab, nothing was generated.
![Screenshot (4720)](https://github.com/WerWolv/ImHex/assets/60736083/94d44907-2e33-41f3-afd3-7526ddbbcba9)

reopen G: drive again, working normally; nothing was generated.
![Screenshot (4721)](https://github.com/WerWolv/ImHex/assets/60736083/2268c99e-ec1f-46df-89d6-3626e2020cfe)

closing ImHex, interface.ini have been created.
![Screenshot (4722)](https://github.com/WerWolv/ImHex/assets/60736083/f2d8098b-f7ba-46fd-9bd9-cd21c2677a76)

interface.ini, the file wasn't the same as 4 files prior.
[https://pastebin.com/2nWFFAjc](https://pastebin.com/2nWFFAjc)

reopen ImHex. interface.ini is still the same as before.
![Screenshot (4723)](https://github.com/WerWolv/ImHex/assets/60736083/d16e92ed-baa7-4e21-be47-6bbd5472e945)

open G: drive. Still doesn't edit anything.
![Screenshot (4724)](https://github.com/WerWolv/ImHex/assets/60736083/f7ff24e9-0630-4cf0-9abc-5069417879bd)

Close Hex Editor tab. Nothing was changed.
![Screenshot (4725)](https://github.com/WerWolv/ImHex/assets/60736083/71c9ab16-e6b9-4eb4-be60-c1fdb93b16ee)

reopen G drive, shows weird dialog. Nothing was changed. (It looks like I need to click ok 2 times. Because clicking ok first time won't close choosing drive dialog box.)
![Screenshot (4726)](https://github.com/WerWolv/ImHex/assets/60736083/ddde4691-68b5-4a69-993c-b80b8b7217ac)

Closing ImHex, interface.ini were changed. Not the same as last 5 files.
![Screenshot (4727)](https://github.com/WerWolv/ImHex/assets/60736083/a4c2d08a-4de8-4949-8c56-93c7f8194460)

interface.ini at this stage:
[https://pastebin.com/nmgsEpQ6](https://pastebin.com/nmgsEpQ6)

Hope this helps.

**Comment by zorone** [comment]
@WerWolv Can you let me fix this bug myself. I want to get some experience while I am still studying in collage as much as possible. Thank you.

**Comment by WerWolv** [comment]
> Can you let me fix this bug myself. I want to get some experience while I am still studying in collage as much as possible. Thank you.

Yeah of course!

> Does this codebase already implement existed provider check? I couldn't find it. Maybe I just blinded.

What do you mean "implement existed provider check"?

**Comment by zorone** [comment]
I mean that is there a way to know whether or not this provider for this specific file is in used. Bacause it could block an access to that particular file for another provider too, I think? I don't use English as my main language, so sorry if I make you confused.

**Comment by WerWolv** [comment]
Ah. No, there's no way to do that right now. The FileProvider for example will just try to load whatever file you throw at it and either open it or display an error if it fails.
