### ISSUE TITLE
Pasting in a page after first one pastes to wrong page.

### ISSUE THREAD

**Issue by butscher** [WerWolv/ImHex#1291]
If you have a large file with multiple pages and paste in the hex editor into a page which isn't the first one, the data is pasted to the wrong page. It follows a pattern:

At page 1 it pastes into page 1
At page 2 it pastes into page 3
3 -> 5
4 -> 7

From a short look at the source I guess that here:

https://github.com/WerWolv/ImHex/blob/26f4aa0d9fb270441cfb635cfd4acb7070153e0d/plugins/builtin/source/content/views/view_hex_editor.cpp#L737

the current page address is added twice.

**Comment by WerWolv** [comment]
Thanks a lot for the report! Latest commit should fix this
