### ISSUE TITLE
[Bug] The float -> buffer -> float conversion in the Data Processor doesn't work

### ISSUE THREAD

**Issue by Nemoumbra** [WerWolv/ImHex#1293]
### Operating System

Windows

### What's the issue you encountered?

![image](https://github.com/WerWolv/ImHex/assets/62447396/3ef44dfa-a084-46c7-b414-d5f4357e1ed0)

The method `const long double& Node::getFloatOnInput(u32 index)` makes the buffer's length equal to 16,
but `sizeof(float) == 4`.
That's why in the method `NodeCastBufferToFloat::process()` the exception is thrown.

### How can the issue be reproduced?

Recreate the scheme as shown in the image.

### ImHex Version

Self-built version (one of the latest)

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Self-built.

**Comment by paxcut** [comment]
It looks like latest release fixed this issue.

![image](https://github.com/WerWolv/ImHex/assets/53811119/b5fe80e6-e4b9-4fbb-a99a-e6d7e1266c71)

**Comment by Nemoumbra** [comment]
Alright, I'm closing this then.
