### ISSUE TITLE
[Bug] Struct passed to `auto` function parameter ignores endianness setting

### ISSUE THREAD

**Issue by bgilbert** [WerWolv/ImHex#1295]
### Operating System

Linux

### What's the issue you encountered?

If a struct is passed to an `auto` parameter of a pl function, that function will access the struct's fields without performing any configured endianness conversion.  This doesn't happen if the parameter has a concrete type, or if a primitive value is passed.

### How can the issue be reproduced?

Consider a file containing four bytes, `00 00 00 08`.  Then this pattern code:

```
#include <std/io.pat>

#pragma endian big

struct S {
    u32 v;
};

fn f_concrete(u32 v) {
    std::print("{}", v);
};

fn f_auto(auto v) {
    std::print("{}", v);
};

fn f_struct_concrete(S s) {
    std::print("{}", s.v);
};

fn f_struct_auto(auto s) {
    std::print("{}", s.v);
};

S s @ 0;

f_concrete(s.v);
f_auto(s.v);
f_struct_concrete(s);
f_struct_auto(s);
```

produces this output:

```
I: 8
I: 8
I: 8
I: 134217728
```

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Fedora (imhex-1.30.1-3.fc38.x86_64)

**Comment by paxcut** [comment]
Om windows 10 using latest commit I get
```
I: 8
I: 8
I: 8
I: 8
I: Pattern exited with code: 0
I: Evaluation took 0.0220405s
```

**Comment by paxcut** [comment]
I also tested on the plcli of my ubuntu wsl2 imhex build and got
```
[INFO]  8
[INFO]  8
[INFO]  8
[INFO]  8
[INFO]  Pattern exited with code: 0
```

**Comment by bgilbert** [comment]
I built `v1.30.1-243-g57084fd797ee` from source and am now seeing four `8` values as well.
