### ISSUE TITLE
[Roadmap] Any plan to support MOS6502 disassembly (already in capstone) ?

### ISSUE THREAD

**Issue by shazz** [WerWolv/ImHex#13]
Everything is in the title :)

Thanks !

**Comment by WerWolv** [comment]
Looks like the latest master of capstone has support for it but it's not yet in a release. I'd like ImHex to be buildable solely with packages available in mingw's and Arch's repository so it's easy to compile. So once capstone makes a new release, I'll make sure to add it :)
