### ISSUE TITLE
[Pattern language] Can't use asserts inside structs

### ISSUE THREAD

**Issue by Frain-Breeze** [WerWolv/ImHex#131]
![image](https://user-images.githubusercontent.com/43963404/104122852-bf2b4700-5347-11eb-9286-e3538ead1936.png)
self-explanatory, really. This is a vital feature for checking the integrity of a file, to make sure individual entries of whatever you're checking is as you expect them to be.

**Comment by WerWolv** [comment]
Function calls inside structs have been implemented
