### ISSUE TITLE
[Bug] Recent files with relative paths

### ISSUE THREAD

**Issue by ev1313** [WerWolv/ImHex#1312]
### Operating System

Linux

### What's the issue you encountered?

When opening imhex in a terminal with a path and then closing it, it will save a relative path in the recent files settings.

When opening imhex in a different working directory, the recent files functionality will not work, because a relative path was saved.

### How can the issue be reproduced?

Open imhex in a terminal with a relative path to a file.
Close imhex.
Open imhex in a different working directory.
The recent files function for the previously opened file doesn't work.

### ImHex Version

v1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Archlinux AUR

**Comment by iTrooz** [comment]
I can reproduce it with the v1.30.1 version but not the latest nightly, considering this as fixed
