### ISSUE TITLE
[Bug] Pattern data (size, start, end) not calculated

### ISSUE THREAD

**Issue by d-Rickyy-b** [WerWolv/ImHex#1313]
### Operating System

Windows

### What's the issue you encountered?

I am currently creating a pattern file for KeePass kdbx files. While doing so I found that for a specific struct imhex does not generate `size`, `start` and `end` values. 

![image](https://github.com/WerWolv/ImHex/assets/5798157/0cd7a151-902d-4b62-9a98-80b7ebe6f6a3)

I also tested this with the latest commit (https://github.com/WerWolv/ImHex/commit/ad69ac84b136441b3bf8d262bd05fac9f33e6be2). While the fields were no longer empty but instead all showed `0x00`

![image](https://github.com/WerWolv/ImHex/assets/5798157/458ed44d-d80f-42ce-ad6a-34ac42d41ef1)

I assume it has something to do with the dynamic array size in the header. The header is parsed until a specific sequence is found.

This is my minimal pattern to reproduce:

```
#pragma description kdbx file format
#pragma base_address 0x00

#include <std/mem.pat>
#include <std/io.pat>

// All kdbx files share a common set of magic bytes @ 0x00
enum MagicBytes : u32 {
    keepassMagic = 0x9AA2D903
};

// kdbx files contain different signatures depending on the version they were created with
enum KeepassSignature : u32 {
    v1    = 0xB54BFB65,
    v2pre = 0xB54BFB66,
    v2    = 0xB54BFB67
};

// The kdbx header consists of multiple Type-Length-Value entries
struct TLV_Entry {
    u8 type [[color("80ff00")]];

    // Length has different size depending on kdbx version
    match (parent.KDBXVersionMajor) {
        (3): u16 length  [[color("0080ff")]];
        (4): u32 length [[color("0080ff")]];
        (_): return;
    }

    u8 value[length] [[color("00bfff")]];
    
    // Add extra check for EndOfHeader so that value gets parsed properly
    if (type == 0x00) {
        break;
    }
};

// Find the offset of the end of the header
u32 EndOfHeaderOffset = std::mem::find_sequence(0, 0x0d, 0x0a, 0x0d, 0x0a);

struct Header {
    MagicBytes magicBytes @ 0x00;
    KeepassSignature keepassSignature @ 0x04;
    
    u16 KDBXVersionMinor @ 0x08;
    u16 KDBXVersionMajor @ 0x0A;
    
    std::print("Parsing KDBX version {}.{}", KDBXVersionMajor, KDBXVersionMinor);
    
    // Dynamically parse all the TLV entries of the header until the EndOfHeader entry was found
    TLV_Entry HeaderFields[while($ < EndOfHeaderOffset)] @ 0x0C;
};

Header header @ 0x00;
```

### How can the issue be reproduced?

1. Load any kdbx file
2. Load my kdbx pattern
3. Check the `size`, `start` and `end` values

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

### Additional context?

For testing purposes I uploaded a freshly created, default kdbx file with KeePass 2. You can find it [here on OneDrive](https://1drv.ms/u/s!AvB3ORp6GdgeiWswowZ4lhyFnlbW).

**Comment by d-Rickyy-b** [comment]
Okay, when removing the @ offsets from the struct, the size, start and end fields are calculated and displayed correctly.

```
struct Header {
    MagicBytes magicBytes;
    KeepassSignature keepassSignature;
    
    u16 KDBXVersionMinor;
    u16 KDBXVersionMajor;
    
    std::print("Parsing KDBX version {}.{}", KDBXVersionMajor, KDBXVersionMinor);
    
    // Dynamically parse all the TLV entries of the header until the EndOfHeader entry was found
    TLV_Entry HeaderFields[while($ < EndOfHeaderOffset)];
};
```
Is it intended that the sizes aren't correctly calculated when the @ offsets are present?

**Comment by paxcut** [comment]
When the pattern does
```cpp
Header header @ 0x00;
```
it places the entire Header struct at position zero so there is no need to place the members of Header again. Moreover if you place the members of Header it creates what is called a view of the data. Views do not advance the cursor like normal members do so the start offset of the next member will occur at the same offset as the one with the @ sign.
```cpp
struct Header {
u8 aView @0;
u8 aMember; // located at zero
};
Header header @0;
```

**Comment by d-Rickyy-b** [comment]
Thank you @paxcut that makes sense.
