### ISSUE TITLE
Can't open saved project on MacOS Sonoma

### ISSUE THREAD

**Issue by palmerj** [WerWolv/ImHex#1315]
### Operating System

MacOS

### What's the issue you encountered?

When opening a project saved with the same version on the same OS it reports "failed to open project: {}". Then "Invalid magic file in project file"

### How can the issue be reproduced?

Save a new project and then try to reopen in.

This is the project file I was testing:

[test.hexproj.zip](https://github.com/WerWolv/ImHex/files/12670069/test.hexproj.zip)

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

homebrew, but have tested both DMG files too. 

### Additional context?

Using M2 Max Macbook pro 16"

**Comment by WerWolv** [comment]
Hey, thanks for the report
Does this happen every time you save a project file? 
Projects are basically just fancy .tar files and there should be a `IMHEX_METADATA` file inside of it. Somehow your project doesn't contain it so ImHex doesn't recognize the project as a valid ImHex project. From what I can tell, it works fine on both Windows and Linux.

Could you maybe try using the latest nightly release and see if it works there? You can download it from https://imhex.download/#nightly

**Comment by paxcut** [comment]
Both WinRar and 7zip find problems with the posted project. The first says that the archive is corrupt but it is unable to repair it. The second says there is data past the end of the extracted content.
