### ISSUE TITLE
[Bug] Crash when editing pattern with auto-eval enabled

### ISSUE THREAD

**Issue by speps** [WerWolv/ImHex#1318]
### Operating System

Windows

### What's the issue you encountered?

When editing a pattern and auto-eval is enabled, it crashes even though the pattern itself works with auto-eval.

### How can the issue be reproduced?

Pattern:
```
u8 name_len @ 0x4;
char name[name_len] @ 0x5;
u32 num_samples @ (0x5 + name_len);
```

File: [R1BS100.zip](https://github.com/WerWolv/ImHex/files/12699385/R1BS100.zip)

On line 3 if you edit it by pressing Backspace with the cursor after the 5, it will crash.

[20230922_095556.log](https://github.com/WerWolv/ImHex/files/12699369/20230922_095556.log)

### ImHex Version

1.30.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by sisco0** [comment]
@speps, could you check if the PR #1387 solution solves the current inconvenience?
Thank you in advance!
