### ISSUE TITLE
[Bug] 1.31.0 - imhex-gui.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by mi-hol** [WerWolv/ImHex#1320]
### Operating System

Windows

### What's the issue you encountered?

![image](https://github.com/WerWolv/ImHex/assets/22799428/d193f2de-652e-448d-8d53-676000bf3a76)

### How can the issue be reproduced?

just run it

### ImHex Version

1.31.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by WerWolv** [comment]
Hey
That's really weird, did you install everything correctly? I just tried all the Windows releases myself and they seem to work fine

**Comment by mi-hol** [comment]
> did you install everything correctly

Please tell me how a .MSI can be installed incorrectly?
As I know MSI it's usually a  previous setup that is not handled by the code in MSI.
I remember that I had previously used a portable version and now replaced it with 1.31.0 portable NoGpu due to above error.
This version works

**Comment by PerikiyoXD** [comment]
Probably you've upgraded a previous installation?

Provide details as:
Windows version
Did you update the imhex version? Or did you remove and install?

**Comment by PerikiyoXD** [comment]
Try uninstalling imhex, make sure the installation folder is empty, and then fresh-install imhex.

Tell us what you've got after that.

**Comment by mi-hol** [comment]
fixed
