### ISSUE TITLE
[Bug] Segfault when exiting (sometimes)

### ISSUE THREAD

**Issue by chenxiaolong** [WerWolv/ImHex#1321]
### Operating System

Linux

### What's the issue you encountered?

When closing ImHex's window (without having done anything else), the program sometimes segfaults. This happens with a default configuration (empty `~/.config/imhex`).

This seems to be happening on both of my machines:

* Desktop: Fedora 38 + KDE + X11 session
  * GPU: Nvidia
  * Segfaults on almost every exit.
  * Stack traces from the last 5 crashes (with debug info): https://gist.github.com/chenxiaolong/9fd6e79960094e689fc29d44381cf094
* Laptop: Fedora 38 + KDE + Wayland session
  * GPU: Intel + Nvidia, but only Intel is active (confirmed that no Nvidia libraries were present in `/proc/$(pidof imhex)/maps`)
  * Segfaults much less frequently than desktop. Maybe every 1 out of 10 attempts.
  * Stack traces from the last 5 crashes (with debug info): https://gist.github.com/chenxiaolong/f8fb159a01c48859ab7b820e07c24fb1

In every case, the messages logged to the terminal after clicking the exit button (or Alt+F4) are:

```
[16:51:34] [FATAL] [main]       Received signal 'SIGSEGV' (11)
[16:51:34] [INFO]  [main]       Wrote crash.json file to /home/chenxiaolong/.config/imhex/config/crash.json
zsh: segmentation fault (core dumped)  imhex
```

The `crash.json` file contains:

```json
{
    "logFile": "",
    "project": ""
}
```

What's weird is that the crash seems to happen at different spots every time. I see the crash handler present in most of these stack traces, so hopefully I'm not grabbing the wrong thing (I'm running `gdb` against the core dump and then `thread apply all bt`).

### How can the issue be reproduced?

1. Open ImHex.
2. Close ImHex.
3. Repeat until crash. (Depending on machine, it may take 20-30 attempts or it may happen nearly every attempt.)

### ImHex Version

1.31.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Fedora package from Fedora's repos, Fedora package from ImHex's release page, and also building from source. All exhibit the same problem.

### Additional context?

(Included in the description above)

**Comment by ZeChArtiahSaher** [comment]
Same thing happens with some files on osx

**Comment by chenxiaolong** [comment]
I'm closing this because I haven't been able to reproduce this with any of the recent imhex releases (running on Fedora 40 KDE Wayland).
