### ISSUE TITLE
[Bug] Editing last byte modifies next

### ISSUE THREAD

**Issue by aedrax** [WerWolv/ImHex#1329]
### Operating System

MacOS

### What's the issue you encountered?

When in the edit mode of the last byte of the row in the Hex Editor, as soon as you hit escape, it will modify the next byte on the following row. It seems to overwrite this byte with the byte in the row above it.
 
![Screenshot 2023-09-28 at 4 34 28 PM](https://github.com/WerWolv/ImHex/assets/5616068/dd0f7868-4fda-44ea-9a05-816d7091af25)
![Screenshot 2023-09-28 at 4 35 04 PM](https://github.com/WerWolv/ImHex/assets/5616068/e58fcafa-ff68-4c23-961a-8c3281836669)
![Screenshot 2023-09-28 at 4 35 09 PM](https://github.com/WerWolv/ImHex/assets/5616068/e4babfb0-94dd-4b11-95f3-7a2b139bd611)

### How can the issue be reproduced?

Click the last byte in a row, enter edit mode with double clicking or pressing 'enter', then hit escape.

### ImHex Version

1.31.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

DMG

### Additional context?

I also tried this on 1.29.0 and the behavior was occurring there as well

**Comment by aedrax** [comment]
More information, this only occurs when `Show ASCII` is also enabled

**Comment by aedrax** [comment]
I've narrowed it down to when this line is enabled: https://github.com/WerWolv/ImHex/blob/e241adab0e1f3896a1071b883380bccf6b6e925d/plugins/builtin/source/ui/hex_editor.cpp#L506

**Comment by CherryDT** [comment]
I can confirm this on Windows too.
