### ISSUE TITLE
[Feature] Support placement syntax inside of structs for calculated/relative pointers

### ISSUE THREAD

**Issue by kitlith** [WerWolv/ImHex#133]
```
struct Parent {
  u16 child_offset;
  Child child @ child_offset;
};
```
would be equiv to
```
struct Parent {
  Child *child : u16;
};
```
and this would also allow for e.g.:
```
struct Parent {
  u16 child_offset;
  // offsets are relative to something else
  Child child @ child_offset + 0x200;
};
```

EDIT: apologies in advance if this is already implemented, i just realized i wasn't testing with the latest version of imhex. >_>

**Comment by WerWolv** [comment]
We were discussing exactly this the other day on the Diacord server. The issue with the placement syntax is, it creates a new member somewhere outside of the struct. So it looks like you're defining a new struct member but that "member" doesn't actually count towards the size of the struct because it's more of a directive for where to put a pattern. I'd find this extremely confusing as a new user.

The solution for this would be to add more syntax to the existing pointers that allows you to specify a base, do math with it's address, etc. Since pointer read the data at the address they are located on, they are part of the struct and count towards its size.

So far I couldn't come up with a good syntax though so if you have an idea, I'd love to hear it :)

**Comment by roblabla** [comment]
> The solution for this would be to add more syntax to the existing pointers that allows you to specify a base, do math with it's address, etc. Since pointer read the data at the address they are located on, they are part of the struct and count towards its size.

Take the following:

```c
struct Test {
    u32 offset;
    u32 size;
    // Assuming we can use FTell() to get the current location for relative offsets.
    u8 data[size] @ FTell() - 8 + offset;
}
```

If we go down the "do math with its address" path, we end up in a tricky situation where we need access to the later fields to define the current one. Here's an example with some very bikesheddy things:

```c
struct Test {
    // A pointer to an u8 array of size bytes.
    u8 *offset[size] : u32;
    u32 size;
}
```

Size is defined *after* the pointer. Could this work?

What about types where the pointer is "split"? Take for instance a [GDT](https://en.wikipedia.org/wiki/Global_Descriptor_Table#/media/File:SegmentDescriptor.svg), which can be defined like so:

```c
struct GDT {
    u16 base_lo;
    u16 segment_limit;
    u8 base_mid;
    u8 flags1;
    u8 flags2;
    u8 base_hi;
    u8 bytes[segment_limit] @ base_lo + base_mid << 16 + base_hi << 24;
}
```

TBF, nobody would likely try to parse a GDT with ImHex, but I've seen this kind of weird "address is split" schemes in file formats that have a long legacy history and tried to add 32-bit support in a backward-compatible way. How would those get represented?

**Comment by kitlith** [comment]
> The issue with the placement syntax is, it creates a new member somewhere outside of the struct. So it looks like you're defining a new struct member but that "member" doesn't actually count towards the size of the struct because it's more of a directive for where to put a pattern. I'd find this extremely confusing as a new user.

As a new user, this was one of the first things I thought of along these lines, and it seemed like a natural extension, but I get where you're coming from.

So, new thought -- if calculated members are implemented (i.e. they add no size to a strict, and contain constants or the result of some calculation) then an alternate form of placement syntax (also usable in structs) could be something like this:

```
u16 child_offset;
Child *child = child_offset + 0x200;
```

but this probably looks too much like member declaration once again. it is also exactly the other solution I immediately reached for.

perhaps you could create a new keyword, call it "place" that is required for placement syntax inside structs? Make it optional when used at top level, to keep compat with existing patterns. Placement syntax would then look like `place Type name @ location`

**Comment by nikitasius** [comment]
it will be very handy, i'm agree
```
be u32 count @ 0x6;

struct Header {
  be u64 cityhash;
  be u64 offset;
  be u16 size;
  char data[size] @ offset;
};

Header headers[count] @ 0x1000;
```

and we have headers and data where they are points

**Comment by WerWolv** [comment]
Something like this that's more part with the philosophy of the language is the `pointer_base` attribute. You can find the documentation about it here: https://imhex.werwolv.net/docs/pattern_language/attributes.html#pointer-base-pointer-base-function-name-1-10-1

**Comment by nikitasius** [comment]
> Something like this that's more part with the philosophy of the language is the `pointer_base` attribute. You can find the documentation about it here: https://imhex.werwolv.net/docs/pattern_language/attributes.html#pointer-base-pointer-base-function-name-1-10-1

thanks, but i have no time to learn C, you know :)

**Comment by nikitasius** [comment]
or even remember those days.. and article is good but there are no examples from A to Z.

**Comment by nikitasius** [comment]
@WerWolv just some criticism about your docs that they aren't adapted for folks who do not code on C.

`[[pointer_base("pointer_base_function_name")]]` and https://imhex.werwolv.net/docs/pattern_language/standard_library/std_ptr.html#pointer-helpers mean zero for me (and maybe for someone else).

Same time if we can say `char data[size]` where `size` is a struct field, we could say `char data[size] @ offset;` where offset is a field too. This is looks logic but fails when i try it.

**Comment by WerWolv** [comment]
That's not logic at all. @ means place some variable AT some location. That syntax therefore would mean "place the pointer variable at some other location" which completely breaks the reason why structs exist, to bundle values together.

For the attributes, they are used like this:

```rust
#include <stdlib/ptr.pat>

struct Test {
    u32 *pointer : u16 [[pointer_base("relative_to_pointer")]];
};

Test test @ 0x00;
```

`relative_to_pointer` is simply a function defined in stdlib/ptr.pat that returns the new base address where the offset value gets afded to. This function returns the current offset so the pointer becomes relative to itself.

I'm going to add some more examples when I have time but it's a lot of work. The Pattern repository is usually a good source for inspiration and to learn how everything works.
