### ISSUE TITLE
[Bug] Break statemeant inside the loop not terminated the third block of the For

### ISSUE THREAD

**Issue by Pruvet1** [WerWolv/ImHex#1338]
### Operating System

Windows

### What's the issue you encountered?

Break statemeant inside the loop not terminated the third block of the For

### How can the issue be reproduced?

Source:
`  

fn SKIP_SPACE(str source,u32 i){ 

    std::print("1:i= {0},{1},",i,source[i]);
    for(i=i,i<std::string::length(source)-1,i+=1){                
        if(source[i]=='\r' && source[i+1]=='\n') break;                
        if(source[i]!=' ') {std::print("2:i= {0},{1},",i,source[i]); ;break;}            
    }
    std::print("3:i= {0},{1},",i,source[i]);    
    return i;
};`
Console output:
I: 1:i= 7, ,
I: 2:i= 16,s,
I: 3:i= 17,e,

### ImHex Version

1.31.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by paxcut** [comment]
maybe the problem is the choice in names for arguments and variables. Arent you using i in both places ? for example the loop
```cpp
for(i=i,i<std::string::length(source)-1,i+=1){ 
```
Is this intended?

**Comment by Pruvet1** [comment]
yes,that's what it's meant to be

 

------------------------------------------------------------------------------------------

С Уважением

 

Главный специалист отдела разработки ПЛК и платформы ЦИКЛОН 

ООО СибКом Цифра

Альберт Евгеньевич Акчурин

+7 (347) 222-84-22 доб.134

 ***@***.***> ***@***.***

**Comment by paxcut** [comment]
ok, just checking, maybe you mean to use return instead of break? break will evaluate until the end of the struct always, but when a break is hit that will be the last evaluation. Return otoh returns immediately sand no more statements are evaluated from the struct/

**Comment by paxcut** [comment]
Could you provide some example input and the expected console output?

**Comment by paxcut** [comment]
It looks like the code works as written. The following code
```cpp
#include "std/string.pat"

fn SKIP_SPACE(str source,u32 i){

    std::print("1:i= {0},{1},",i,source[i]);
    for(i=i,i<std::string::length(source)-1,i=i+1){                
        if(source[i]=='\r' && source[i+1]=='\n') {
          break;
        }
        if(source[i]!=' ') {
            std::print("2:i= {0},{1},",i,source[i]);
            break;
        }            
    }
    std::print("3:i= {0},{1},",i,source[i]);    
    return i;
};

SKIP_SPACE("        \r\n",1);
```
produces this
```cpp
I: 1:i= 1, ,
I: 3:i= 9,
I: ,
I: Pattern exited with code: 0
I: Evaluation took 0.0024525s
```
which is what I would expect.

**Comment by Pruvet1** [comment]
SKIP_SPACE(" test1",1);
 
SKIP_SPACE("test2",1);
 

 

------------------------------------------------------------------------------------------

**Comment by paxcut** [comment]
Ok, i tried those and they return
```cpp
I: 1:i= 1,t,
I: 2:i= 1,t,
I: 3:i= 2,e,
I: 1:i= 1,e,
I: 2:i= 1,e,
I: 3:i= 2,s,
I: Pattern exited with code: 0
I: Evaluation took 0.0191265s
```
So yes, the third block of the loop is executed before loop is exited. The documentation on [break](https://docs.werwolv.net/pattern-language/core-language/control-flow#break) does not address how it behaves inside a for loop, but it says that in structs it keeps all the array elements that have been processed so far including the one being processed. In a for loop that implies that the end of the loop will be reached and the third block will be executed once before the loop is exited. 

Keep in mind that although the pattern language may have a syntax that is similar to C/C++ in some cases, this does not imply that we should expect it to behave like C or C++. I don't know for sure, but this may be one of those cases. Somebody who is more familiar with how the exact inner working of pl would have to comment here. My guess is that this is how it was implemented but never checked rigorously. At the very least it was never fully documented.
