### ISSUE TITLE
[Bug] Random freeze when moving window in Linux

### ISSUE THREAD

**Issue by abiriadev** [WerWolv/ImHex#1348]
### Operating System

Linux

### What's the issue you encountered?

The window freezes randomly, not only when I move the window but also when I move the cursor.

I couldn't figure out what is the exact cause for this.

https://github.com/WerWolv/ImHex/assets/72962900/7e8b6efb-c2ae-4c1c-8666-8c45bf395b3a

### How can the issue be reproduced?

This issue can be seen in both AUR `imhex-bin` and manual build.

First, I cloned the repository and followed [compiling guide](https://github.com/WerWolv/ImHex/blob/master/dist/compiling/linux.md) exactly.

Also, I used `glfw-x11 3.3.8-1`.

### ImHex Version

1.31.0

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

both AUR and manual build.

### Additional context?

Used commit for build: e2b7427

Thank you for your help in advance.

**Comment by WerWolv** [comment]
Hey! It looks like ImHex opens a popup window, probably one that asks you on the first start if you want to allow telemetry, however it seems to open it somewhere off-screen so you can't interact with it. You can try deleting the `~/.config/imhex/config/interface.ini` file maybe and hope the popup will appear back on-screen again

**Comment by WerWolv** [comment]
The latest commit should now force popups back to the center of the screen in cases like this

**Comment by abiriadev** [comment]
It works like a charm! Thank you for creating such a great tool!
