### ISSUE TITLE
ImHex as a library

### ISSUE THREAD

**Issue by Lectem** [WerWolv/ImHex#135]
I just discovered ImHex and I already like it (I was looking for a free replacement to 010 editor and its templates.
Since ImHex uses imgui, I immediatly thought the following:

Could it be easily integrated in another game/engine that already has ImGui support ?
This is somehow #84 but pushed further: isolate anything platform specific so that we can just "plug an play" in another engine.
You could even imagine using DLL injection mentioned in (such as the one mentioned in your blog the https://werwolv.net/blog/dll_injection ) to analyze a process! (debugger ?)

It's a wild suggestion, but it would be awesome !
(My use case would be for a file explorer for Diablo2 reverse engineering)

**Comment by WerWolv** [comment]
Hi!
Yeah that might in theory be possible, however it doesn't really sound practical to me. Instead, consider making a plugin for ImHex that can attach to Diablo (or other processes) and provides all features you're looking for. Plugins allow you to add new windows, data sources and a lot of other things. Check out the wiki for that.

**Comment by Lectem** [comment]
Well writing a plugin definitely is a solution, but I can't help but like the idea of having all the visualization tools being in the same window, as for example it makes it easier when in fullscreen.
It's definitely not a "must have", but still think it'd be awesome and (maybe?) easier than writing a plugin at 1st!

**Comment by WerWolv** [comment]
It is absolutely not easier to do as it requires changing a lot of the glfw window code, docking and multi-viewport code. ImHex is not designed for that. Plugins however give you a flexible way of integrating your own functionality that you need for your project without killing compatibility with other plugins and my own additions. All inside a separate and tidy window.
You are of course free to fork ImHex and try yourself but I discourage it.
