### ISSUE TITLE
Closing non focused tab freezes the rest

### ISSUE THREAD

**Issue by MilanTodorovic** [WerWolv/ImHex#1350]
### Operating System

Windows

### What's the issue you encountered?

If you have two or more tabs open and then close the left most tab when it is NOT in focus, the program freezes other tabs and prompts you to the welcome screen. In order to unfreeze them, you must open a new file.

![frozen_tab](https://github.com/WerWolv/ImHex/assets/12709764/60aaf2eb-7159-4821-9729-df91775e6904)

### How can the issue be reproduced?

Open two files.
Click on the second tab.
Close the first tab by clicking the X button.

### ImHex Version

1.31.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

### Additional context?

Windows 10 Pro 22H2
Build 19045.3516

**Comment by WerWolv** [comment]
Thanks for the report! I fixed this issue a few days ago but it's not in a release yet. You can use the nightly version for now which has the issue corrected. https://imhex.download/#nightly
