### ISSUE TITLE
[Bug] diff table not visible

### ISSUE THREAD

**Issue by dsl400** [WerWolv/ImHex#1362]
### Operating System

Linux

### What's the issue you encountered?

first the diff table was not resizable but usable, after a few restarts it is no longer visible  

### How can the issue be reproduced?

no details yet

### ImHex Version

1.25.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

appimage

**Comment by WerWolv** [comment]
Hey

Please update ImHex to the latest version. We're on version 1.31.0 by now and the diff view has since been completely rewritten. If the issue still persists, please let me know.
