### ISSUE TITLE
Opening screen can have windows overlayed

### ISSUE THREAD

**Issue by paxcut** [WerWolv/ImHex#1364]
### Operating System

Windows

### What's the issue you encountered?

If a window is docked at the top of the ImHex display, the next time ImHex starts shows that window overlaying the normal starting window.

### How can the issue be reproduced?

1) start ImHex and select View>Tools. Drag the ASCII table tool out of tools and dock it at the top-center docking point. Exit ImHex and restart it (Project doesn't need to be saved because error occurs before project can be loaded). After the splash screen the following Initial window is displayed . To access the Initial window entry you have to close the ASCII table tab.

![image](https://github.com/WerWolv/ImHex/assets/53811119/9cc8c16e-e169-47db-b183-900b557e4f8a)

### ImHex Version

1.31.0

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

built locally using clion

**Comment by WerWolv** [comment]
Thank you! Latest commit should fix this
