### ISSUE TITLE
Feature Request: Clickable entropy graph

### ISSUE THREAD

**Issue by dmitry64** [WerWolv/ImHex#137]
It would be very useful to navigate in a file by clicking on entropy graph. For example if you see some spike on the graph, you click on it and hex editor window jumps to that position in the file.

**Comment by WerWolv** [comment]
Cool idea but currently not possible with ImGui. However the documentation states that clicking will properly be exposed in a future version. So once that's there, I'll definitely look into adding it.

**Comment by WerWolv** [comment]
This has been implemented. There's now a slider on the entropy graph
