### ISSUE TITLE
[Bug] File with chinese name can not open

### ISSUE THREAD

**Issue by qux-bbb** [WerWolv/ImHex#1380]
### Operating System

Windows

### What's the issue you encountered?

I have a file named "测试.exe_". If I open it with Context "Open with ImHex", ImHex will show:  
```
Failed to open provider: Failed to open file
D:\recent\tmp\??.exe_: No such file or directory
```

### How can the issue be reproduced?

Rename any file to a chinse name, then open it with Context "Open with ImHex".

### ImHex Version

1.31.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by iTrooz** [comment]
After investigating, I can reproduce this on Windows in release (1.31.0) (but not 1.30.1), but not on Linux

So I'm going to unassign for this and let someone who use Windows more pick it up
