### ISSUE TITLE
Feature Request: Add filename to window title

### ISSUE THREAD

**Issue by dmitry64** [WerWolv/ImHex#139]
It's a bit difficult to use multiple instances of ImHex because all windows have the same title. It would be much better if filename was in the window title so that you don't have to guess which file is in which window.
![image](https://user-images.githubusercontent.com/15170743/104908800-a3e7b980-598f-11eb-87b5-ba2e36897daa.png)

**Comment by WerWolv** [comment]
This has been implemented
