### ISSUE TITLE
v1.4.0 "File->Open File" dialog does not appear

### ISSUE THREAD

**Issue by mgerhardy** [WerWolv/ImHex#14]
Using latest release and trying to open a file doesn't bring up the dialog.

No log on the console.

Running on Debian testing.

Not sure if I should open a separate ticket as feature request for this, but it would be sweet to open a file from the command line.

Thanks a lot for the tool.

**Comment by WerWolv** [comment]
Hi! This is an issue in the v1.4.0. I was made aware of it already and fixed it in master so it will be available in v1.5.0.
In the meantime, the workaround is to just open the hex view first by going under `View -> Hex Editor View`. After that it will work :)

**Comment by gavz** [comment]
also drag and drop on windows 8.1 the program crashes

**Comment by farteryhr** [comment]
it seems to be dragging an exe into the window that crashes it.
opening exe through menu works, and dragging files of other types in works too.
