### ISSUE TITLE
Releases 1.6.0 and 1.6.1 broken on Windows 7 Entreprise

### ISSUE THREAD

**Issue by octy83** [WerWolv/ImHex#140]
Release 1.5.0 is working well but the two next releases fail to start, with different messages depending on the version:

1.6.0 has this error at launch
![Capture1 6 0](https://user-images.githubusercontent.com/77622452/104919188-23788700-5996-11eb-9c0c-fc26a8beb2c1.PNG)
I've checked that my system is not corrupted. 
This is true this DLL is missing but it is not detected as abnormal situation by Windows fixing tool. Is this dependency compliant with only some Windows version?

1.6.1 (Portable flavor) has this one
![Capture1 6 1](https://user-images.githubusercontent.com/77622452/104919233-3428fd00-5996-11eb-9d59-8e5de89248a0.PNG)
This issue was also present in some other projects (like https://lists.gnu.org/archive/html/help-gnu-emacs/2017-09/msg00154.html), and it seems it was solved by some libraries link order.

**Comment by MarcinT93** [comment]
this issue is still present in newest NightlyBuild (07.02)

**Comment by WerWolv** [comment]
The issue most likely is that everything is built on a Windows 10 machine. So it will link in Windows 10 system libraries. I'll try to setup a Windows 7 CI in the future but you may try to just compile ImHex yourself to get it to work in the meantime.

**Comment by MarcinT93** [comment]
Huh i need to create W7 VM then cause there are some dependencies i can not setup on my current config. I have found some info regarding this issue on web, maybe useful for you: [](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=28493)
        > The doc for ScriptFreeCache
        >       <https://msdn.microsoft.com/en-us/library/windows/desktop/dd319121(v=vs.85).aspx>
        >       has this note:
        >       [Important] Starting with Windows 8: To maintain the ability to run on
        >       Windows 7, a module that uses Uniscribe must specify Usp10.lib before
        >       gdi32.lib in its library list.

Its looks like the thing is the order of library, but my C++ knowledge is about zero...

**Comment by bvernoux** [comment]
This issue seems to comes from a dependency in the project as even when the full project is built on native Windows7 SP1 Pro/Entreprise there is the error ![image](https://user-images.githubusercontent.com/77622452/104919233-3428fd00-5996-11eb-9d59-8e5de89248a0.PNG) see https://github.com/WerWolv/ImHex/pull/158

**Comment by LionNatsu** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/usp10/nf-usp10-scriptfreecache
> Important  Starting with Windows 8: To maintain the ability to run on Windows 7, a module that uses Uniscribe _must specify Usp10.lib before gdi32.lib in its library list_.
