### ISSUE TITLE
[Bug] Can't import Data Processor Workspace

### ISSUE THREAD

**Issue by copyrat90** [WerWolv/ImHex#1405]
### Operating System

Windows

### What's the issue you encountered?

When I tried to load a Data Processor Workspace, it fails to load with this error message:
```
Failed to load nodes: [json.exception.type_error.305]
cannot use operator[] with a string argument with string
```

![image](https://github.com/WerWolv/ImHex/assets/34793045/115b1dc3-bc70-404e-ac25-f1cbb907b26b)

Also, loading the individual node gives the same error.

### How can the issue be reproduced?

1. Add any node in a Data Processor
2. Save the workspace via `File > Export... > Data Processor Workspace`
3. Try to load it via `File > Import... > Data Processor Workspace`

### ImHex Version

1.31.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Windows Portable NoGPU

**Comment by paxcut** [comment]
I was able to reproduce this bug, but only on last release. My local build loads the workspace just fine. I'll try a nightly build next and will post the result here.

**Comment by WerWolv** [comment]
Thanks for the report! This was indeed a bug in the latest release but I've since fixed it. Using the latest nightly as described by paxcut will solve the issue
