### ISSUE TITLE
[Bug] Structure instance passed as a template argument is not output to the pattern data

### ISSUE THREAD

**Issue by arcusmaximus** [WerWolv/ImHex#1412]
### Operating System

Windows

### What's the issue you encountered?

If you define a structure-typed field, then pass that field as a template parameter to another structure, the field is no longer output to the pattern data.

The same goes for array fields.

### How can the issue be reproduced?

The following snippet outputs three arrays that should be identical. However, while the WorkingArray shows its length field in the Pattern Data panel, the two BrokenArrays do not.

Note that, even though the BrokenArrays don't output their length, they still read it correctly (same number of elements in `content.data` as in WorkingArray).

```
// Passing a primitive value as a template argument

struct WorkingArrayContent<auto length>
{
    u8 data[length];
};

struct WorkingArray
{
    u8 length;
    WorkingArrayContent<length> content;
};

WorkingArray workingArray @ 0;




// Passing a structure instance as a template argument

struct BrokenArray1Length
{
    u8 length;
};

struct BrokenArray1Content<auto arrayLength>
{
    u8 data[arrayLength.length];
};

struct BrokenArray1
{
    BrokenArray1Length arrayLength;
    BrokenArray1Content<arrayLength> content;
};

BrokenArray1 brokenArray1 @ 0;



// Passing an array as a template argument

struct BrokenArray2Content<auto lengths>
{
    u8 data[lengths[0]];
};

struct BrokenArray2
{
    u8 lengths[1];
    BrokenArray2Content<lengths> content;
};

BrokenArray2 brokenArray2 @ 0;
```

### ImHex Version

1.31.0 7d53636

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Portable

**Comment by paxcut** [comment]
I tried the first three patterns using my own input file and it seems to work. can you also post input file to test bug?

**Comment by arcusmaximus** [comment]
A file with the following content will do: `01 00`
