### ISSUE TITLE
[Bug] Symlink in themes folder prevents built-in plugins from loading

### ISSUE THREAD

**Issue by EvelynTSMG** [WerWolv/ImHex#1428]
### Operating System

Windows

### What's the issue you encountered?

I created a symlink to a theme file in the themes folder
I tried to open ImHex
It [broke](https://discord.com/channels/789833418631675954/789838296376803358/1174483771676962946)

### How can the issue be reproduced?

1. Export a new theme using the Theme Manager
2. Create a symlink to it with `mklink C:\Users\%USERNAME%\AppData\Local\imhex\themes\theme.json .\theme.json`
3. (Re)Open ImHex

### ImHex Version

[dd2ecb3](https://github.com/WerWolv/ImHex/commit/dd2ecb3dd942c05f22b03f0f33449d257089d427)

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

ninja -j8 install, why is this field required when building from sources

### Additional context?

No code changes compared to commit

**Comment by iTrooz** [comment]
Hey, could you send us the log file ?

**Comment by EvelynTSMG** [comment]
[20231115_181044.log](https://github.com/WerWolv/ImHex/files/13370596/20231115_181044.log)
Presumably, ImHex tries to open it as a json file, while in reality it's a symlink which it should attempt to follow to the actual file

**Comment by EvelynTSMG** [comment]
As a quick sidenote, opening the symlink in ImHex caused a new file to be made
![image](https://github.com/WerWolv/ImHex/assets/96205195/4d077d20-6a47-4810-9912-efc7eede648d)

**Comment by WerWolv** [comment]
The issue is quite simply, ImHex never tries to follow symlinks. Honestly I'm also not sure if it actually should since symlinks can introduce a whole new kind of errors we and users will have to deal with if they're used improperly
