### ISSUE TITLE
Add alignment helper function to pattern language

### ISSUE THREAD

**Issue by Moneyl** [WerWolv/ImHex#143]
I have a file with the start of each data section aligned to 2048 bytes. I'm not sure how to handle alignment in variable placement as is. It'd be useful to have a built in alignment function. Usage might look something like this:
```c
u32 entryBlockSize @ 0;
u32 nameBlockSize @ 4;
u8 entryBlock[entryBlockSize] @ 8;
u8 nameBlock[nameBlockSize] @ align(2048, 8 + entryBlockSize);
```
So, for example, lets say entryBlockSize = 3000, then nameBlock would start at 4096. In c++ the align function might look like this:
```cpp
size_t align(size_t alignmentValue, size_t position)
{
    const size_t remainder = position % alignmentValue;
    size_t paddingSize = remainder > 0 ? alignmentValue - remainder : 0;
    return position + paddingSize;
}
```

**Comment by WerWolv** [comment]
Hi. That's a neat idea. 
For now you can do is `u8 nameBlock[nameBlockSize] @ ((entryBlockSize + 8) + 2048) & ~2048;` to align the value to 2048.
