### ISSUE TITLE
About the installation issue of macOS

### ISSUE THREAD

**Issue by zhxknb1** [WerWolv/ImHex#1432]
<img width="920" alt="image" src="https://github.com/WerWolv/ImHex/assets/59738277/075fd64c-e476-4c8d-99ac-c7a07f1d82d2">
Hello, distinguished developer. After opening the dmg file, how are the other two files (libnethost.dylib, plugins folder) placed or configured in addition to the imhex.app file? is there any use?

**Comment by WerWolv** [comment]
Hey. They're supposed to go into the ImHex.app. The next release will fix that problem though so if you want, you can download the latest nightly instead from https://imhex.download/#nightly
