### ISSUE TITLE
Variable placement relative to other variables

### ISSUE THREAD

**Issue by Moneyl** [WerWolv/ImHex#144]
EDIT: The example I gave here isn't depicting the problem I ran into. See my second message for a better one.

~~It'd useful if you could position variables relative to other variables. In particular when a file has dynamically sized buffers. Example:~~
```c
u32 entryBlockSize @ 0;
u32 nameBlockSize @ 4;
u8 entryBlock[entryBlockSize] @ 8;
//First argument is the variable we're offsetting from, second argument is the relative offset
u8 nameBlock[nameBlockSize] @ relative(entryBlock, entryBlockSize);
```
~~So, for example, if entryBlockSize = 200, then nameBlockSize would start at 208.~~

~~Note: I realize this looks very similar to the example I gave in #143. They're two different formats it just turns out the same example works well for both. Figured I should mention that to avoid confusion.~~

**Comment by Moneyl** [comment]
I realized the example I gave in the first message isn't depicting the problem I ran into correctly. Here's a better one:
```c
//Null terminated string
struct String
{
    char Value[];
};

u32 numTextureNames @ 0;
//Array of null terminated strings
String textureNames[numTextureNames] @ 4;
//Place someOtherValue immediately after textureNames
u32 someOtherValue @ endPosition(textureNames);
```
So in this example the format has an array of null terminated strings followed by some other data. I don't see a way to calculate the end position of the array since each string could be any size. That's where having a function `endPosition` which returns the end offset of a variable would come in.

**Comment by 1122wwee33** [comment]
سلام عليكم ورحمة الله وبركاته مساء الخير

**Comment by WerWolv** [comment]
Wouldn't it be better to put these variables into a struct if you want them one after the other?
I'm planning on adding `addrof`, `offsetof`, `sizeof` and `endof` though

**Comment by Moneyl** [comment]
Ah yeah, using a struct works. That's what I'll do for now. 

It's not completely intuitive to put those two values in a struct since the string array and the value following it are unrelated. That's where having some of the functions you mentioned would be useful.
