### ISSUE TITLE
[Bug] The cmd window will open when imhex/imhex-gui.exe runs

### ISSUE THREAD

**Issue by Spear-0** [WerWolv/ImHex#1452]
### Operating System

Windows

### What's the issue you encountered?

Running either imhex-gui or imhex will open the cmd window

### How can the issue be reproduced?

double click imhex.exe or imhex-gui.exe

### ImHex Version

1.31.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Both MSI and Portable

**Comment by WerWolv** [comment]
Hey! This is probably an issue with the Windows Terminal. It ignores hide / free requests.
The latest nightly has a workaround for it implemented, you can download it from https://imhex.download/#nightly or you can wait for the next release
