### ISSUE TITLE
[Bug] Opening Intel Hex and the saving it never stops filling a file

### ISSUE THREAD

**Issue by ketukil** [WerWolv/ImHex#1454]
### Operating System

Windows

### What's the issue you encountered?

I've opened an Intel HEX file by using Intel Hex Provider
![image](https://github.com/WerWolv/ImHex/assets/8713394/0e544e08-ef81-457a-9c7c-94241193ee4d)

with the intention to save is as a binary file afterwards
![image](https://github.com/WerWolv/ImHex/assets/8713394/2806babc-bd93-4862-91bf-a05f06f32e7c)

It ended up writing to the binary file until disk space was exhausted (in my case about 300+ GB) . 

### How can the issue be reproduced?

To be specific I've opened micropython-microbit-v2.1.1.hex and saved it as mbit.bin.

### ImHex Version

1.31.0 0master@f5b8021

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

imhex-1.31.0-Windows-x86_64.msi

**Comment by WerWolv** [comment]
Thanks for the report! The latest commit should fix this
