### ISSUE TITLE
Goto and bookmarks not working for large files

### ISSUE THREAD

**Issue by JnCrMx** [WerWolv/ImHex#146]
While working on a plugin for opening memory of other processes in ImHex, I've noticed weird behavior for very large files.
Even though the size of "files" I was initially working with is about 128 GiB, the issues also occur for much smaller (but still pretty large) files of about 4 GiB.

When using Goto for any address that is not on the first page, it only switches to the correct page, but does not change the scroll bar position. That issue also occurs when jumping to a bookmark that is not on the first page.

Also, it is not possible to set bookmark on any pages that are not the first (except if you do it programmatically).
The bookmark is placed on the correct offset, but on the first page.

Steps to reproduce:
1. Create a large file
2. Open it in ImHex
3. Goto an address on any page that is not the first (> ``0xFFFFFFF``)
4. Try to set a bookmark on any page that is not the first

System details:
- Arch Linux Kernel 5.10.9-arch1-1
- 64 bit system
- ImHex built from source (commit 0300d77fdb18c54eec2a40cbbae6e2a3b1ec1649)
- GCC version 10.2.0
- cmake version 3.19.3

**Comment by JnCrMx** [comment]
There is also an issue with the patches/editing mechanic:

``FileProvider::read`` checks if the patch contains an entry for the address relative to the page start, but then reads the patch from the absolute address.

``FileProvider::write`` stores the patch at a sort of absolute address, but uses ``m_baseAddress``, which ``FileProvider::read``.
In this case it doesn't really matter whether the base address is used or ignored, but it should be consistent between ``FileProvider::read`` and ``FileProvider::write``.
I would personally suggest ignoring the base address, because otherwise all patches would be lost when the base address changes. ``MemoryEditor`` only uses the base address of display and ignores it when calling the write function.

Using absolute addresses for patches would be a good option (otherwise you couldn't have temporary changes on more than one page at a time), but would conflict with saving, because ``FileProvider::writeRaw`` accepts only offsets relative to the page start.

I think it would be important and helpful to clearly decide and specify which methods use absolute and which use page relative addresses.

**Comment by WerWolv** [comment]
This has been greatly improved with the latest release
