### ISSUE TITLE
[Bug] automated winget release failed for v1.32.0

### ISSUE THREAD

**Issue by rursprung** [WerWolv/ImHex#1473]
### Operating System

Windows

### What's the issue you encountered?

v1.32.0 didn't get released on winget since [the workflow failed](https://github.com/WerWolv/ImHex/actions/runs/7342849140/job/19992654878):

> ```
> Set-Variable: D:\a\_temp\013703af-4014-4d4b-ba62-3bcb33dd537f.ps1:2
> Line |
>    2 |  set -x
>      |      ~~
>      | A parameter cannot be found that matches parameter name 'x'.
> 
> Error: Process completed with exit code 1.
> ```

the problem is this line:
https://github.com/WerWolv/ImHex/blob/63042dbba8829f3009f2d3a787553cb37cdbabd6/.github/workflows/release.yml#L157

`set -x` doesn't work in powershell (it's a bash thing). it was added by #1447 which should've only added it to bash scripts (or have added an equivalent for powershell if that exists and is needed).

### How can the issue be reproduced?

check that the release works.

### ImHex Version

1.32

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

n/a

### Additional context?

it's probably enough to remove that line and then re-trigger the release (maybe it has to be done manually this time as the rest of the workflow shouldn't run again?)

**Comment by WerWolv** [comment]
Thank you! I'll manually submit the update
