### ISSUE TITLE
[Bug] Question window appears but it isn't visible in desktop

### ISSUE THREAD

**Issue by aybe** [WerWolv/ImHex#1476]
### Operating System

Windows

### What's the issue you encountered?

After leaving the application running in background and switching back to it, it is stuck showing a question window that I cannot switch to, as can seen in taskbar, the window has no content:

<img width="959" alt="image" src="https://github.com/WerWolv/ImHex/assets/1537591/a30b31d0-8856-4798-8ea1-92906041cd2a">

When hovering the window in task bar, it shows the desktop, i.e. window has no content at all.

You can also see that minimize button is stuck in main window.

Had no other choice than kill process in task manager.

### How can the issue be reproduced?

Left the application running in background for say 1/2 hours.

### ImHex Version

1.32.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by WerWolv** [comment]
Hmm I can't think of any Question popup that only shows up after half an hour. I'll try to reproduce it but I feel like there's more to this

**Comment by aybe** [comment]
Ok, I am trying the same scenario a 2nd time and see if it ever happens again, posting back the result in a few hours.

**Comment by aybe** [comment]
Left if a few hours but it didn't happen again...

I've noticed you ship PDBs, will try to attach and debug the situation if it ever happens again.
