### ISSUE TITLE
[Bug] Custom font not being used in 1.32.1

### ISSUE THREAD

**Issue by Infernio** [WerWolv/ImHex#1483]
### Operating System

Linux

### What's the issue you encountered?

I use Fira Code with ImHex on Arch Linux. Since 1.32.1, ImHex seems to ignore my custom font and instead uses the default(?) font.
Either that or there's some rendering bug going on that's making the font look ugly.

### How can the issue be reproduced?

Launch ImHex with Fira Code set as custom font.

### ImHex Version

1.32.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

AUR

### Additional context?

My [settings.json](https://github.com/WerWolv/ImHex/files/13801392/settings.json).

Picture of ImHex on 1.31.0 (how I'd want the font rendering to look):

![image](https://github.com/WerWolv/ImHex/assets/2845240/6a2328b5-5846-4d38-b5ba-3d1b886d3941)

Picture of ImHex on 1.32.1:

![image](https://github.com/WerWolv/ImHex/assets/2845240/1e0fd331-71ef-4342-b1f9-acc7c512792d)

**Comment by WerWolv** [comment]
Hey, I think this is just Anti Aliasing not being enabled by default. I added a bunch of extra settings to the Fonts menu and the ability to toggle Anti-Aliasing is one of them. Try enabling it under Settings -> Fonts and it should look fine

**Comment by Infernio** [comment]
That did it, thank you!
