### ISSUE TITLE
[Bug] Jump to big endian address doesn't work.

### ISSUE THREAD

**Issue by izMoff** [WerWolv/ImHex#1487]
### Operating System

Windows

### What's the issue you encountered?

As it says in the title. The address shows up correctly in the menu where you select the endianness. but when i click it, nothing happens. After fiddling around with it a bit, i found that i can jump to b.e. address if i select one or two bytes, but if i select three or more bytes, it stops working. That doesn't depend on the address itself. I can jump to FF or FFFF, but 0000FF or longer doesn't work.

### How can the issue be reproduced?

1. Open any file of appropriate size.
2. Select any string of bytes longer than 2 and attempt to jump to big endian address.

### ImHex Version

1.32.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by WerWolv** [comment]
Thanks for the report! Latest commit should fix this
