### ISSUE TITLE
libimhex.so missing from binary download

### ISSUE THREAD

**Issue by bluecmd** [WerWolv/ImHex#149]
Hi,

I just downloaded the latest Linux ELF package. Looking at the linked libraries, one stands out:
```
$ ldd .local/bin/imhex
	linux-vdso.so.1 (0x00007fffe5cf1000)
	libmagic.so.1 => /lib/x86_64-linux-gnu/libmagic.so.1 (0x00007ffd925a0000)
	libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007ffd922c0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffd922b0000)
	libcapstone.so.3 => /lib/x86_64-linux-gnu/libcapstone.so.3 (0x00007ffd92000000)
	libimhex.so => not found
	libpython3.8.so.1.0 => /lib/x86_64-linux-gnu/libpython3.8.so.1.0 (0x00007ffd91ab0000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007ffd919e0000)
	libglfw.so.3 => /lib/x86_64-linux-gnu/libglfw.so.3 (0x00007ffd91970000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ffd91780000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffd91631000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ffd91610000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffd91410000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007ffd913d0000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007ffd913b0000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ffd91390000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffd9136d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffd92700000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007ffd91330000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007ffd91360000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007ffd912e0000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007ffd911a0000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007ffd91170000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007ffd91160000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007ffd91150000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007ffd91120000)
```

libimhex.so does not appear to be in the .zip file.

**Comment by WerWolv** [comment]
Oh boy that's not good. I didn't notice this for over two weeks.
I'll take care of it, thanks for letting me know!

**Comment by mrozekma** [comment]
@WerWolv That PR says "Properly pack all dependencies" -- is it actually supposed to include all dependencies? I'm missing libcapstone, libpython, and libglfw on my system. The only lib included in the zip seems to be libimhex.

**Comment by WerWolv** [comment]
@mrozekma It means properly pack all dependencies that can't be installed in other means. You should install all other libraries through your distro's package manager.

**Comment by ihipop** [comment]
> @mrozekma It means properly pack all dependencies that can't be installed in other means. You should install all other libraries through your distro's package manager.

Suggested an AppImg release

**Comment by mrmaxguns** [comment]
I downloaded the linux zip file from https://github.com/WerWolv/ImHex/releases/tag/v1.7.0. The file did contain `libimhex.so` along with the `imhex` executable. Executing `imhex` still gives `./imhex: error while loading shared libraries: libimhex.so: cannot open shared object file: No such file or directory`. Running `ldd` results in the same output as in the original issue.

**Comment by ihipop** [comment]
> I downloaded the linux zip file from https://github.com/WerWolv/ImHex/releases/tag/v1.7.0. The file did contain `libimhex.so` along with the `imhex` executable. Executing `imhex` still gives `./imhex: error while loading shared libraries: libimhex.so: cannot open shared object file: No such file or directory`. Running `ldd` results in the same output as in the original issue.

Please set `LD_LIBRARY_PATH` to the directory where `libimhex.so` is located.
basic  skill
