### ISSUE TITLE
[Bug]  JSON export of Pattern Data contains undesired characters

### ISSUE THREAD

**Issue by speters** [WerWolv/ImHex#1492]
### Operating System

Linux

### What's the issue you encountered?

Exported string Pattern Data in JSON file contains the complete contents of the "Value" column field with quotation marks and a trailing space in URL-encoded form:
![image](https://github.com/WerWolv/ImHex/assets/1384994/5a747da3-d35d-4ba1-b6de-51ab37ae4f95)

A similar observation can be made with strings containing zero bytes, where the backlash-representation of the Pattern Data display is encoded in the JSON data.

Expected behaviour:
JSON field just contains the URL-encoded data.

### How can the issue be reproduced?

Test case containing file `i` as data provider, `i.hexproj` as ImHex project with pattern and `i.json` as exported data:
[test.zip](https://github.com/WerWolv/ImHex/files/13936187/test.zip)

General procedure to reproduce:
 * Load data provider containing string/char data.
 * set up a pattern file to read  some  `char name[len] @ addr`
 * run pattern
 * observe Pattern Data output value field and compare with exported JSON

### ImHex Version

v1.32.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Arch package from GH releases

**Comment by paxcut** [comment]
I have a similar experience except I am running on windows 10 ans using the plcli in format mode. when i run the pattern in Imhex the output string looks fine:

![image](https://github.com/WerWolv/ImHex/assets/53811119/f3f9fa24-5cbf-4c99-8c79-e40a4c8f00d8)


however the json output I get from plcli is:
```json
{
    "test": {
        "array": [
            135,
            121,
            152,
            135
        ],
        "chars": "-------%20With%20%23define%20%3A----------"
    }
}
```

**Comment by PerikiyoXD** [comment]
Probably it's caused because we take the whole displayed string instead of the inner value

**Comment by dlabz** [comment]
Also present in yaml and HTML strings and magics (but not on static strings, I'd say)
