### ISSUE TITLE
License Question: Which one was used by this project, GPL-2.0-only or GPL-2.0-or-later

### ISSUE THREAD

**Issue by CoelacanthusHex** [WerWolv/ImHex#1496]
I maintain the package of this project in [archlinuxcn](https://github.com/archlinuxcn/repo). Recently, Arch Linux enforced using the SPDX identifier via RFC16[^1]. It differs from GPL-2.0-only and GPL-2.0-or-later. So I need to know which one was used in this project.
Thank You!

[^1]: https://gitlab.archlinux.org/archlinux/rfcs/-/blob/master/rfcs/0016-spdx-license-identifiers.rst

**Comment by WerWolv** [comment]
Hey! All code in ImHex is under GPL-2.0-only currently.
