### ISSUE TITLE
Builds & Runs fine in Catalina... Any chance of dropping the Big Sur requirement for a while?

### ISSUE THREAD

**Issue by JonathanDotCel** [WerWolv/ImHex#150]
Not a huge deal, but just in case it hadn't been tested.

Thanks,
J

**Comment by WerWolv** [comment]
I'm not quite sure what you mean. Where are we requiring Big Sur?

**Comment by xvoland** [comment]
<img width="1546" alt="Снимок экрана 2021-02-22 в 01 13 33" src="https://user-images.githubusercontent.com/75009/108646123-d021b900-74ac-11eb-8834-7089a74f2c20.png">


```
cd ~/Desktop
git clone https://github.com/WerWolv/ImHex.git
cd ImHex
brew update && brew upgrade
brew bundle --no-lock --file dist/Brewfile
mkdir build
cd build
CC=$(brew --prefix llvm)/bin/clang CXX=$(brew --prefix llvm)/bin/clang++ PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig":"$(brew --prefix)/lib/pkgconfig" cmake -DCMAKE_BUILD_TYPE=Release ..
make -j
```

After many warnings, it should be compiled.
Now, from the directory  `~/Desktop/ImHex/build/` copy file ./imhex to package DMG  `Contents/MacOS/`

**Comment by WerWolv** [comment]
MacOS is much better supported nowadays
