### ISSUE TITLE
[Bug] Build fails on Apple silicon Ventura 

### ISSUE THREAD

**Issue by qw42** [WerWolv/ImHex#1502]
### Operating System

MacOS

### What's the issue you encountered?

The version 1.32.2 from homebrew failed to run with error message "wrong OS version" so I decided to build it myself following the instructions from this page
https://github.com/WerWolv/ImHex/blob/master/dist/compiling/macos.md

It seems that the actual compilation completed without errors, but during the packaging stage there were several errors saying "error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: no LC_RPATH load command with path:"

After that the process hanged after printing "CPack: Create package".

I tried resetting and re-installing xcode command line tools, but it didn't help. 

I tried to build both master branch's head and v1.32.2.

### How can the issue be reproduced?

Follow the instructions from https://github.com/WerWolv/ImHex/blob/master/dist/compiling/macos.md

### ImHex Version

1.32.2

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Built from source

**Comment by digital-polyglot** [comment]
Also fails on Sonoma 14.2.1...

**Comment by WerWolv** [comment]
The version on Homebrew isn't maintained by us at all. Please report this issue to whoever maintains it.

**Comment by qw42** [comment]
> The version on Homebrew isn't maintained by us at all. Please report this issue to whoever maintains it.

I was reporting the bug related to building from source code, not to the homebrew version,

I also download v.1.32.2 binary from github and got the same error message - "wrong OS version".

**Comment by WerWolv** [comment]
I just built it myself on my M2 mac using the following commands and I was able to launch it just fine.
```
CC=$(brew --prefix llvm)/bin/clang CXX=$(brew --prefix llvm)/bin/clang++ cmake .. -DIMHEX_GENERATE_PACKAGE=ON -G Ninja -DCMAKE_INSTALL_PREFIX=./install
ninja install
codesign --force --deep --sign - ./install/imhex.app
```

The 1.32.2 release required macOS 14.0 to run, I've since lowered that requirement down to 12.1, the same version the x86 release requires too.

**Comment by qw42** [comment]
Worked for me as well. It seems that switching compiler from GCC to clang fixed the issue. Maybe [build instructions](https://github.com/WerWolv/ImHex/blob/master/dist/compiling/macos.md) should be updated?
