### ISSUE TITLE
libimhex.so isn't installed when using `sudo make install`

### ISSUE THREAD

**Issue by Calinou** [WerWolv/ImHex#151]
Related to #149.

After installing ImHex system-wide on Fedora 33, running it will result in an error:

```
❯ imhex
imhex: error while loading shared libraries: libimhex.so: cannot open shared object file: No such file or director
```

However, you can still run ImHex in its build folder.

To solve this, I copied `libimhex.so` to `/usr/lib64` but it won't work if you move the library to `/usr/local/lib64` (as it should be for locally-installed software).

**Comment by Mailaender** [comment]
Why is this library not shipped with https://github.com/WerWolv/ImHex/releases/download/v1.6.1/ImHex_1.6.1_Linux.zip?

**Comment by jam1garner** [comment]
I'm still getting this issue @WerWolv, installing from `sudo make install` on  Ubuntu 20.04 will installed to `/usr/local/lib/libimhex.so`, copying it over to `/usr/lib/libimhex.so` fixed the issue as mentioned in the OP.
