### ISSUE TITLE
“imhex” is damaged and can’t be opened. You should move it to the Bin.

### ISSUE THREAD

**Issue by balotofi** [WerWolv/ImHex#1521]
### Operating System

MacOS

### What's the issue you encountered?

i downloaded the dmg from https://imhex.werwolv.net/. 

i moved the icon into the applications folder.

i went to applications, double clicked, a popup says {“imhex” is damaged and can’t be opened. You should move it to the Bin.}

### How can the issue be reproduced?

I am running on a 16GB Apple M1 Pro running on mcOS 14.2.1 (23C71). I downloaded the DMG from chrome

### ImHex Version

1.32.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

DMG

**Comment by glpnk** [comment]
Probably you downloaded version for Intel Mac, not m1, try to download from Github released https://github.com/WerWolv/ImHex/releases/download/v1.32.2/imhex-1.32.2-macOS-arm64.dmg

**Comment by balotofi** [comment]
thank you. after clicking the link, it downloaded directly. 

i moved it to the applications folder.

i double clicked it within the application folder and i recieved a new error message

[“ImHex” cannot be opened because the developer cannot be verified.] macOS cannot verify that this app is free from malware

**Comment by balotofi** [comment]
I went into the settings for my laptop and allowed access to ImHex. the program has now opened. you may close this issue

system settings > privacy & security > security > allow anyway

**Comment by glpnk** [comment]
@WerWolv closed

**Comment by WerWolv** [comment]
@balotofi 
> ImHex” cannot be opened because the developer cannot be verified

That message shows up because ImHex isn't signed with a code signing cert because I refuse to spend a bunch of money on something stupid like that.
It can easily be circumvented by just right clicking the .app bundle once and selecting Open there. It will show a slightly different message then where you can open ImHex anyways. That will automatically add an exception then and the app can be launched.

**Comment by slasyz** [comment]
I got the same error (`“imhex” is damaged and can’t be opened. You should move it to the Bin.`), but the binary version was correct. The same error happened when I tried to install ImHex via brew.

This helped me:
```
xattr -c /Applications/ImHex.app
```

**Comment by A-caibird** [comment]
> I got the same error (`“imhex” is damaged and can’t be opened. You should move it to the Bin.`), but the binary version was correct. The same error happened when I tried to install ImHex via brew.
> 
> This helped me:
> 
> ```
> xattr -c /Applications/ImHex.app
> ```

thank you

**Comment by gnought** [comment]
Instead of clearing all flags, just clearing `com.apple.quarantine` will work.
```
xattr -d com.apple.quarantine /Applications/ImHex.app
```
