### ISSUE TITLE
Cannot save edited file

### ISSUE THREAD

**Issue by dmitry64** [WerWolv/ImHex#154]
Changes are not saved to the file when I press "Save" from File menu or press Ctrl-S. Using "Save As" and saving into a new file works fine. Using "Save As" to the original file crashes the editor and destroys original file by making it empty. 

I'm running fa352b6917472f5448f41a4af58c7344ff01d750 on Linux.

**Comment by philippgovernale** [comment]
I am having the same issue on current Windows Nightly version

**Comment by WerWolv** [comment]
This should be working fine now
