### ISSUE TITLE
[Proposal] On Windows 11+, try out the new `consoleAllocationPolicy` manifest entry

### ISSUE THREAD

**Issue by DHowett** [WerWolv/ImHex#1543]
Hey! :wave:

I'm the maintainer for the Windows Console subsystem, and a big ImHex fan. I remember the discussion we had over in https://github.com/microsoft/terminal/issues/16174 about `imhex-gui` and `imhex` being allocated a console due to being compiled with `/SUBSYSTEM:CONSOLE`.

In the recent insider builds for Windows 11, we finally added support for `CONSOLE` subsystem applications to opt-out of automatic console allocation.

The spec is [here](https://github.com/microsoft/terminal/blob/main/doc/specs/%237335%20-%20Console%20Allocation%20Policy.md), though it's a bit dense.

In short, you add this to your win32 manifest:

```xml
<!-- You probably already have these lines
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <application>
    <windowsSettings>
-->
      <consoleAllocationPolicy xmlns="http://schemas.microsoft.com/SMI/2024/WindowsSettings">detached</consoleAllocationPolicy>
<!-- (and these)
    </windowsSettings>
  </application>
</assembly>
-->
```

With that entry, your EXE will only get a console if it inherits one. It won't automatically make one -- ever[^1] -- unless you call `AllocConsole` or this new `AllocConsoleWithOptions` API.

Feel free to close this out, or follow up with any questions! I'd be happy to test out any builds if you can't get at a Windows Insider machine/VM. 🙂 

[^1]: I'm hoping to get this backported to Windows 10 and the current in-market versions of Windows 11 as well. That will take some time. But since we didn't want to break all existing console applications . . . on Windows <=11 2023 it actually _will_ automatically get a console. Ugh.

**Comment by WerWolv** [comment]
Hey, thanks a lot! That's some fantastic news and a huge step in the right direction!

I'm happy to add this to ImHex, however if this only applies to very new versions of Windows 11, I'll probably still have to keep the current forwarder application around for the time being. 

We currently don't have a manifest like this yet and I honestly also don't know much about them. ImHex is built using MinGW on Windows and I'm not sure if that supports embedding those easily. I'll definitely look into it though.

**Comment by DHowett** [comment]
I just tried out 6a5473f (portable), and I love it. It works exactly like I'd expect an application on e.g. Linux to work 🙂.
