### ISSUE TITLE
[Bug] `imhex` crashes instantly after startup on Gentoo Linux

### ISSUE THREAD

**Issue by kernaltrap8** [WerWolv/ImHex#1547]
### Operating System

Linux

### What's the issue you encountered?

Upon launching `imhex`, the following output is presented and then the program crashes with exit status `127`
```
~>imhex                                                                                               608.847s 21:58
[11:49:51] [INFO]  [main]       Welcome to ImHex 1.32.2!
[11:49:51] [INFO]  [main]       Compiled using commit Unknown@Unknown
[11:49:51] [INFO]  [main]       Running on Linux 6.7.4-gentoo-dist #1 SMP PREEMPT_DYNAMIC Wed Feb 14 16:54:17 CST 2024 (x86_64)
[11:49:51] [INFO]  [main]       Native scaling set to: 1.0
[11:49:51] [INFO]  [main]       Using 'Intel' GPU
[11:49:51] [INFO]  [main]       Task 'Setting up environment' finished successfully in 0 ms
[11:49:51] [INFO]  [main]       Task 'Creating directories' finished successfully in 0 ms
[11:49:51] [INFO]  [main]       Task 'Loading settings' finished successfully in 0 ms
[11:49:51] [INFO]  [main]       Loading plugin 'ui.hexpluglib'
~[127]>       
```

### How can the issue be reproduced?

Launch `imhex` under Wayland on Gentoo

### ImHex Version

1.32.2

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

From source using `portage` package manager

**Comment by WerWolv** [comment]
Hey! Thanks for the report
Gentoo isn't officially supported by us so you'll need to bring this up with the people who put ImHex on portage.
You can try using the AppImage build and see if that works for you though.

**Comment by kernaltrap8** [comment]
sounds great, will do. thank you for the response.

**Comment by TakuikaNinja** [comment]
I have the same issue on EndeavourOS (X11, XFCE), using the `imhex-bin` AUR package and direct installation with pacman. The `imhex` package compiles and runs fine, however.

**Comment by kernaltrap8** [comment]
> I have the same issue with version 1.33.0 on EndeavourOS (X11, XFCE), using the `imhex-bin` AUR package and direct installation with pacman. The `imhex` package compiles and runs fine, however.

the thing is; im running Gentoo, so packages are compiled from source anyway, maybe its an ebuild issue. not too sure.

**Comment by kernaltrap8** [comment]
It does.

**Comment by RocketMaDev** [comment]
I have the same issue, using Arch Linux. I just `yay imhex-bin`.

**Comment by iTrooz** [comment]
Feel free to use the AppImage until I get the time to fix this.

If someone wants to make a PR, also feel free to :)

**Comment by iTrooz** [comment]
I can confirm the issue. It seems to be caused by `-DUSE_SYSTEM_YARA=ON`

**Comment by kernaltrap8** [comment]
> I can confirm the issue. It seems to be caused by `-DUSE_SYSTEM_YARA=ON`

great you found the issue! lmk when you fix the ebuild and i can resync the repo
