### ISSUE TITLE
[Bug] Data Processor Read Buffer not working.

### ISSUE THREAD

**Issue by Uzver123** [WerWolv/ImHex#1549]
### Operating System

Windows

### What's the issue you encountered?

Read buffer displays same regardless what selection i make

![1](https://github.com/WerWolv/ImHex/assets/143356096/a4203f93-6a25-45b6-986d-474fde8af5a7)

### How can the issue be reproduced?

Follow what's on screenshot

### ImHex Version

1.32.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by paxcut** [comment]
I  just tried it and it works. Are you pressing the run button after selecting (or turning on continuous evaluation?

![image](https://github.com/WerWolv/ImHex/assets/53811119/aa23a174-fd0b-43c0-9b31-777e811adbb8)

**Comment by Uzver123** [comment]
Guess that was the issue, works now.
