### ISSUE TITLE
[Bug] ImHex crashed during initial setup (crashes only when launched from context menu)

### ISSUE THREAD

**Issue by ezxpro** [WerWolv/ImHex#1559]
### Operating System

Windows

### What's the issue you encountered?

On my machine, when I launch imhex from the context menu I get this error:
![image](https://github.com/WerWolv/ImHex/assets/15344931/f49457a6-61a8-4116-8068-a568c98273c0)

### How can the issue be reproduced?

Everytime I try to launch it from the context menu I get this issue, but it just happens on this machine

### ImHex Version

1.32.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

official MSI from github

### Additional context?

I'm on Windows 10 22H2 64 bit. I have other machines with windows 10 and they run from the context menu just fine. Not sure why this happens on this machine.

This is possibly related to #1514 , the error is the same, but the context is different. In that issue, the person sees the error when they launch the app. Here it launches and works fine, but when launched from context menus, that error shows up.

**Comment by WerWolv** [comment]
Hey! Could you maybe try the nightly build? You can download it from https://imhex.download/#nightly.
It works for me locally on Windows 11

**Comment by ezxpro** [comment]
> Hey! Could you maybe try the nightly build? You can download it from https://imhex.download/#nightly. It works for me locally on Windows 11

Problem solved, many thanks.
