### ISSUE TITLE
[Bug] Saving a file doesn't work properly

### ISSUE THREAD

**Issue by Panquesito7** [WerWolv/ImHex#1568]
### Operating System

Windows

### What's the issue you encountered?

If you modify a file, the changes will instantly be written to disk, but it'll still report that the changes are unsaved.
When trying to save, the unsaved status is kept, no matter how many times you click save. When trying to exit, the program will tell you the changes are unsaved, even if the changes were already written to disk without even clicking on the save button.

### How can the issue be reproduced?

1. Open and modify any file with any change.
2. The changes will be written to the disk. You can verify this by opening the file with another editor after you make the change.
3. Try to save the file or exit the program, and the unsaved status will remain present, as well as the changes you made.

### ImHex Version

1.33.2 (latest as of now).

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable.

### Additional context?

Looks like this happens with any file. I even created a simple 2-byte TXT file, and the same issue occurs.

**Comment by WerWolv** [comment]
This has been fixed as of latest master.
