### ISSUE TITLE
[Bug] Processing Advanced Data Information fails

### ISSUE THREAD

**Issue by heapoverride** [WerWolv/ImHex#1571]
### Operating System

Windows

### What's the issue you encountered?

I installed the latest ImHex release on a new Windows 10 machine to test new features and noticed that it fails to process Advanved Data Information. Nothing about the error is displayed in Log Console but there is an error popup saying:
```
Failed to process information section Advanded Data Information: 'Invalid romfs resource path! File 'yara_rules' : C:\Users\<username>\AppData\Local\imhex\yara\advanced_analysis\compiler.yar'
```
I'm able to navigate to the directory and see the Yara file (compiler.yar) there but ImHex fails to load it for some reason.

### How can the issue be reproduced?

1. Open ImHex on Windows
2. Open Windows executable file in ImHex
3. Open Data Information window
4. Click on "Analyze page"

### ImHex Version

1.33.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by WerWolv** [comment]
Derp, thank you. Latest commit fixes this
