### ISSUE TITLE
[Bug]  Import menu disabled on read-only files

### ISSUE THREAD

**Issue by FireNX70** [WerWolv/ImHex#1573]
### Operating System

Linux

### What's the issue you encountered?

Starting with 1.33, importing files is disabled when working on read-only files. Patterns can still (for example) be copied manually from their corresponding file and run, but it's a nuisance. Do note that, when both read-only and read-write files are open, the import menu is enabled while a read-write file is selected.

### How can the issue be reproduced?

Open read-only file. Open the file menu. Notice the greyed-out "Import" option.

### ImHex Version

1.33.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Appimage

### Additional context?

Tested on Debian 11, in case it may be somehow relevant.

**Comment by WerWolv** [comment]
Thank you!

**Comment by FireNX70** [comment]
Same to you. That was really fast.
