### ISSUE TITLE
[Bug] Endian pragma ignored

### ISSUE THREAD

**Issue by x4fx77x4f** [WerWolv/ImHex#1588]
### Operating System

Linux

### What's the issue you encountered?

The `endian` pragma is ignored. While writing a pattern for a big endian format, I was experiencing unintended behavior.

### How can the issue be reproduced?

With this file
```
00000000: a1b2                                     ..
```
and this pattern
```
#pragma endian big
u16 value_default @ 0;
be u16 value_be @ 0;
le u16 value_le @ 0;
```
, the values in the pattern data are 0xb2a1, 0xa1b2, and 0xb2a1 instead of 0xa1b2, 0xa1b2, 0xb2a1 as expected.

### ImHex Version

1.33.0 (master@f050c69)

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Compiled from source

### Additional context?

My machine is little endian. `std::core::set_endian` works as expected.

**Comment by tim-tim707** [comment]
Don't have this problem on windows with version 1.31 and 1.33 but a friend of mine had this issue on windows 1.33 first install and rollback to version 1.31 which works for him

**Comment by elafargue** [comment]
Same issue here an an Intel Mac, v1.33.1

**Comment by WerWolv** [comment]
Latest commit fixes this issue
