### ISSUE TITLE
cmake index error in Python version

### ISSUE THREAD

**Issue by DrivebyCoding** [WerWolv/ImHex#159]
On Ubuntu 20.04, cmake 3.16.3 and Python 3.8.5  (what an updated Ubuntu 20.04 has by default today) cmake gets an error:

```
-- Found Python: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8") found components: Development 
CMake Error at cmake/build_helpers.cmake:54 (list):
  list index: 2 out of range (-2, 1)
Call Stack (most recent call first):
  CMakeLists.txt:22 (findLibraries)
```

Line numbers are slightly off because I have debug printf's in my local version.

The error is because PYTHON_VERSION_MAJOR_MINOR = "3;8". There is no 3rd list member so this fails:
`    list(REMOVE_AT PYTHON_VERSION_MAJOR_MINOR 2)`

Is the code trying to remove a potential BUILD version? If so, this probably works better:
`   list(SUBLIST PYTHON_VERSION_MAJOR_MINOR 0 2 PYTHON_VERSION_MAJOR_MINOR)`

With that change it goes through, the variable gets set to "3.8" and the build succeeds. The resulting executable dumps core complaining about "[json.exception.type_error.302] type must be number, but is null", but that is a problem for another day.

**Comment by imjasonmiller** [comment]
Thank you for raising the issue. I was running into a similar issue and ended up finding _one result_, [this Japanese blog](https://soji256.hatenablog.jp/entry/2021/01/25/070000) that seems to mention the same.
