### ISSUE TITLE
[Feature] LZ4 Compressed Bytes

### ISSUE THREAD

**Issue by simplexidev** [WerWolv/ImHex#1593]
### What feature would you like to see?

I'd like to have a way to decompress a section of bytes in the file using the LZ4 format.

### How will this feature be useful to you and others?

This will allow for the decompression/compression of bytes in a file to be read and parsed by the editor when used in a pattern file.

### Additional context?

Unrelated, but similar issue for ZLib: #1498

**Comment by WerWolv** [comment]
Hey, we currently have zlib, bzip2, lzma and zstd available through the pattern language.
https://github.com/WerWolv/ImHex-Patterns/blob/master/includes/hex/dec.pat#L23-L62

Are you sure none of them can handle your data? I'd like to keep the number of libraries that are needed for this to a minimum.

**Comment by simplexidev** [comment]
I will be checking here shorty, but i also seem to have no idea how I would use that to decommpress data from the file then parse it, property?

**Comment by simplexidev** [comment]
I figured it out, and also it will work, I just need to recompile to support that function apparently.

**Comment by sinni800** [comment]
> I figured it out, and also it will work, I just need to recompile to support that function apparently.

It would be wonderful if you provided the steps in which you got lz4 decompression to work
