### ISSUE TITLE
[Bug] Denying server contact in initial wizard still keeps crash reports uploads enabled

### ISSUE THREAD

**Issue by sbdswr** [WerWolv/ImHex#1594]
### Operating System

Linux

### What's the issue you encountered?

The initial settings dialog asks whether user wants to share data with ImHex, giving separate option for usage data, just crash logs, or nothing:

![imhex-server-contact](https://github.com/WerWolv/ImHex/assets/111827012/1e7bc6a6-efb7-425f-8cfe-c96db7c8a22c)

However choosing "Deny" still results in crash logs enabled in settings:

![imhex-settings](https://github.com/WerWolv/ImHex/assets/111827012/59bec085-d3cc-46df-ac14-7fa491d6dafe)

The expected behavior would be for that option to be disabled after choosing "Deny".

### How can the issue be reproduced?

Start with fresh settings, e.g. `rm -rf ~/.config/imhex`, run ImHex.

### ImHex Version

v1.33.0-70-g876f0912

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Built from source

**Comment by WerWolv** [comment]
Hey! Thanks for making me aware of this. This should not have happened.
Latest commit now properly disables the option in that case
