### ISSUE TITLE
[Bug] Pattern placed in section doesn't appear in Pattern Data

### ISSUE THREAD

**Issue by bgilbert** [WerWolv/ImHex#1602]
### Operating System

Linux

### What's the issue you encountered?

Patterns placed using `@ nnn in sec` syntax don't appear in the pattern view.

### How can the issue be reproduced?

```
import std.mem;

auto s = std::mem::create_section("s");
std::mem::set_section_size(s, 4);
u8 arr[4] @ 0 in s;
```

Result:

![image](https://github.com/WerWolv/ImHex/assets/361374/ec92ba77-c816-41d9-8ff9-e0cce3c273d7)

### ImHex Version

v1.33.0-105-g48db4df02833

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Source

### Additional context?

Fedora 39

**Comment by paxcut** [comment]
Sections have their own hex displays separate from the main one. To access them click on the section tab under the pattern editor.

![image](https://github.com/WerWolv/ImHex/assets/53811119/d651f162-96ba-4d81-93bc-564ef2dfa49d)

Click on the icon on the right to open the section display

![image](https://github.com/WerWolv/ImHex/assets/53811119/419b39d7-385e-4f9e-af40-e4d738b92743)

**Comment by bgilbert** [comment]
Yup, found it.  Thanks for the pointer.
