### ISSUE TITLE
[Crash] SIGSEGV when pattern evaluation tries to raise some errors.

### ISSUE THREAD

**Issue by MinekPo1** [WerWolv/ImHex#1611]
### Operating System

Linux

### What's the issue you encountered?

SIGSEGV when pattern evaluation tries to raise some errors.

### How can the issue be reproduced?

- Enter `u8 arr[while(!std::mem::eof())] @ 0x00;` as a pattern
- evaluate the pattern

### ImHex Version

1.33.1

### ImHex Build Type

- [x] Nightly or built from sources

### Installation type

FlatPak

### Additional context?

note that the sample does not have any errors and thus does not crash if you include `sys.mem`

**Comment by MinekPo1** [comment]
Reproduced the issue on nightly

**Comment by jumanji144** [comment]
Thanks, i confirmed the bug and will be working on a fix

**Comment by MinekPo1** [comment]
I think this is a duplicate of [PatternLanguage#79](https://github.com/WerWolv/PatternLanguage/issues/79)? Honestly I forgot to check for duplicates, sorry, though I doubt I would have found that one anyway. Similarly to how @wolfgang42 found, the issue disappears on web.

**Comment by MinekPo1** [comment]
Yeah, pretty sure the SIGSEGV is caused by the pattern language impl, the cli also crashes, I'm gonna leave it to a contributor if this issue should be closed or not

**Comment by jumanji144** [comment]
I can confirm this is a bug native to the pattern language, therefore you can either re-open it on the PatternLanugage repo, or i can mark it as a duplicate of https://github.com/WerWolv/PatternLanguage/issues/79

**Comment by MinekPo1** [comment]
I think a duplicate is more appropriate , I'm trying to add some more info to [WerWolv/PatternLanguage#79](https://github.com/WerWolv/PatternLanguage/issues/79)
