### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Wongani-Ngoma** [WerWolv/ImHex#1614]
### Operating System

Windows

### What's the issue you encountered?

ImHex thinks my cursor is pointing to a position slightly below the actual position it's pointing, also ImHex seems does not fit properly in the window that it occupies, I'm guessing these two issues are connected, the cursor position displacement is probably due to the displacement of the GUI components from the window.

### How can the issue be reproduced?

Maybe by running the application in windows 11 on 1366 x 768 resolution, because that's what I'm using

### ImHex Version

1.33.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI and Portable

### Additional context?

Am on Windows 11.  My laptop's max resolution is 1366 x 768

https://github.com/WerWolv/ImHex/assets/146844968/e4301ed5-12cc-4ee7-824d-1caf8cb760c3

**Comment by WerWolv** [comment]
Hey!
Hmm yeah this is most likely due to your screen size. I think ImHex thinks it's maximized while it isn't actually.
Can you try un-maximizing it and shrinking the window down a bit? Does it work then?

**Comment by Wongani-Ngoma** [comment]
Thanks for replying.
Whether it's minimized or maximized, same issue.
The portable version has another issue in addition, it doesn't respond to
any of my mouse clicks.
Also, now when I open the version installed using the installer, a small
black rectangle appears on the top left corner of the screen, I can't
interact with it in any way.

The problem is probably the pc am running it in, Maybe  building it from
source on my machine will solve these problems.

**Comment by jumanji144** [comment]
Was this resolved?

**Comment by Wongani-Ngoma** [comment]
> Was this resolved?
Sorry for the late reply, I got a new laptop and it seems to be working fine on it. The problem may have just be the graphics processor on the old laptop.

**Comment by U65535F** [comment]
Same problem on i3-4160 (iGPU, Intel HD Graphics 4400), latest version of software.
It's a bug with the iGPU I think.

**Comment by adamnielson42** [comment]
I'm having the same problem on an intel i5 4210.
