### ISSUE TITLE
Windows Releases 4x larger since version 1.33.0

### ISSUE THREAD

**Issue by haku1gh** [WerWolv/ImHex#1615]
Not sure if it is intended or a bug, but I recognized that since version 1.33.0 the releases are 4x larger than before. It looks like a lot of debug files have been added. Is there a possibility to bring back the more compact release versions without the debug stuff?

https://github.com/WerWolv/ImHex/releases/tag/v1.33.0
The "imhex-1.33.0-Windows-Portable-x86_64.zip" for example is 210MB large.

https://github.com/WerWolv/ImHex/releases/tag/v1.32.2
The "imhex-1.32.2-Windows-Portable-x86_64.zip" for example is 50.5MB large.

**Comment by Crystal-RainSlide** [comment]
I found it's the `plugins/builtin.hexplug` become much larger. Not sure what's inside.

In [1.31.0](https://github.com/WerWolv/ImHex/releases/tag/v1.31.0), the size of the AppImage doubled, the size of Ubuntu deb is almost 8x larger. So it's been around for half a year.

**Comment by Calinou** [comment]
Personally, I'd say the debug symbols should remain available as separate downloads (`.pdb` for Windows MSVC, `.debug` for other platforms). This would be required for https://github.com/WerWolv/ImHex/issues/1580 to be useful with official builds, otherwise it'll only be useful with self-compiled builds./

**Comment by iTrooz** [comment]
https://github.com/WerWolv/ImHex/pull/1719 and https://github.com/WerWolv/ImHex/pull/1720 should improve this

**Comment by iTrooz** [comment]
> .debug for other platforms
@Calinou I never saw .debug files for Linux and MacOS. Do you have a source for this ?

**Comment by Calinou** [comment]
> @Calinou I never saw .debug files for Linux and MacOS. Do you have a source for this ?

I don't mean for ImHex specifically, it's just that `.debug` is the default suffix when you choose to enable separate debug symbols in GCC/Clang-based compilers.

**Comment by iTrooz** [comment]
Humm ok

In any case, I don't think  I can significantly reduce artifact size anymore without removing our ability to have stacktraces, so I'm going to close this.

If you have any idea in mind to improve the situation, please feel free to tell

**Comment by iTrooz** [comment]
Link: https://github.com/WerWolv/ImHex/issues/1615
