### ISSUE TITLE
[Bug] CJK glyphs are display in wrong size (larger then ascii characters) when using fractional scaling (1.5x etc.)

### ISSUE THREAD

**Issue by Demonese** [WerWolv/ImHex#1616]
### Operating System

Windows

### What's the issue you encountered?

CJK glyphs are display in wrong size (larger then ascii characters) when using fractional scaling (1.5x etc.).

### How can the issue be reproduced?

Device:
* Windows 10/11
* 3840x2160 150% scaling

Steps:
* download 1.33.2
* open imhex-gui and set interface scaling to native (x1.5 on my device)
* switch to CJK language

### ImHex Version

1.33.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

### Additional context?

![image](https://github.com/WerWolv/ImHex/assets/57629614/b2ba6bd7-93ed-42da-8897-f1fce76cbf88)
![image](https://github.com/WerWolv/ImHex/assets/57629614/4a51117b-95ac-40d3-ba15-f7a07d222ff8)
![image](https://github.com/WerWolv/ImHex/assets/57629614/d589f486-6d72-4ed2-88ef-9eb0db74e3aa)
![image](https://github.com/WerWolv/ImHex/assets/57629614/09023fcc-2564-4c86-b400-704e1515d2c3)

**Comment by Demonese** [comment]
I think the currently recommended solution is: use a custom font, for example Sarasa Gothic, built-in font have CJK glyph size issues
![image](https://github.com/WerWolv/ImHex/assets/57629614/d5c9b63f-de3a-406c-b09d-ea688d8573a9)

**Comment by paxcut** [comment]
Issue #1604 asked to change the size of the default unicode font (unifont) from 13 which is the native size of the default font (proggy) to 16 which is its native size, so the  size discrepancy is not a bug. 

It looks like either scaling is not being handled properly for the default case or that the user interface was not scaled accordingly to the bigger unicode size. What you propose (using custom fonts) is not a solution, it is just a workaround. The real solution is to make sure that the default fonts work equally well (within reason) for all locales.

**Comment by Demonese** [comment]
> What you propose (using custom fonts) is not a solution, it is just a workaround.

Yes it's just a temporary solution for me.
