### ISSUE TITLE
[Bug]  #pragma pattern_limit is bugged

### ISSUE THREAD

**Issue by FireNX70** [WerWolv/ImHex#1618]
### Operating System

Linux

### What's the issue you encountered?

#pragma pattern_limit only appears to work on the first file opened. On other files, it is simply ignored. If the first file is closed, it still doesn't work for the other files. Closing all files but one will not make it work for the only file either.

### How can the issue be reproduced?

Open at least two files and try to change the pattern limit (through #pragma pattern_limit) on any file besides the one that was opened first.

### ImHex Version

1.33.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Both AppImage and .deb package (Ubuntu 23.04, but it works fine on Debian 12)

### Additional context?

Both this and #1617 are already broken on 1.33.1, so these aren't recent bugs.

**Comment by ZwipZwapZapony** [comment]
This also affects `#pragma array_limit`, `#pragma debug`, `#pragma eval_depth`, and likely any other pragma. This doesn't affect `#define`, so it doesn't just apply to the pre-processor in general. "*Extras*" > "*Settings*" > "*General*" > "*Patterns*" > "*Sync pattern source code between providers*" doesn't affect this.

**Comment by paxcut** [comment]
I tested this bug on 1.33.0 (master branch) which is what the nightly gives for windows and I couldn't reproduce this, so it could be a release branch only bug or less likely  a linux only problem.

**Comment by mandar1jn** [comment]
this is not a windows-specific issue as I have been running into the same thing on windows

**Comment by paxcut** [comment]
It looks like it is a known problem on the release branch (1.33.1 and 1.33.2) the bug was fixed on master branch (1.33.0) but hasn't been applied to release branch according to posts on discord.

**Comment by FireNX70** [comment]
I can confirm that `#pragma pattern_limit`  is fixed in recent nightlies. I haven't tested the other pragmas mentioned by @ZwipZwapZapony (I'm assuming it's the same bug affecting these) and the fix hasn't made it into a release yet, so I'll leave the bug report open for now.

**Comment by FireNX70** [comment]
Closing this since it's fixed in the most recent release.
