### ISSUE TITLE
Very large memory growth when using pattern editor

### ISSUE THREAD

**Issue by Varunda** [WerWolv/ImHex#163]
When editing a file, using the pattern editor to do simple text changes (such as backspace, then new line) cause the memory usage to grow each time. As an example, a file opened starts around 600Mb. I add the pattern viewer and editors, paste in the pattern, and the memory usage is now 2GB. I go to the end of the editor, and press enter, adding a new line. The memory usage jumps to around 2.4GB. Pressing backspace jumps the memory usage to 3.6GB, and so on.

Version: 1.7.0
Reproduction repo: https://github.com/Varunda/imhex-memory-repo. This repo has the file used in the viewer, as well as the pattern used

If you need more information lemme know!

**Comment by Varunda** [comment]
Testing with build #346

Open project: 2GB
Press backspace: Memory usage drops to 600MB, then goes back to 2GB
Again: 2'016 MB => 2'025 MB
Again: 2'025 MB => 2'035 MB
Again: 2'035 MB => 2'042 MB

So seems like there's still a small one, but much better. The big hiccup now is the massive memory drop then it returns to just a little bit more than what it had before. It makes editing the pattern a huge pain, as I have to wait several seconds before the editor is usable again.

**Comment by WerWolv** [comment]
Big arrays of static or built-in types are now being optimized
