### ISSUE TITLE
[Bug] readme.md claims support for MacOS Big Sur but pre-packaged 1.33.2 MacOS .DMG won't install there

### ISSUE THREAD

**Issue by gtackett** [WerWolv/ImHex#1647]
### Operating System

MacOS

### What's the issue you encountered?

The [requirements section of the readme.md](https://github.com/WerWolv/ImHex/?tab=readme-ov-file#requirements) claims support for MacOS Big Sur (11.x) or later, but the prepackaged .DMG for release 1.33.2 available at https://imhex.werwolv.net/ can't be installed on Big Sur because it was built against (I think) Sonoma.

If it's no longer feasible to provide a version installable on Big Sur, then the `readme.md` needs to be corrected.
Otherwise, please do provide such a version.

### How can the issue be reproduced?

1. Download the MacOS .DMG available at https://imhex.werwolv.net/.
2. On a MacOS Big Sur system, mount that .DMG.
3. In the Finder window that appears, attempt to launch ImHex.

### ImHex Version

1.33.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

DMG from https://imhex.werwolv.net/

**Comment by WerWolv** [comment]
Hey
When building ImHex from sources, it should definitely still support these old versions. macOS is sadly very picky about the versions applications support and we don't have real access to CI runners with those versions anymore. 
I'll update the readme.

**Comment by gtackett** [comment]
> When building ImHex from sources, it should definitely still support these old versions

See https://github.com/WerWolv/ImHex/discussions/1648#discussion-6587035 which will also get you to a comment I made on #910.

**Comment by madranet** [comment]
Came here to report the same issue [albeit more pictorially!]:

![Screenshot 2024-06-29 at 09 29 54](https://github.com/WerWolv/ImHex/assets/669658/cba9152b-69be-4979-833f-fec1b8a4d619)

![Screenshot 2024-06-29 at 09 26 41](https://github.com/WerWolv/ImHex/assets/669658/6675d689-44e8-4d4b-872b-31fc28586396)

![Screenshot 2024-06-29 at 09 29 02](https://github.com/WerWolv/ImHex/assets/669658/5fa30f4d-8b48-4e3d-bed2-ffb18b032421)

**Comment by WerWolv** [comment]
Updated the text in the readme now, thank you.
ImHex will almost certainly run on macOS version < 12.1 when compiled yourself though. The version restriction is entirely arbitrary and just enforced by Apple.
