### ISSUE TITLE
[Bug] Nightly - text cursor is invisible in a pattern editor

### ISSUE THREAD

**Issue by galkinvv** [WerWolv/ImHex#1649]
### Operating System

Linux

### What's the issue you encountered?

Invisible cursor in the pattern editor

### How can the issue be reproduced?

- open any file in a hex editor
- switch to pattern editor
- Result: the editing can be performed, but the text cursor is invisible. I have a deafult dark theme, never changed any colors

The problem is nightly-specific, latest Release 1.33.2 works fine. However it already present in nightlies for several weeks by now, not only in latest build.

### ImHex Version

1.33.0  master@ef99e9d

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Installed from nightly artifacts ubuntu 23.04 deb on a debian unstable.

**Comment by zziger** [comment]
Can confirm this happened when I built latest master branch today

**Comment by paxcut** [comment]
I am using a master nightly (1.33.0) from April 27 and the cursor is displayed fine. I suspect that this bug occurs because there are two systems that check for focus and both work on windows but using both doesn't work on Linux and on Web builds.

**Comment by galkinvv** [comment]
Seems to be fixed by https://github.com/WerWolv/ImHex/commit/10351c5bdc27ee3cd943316c719f086a9adc6439 - I have cursor ok with .deb Ubuntu 22.04 build from last nightly - https://github.com/WerWolv/ImHex/actions/runs/9009032110

This was nightly-only bug never presented in tagged release, so closing it.
