### ISSUE TITLE
Feature Request: Struct parameters/Abilities for structs to reference parent values

### ISSUE THREAD

**Issue by maddiethecafebabe** [WerWolv/ImHex#165]
Sometimes you run into a format that looks (simplified) like one of these 
```c
struct child1_t {
  char foo[]; // char[parent.len]
};

struct child2_t {
  //if parent.foo
  int value_1;
  //else
  float value2;
};

struct parent_t {
  u8 len;
  u8 foo;  
  child1_t child1;
  child2_t child2;
};
```
The core problem here is that the child structs need to backreference a value in an "upper" struct but there is not really a way to do so as far as I can tell. This is a issue a lot of format parsing utilities share and it makes working with formats like it a big pita. 

A problem in implementing a syntax for this would most likely be ugly and stray further away from "pure" C than we already are. Those are 2 syntax' I could think of that imo don't look all too horrible:

1. python-ish parent-referencing syntax
```c
struct child_t {
  char array[super().len];
};

struct parent_t {
  u8 len;
  child_t child;
};
```
`super()` here would allow an struct to access its current parent struct and access any member of it. The downsides with that are that it would mean those structs could not be used at the top level anymore.

2. c++/rust-type-parameter-ish syntax
```c++
struct child_t<len, extended> {
  char array[len];
  if (extended == 1)
    int extended_value;
};

struct parent_t {
  u8 len;
  u8 extended;
  child_t<len, extended> child;
};
```
The parameter list can be thought off as the parameter list in a function call. This would allow those structs to be used at the top level by using literals (e.g. `child_t<2, 0> child @ 0x00;`) but might look very alien to people expecting c/c++-ish struct syntax.

**Comment by fosterbrereton** [comment]
I believe this is already available with the `parent` keyword:

```
struct child_t {
  char array[parent.len];
};

struct parent_t {
  u8 len;
  child_t child;
};
```

**Comment by maddiethecafebabe** [comment]
Yeah, must have missed when that got implemented 2 months later. Guess I'll close this then
