### ISSUE TITLE
[Bug] ImHex fails to render on LLVMpipe

### ISSUE THREAD

**Issue by FireNX70** [WerWolv/ImHex#1653]
### Operating System

Linux

### What's the issue you encountered?

Attempting to run ImHex in a VM running Debian (using LLVMpipe for software rendering) will only render the window decorations. The program is still interactable, clicking on different parts of ImHex's window will execute different actions. The program can also be closed.

ef99e9d worked fine. From 1df0eea onward, I'd get a fatal error on start. 5785755 worked fine again. 0f5e125 and newer print multisampling errors and render window decorations only.

### How can the issue be reproduced?

Run ImHex (0f5e125 or newer) on Linux using LLVMpipe.

### ImHex Version

1.33.0 (0f5e125 or newer)

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Built with the build instructions for Linux

### Additional context?

Tested on Debian 12 with LLVMpipe 22.3.6.

**Comment by WerWolv** [comment]
Hey, could you please try with the latest commit? I explicitly check that the right OpenGL version is available now before activating it and don't immediately exit anymore if the splash screen couldn't be loaded. Hopefully that fixes it.

**Comment by FireNX70** [comment]
It's 89f360d, right? The error message has changed (still a multisampling error) but it still doesn't render anything besides window decorations.

**Comment by WerWolv** [comment]
Could you post your logs?

**Comment by FireNX70** [comment]
It doesn't seem to be writing any logs, the most recent ones are over a month old. They're supposed to be in my home (~/.local/share/imhex/logs/), right? I've been testing without installing (calling ninja without the install arg), I don't know if that could be affecting it.

**Comment by WerWolv** [comment]
It doesn't create any logs if ImHex is started from a console, it just logs to the console then. Could you post that?

**Comment by FireNX70** [comment]
I've installed it and run it from KDE's menu so now I do have a log file.
[20240508_230100.log](https://github.com/WerWolv/ImHex/files/15254719/20240508_230100.log)

**Comment by WerWolv** [comment]
Thank you. Could you try the latest commit again? I think that should fix it

**Comment by FireNX70** [comment]
Yeah, it's fixed.

**Comment by WerWolv** [comment]
Awesome, thanks a lot for testing!
There might still be an issue with LLVMpipe though. From the logs, it reports that it does support texture multisampling but the actual calls fail then. Might be worth reporting to them

**Comment by FireNX70** [comment]
Yeah, I guess I should submit a bug report to the Mesa devs.

**Comment by FireNX70** [comment]
For the record: https://gitlab.freedesktop.org/mesa/mesa/-/issues/11135
