### ISSUE TITLE
[Bug] Changing encoding in search panel closes panel

### ISSUE THREAD

**Issue by mehlian** [WerWolv/ImHex#1679]
### Operating System

Windows

### What's the issue you encountered?

When we try to change encoding on search panel under 'String' tab, by clicking on encoding dropdown then search panel closes.

### How can the issue be reproduced?

1. open any file
2. press ctrl+f in 'hex editor' view to show 'search panel'
3. go to 'String' tab
4. try to select encoding
5. search panel disappears

### ImHex Version

1.33.0

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Portable

### Additional context?

It should not close search panel when we try to change encoding.

**Comment by WerWolv** [comment]
Fixed in master
