### ISSUE TITLE
[Bug] When working on more than one file, the patter editor ignores new settings

### ISSUE THREAD

**Issue by Kaba8081** [WerWolv/ImHex#1682]
### Operating System

Windows

### What's the issue you encountered?

When importing files into a project, pattern editor ignores specified settings and uses default values.  By opening the file in a new window, everything is working fine, but rewriting the pattern, importing diffrent files, from diffrent locations did not fix the issue.

### How can the issue be reproduced?

Import a second file into a project by drag and dropping or File -> Open File.

### ImHex Version

1.33.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI installer

### Additional context?

First file opened in the project and it's values.
![OriginalFile](https://github.com/WerWolv/ImHex/assets/38621054/5c3e076f-7ea2-40b6-ad44-d56079d22a1b)

Every other has it's settings set to default (`endian little`, `bitfield_order right_to_left`, etc.) even though they should be changed.
![SecondFile](https://github.com/WerWolv/ImHex/assets/38621054/5973887c-d66b-431b-a112-91da6b28ce8b)

**Comment by paxcut** [comment]
The values on pragmas are not options that the pattern editor reads to use as values for newly opened or created patterns. pragmas are like any other preprocessor directives. A pattern file is just a text file that the pattern editor reads, displays and allows you to edit. Pattern editor does not perform any of the  duties associated with parsing or evaluating patterns , it is just a text editor. As it stands there is no way to specify a pragma value in one pattern that applies to all the patterns that are opened afterwards, unless you sync the patterns which means that all patterns are the same.

**Comment by Kaba8081** [comment]
You are right. Updating to the latest nightly version fixed the issue.
