### ISSUE TITLE
enhancement: conditional field / algebaric data type / tagged union

### ISSUE THREAD

**Issue by farteryhr** [WerWolv/ImHex#17]
something like a field in a struct with predicates about previous variable.
```
enum TypeTag : u8{
    U32 = 1,
    ARRAY = 2
}
struct Variable {
    TypeTag tag;
    u32 u32Value if tag==TypeTag.U32;
    u32 length if tag==TypeTag.ARRAY;
    Variable elements[length] if tag==TypeTag.ARRAY; // or pointer to array
}
```
that may help parsing of byte streams with a bit more complex structures with branching (like some simplified version of MessagePack, Protocol Buffer...) (but they're more complicated, e.g. the type tag is in bitfield, and needs more advanced way to spedcify how to parse a variable int, etc.)

**Comment by Kein** [comment]
Yep, that would be useful, 0Editor has similar stuff in his conditional parser

**Comment by WerWolv** [comment]
As of the latest commit, ImHex supports control flow statements using the `if` and `else` keywords. I hope this will make the language a lot more useful for you :)
![](https://puu.sh/H4sRE/a9ed41f9c7.png)
