### ISSUE TITLE
Pattern Language - Read byte/Seek

### ISSUE THREAD

**Issue by crziter** [WerWolv/ImHex#170]
Hello!

Thank you for great application!
I have an issue of using Pattern Language to parse H264 NAL stream, mainly because it don't have fixed size struct but use a dedicated bytes (0x000001 or 0x00000001) to mark as start of chunk. How can I scan the file to find those bytes with Pattern Language?

**Comment by WerWolv** [comment]
Hi. Please check out the pattern language [documentation](https://github.com/WerWolv/ImHex/wiki/Pattern-Language-Guide)! There's a built-in function called `findSequence` for exactly your usecase :)
