### ISSUE TITLE
[Bug] Imhex scaling issue at 1080 1.5x

### ISSUE THREAD

**Issue by NastyFlytrap** [WerWolv/ImHex#1703]
### Operating System

Windows

### What's the issue you encountered?

The top icons are cut off. The smiley face, the maximize window button, and the imhex exclusive buttons too like the bookmark green flag for example. All of them have their tops cut off. 

### How can the issue be reproduced?

Download the version listed below, resize the UI on a 1080p screen.

### ImHex Version

1.33.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by WerWolv** [comment]
Hey, I fixed this in the nightly builds but it hasn't ended up in a full release yet. A workaround you can use is to specify a custom font instead of using the default one or you download the latest build from https://imhex.download/#nightly

**Comment by NastyFlytrap** [comment]
> Hey, I fixed this in the nightly builds but it hasn't ended up in a full release yet. A workaround you can use is to specify a custom font instead of using the default one or you download the latest build from https://imhex.download/#nightly

Ah, neat! Alright, i'll just wait for it to be pushed live then, thanks!
