### ISSUE TITLE
Can not build in ubuntu 18 with Anaconda installed

### ISSUE THREAD

**Issue by alex-bender** [WerWolv/ImHex#171]
```
~ cmake -DCMAKE_BUILD_TYPE=Release ..
-- Checking for one of the modules 'libmagic'
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/alex/src/ImHex/plugins/libimhex/MBEDTLS_INCLUDE_DIR
   used as include directory in directory /home/alex/src/ImHex/plugins/libimhex

CMake Warning at CMakeLists.txt:37 (add_executable):
  Cannot generate a safe runtime search path for target imhex because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libfreetype.so.6] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/alex/anaconda3/lib

  Some of these libraries may not be found correctly.


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

```
How can I troubleshoot this better?

**Comment by theKidOfArcrania** [comment]
First, I suggest you check the `dist/get_deps_debian.sh` file that installs all the dependencies (this file is used in the automatic workflows), and make sure you have all of them installed. In this case if you look at the first error, that is actually just having the lack of libmbedtls-dev installed. If you look at the second note, that's just a warning, so it has nothing to do with anaconda

**Comment by dragonxtek** [comment]
I can't compile it in Ubuntu 20.10.
After running ./get_deps_debian.sh I get the following:
`cmake -DCMAKE_BUILD_TYPE=Release ..

-- Checking for one of the modules 'libmagic'
CMake Error: File /tmp/ImHex/external/yara/yara/libyara/yara.pc.in does not exist.
CMake Error at external/yara/CMakeLists.txt:124 (configure_file):
  configure_file Problem configuring file


CMake Error at plugins/libimhex/CMakeLists.txt:8 (add_subdirectory):
  The source directory

    /tmp/ImHex/external/nativefiledialog

  does not contain a CMakeLists.txt file.


CMake Error at plugins/libimhex/CMakeLists.txt:9 (add_subdirectory):
  The source directory

    /tmp/ImHex/external/fmt

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/tmp/ImHex/build/CMakeFiles/CMakeOutput.log".

`

**Comment by WerWolv** [comment]
You didn't clone the repository correctly. Delete it and try again with `git clone https://github.com/WerWolv/ImHex --recurse-submodules`
