### ISSUE TITLE
[Bug] #pragma eval_depth is nonfunctional and seemingly ignored by the compiler

### ISSUE THREAD

**Issue by EtiTheSpirit** [WerWolv/ImHex#1716]
### Operating System

Windows

### What's the issue you encountered?

I am crossporting a piece of code from 010 editor, and when doing this, I ran into the evaluation depth limit. When prompted with the instructions of how to raise the limit, I did exactly as it suggested, only to see the exact same error appear with the same limit of 32 reported to me.

I tried a bunch of numbers, all of which made no change, until I ultimately decided I'd take a break and type in some random nonsense before I moved onto other work. It was in this moment I learned that indeed, `#pragma eval_depth at least seven` will compile. This also includes negative values, floating point values, nothing. It just works™. Good.

### How can the issue be reproduced?

1. Make a new file and open the pattern editor.
2. Enter `#pragma eval_depth asdfg` and compile.
3. This should compile without error. Anything after eval_depth (including nothing) will compile without complaint.

### ImHex Version

1.33.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by paxcut** [comment]
The bug only exists on the release branch (1.33.2). Master branch (1.33.0) fixes it and any recent nightly build with version 1.33.0 should have working `#pragma` directives.
