### ISSUE TITLE
Add create new file feature

### ISSUE THREAD

**Issue by bvernoux** [WerWolv/ImHex#172]
Any Hex Editor can create file but it is not possible to do that with ImHex so far so it will be great to add that to create a file (binary/txt ...) from scratch from ImHex like we can do with any Hex Editor

**Comment by bvernoux** [comment]
Any Hex Editor can create file but it is not possible to do that with ImHex so far so it will be great to add that to create a file (binary/txt ...) from scratch from ImHex like we can do with any Hex Editor

**Comment by khyveasna11111908** [comment]
HDD usage for you and

**Comment by Wunkolo** [comment]
+1 from me!
I would absolutely love this feature so I can quickly create a new file and start typing in hex values and such.
