### ISSUE TITLE
[Bug] In the Pattern editor, std::print(") without a corresponding quote crashes ImHex

### ISSUE THREAD

**Issue by rxxsta** [WerWolv/ImHex#1725]
### Operating System

Linux

### What's the issue you encountered?

In the "Pattern editor" view, whenever `std::io::print()` contains only one quote (") or single quote (') and it does not have a corresponding quote, ImHex crashes. The crash does not seem to show up in the crash logs. And note, the `std.io` library does not need to be imported.

### How can the issue be reproduced?

Open any file > Pattern editor > paste the following and run/evaluate:
```rust
std::io::print(");
```

### ImHex Version

1.33.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Archlinux AUR Package

**Comment by WerWolv** [comment]
Thanks for the report, this should be fixed in the latest master
