### ISSUE TITLE
[Bug] Export selection to file infinite loop

### ISSUE THREAD

**Issue by kyle-sylvestre** [WerWolv/ImHex#1733]
### Operating System

Windows

### What's the issue you encountered?

This is a test of fix #1619 
The created file contains everything except the last byte still.
The task now loops infinitely.

![Untitled](https://github.com/WerWolv/ImHex/assets/25188464/579fdf4c-6aaa-4500-a605-8bfa8f34db45)

### How can the issue be reproduced?

1. open file
2. select a range of bytes
3. click File > Export > Selection to File...
4. select output file
5. observe task stuck in an infinite loop

### ImHex Version

1.34.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

imhex-1.34.0-Windows-Portable-x86_64.zip

**Comment by Nemoumbra** [comment]
Thank you for your input! We have found this bug too, I just didn't create an issue (hoped in would be resolved prior to the release).
