### ISSUE TITLE
[Bug] Search backward never finished in some file

### ISSUE THREAD

**Issue by yyjdelete** [WerWolv/ImHex#1734]
### Operating System

Windows

### What's the issue you encountered?

1. Search backward will never finished in some file
2. and you can't cancel the task or quit imhex without kill the whole process.

### How can the issue be reproduced?

1. Open `imhex-gui.exe`
3. Move to end of the file
4. Try search `637878` in hex(or `cxx` in utf8) backward

Search forward works well.

### ImHex Version

v1.34.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

### Additional context?
The last working version is `v1.32.2`

System Language: Chinese(zh_CN), encoding=gb2312(cp936), if it's an system encoding related problem.
![image](https://github.com/WerWolv/ImHex/assets/1819074/6de4f0b7-38fb-45a4-aee6-3fa66edee625)

**Comment by yyjdelete** [comment]
Still see another `infinite loop` after the PR, seems something is out of sync, and it does search out of the file range
1. Create an new file(length=1);
2. Search anything forward, and reach the end(No more results);
3. `Edit->Resize`, and resize it to length=`0x0` 
5. Search forward again and infinite loop;

**Comment by WerWolv** [comment]
Thanks a lot for the PR and the investigation! I'll take a look at the new infinite loop you've discovered
