### ISSUE TITLE
OpenGL 3.0

### ISSUE THREAD

**Issue by ranoke** [WerWolv/ImHex#174]
My pc does not support opengl 3.2 and greater. Pls add configuration so i can set opengl3.0 to use :)

**Comment by htfvbrt5** [comment]
Bj

**Comment by xtexChooser** [comment]
May you can try MESA3d with software renderering.

If you don’t mind Chinese, maybe you can take a look at this document I wrote before:
[http://xtexx.ml/blog/software-renderer-for-opengl32/](http://xtexx.ml/blog/software-renderer-for-opengl32/)
