### ISSUE TITLE
[Bug] DDS pattern is incorrect

### ISSUE THREAD

**Issue by RunDevelopment** [WerWolv/ImHex#1744]
### Operating System

Windows

### What's the issue you encountered?

`PixelFormatFlags` in the pattern for DDS files is incorrect. This is the current pattern:

```c
bitfield PixelFormatFlags {
  alphaPixels : 1;
  alpha       : 1;
  fourCC      : 1;
  padding     : 3;
  rgb         : 1; // 0x40
  padding     : 2;
  yuv         : 1; // 0x200
  padding     : 3;
  luminance   : 1; // 0x20000
  padding     : 17;
};
```

The bug is that the padding between `yuv` and `luminance` should be 7 and not 3. This can be seen by looking at the hex constants in the comments (count the zeros).

The correct version should be:

```c
bitfield PixelFormatFlags {
  alphaPixels : 1;
  alpha       : 1;
  fourCC      : 1;
  padding     : 3;
  rgb         : 1; // 0x40
  padding     : 2;
  yuv         : 1; // 0x200
  padding     : 7;
  luminance   : 1; // 0x20000
  padding     : 13;
};
```

### How can the issue be reproduced?

-

### ImHex Version

1.34.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

### Additional context?

I'm not sure whether this is the right place to report this issue.

**Comment by sisco0** [comment]
The issue should be moved to this other repository, which is focused on ImHex Patterns: https://github.com/WerWolv/ImHex-Patterns/issues

**Comment by sisco0** [comment]
I created the Pull Request to consider the current [GIMP](https://gitlab.gnome.org/GNOME/gimp/-/blame/master/plug-ins/file-dds/dds.h#L145) implementation for Direct-Draw Surface (DDS).

**Comment by WerWolv** [comment]
Merged 👍 Thanks a lot for the effort

**Comment by RunDevelopment** [comment]
Thank you!
