### ISSUE TITLE
Just run and exit.

### ISSUE THREAD

**Issue by lijicheng168** [WerWolv/ImHex#175]
HI, I try to run the imhex.exe but it just run with 40k memory,and exit after few seconds.
There is no error message box and nothing.
I try the portable and ths Installer with the same error.

**Comment by sandorex** [comment]
I had the same issue, i had to run the exe as administrator for it to work

**Comment by auxym** [comment]
Same issue here with the latest release (1.8) on win10. After running once in admin mode, running in regular mode works.

**Comment by fenginsc** [comment]
This software has never been successfully run on my computer, no matter what version, my system is windows7 64-bit professional edition

**Comment by WerWolv** [comment]
Windows 7 is currently unsupported. I'm still looking into how to fix it.
Try Windows 10 or any other of the supported OSes
