### ISSUE TITLE
[Bug] Elevated ImHex creates application settings folders in C:\Program Files\ImHex, they overlap effective layout settings

### ISSUE THREAD

**Issue by pnosov** [WerWolv/ImHex#1767]
### Operating System

Windows

### What's the issue you encountered?

ImHex tries to create application settings folders in its Program Files directory every time it starts.

![image](https://github.com/WerWolv/ImHex/assets/62751738/65f95cab-2ce6-427f-80b8-b5e0f7063880)

When running as normal user, this action fails because normal user only has read rights under Program Files folder. But when ImHex is launched with UAC (run as administrator), a new set of user settings folders is created in C:\Program Files\ImHex is created.

![image](https://github.com/WerWolv/ImHex/assets/62751738/0fad60a9-3af3-4c79-87f7-33a3d7e59a97)

![image](https://github.com/WerWolv/ImHex/assets/62751738/eab33fc6-f3cd-431a-9623-fab92fe90b38)

This default workspace from this set is used every time when ImHex is launched even as a normal user. If I change layout - show or hide tabs, resize them - the change is ignored after application restart.

From this moment, layout cannot be modified unless ImHex is launched as administrator. Either, deletion of these new settings folders in Program Files helps, but until ImHex is launched again as administrator.

### How can the issue be reproduced?

Try to run ImHex as administrator, new set of folders appears in installed program folder (C:\Program Files\ImHex):

backups     
config      
layouts     
lib         
logs        
recent      
resources   
scripts     
themes      
workspaces  
yara        

All of them are empty, except for workspaces which contain two files - default.hexws and minimal.hexws.

After that, when running ImHex with non-elevated rights, settings such as layout cannot be changed, they revert after restart.

### ImHex Version

1.34.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

### Additional context?

Windows 11 23H2

**Comment by WerWolv** [comment]
Hey, thanks for the report! The latest commit should improve upon this and no longer try to write to any system directories. Could you try out the nightly once it finished building?

**Comment by pnosov** [comment]
Thank you for your respond. I have tried today's nightly MSI build.

After installing it and running ImHex as administrator, 10 empty directories are still being created:

scripts
workspaces
layouts
themes
logs
resources
backups 
yara
patterns\include
lib

At least, default workspace layout files aren't being created, this solves a problem with settings overlapping. Although, I suppose these directories shouldn't be created at all in Program Files.

**Comment by WerWolv** [comment]
Latest commit should fix this as well. Thanks a lot for testing!
