### ISSUE TITLE
Add repology badge

### ISSUE THREAD

**Issue by luzpaz** [WerWolv/ImHex#177]
### Summary
A way for devs, package managers, and users to see what downstream repositories carry imhex

### Proposed design
The full badge looks like so:  
[![Packaging status](https://repology.org/badge/vertical-allrepos/imhex.svg?header=rtmidi)](https://repology.org/project/imhex/versions)  

but since it take up a lot of room it can be simply added as a single badge such as:

[![Packaging status](https://repology.org/badge/tiny-repos/imhex.svg)](https://repology.org/project/imhex/versions)

**Comment by WerWolv** [comment]
None of these repo entries are maintained by me so I don't think it makes sense to have them in the repo

**Comment by luzpaz** [comment]
Of course, but have you heard of an opensource project that maintains all its own packages on the ever-expanding number of the  platform/distro ecosystem? The point of the badge is to show the versions available in the ecosystem.

**Comment by WerWolv** [comment]
Hm are these badged automatically getting updated? e.g if ImHex gets added to a new repository, will it automatically get picked up by this service? Otherwise I'd probably not be very up-to-date

**Comment by luzpaz** [comment]
Yes, auto-updated
