### ISSUE TITLE
libmbedtls.so.20: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by thaMilo** [WerWolv/ImHex#1770]
### Operating System

Linux

### What's the issue you encountered?

Just downaloaded the arch linux release and installed it as written in the documentation. Tried to run it but got this error:

imhex: error while loading shared libraries: libmbedtls.so.20: cannot open shared object file: No such file or directory

### How can the issue be reproduced?

1. Running arch linux download and install the latest release version for the operating system
2. Run the imhex command from cli

### ImHex Version

1.34.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Arch linux package

**Comment by WerWolv** [comment]
Hey, thank you for the report

This issue keeps coming back because Arch Linux keeps renaming the mbedtls library with every new version but they don't keep around the older versions. It will fix itself with the next release. Until then, please use the AppImage build or the Flatpak instead

**Comment by thaMilo** [comment]
Oh that's a shame...
Thank you anyway! Keep up the good work @WerWolv !

**Comment by iTrooz** [comment]
Main issue: https://github.com/WerWolv/ImHex/issues/1532
