### ISSUE TITLE
[Bug] 1.35.2 Stuck at "Creating Directories..."

### ISSUE THREAD

**Issue by mikeswanson** [WerWolv/ImHex#1777]
### Operating System

Windows

### What's the issue you encountered?

I just downloaded and installed `imhex-1.35.2-Windows-x86_64.msi` on Windows 11. When I try to launch the app, it never makes it past the "Creating Directories..." phase of the start-up window.

<img width="971" alt="ImHex" src="https://github.com/WerWolv/ImHex/assets/1572534/c1daeef5-8173-45ae-bf02-42633d0d6f41">

### How can the issue be reproduced?

1. Download `imhex-1.35.2-Windows-x86_64.msi`.
2. Start the app.

### ImHex Version

1.35.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

imhex-1.35.2-Windows-x86_64.msi

**Comment by WerWolv** [comment]
Why is it so hard to get this right 😢

**Comment by WerWolv** [comment]
Could you please check the latest nightly build once github finished building it? That should hopefully correct it.
Here's the link: https://github.com/WerWolv/ImHex/actions/runs/9726353753

**Comment by WerWolv** [comment]
Actual download link: https://github.com/WerWolv/ImHex/actions/runs/9726353753/artifacts/1651649221
I tested it on Windows 11, macOS 15 and Ubuntu 24.04 now and it seems to work on all of them. I _really_ hope that fixes it

**Comment by arek-kwapis** [comment]
> Actual download link: https://github.com/WerWolv/ImHex/actions/runs/9726353753/artifacts/1651649221 I tested it on Windows 11, macOS 15 and Ubuntu 24.04 now and it seems to work on all of them. I _really_ hope that fixes it

I was experiencing the exact same issue, can confirm this build has resolved the issue for me and ImHex has successfully started up. Windows 11 23H2, clean install of ImHex using the build linked in reply.

**Comment by WerWolv** [comment]
Awesome thanks a lot. I'll release _yet another_ version with this fix then

**Comment by arek-kwapis** [comment]
Additional info:

This seems to only affect normal install, portable works without issue. Installing the aforementioned build on top of affected install also does fix the issue. 

Attached is the output of both with verbose arg passed

![imhex-1352](https://github.com/WerWolv/ImHex/assets/41341520/ffe0720c-b40d-4844-851c-291cb18b609e)

**Comment by mikeswanson** [comment]
Just adding that the linked-to build also fixed it for me. Thank you for the quick response!
