### ISSUE TITLE
[Bug] Clicking "New Update Available" Doesn't Work

### ISSUE THREAD

**Issue by mikeswanson** [WerWolv/ImHex#1780]
### Operating System

Windows

### What's the issue you encountered?

Clicked the "New Update Available" announcement in the opening window, a command-line window quickly flashes, then exits. Nothing else happens.

I was able to quickly screenshot the window:

<img width="477" alt="ImHex_Bug" src="https://github.com/WerWolv/ImHex/assets/1572534/1b81069b-6989-4032-aab6-719849eedecd">

### How can the issue be reproduced?

Click on the "New Update Available" announcement in Windows 11.

### ImHex Version

1.36.0.WIP

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

imhex-1.36.0.WIP-Windows-x86_64.msi

### Additional context?

This is the interim/test build for the issue where ImHex wouldn't launch correctly in Windows 11, so perhaps it's specific to that special release.

**Comment by WerWolv** [comment]
Thanks for the report, the latest commit should fix this now. Also the latest release should start properly on Windows 11 as well again
