### ISSUE TITLE
[Bug] Type error while building sample plugin using MSVC Build Tools 2022

### ISSUE THREAD

**Issue by syntroniks** [WerWolv/ImHex#1790]
### Operating System

Windows

### What's the issue you encountered?

From the sample plugin repo (issues are disabled) https://github.com/WerWolv/ImHex-Plugin-Template

After gathering required packages (freetype, glfw3) using `vcpkg`, compilation stops around

```
[build] C:\Program Files\ImHex\sdk\lib\external\libwolv\libs\types\include\wolv\types.hpp(21,22): error C2061: syntax error: identifier '__int128_t' [C:\Users\user\ImHex-Plugin-Template\build\ImHexSDK\lib\external\libwolv\libs\utils\libwolv-utils.vcxproj]
[build]   (compiling source file '../../../../../../../../../../Program%20Files/ImHex/sdk/lib/external/libwolv/libs/utils/source/utils/string.cpp')
[build]   
```

### How can the issue be reproduced?

1. Clone https://github.com/WerWolv/ImHex-Plugin-Template
2. Configure the project
3. Attempt to build the `example_plugin` target

Some targets succeed like `generator-example_plugin`

### ImHex Version

1.32.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

### Additional context?

Additional guidance for Windows plugin building would be helpful.

Alternatively, a less restricted plugin interface (DLL exports/import) or scripting language bindings could make plugin development more accessible.

My goal is to add new data processor nodes.

**Comment by WerWolv** [comment]
Compiling using MSVC or clang-cl are majorly unsupported. You need to use mingw if you're working on Windows.

> Alternatively, a less restricted plugin interface (DLL exports/import) 

That would require exposing the entire API as a C interface as well which is a major endeavour

> scripting language bindings

We have support for .NET scripts nowadays, there's a template in `plugins/script_loader/templates` but the capabilities are also still limited. Adding a new data processor node is not possible with it.
