### ISSUE TITLE
[Bug] Font problem in 4k monitors

### ISSUE THREAD

**Issue by HolyOne** [WerWolv/ImHex#1794]
### Operating System

Windows

### What's the issue you encountered?

I use a 4k monitor and the application starts ike it is built for ants. very small fonts. not usable.
Then I click settings, to change font size i have to change the font.
OK I change the font but i see no preview of the size. I have to restart the applciation just to see if the font size is ok.
too much hustle to make a hex editor work. 
First impression is important, so I think this should be a priority

### How can the issue be reproduced?

Just open the application in a 4k monitor

### ImHex Version

1.35

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by WerWolv** [comment]
No need to be snarky like that.

A 4k monitor is not something any of us just has laying around so fixing this is really not straight forward. If you, or anybody else, has a 4k monitor, please consider submitting a PR instead of just making passive aggressive comments.

**Comment by HolyOne** [comment]
I am frustrated because i like the hex editor so much and not usable on my 4k screen :)

note: dont forget to increase font size on 4k test, most people use larger font size (150%)  on 4k. but ImHex dont take text size setting (on display settings) into consideration so its text remains tiny
