### ISSUE TITLE
PKGBUILD for Arch

### ISSUE THREAD

**Issue by Dax89** [WerWolv/ImHex#18]
Hi, first of all: very nice project!
We need a good cross platform hex editor and this is a great one!

I have prepared a PKGBUILD so it can be uploaded on AUR:
```
pkgname=imhex-git
pkgver=r183.5915525
pkgrel=1
url='https://github.com/WerWolv/ImHex'
arch=('i686' 'x86_64')
pkgdesc='A Hex Editor for Reverse Engineers and Programmers'
license=('GPL2')
depends=('glm' 'glfw' 'file' 'openssl' 'capstone' 'llvm' 'llvm-libs' 'nlohmann-json' 'python3')
makedepends=('git')
conflicts=(imhex)
provides=(imhex)
source=('git+https://github.com/WerWolv/ImHex.git' 'imhex')
md5sums=('SKIP' 'cc704bc8db518dbf16197e3a0a9b94ad')

pkgver() {
  cd ImHex
  printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

build() {
  mkdir -p build
  cd build
  cmake ../ImHex -DCMAKE_INSTALL_PREFIX=/usr
  make -j
}

package() {
  install -D -m755 imhex ${pkgdir}/usr/bin/imhex
  cd build
  install -D -m755 ImHex ${pkgdir}/usr/bin/ImHex
}
```

There is also a little bash script called `imhex`, so `imgui.ini` is saved in `$HOME/.local/share/ImHex` (I don't know if this path can be changed from C++):

```
#! /bin/sh

SETTINGS_FOLDER=$HOME/.local/share/ImHex
mkdir -p $SETTINGS_FOLDER
cd $SETTINGS_FOLDER
/usr/bin/ImHex
```

**Comment by Thog** [comment]
Was planning to do one today :cry: 

Anyhow, i686 target will surely not work right now so might be a good idea to drop it for now.
Also, would be nice to explicitly support aarch64 too.

**Comment by WerWolv** [comment]
Thanks a lot :)
Yeah what @Thog said. Right now 32 bit fails to build because there's no 128 bit type available and some other oversights. I' also can't guarantee yet that it will work properly afterwards. So I suggest removing that build for now until I properly managed to fix those issues

**Comment by Foxboron** [comment]
I'm planning packaging this up for `[community]`. What I'd like to see is some standardized directory to look for settings and patterns. `/usr/lib/imhex/patterns` or something would be wonderful. Can then provide a clone of the patterns repository for the package as well.

**Comment by umarcor** [comment]
I'd be glad to add CI testing for the Arch Linux PKGBUILD recipe in the GitHub Actions workflow: #31.

**Comment by Mailaender** [comment]
I used your handy wrapper script in https://build.opensuse.org/request/show/853394 Thanks!
