### ISSUE TITLE
[Bug] Frequent crashes on MacOS

### ISSUE THREAD

**Issue by TheOnlyZac** [WerWolv/ImHex#1805]
### Operating System

MacOS

### What's the issue you encountered?

ImHex is frequently crashing for me on MacOS. The crashes seem random, I can't find any correlation between them and anything I am doing. It even crashes if I just leave it running in the background. The only common thread is that I was working with a particular binary file and a pattern I wrote, but sometimes it crashed before I even evaluated the pattern.

### How can the issue be reproduced?

Open ImHex and open the binary file, paste the pattern into the pattern editor. After some time it crashes randomly whether or not I do anything.

### ImHex Version

1.35.3

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

.dmg from the website

### Additional context?

2019 Macbook Pro (Intel i7, 16 GB RAM, MacOS Sonoma 14.2.1).
[binary+pattern.zip](https://github.com/user-attachments/files/16137670/binary%2Bpattern.zip)
[logs.zip](https://github.com/user-attachments/files/16137215/logs.zip)

**Comment by jepebe** [comment]
I experienced similar random crashes. Both with the DMG and the Brew version. 

Ventura 13.4.1
Apple M1 Pro

**Comment by WerWolv** [comment]
Please update to the latest release, that should have the issue fixed.
