### ISSUE TITLE
Settings not being saved

### ISSUE THREAD

**Issue by Kibouo** [WerWolv/ImHex#182]
Settings _not_ related to window placement are not being saved.

Example:
- Change theme to "Light" -> see UI change -> restart -> UI is dark again
- Go to `Options` (bottom left) of the Hex Editor view and change any option -> restart -> options have been reset

There might be many more possible options which aren't being saved, these are only a few examples.

Version:
1.7 from the AUR.

**Comment by Kibouo** [comment]
Was having a look at the source. The examples I mentioned are actually 2 different "types" of options.

The `Help` -> `Settings` options are global. They do not persist because ImHex tries to write `settings.json` next to the binary. My binary resides in `/usr/bin`, so it doesn't have permissions to write the file.
This could be solved by having it write to a proper config directory, e.g. `$HOME/.config/imhex` on Linux or in AppData on Windows. This could be made to fix #46 as well.

The 2nd types of options are specific to their views. Thus, they could be solved by adding virtual methods to `View` which get/set their options. These methods would then be used in `ImHexSettingsHandler_ReadLine` and `ImHexSettingsHandler_WriteAll` to save the settings to the `imgui.ini` file.

These are only suggestions. Maybe the author already had a solution in mind.

I'd be willing to write a PR to fix these setting issues.

**Comment by WerWolv** [comment]
Hi
Yeah, the exact issue is that currently imhex tries to fins all its metadata files directly next to the executable. This however will be fixed soon though through PR #181 and #183 :)

**Comment by Kibouo** [comment]
Ah yes, those PRs look nice!

However, View options such as these would still not be saved, right? (Maybe you don't intend for them to be saved...?)
![image](https://user-images.githubusercontent.com/25766329/109434268-c223e900-7a14-11eb-89d8-b407de5fbce3.png)

**Comment by WerWolv** [comment]
Ah no they aren't hooked up at all. They were part of the original hex editor template I used and should really be part of the main settings interface. I'll take care of it once the other PRs have been merged

**Comment by Flamaros** [comment]
As user I am also expecting that the window size and positions to be restored when restarting ImHex or loading a session.
I am under Windows and settings files can't stay in the same folder as suggested in PR #181 and #183, some directories like "C:\Program Files" requires administrator right to be able to write in it and this is the default folder selected by the installer.

Settings files should go to local app data or roaming, take a look at https://docs.microsoft.com/fr-fr/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath?redirectedfrom=MSDN

Qt seems to use correct folders on multiple OS:
https://doc.qt.io/qt-5/qstandardpaths.html

**Comment by roblabla** [comment]
> some directories like "C:\Program Files" requires administrator right to be able to write in it and this is the default folder selected by the installer.

We could fix this by setting up an SDDL that makes the C:\Program Files\imhex folder world writable in the Windows MSI Installer. That would be a simpler solution.

**Comment by Kibouo** [comment]
Why not just change https://github.com/WerWolv/ImHex/blob/3e6865ffa9e6bd04c059d13c380c26394b86812f/plugins/libimhex/source/helpers/utils.cpp#L201 to point to `AppData/Roaming`? The path is even available from the env var `{FOLDERID_RoamingAppData}` iirc.
