### ISSUE TITLE
[Bug] "Edit the hex" achievement doesn't unlock

### ISSUE THREAD

**Issue by BobSmun** [WerWolv/ImHex#1846]
### Operating System

Windows

### What's the issue you encountered?

Modifying a byte by double-clicking on it and then entering the new value does not unlock the "Edit the hex" achievement

### How can the issue be reproduced?

* open any file
* ensure that the prerequisite achievement ("You and you and you") has been completed, but "Edit the hex" has not 
* double-click on a byte in the 'Hex Editor' view
* type a different value, such that the byte shows red as modified
* single-click elsewhere in the 'Hex Editor' view to finalize modifying

Alternatively, use enter (_not_ num-pad enter) to start or finish the edit

### ImHex Version

1.35.4

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

### Additional context?

In the code, it looks like `EventPatchCreated` is subscribed to, to unlock the achievement, but a search does not show the event being posted / raised anywhere

**Comment by paxcut** [comment]
I can confirm issue on dev branch 1.36.0-wip as well, but I think `EventPatchCreated ` may be for the ROM hacks achievement. If so and it is not posted maybe that one doesn't work either.

**Comment by BobSmun** [comment]
`EventPatchCreated` certainly sounds like it would be intended for the 'ROM hacks' achievement, but it unlocks "hex.builtin.achievement.hex_editor.modify_byte.name", whereas the `exportIPSPatch` and `exportIPS32Patch` functions call `unlockAchievement` (with "hex.builtin.achievement.hex_editor.create_patch.name") directly

**Comment by iTrooz** [comment]
Fixed by #1985
