### ISSUE TITLE
[Bug] Open file/project immediately crashes ImHex

### ISSUE THREAD

**Issue by m0nhawk** [WerWolv/ImHex#1851]
### Operating System

Linux

### What's the issue you encountered?

ImHex is immediately crashes on either "Open File" or "Open Project".

### How can the issue be reproduced?

1. Open ImHex.
2. Click "Open File" or "Open Project".
3. ImHex crashes without any errors.

### ImHex Version

1.35.4

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Fedora package: imhex-1.35.4-1.fc40.x86_64.rpm

### Additional context?

There are no errors while running `imhex --verbose`. The last few lines are:
```
[23:01:36] [DEBUG] [libimhex | Main]           Creating background task Load banner
[23:01:36] [INFO]  [libimhex | Main]           Updating workspace
[23:01:36] [DEBUG] [libimhex | Load banner]    Task 'Load banner' finished
 ~ 1 $ 
```

Running under Gnome and Wayland.

**Comment by Squiblydoo** [comment]
I'm experiencing this problem as well. It appears to be an issue with opening the dialog to view files on the local drive. As one can open a file by dragging-and-dropping. 

Other options such as attempting to "Browse" the local drive for things such as Pattern files will also cause ImHex to crash.
I'm using Ubuntu 22 and am on ImHex v1.35.4.

**Comment by btzy** [comment]
I think the nativefiledialog-extended submodule needs to be bumped; https://github.com/btzy/nativefiledialog-extended/commit/2d21ecbfaec051c4b32e586c664b3c5743c3097d probably fixes it.  Can you try the CI build from #1834?

**Comment by m0nhawk** [comment]
@btzy Yes, it works now: a couple of days ago I received an update to [`nativefiledialog-extended-1.2.1-1.fc40` ](https://packages.fedoraproject.org/pkgs/nativefiledialog-extended/nativefiledialog-extended/fedora-40-updates.html).

I guess I can close it now. :smiley:
