### ISSUE TITLE
[Bug] Cannot cast bitfield in bitfield/struct to type 'integer'

### ISSUE THREAD

**Issue by adavidzh** [WerWolv/ImHex#1853]
### Operating System

MacOS

### What's the issue you encountered?

While a bitfield/struct direct member can be cast to an integer (for comparison purposes) if the member is a bitfield itself then it seems it can't. My use case is an array of 3-bit fields.

For instance, the following works:
```
bitfield SomeBits{
    first_nibble: 4;
    second_nibble: 4;
    last_byte: 8;
}[[static]];

fn compare_some_bits(SomeBits bits){
    if(bits.first_nibble - 0){
        std::print("Yay!");
    }
};

SomeBits some_bits @ 0x00;
compare_some_bits(some_bits);
```
On the other hand, neither of the following two work:
```
bitfield MyField{
    field: 4;
}[[static]];

struct UnrolledBits{
    MyField flags0;
    MyField flags1;
    u8 last_byte;
}[[static]];

fn compare_unrolled_bits(UnrolledBits bits){
    if(bits.flags0 - 0){
        std::print("Yay!");
    }
};

UnrolledBits unrolled_bits @ 0x00;
compare_unrolled_bits(unrolled_bits);


bitfield ArrayBits{
    MyField flags[2];
    last_byte: 8;
}[[static]];

fn compare_array_bits(ArrayBits bits){
    if(bits.flags[0] - 0){
        std::print("Yay!");
    }
};

ArrayBits array_bits @ 0x00;
compare_array_bits(array_bits);
```
They both croak with something like
```
E: [ Stack Trace ]
E: <Source Code>:34:22
E: 34 |     if(bits.flags0 - 0){
E:                           ^
E: <Source Code>:36:5
E: 36 |     }
E:          ^
E: <Source Code>:41:36
E: 41 | compare_unrolled_bits(unrolled_bits);
E:                                         ^


E: runtime error: Cannot cast value to type 'integer'.
```

I would have expected members struct/bitfield members of a struct/bitfield to be able to be cast to integers.

### How can the issue be reproduced?

See code above and the [SomeBits.hexproj.gz](https://github.com/user-attachments/files/16637804/SomeBits.hexproj.gz) project (gzipped because of github).

### ImHex Version

1.35.4

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

brew

**Comment by paxcut** [comment]
I don't think there is a bug here. The reason for the error message is that you are trying to use variables of type `MyField` as if they were integers. They contain integer members that you could use in the operation like this:
```cpp
fn compare_unrolled_bits(UnrolledBits bits){
    if(bits.flags0.field - 0){
        std::print("Yay!");
    }
};

fn compare_array_bits(ArrayBits bits){
    if(bits.flags[0].field - 0){
        std::print("Yay!");
    }
};
```
Another way of saying the same thing is that what you are trying to do in the last two examples that croak  would be equivalent to doing this in the first example which would also croak.
```cpp
fn compare_some_bits(SomeBits bits){
    if(bits - 0){
        std::print("Yay!");
    }
};
```
To cast to an integer a variable has to be of an integer type. struct and bitfield variables cannot  cast to integers, ever. struct or bitfield member variables can cast to integers only if they are integers themselves.

**Comment by adavidzh** [comment]
Ah, I see what you mean. It's the field in the `bitfield` that can be cast, not the `bitfield` itself. That makes sense.

(Is there a way to have non-`uN` `enum`s?)

**Comment by paxcut** [comment]
from the docs:
```
The type following the colon after the enum name declares the enum’s underlying type and can be any built-in datatype. This type only affects the enum’s size.
```
So yes, they can be any built-in type, but that's only to determine the size. If you use floats, you'll get s32, if you use doubles, s64. At least that's how i interpret that cause i never have tried anything other than integer types.

**Comment by adavidzh** [comment]
Hm. The following is not happy at all:
```
bitfield Status{
    value: 3;
}[[static]];

enum Flags: Status {
   one, two, three, four, five, six, seven, eight,
};

bitfield Thing{
    Flags status[5];
    padding: 1;
}[[static]];

Thing thing @ $;
```
tells me that
```
E: runtime error: Bitfield arrays may only contain bitwise fields.
E:   -->   in <Source Code>:10:19
E: 10 |     Flags status[5];
```

[BitfieldEnum.hexproj.gz](https://github.com/user-attachments/files/16647995/BitfieldEnum.hexproj.gz)

 (Should I open a different ticket?)

**Comment by paxcut** [comment]
Only builtin types means what you would call basic types. integers, bools, etc. enums structs union and such create user defined types and those cannot be used
