### ISSUE TITLE
Improve file dialog

### ISSUE THREAD

**Issue by Flamaros** [WerWolv/ImHex#188]
As Windows user I am a little perturbed by the actual file dialog, a lot of features of the default Windows implementation are lacking:

- Default folder shortcuts (Computer, Documents, pictures, favorites,...)
- Can't use File explorer features in the file list (right click for creating folders, renaming files,...)

As this is a temporary dialog maybe instead of trying to recreate the OS specific dialog it is better to use it even if it will break the application skin.

This is a difficult question as developer, I don't really know how to address correctly this issue, maybe it worth it to try to re-implement the file dialog even if for the moment I never saw an application providing a custom implementation that is good enough. Is your version provided directly by Dear ImGUI, in which case I should report an issue to this library or try to submit a PR.

**Comment by WerWolv** [comment]
Hi
I already replaced the custom one with a library that handles file dialogs on all OSes a few commits ago. It will be in the next release :)

**Comment by Flamaros** [comment]
Wow, super fast answer thx.

Can you tell me which library you use?

**Comment by WerWolv** [comment]
Yeah sure. I used this one here: https://github.com/btzy/nativefiledialog-extended as recommended by @roblabla
