### ISSUE TITLE
Feature request: Specify base address

### ISSUE THREAD

**Issue by jared52005** [WerWolv/ImHex#19]
Hi, I would like to be able to specify base address of loaded file.
i.e. File is downloaded from a RAM of CortexM4 (0x20000000). Being able to specify base address, navigation would be easier.

**Comment by WerWolv** [comment]
Hi!
Right now you can only do that in the disassembly view but that sounds like a nice thing to have in general. I'll look into it

**Comment by sonerb** [comment]
I have a application code start at spesific address.
I need this feature too. 👍
