### ISSUE TITLE
[Bug] Parser error on placement of anonymous variable inside struct

### ISSUE THREAD

**Issue by mrnerdhair** [WerWolv/ImHex#1900]
### Operating System

Linux

### What's the issue you encountered?

```
E: error: Expected N2pl4core5Token10IdentifierE, got PN2pl4core5Token10IdentifierE.
E:   -->   in <Source Code>:15:25
E: 15 |     type::Magic<"\x00"> @ $ + len;
E:                              ^

E: This is a serious parsing bug. Please open an issue on GitHub!
E: error: This is a parser bug!
E:   -->   in <Source Code>:15:25
E: 15 |     type::Magic<"\x00"> @ $ + len;
E:                              ^
I: Evaluation took 0.0208209s
```

### How can the issue be reproduced?

This seems to occur with a minimal repro of
```
struct Foo {
    u8 @ 0x00;
};
```

### ImHex Version

1.35.4

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Flatpak

**Comment by paxcut** [comment]
this is a duplicate of #1415 and now there should be a link from that issue to this one. The error seems to only occur when using templates. and not on it happening inside a struct.
I am a bit curious about how the intention of placing anonymous variables as a means to an end cause I can't think of any ends that would require said means.

**Comment by mrnerdhair** [comment]
Huh; not sure why I didn't find that one myself! FWIW, I was trying to ensure a certain byte was zero but didn't care about its semantic meaning, using `type::Magic<"\x00"> @ $ + len`. I had no idea if that would officially work but I tried it out to see what would happen and got this error.

**Comment by paxcut** [comment]
There are ways to accomplish that goal which are fully documented as working. For example, `std::mem::read_unsigned(address,byteCount, Endianness);` can be used to read any number of bytes and doesn't require a variable to test its value. Probably the preferred way would be `$[$+len]==0` which does exactly what you describe but is more verbose and easier to read.

**Comment by mrnerdhair** [comment]
Yeah, I ended up using `std::assert_warn`, but I do think that placing an anonymous struct *should* work in the abstract. Still, closing as dupe.
