### ISSUE TITLE
Feature request: number input base option

### ISSUE THREAD

**Issue by russkel** [WerWolv/ImHex#192]
Hi,

I am loving using ImHex. Is it possible to change all the instances of data/offset input boxes to a special widget that lets you specify the base the input value is? At the moment I am using galculator to change from DEC to HEX.

Example being the Goto command. I believe the Search option already has something like this.

Kind regards,

Russ

**Comment by WerWolv** [comment]
The Goto command has since been changed to support both hexadecimal and decimal inputs as well as full math expressions.
