### ISSUE TITLE
Feature request: findOccurance with startIndex

### ISSUE THREAD

**Issue by yatli** [WerWolv/ImHex#194]
Hi!

My use case is sysex, where the end of the packet is determined by a single 'F7'
![image](https://user-images.githubusercontent.com/20684720/109911185-8f177900-7ce4-11eb-80c3-06da09e11cfa.png)

However findOccurence asks for an absolute occurrence number, whereas in a struct I want it to look up the first occurrence after the current position.

Context:

https://github.com/WerWolv/ImHex/blob/4a908a314f7a2df9ed4d7f9dd50af1cd3f6cd4e5/plugins/builtin/source/content/lang_builtin_functions.cpp#L34

It always searches from index 0.

**Comment by WerWolv** [comment]
You should be able to implement this now using custom functions and global variables
