### ISSUE TITLE
[Bug] Formatter does not work with manipulated data

### ISSUE THREAD

**Issue by rudolfheszele** [WerWolv/ImHex#1945]
### Operating System

Windows

### What's the issue you encountered?

I have a simple struct in my pattern, representing a string:
```c
struct String {
    u32 size;
    char value[size];
} [[format("String_Formatter")]];
```
Sometimes the formatter just returns `value`, but sometimes it needs to manipulate it and return that manipulated data. In the first case, the formatter works fine, but in the other, the returned `char` array is displayed as a literal `char` array, instead of a string.
Here is the formatter code:
```c
fn String_Formatter(ref String s) {
    if(s.size < 2) {
        // This case works fine
        return s.value;
    }
    
    char result[s.size];
    for(u32 i = 0, i < s.size, i = i + 1) {
        // In the real code, the data is changed here
        result[i] = s.value[i];
    }
    
    // This case does not work
    return result;
};
```

### How can the issue be reproduced?

Use the above pattern with the following data
```c
const uint8_t data[6] = {
    0x02, 0x00, 0x00, 0x00, 0x65, 0x66, 
};
```
Here is a picture how the formatter displays the struct in the "Pattern Data":
![image](https://github.com/user-attachments/assets/a6efb08f-dbfb-44af-b50f-67641aa925c5)
I am new to this, so I probably do something wrong. I tried many things, using `std::format`, `std::string::to_string`, nothing helped. I am really lost, and would like to find a way to fix this.

### ImHex Version

1.35.4

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by paxcut** [comment]
I think what happens is that if size < 2 then size is either 1 or zero so it displays only one char  and not a char array. If you want to print strings then use an string instead of a char array:
```cpp
fn String_Formatter(ref String s) {
    if(s.size < 2) {
        // This case works fine
        return s.value;
    }
    
    str result;
    for(u32 i = 0, i < s.size, i = i + 1) {
        // In the real code, the data is changed here
        result += s.value[i];
    }
    
    // This case does not work
    return result;
};
```

**Comment by rudolfheszele** [comment]
That `if()` statement is just there to easily switch between the two cases. With the given example data, the string is always two characters long, so I only changed the condition to `if(s.size < 3)` to trigger the "other" `return` statement.
But, your suggestion with the `str` seems to work, thanks for the quick response! :)
![image](https://github.com/user-attachments/assets/aa661b40-80a4-400f-8cde-58f6d1d505c3)
I still wonder if it is a bug or not? According to the documentation, `char` arrays should be treated as `string`s: https://docs.werwolv.net/pattern-language/core-language/data-types#strings

**Comment by paxcut** [comment]
My understanding (and I may be wrong) of char arrays and strings is that  char arrays in patterns are converted and printed as a strings as seen in your example. Char arrays returned from functions are not converted to strings though so that you can return either or. I think the docs are only referring to char arrays defined inside patterns.

**Comment by rudolfheszele** [comment]
That actually makes sense. This is why it worked, when I directly returned with the value of the string, since that was from the pattern. Thanks for the help! :)

**Comment by paxcut** [comment]
No problem, if you think this is resolved it would be great if you could please close the issue.
