### ISSUE TITLE
[Bug] `pragma bitfield_order` crashes ImHex if used in an unexpected location

### ISSUE THREAD

**Issue by xy2i** [WerWolv/ImHex#1948]
### Operating System

Windows

### What's the issue you encountered?

I was trying out the `bitfield_order` pragma and used it in an unexpected location. When i tried to evaluate the pattern, Imhex crashed

### How can the issue be reproduced?

In pattern editor:
 
```
#pragma bitfield_order left_to_right

enum A: u8 {};
```

then evaluate the pattern

### ImHex Version

1.35.4

### ImHex Build Type

- [x] Nightly or built from sources

### Installation type

MSI

**Comment by paxcut** [comment]
I was able to reproduce this issue in ImHex 1.35.4 just using the `#pragma` directive. I tried ImHex 1.36.0 wip (dev branch) and the crash doesn't occur there and instead it prints a message stating that the bit-field order `#pragma` is no longer supported. It looks like this has been fixed already but the fix hasn't made it to the master branch yet.

**Comment by sbond75** [comment]
How can I use bitfields with left to right order in 1.35.4 then?

**Comment by paxcut** [comment]
use the attribute on the bitfield definition
```cpp
bitfield Name {
// bitCount is the number of bits spanned by bitfield
// your definitions go here
...
} [[bitfield_order(std::core::BitfieldOrder::MostToLeastSignificant, bitCount)]];
 ```
