### ISSUE TITLE
Parsing Linked Lists

### ISSUE THREAD

**Issue by alexeRadu** [WerWolv/ImHex#195]
Hi,

first of all congrats for the project. I think it is very useful and cool.
Second I would like to be able to parse linked lists. In this situation I have inside of the structure a pointer to the same kind:

```c
struct ListHdr {
    u32 value;
    ListHdr *next : u32;
};
```

The pattern editor says that it doesn't know who ListHdr is, so I guess the code tries to resolve the type association at that moment and not postpone it for later (in the hope that it may find it later).
Is there any way I can write this to work (in the current version)?

Also it might be mandatory to impose some restrictions on the pointer so that this recursive parsing doesn't happen forever (like for example if next is not null or if it points inside the file).

**Comment by WerWolv** [comment]
Nested types are now supported
