### ISSUE TITLE
[Bug] macOS Shortcuts: Command and Control keys are swapped from how they are displayed in settings

### ISSUE THREAD

**Issue by Next-Door-Tech** [WerWolv/ImHex#1954]
### Operating System

MacOS

### What's the issue you encountered?

On macOS, the shortcut keybinds shown in the menu / settings say they use the command key, but work using the control key instead. Likewise, when setting keybinds in the settings menu, 

### How can the issue be reproduced?

Verifying <kbd>CMD</kbd> and <kbd>CTRL</kbd> are swapped when using shortcuts:
1. On macOS, open ImHex without loading a file.
2. Verify that the "New File..." shortcut is supposedly set to "CMD + N" under the File menu.
3. Press <kbd>CMD</kbd>+<kbd>N</kbd> on the keyboard to create a new file.
    - Nothing happens.
4. Press <kbd>CTRL</kbd>+<kbd>N</kbd> on the keyboard, which should not be bound to anything on a default installation.
    - A new file is created.

Verifying <kbd>CMD</kbd> and <kbd>CTRL</kbd> are swapped when assigning shortcuts:
1. Go to Settings > Shortcuts.
2. Attempt to change the "New File..." shortuct. Press <kbd>CMD</kbd>+<kbd>N</kbd> as the new shortcut.
    - The new keybind that appears is shown as "CTRL + N".
    - If the settings menu is closed, pressing <kbd>CMD</kbd>+<kbd>N</kbd> creates a new file. Pressing <kbd>CTRL</kbd>+<kbd>N</kbd> does nothing.
3. Attempt to change the "New File..." shortuct again. Press <kbd>CTRL</kbd>+<kbd>N</kbd> as the new shortcut, or reset the keybind to default.
    - The new keybind that appears is shown as "CMD + N".
    - If the settings menu is closed, pressing <kbd>CTRL</kbd>+<kbd>N</kbd> creates a new file. Pressing <kbd>CMD</kbd>+<kbd>N</kbd> does nothing.

### ImHex Version

1.35.4

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

DMG

**Comment by paxcut** [comment]
this is most likely a duplicate of issue #1757. At least, the same issue of cmd/ctrl key swapping on MacOS is also described there.

**Comment by Next-Door-Tech** [comment]
> this is most likely a duplicate of issue #1757. At least, the same issue of cmd/ctrl key swapping on MacOS is also described there.

Yes, #1757 seems to be describing the same issue, but in a more narrow context. (Frankly, not sure how I managed to miss it when I searched for existing issues.)

In any case, the issue where cmd/ctrl are swapped **affects ALL shortcuts** (not just the pattern editor), and also **affects Intel Macs** (I'm on a MBP 16" 2019 w/ a Core i9).

**Comment by Next-Door-Tech** [comment]
Closed as duplicate. Added comment to #1757
