### ISSUE TITLE
[Bug] AES decrypt node cannot work in ECB mode.

### ISSUE THREAD

**Issue by xiangluoming** [WerWolv/ImHex#1957]
### Operating System

Windows

### What's the issue you encountered?

When I use AES node with ECB node, it says *Nothing connected with 'IV'*. But as far as I know, AES ECB mode don't need IV and nonce.
![image](https://github.com/user-attachments/assets/cae84599-d4dc-4ad2-9f1d-f0e27ee1e9ab)

### How can the issue be reproduced?

Use AES node in ECB mode.

### ImHex Version

1.35.4

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by jumanji144** [comment]
Please use the Constants -> Nullpointer node and connect them to the nonce and iv. But related to this, the ECB cipher never actually worked, working on a fix for it

**Comment by jumanji144** [comment]
> `getBufferOnInput` checks whether there is data available so that doesn't work. An empty buffer node doesn't work for the same reason, but one of size 1 can be used.

This will be accounted for in the fix

> Is there something specific about it that doesn't work? I successfully used ECB mode just yesterday, but admittedly I only used it for a single block.

It incorrectly uses the mbedtls library not according to it's specification and also silently ignores any cipher errors occuring.

**Comment by jumanji144** [comment]
Fixed
