### ISSUE TITLE
Build failed on Ubuntu 20.04

### ISSUE THREAD

**Issue by Londek** [WerWolv/ImHex#198]
Just like in title - I cannot build ImHex

System:
Ubuntu 20.04 x86_64

Steps to reproduce:
```
git clone --recurse-submodules https://github.com/WerWolv/ImHex.git 
cd ImHex
sudo ./dist/get_deps_debian.sh
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j
```

Error: 
```
Generally every C file that includes "concepts" is broken.
[...]/ImHex/plugins/libimhex/include/hex/helpers/utils.hpp:66:10: Fatal error: concepts: No such file or directory
   66 | #include <concepts>

```

**Comment by WerWolv** [comment]
Hi
Please check the Readme and the CI script for how to build it. ImHex uses C++20 features for which you need a compiler that supports them (e.g gcc10 or higher)

**Comment by Londek** [comment]
Thanks it actually pushed building process forward, but at the end of the day I had to add `-fPIC` CXX flag for fmt.
Much appreciate - works like a charm now
