### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by trlsmax** [WerWolv/ImHex#2]
I just finding hex editor yesterday and saw your ImHex in the gallery thread of ImGui.
Great !

It will be more convenience if these features are implemented for the pattern.

1. null-terminated string like this:

```
s8 string[];
```

2. variable array size
```
struct tmp
{
    s8 arraySize;
    s8 arr[arraySize];
};
```

3. tree view of pattern data

**Comment by WerWolv** [comment]
Hi! Glad you like my project :)

The first two features are planed and I'll start working on them soon. The tree view I just finished implementing:
![](https://i.imgur.com/wgDZjsI.png)

**Comment by trlsmax** [comment]
Thank you.
Looking forward to it.

**Comment by WerWolv** [comment]
Latest commit implements array sizes based on local variables :)

![](https://i.imgur.com/xRaxvwF.png)
![](https://i.imgur.com/v8tKyy1.png)

**Comment by Foxboron** [comment]
As a note, if `u8 size` is 0 and used in the array, it segfaults the application.

**Comment by WerWolv** [comment]
Closing as this has been implemented ages ago
