### ISSUE TITLE
Drag and drop is crashing the hex editor

### ISSUE THREAD

**Issue by Wdestroier** [WerWolv/ImHex#20]
![csdpuXGkuV](https://user-images.githubusercontent.com/14764307/101160174-601e3800-360d-11eb-8279-39a792c57e97.gif)

The GIF explains the issue

OS: Windows 10 (2004)

**Comment by roblabla** [comment]
I'm having the same issue. Linux does not exhibit the same behavior. Somewhat frustratingly, I tried and failed to reproduce the issue while running ImHex in a debugger. When running ImHex under WinDBG Preview, it works correctly :confused:

**Comment by aziascreations** [comment]
I'm also having the same issue recently.
It happens regardless of which executable I drop into it and I can't try to see if the same thing happens since the "Open File" menu item does not appear to work.

I'm using the latest release (1.4.0) on Windows 10 20H2

**Comment by WerWolv** [comment]
Weird I cannot reproduce this issue at all. Does it work if you first open the Hex editor view under the `View` menu item?

**Comment by 4B4DB4B3** [comment]
This is error in code -` ImGui::OpenPopup("Accept pattern");` in (view_pattern.cpp)

**Comment by WerWolv** [comment]
Thanks @4B4DB4B3, this was a great hint! Found it within minutes :)
