### ISSUE TITLE
Please support macOS Catalina

### ISSUE THREAD

**Issue by acisternino** [WerWolv/ImHex#200]
The current macOS version only supports macOS Big Sur (11).

Given the amount of Macs still on Catalina (10.15), it would be very helpful to be a bit more conservative in the minimum OS version supported.

As an example, all Macs at my company are still with Catalina with no plan to upgrade given how many problems has Big Sur introduced.

Thanks!

**Comment by WerWolv** [comment]
Hi
Catalina should already be supported. However since the releases are built on GitHub's Big Sur CI, they are built for that. If you compile it yourself though on Catalina, it should just work.

**Comment by acisternino** [comment]
Hi,

Thanks for the info, I'll compile it myself.

However, this is what I get when I try to run the binary you provide:

![Screen Shot 2021-03-10 at 15 14 53](https://user-images.githubusercontent.com/475646/110642719-92fb3d80-81b3-11eb-90eb-4510464992aa.png)

HTH.
