### ISSUE TITLE
is the mac version broken?

### ISSUE THREAD

**Issue by pbartolome** [WerWolv/ImHex#201]
I tried the nightly version and precompiled DMGs as well as compiling from source and I always get this result:

![image](https://user-images.githubusercontent.com/2429905/110650905-3ef45700-81bb-11eb-9e9a-13c9aa30e91f.png)

Besides the string tokens not being replaced with the actual text, the resolution of the whole application doesn't match the screen resolution. I don't see any other open issues, so I'm starting to wonder it could be something about my machine....

**Comment by roblabla** [comment]
I took a quick look. I think since #181, imhex stopped looking at its own appbundle for plugins, which means it fails to find the builtin plugin (which contains the translations).

Ideally, I think [this](https://github.com/WerWolv/ImHex/blob/master/plugins/libimhex/source/helpers/utils_mac.mm#L7) should return two paths: One in the ApplicationSupport directory, and another inside the app bundle, similar to what is done on linux.

**Comment by aj3423** [comment]
Same problem on Kali LInux. Compiled from the latest source, No response on startup.
![imhex](https://user-images.githubusercontent.com/4710875/112371034-1ae75880-8d19-11eb-9351-8b5050113e7c.png)

**Comment by roblabla** [comment]
@aj3423 you need to copy various files to their correct location. Look at https://github.com/WerWolv/ImHex#linux. In particular, you need to put builtins.imhex in either /usr/share/imhex/plugins or ~/.local/share/imhex/plugins.

**Comment by aj3423** [comment]
> @aj3423 you need to copy various files to their correct location. Look at https://github.com/WerWolv/ImHex#linux. In particular, you need to put builtins.imhex in either /usr/share/imhex/plugins or ~/.local/share/imhex/plugins.

Thanks, it works.

**Comment by DrivebyCoding** [comment]
The correct fix for Linux as of today seems to be
```
make install
cp ./plugins/builtin/builtin.hexplug ~/.local/share/imhex/plugins/
```

**Comment by 0400H** [comment]
> The correct fix for Linux as of today seems to be
> 
> ```
> make install
> cp ./plugins/builtin/builtin.hexplug ~/.local/share/imhex/plugins/
> ```

@DrivebyCoding 
@aj3423 

It is not work for me on ubuntu 20.04

![Screenshot from 2021-05-20 00-32-25](https://user-images.githubusercontent.com/16373603/118850501-6c6c2800-b903-11eb-90f5-ecc8cd0fef3b.png)

**Comment by fosterbrereton** [comment]
The Mac version should behave better as of PR #258. Please make sure the necessary components are installed under the `Application Support/imhex` folder according to the README.

**Comment by WerWolv** [comment]
This should work better now
