### ISSUE TITLE
[Bug] Pattern Editor detects CTRL as stuck

### ISSUE THREAD

**Issue by PerfectlyFineCode** [WerWolv/ImHex#2019]
### Operating System

Windows

### What's the issue you encountered?

Sometimes pattern editor thinks CTRL modifier key is pressed so the pattern editor becomes unusable.

### How can the issue be reproduced?

1. Write something in pattern editor
2. *not exactly sure what I did but I just alt tabbed (ALT + TAB) out of the program and it started acting weird*

### ImHex Version

1.35.4 [811214d]

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by WerWolv** [comment]
Hey! I've had this issue before too but so far only on Linux. On Windows it seems to work pretty consistently for me. Does it only affect the pattern editor for you or is it the entirety of ImHex? Like other text fields / shortcuts / etc as well?

**Comment by WerWolv** [comment]
Might be something for @paxcut

**Comment by paxcut** [comment]
Is this reproducible in your computer? Does it happen every time you Alt-TAB in and out of the editor? I tried it on my local build and nothing bad happened. I 've had similar problems but on clion, not on imhex usually pressing ctrl-alt on both left and right sides clears it. Im not sure what causes it though it is not alt-tab

**Comment by PerfectlyFineCode** [comment]
Recording when reproducing it:
https://github.com/user-attachments/assets/bfcba078-a4da-438d-890e-e144ae914f5f

**Comment by paxcut** [comment]
Im not sure what to make of this. I turned auto evaluate on and proceeded to spam keys and delete them as you do and I can't get it stuck like you show. If i pause the spamming for a second the auto evaluate kicks in and I loose focus to the screen so i just click it and continue to spam and delete keys. Does it only happen when auto evaluate is on?

**Comment by PerfectlyFineCode** [comment]
> Im not sure what to make of this. I turned auto evaluate on and proceeded to spam keys and delete them as you do and I can't get it stuck like you show. If i pause the spamming for a second the auto evaluate kicks in and I loose focus to the screen so i just click it and continue to spam and delete keys. Does it only happen when auto evaluate is on?

I got the bug with auto evaluate being toggled off too. 🤔

**Comment by WerWolv** [comment]
Yeah I don't think this has anything to do with auto evaluate. Rather with the Shortcut manager or with how ImGui/glfw handles modifiers

**Comment by WerWolv** [comment]
Okay I managed to reproduce it everywhere now pretty consistently. If you hold down ALT GR first, then hold down SHIFT and then press enter while still holding the two other keys, CTRL gets stuck pretty consistently. 
The reason seems to be a glfw bug of some sorts. ImGui uses `glfwGetKey(window, GLFW_KEY_LEFT_CONTROL) == GLFW_PRESS)` to check if the ctrl button is being pressed. This function returns the last key event that was sent for this key. When in this weird state, glfwGetKey seems to always return GLFW_PRESS as if glfw didn't receive a key release event.

I'll see if I can rewrite the code somehow to work around this bug, just figured I'd report my findings back for now

**Comment by WerWolv** [comment]
@PerfectlyFineCode Do you happen to use a German (or similar) keyboard layout as well?

**Comment by PerfectlyFineCode** [comment]
> @PerfectlyFineCode Do you happen to use a German (or similar) keyboard layout as well?
> 
> Edit: Actually I believe any keyboard layout that maps ALT GR to CTRL + ALT causes the issue.

Yes, I use the Nordic keyboard layout.

**Comment by WerWolv** [comment]
I believe I managed to fix it. At least I can't reproduce it anymore like I did before.
If you have time, could you try the latest build once GitHub is done building it?

**Comment by PerfectlyFineCode** [comment]
> I believe I managed to fix it. At least I can't reproduce it anymore like I did before. If you have time, could you try the latest build once GitHub is done building it?

I haven't been able to reproduce it yet using the fix: https://github.com/WerWolv/ImHex/commit/5af28670f0b538393ece8712b996f3c5d6c66c2a
