### ISSUE TITLE
[Bug] Crashes immediately upon startup

### ISSUE THREAD

**Issue by beanieaxolotl** [WerWolv/ImHex#2028]
### Operating System

Windows

### What's the issue you encountered?

An error message pops up instead of the program actually booting:

![image](https://github.com/user-attachments/assets/f1948533-6c07-4dc0-abce-dd719d913373)

### How can the issue be reproduced?

Open either imhex.exe or imhex-gui.exe

### ImHex Version

1.36.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by beanieaxolotl** [comment]
Nevermind, I just fixed this by selecting the repair option in the installer

**Comment by paxcut** [comment]
When that happens it means that it hasn't been able to copy the new executable. either uninstall completely or repair
