### ISSUE TITLE
[Bug] Won't launch

### ISSUE THREAD

**Issue by XatiX** [WerWolv/ImHex#2036]
### Operating System

Windows

### What's the issue you encountered?

---------------------------
Error
---------------------------
ImHex crashed during initial setup!
Error: Received signal 'SIGSEGV' (11)
---------------------------
OK   
---------------------------

### How can the issue be reproduced?

New install on both installer/portable package. Try to open imhex.exe/imhex-gui.exe

Reverted to 1.36.0 and launches no problems.

### ImHex Version

1.36.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI/Portable

**Comment by WerWolv** [comment]
Hey, could you please post your log file? It can be found under `%localappdata%/imhex/logs`

**Comment by XatiX** [comment]
Here you go mate.
[20241228_145506.log](https://github.com/user-attachments/files/18266521/20241228_145506.log)

**Comment by paxcut** [comment]
I just tried the new release and it worked for me no problems

**Comment by WerWolv** [comment]
Latest commit should fix the issue. I'll let the CI build and if everything's okay then I guess I'll push yet another release. Sorry about that

**Comment by paxcut** [comment]
I think maybe I got past that check using admin installation of msi. I usually don't install msi packages directly.

**Comment by WerWolv** [comment]
I believe the issue only occurs when the settings file doesn't have the previous launch version field populated yet. 
The fix I did now combats the symptoms but I'll need to look into fixing the actual root cause later. For now, I'll make a new release with the fix included

**Comment by XatiX** [comment]
No problem. Will give it a test once release it up and keep you informed.

**Comment by XatiX** [comment]
I can confirm issue is resolved in new release. Cheers @WerWolv

**Comment by arcanelab** [comment]
Which version is supposed to be fixing this issue? With 1.36.2 I still have this issue happening.

[20250101_231705.log](https://github.com/user-attachments/files/18286806/20250101_231705.log)

**Comment by WerWolv** [comment]
@arcanelab That's actually a completely unrelated issue you're experiencing. Looks like a crash inside of glfw to me or rather inside some Apple framework. v1.36.2 fixes the issue mentioned here and works correctly on my M2 macbook air
