### ISSUE TITLE
[Bug] Most of the pattern files included are completely nonfunctional

### ISSUE THREAD

**Issue by beanieaxolotl** [WerWolv/ImHex#2039]
### Operating System

Windows

### What's the issue you encountered?

I am aware that this may be a duplicate of issue #1946, and this is indeed known by a few, but I thought I would let you know anyways. If this is not needed, _by all means_, feel free to close this:
Any pattern file using std.mem fails to load with the same series of error messages (with a few variations in different files). For example, I used a Blender file and clicked Yes on the Accept Pattern dialog:

(_User_ here is pretty generic, so that's why I left it as is)

```
E: error: Expected ';' at end of statement, got Keyword (from).
E:   -->   in C:\Users\User\AppData\Local\imhex\includes\std/mem.pat:261:9
E:    >> from C:\Users\User\AppData\Local\imhex\includes\hex/dec.pat:5:12
E:    >> from <Source Code>:19:16
E: 261 |         From from;
E:               ^^^^
E: error: Invalid struct member definition.
E:   -->   in C:\Users\User\AppData\Local\imhex\includes\std/mem.pat:261:14
E:    >> from C:\Users\User\AppData\Local\imhex\includes\hex/dec.pat:5:12
E:    >> from <Source Code>:19:16
E: 261 |         From from;
E:                    ^^^^
E: error: Invalid struct member definition.
E:   -->   in C:\Users\User\AppData\Local\imhex\includes\std/mem.pat:261:18
E:    >> from C:\Users\User\AppData\Local\imhex\includes\hex/dec.pat:5:12
E:    >> from <Source Code>:19:16
E: 261 |         From from;
E:                        ^
E: error: Expected ';' at end of statement, got Separator (}).
E:   -->   in C:\Users\User\AppData\Local\imhex\includes\std/mem.pat:271:57
E:    >> from C:\Users\User\AppData\Local\imhex\includes\hex/dec.pat:5:12
E:    >> from <Source Code>:19:16
E: 271 |  % Alignment) + 1)];
E:                           ^
I: Evaluation took 0.0411185s
```
I did some quick calculations (i.e using the calculator on Bing), and I found out that out of the 144 pattern files included with ImHex 1.36.2, only 38 of them actually work, and 106 return this error. In terms of percentage, ~73.6% of the patterns included don't actually work, while ~26.4% of the patterns do work.

### How can the issue be reproduced?

- Load up any file
- Load up any .hexpat file that calls std.mem
- Observe the console output

### ImHex Version

1.36.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

### Additional context?

I first started noticing the bug around 1.36.0 (in terms of stable releases).

**Comment by paxcut** [comment]
This problem is related to the issue mentioned but it is not the same. The problem that was causing the issue mentioned was fixed, but in order to have the fix included in your library you need to update the standard libraries from the content store.

**Comment by beanieaxolotl** [comment]
Updating the libraries seems to have fixed the issue, tysm!

**Comment by WerWolv** [comment]
For future reference, the latest nightly now auto-updates all downloaded items from the content store after ImHex is updated. This should hopefully solve situations like this in the future
