### ISSUE TITLE
How do you edit?

### ISSUE THREAD

**Issue by snaphat** [WerWolv/ImHex#209]
How do you edit? I cannot figure out how editing works. Is it broken in windows? Attempting to select bytes and modify them does nothing.

**Comment by snaphat** [comment]
For reference, this is what I see when right clicking any file

![image](https://user-images.githubusercontent.com/5836001/111830502-6e464a80-88c4-11eb-9abd-daa5cc9b15c6.png)

**Comment by WerWolv** [comment]
Double click the byte you want to edit and it will become highlighted and it becomes editable
