### ISSUE TITLE
Use SUBSYSTEM:WINDOWS when making the Windows build

### ISSUE THREAD

**Issue by mlarouche** [WerWolv/ImHex#21]
You should use the SUBSYSTEM;WINDOWS parameter to MSVC so that it doesn't open a console window before opening the actual window

**Comment by Kein** [comment]
Console window should not be there to begin with.

**Comment by WerWolv** [comment]
Has been fixed since in the latest nightly build.
The issue is not ImHex this time but the Windows Terminal
