### ISSUE TITLE
[Feature] Optionally read patterns relative to base address

### ISSUE THREAD

**Issue by XAYRGA** [WerWolv/ImHex#219]
This feature would be useful for parsing ram dumps, as not all memory pointers are relative, some are absolute..

An example, is that in this file, i have three pointers at the top that point to various data's inside of the dump

![HEX Editor](https://xayr.ga/share/04-2021/08-18h-48-imhex_f3f46811-aa34-4ee1-92af-8524dafd30ef.png)

My base address is 0x8C900000, but the pattern editor doesn't take. 

![pattern editor](https://xayr.ga/share/04-2021/08-18h-50-imhex_c4f7b87b-6772-4bb7-a70a-55c73af82989.png)

Even if I specify that as the base address of the file, any pointer I read is going to be worthless because they all point to the memory region of which they are mounted at

![Pattern editor, bad pointer](https://xayr.ga/share/04-2021/08-18h-51-imhex_e85bbee8-0f51-47d3-9773-6606317a6e49.png)

**Comment by WerWolv** [comment]
Latest commit just fixed this. Patterns now properly respect the set base address and there's also a new pragma `#pragma base_address 0x10000000` to set the loaded data's base address to this value on execution :)
