### ISSUE TITLE
Some suggestions and a question

### ISSUE THREAD

**Issue by naikrovek** [WerWolv/ImHex#22]
Not sure where to put this other than an issue.  If this is not the correct place, please let me know where to put the suggestions and then close the issue.

Suggestions:
1) Arrow keys should move the cursor in the hex editor.
2) Cheat Sheet dialog should not be modal - I need to be able to type into the Pattern editor pane as I read the cheat sheet.
3) Allow me to choose a different monospaced font for the GUI.  The default IMGUI font is non-ideal, to me.  
4) Related to 3: Allow me to change the scaling of the application.  This thing is tiny on my 4K monitor.  I can use it, but I want to scale it up just a bit without scaling up other windows (I don't want to scale everything, just this one program.)

Question: I want to write a pattern for a filetype which has an uncompressed header and a gzip-compressed payload.  Is that kind of thing supported in the pattern editor?  If not, please add!

This is already shaping up to be a fantastic tool.

**Comment by WerWolv** [comment]
First two suggestions have been implemented just now :)
For the third one, this will be added soonish with the implementation of custom text encoding.
For the fourth one, currently there's no settings menu for it but check the `imgui.ini` config file that gets generated. There's a Scaling and a FontScaling option in there that you can increase
