### ISSUE TITLE
Feature request: constant that is equal to last address of the file

### ISSUE THREAD

**Issue by sandorex** [WerWolv/ImHex#220]
Im trying to parse compiled terminfo and the extended part of the file is optional and there is no way to know if it will be there other than checking if the size of the file is bigger than the size in the header
So my proposal is to add a constant like `$` for example `#` which is equal to address of last byte of the file

**Comment by WerWolv** [comment]
Hi
There's already the `$` operator to get the current offset within the file. To get the file size, you can use the `dataSize()` built-in function

**Comment by sandorex** [comment]
Oh thank you, the `dataSize()` is not mentioned on the wiki so i did not know it existed

**Comment by WerWolv** [comment]
Oh yeah that was added after the 1.7.0 release. That's why it's not yet in the documentation. Sorry about that.

I'll add it to the docs before releasing the new version
