### ISSUE TITLE
Pattern pointers "Out of range"

### ISSUE THREAD

**Issue by XAYRGA** [WerWolv/ImHex#221]
Pattern pointers which are > 0x7FFFFFFF are considered out of range

![https://xayr.ga/share/04-2021/15-19h-40-imhex_76c736bf-df0c-4441-b13a-655e8b2877e1.png](https://xayr.ga/share/04-2021/15-19h-40-imhex_76c736bf-df0c-4441-b13a-655e8b2877e1.png)

Intended behavior (0x7FFFFFFF or less) 

![https://xayr.ga/share/04-2021/15-19h-39-imhex_59fb7157-437d-4f77-b1aa-b0c3dd55e2cf.png](https://xayr.ga/share/04-2021/15-19h-39-imhex_59fb7157-437d-4f77-b1aa-b0c3dd55e2cf.png)

**Comment by XAYRGA** [comment]
Maybe 

https://github.com/WerWolv/ImHex/blob/950598911cb856d949308e487ef4d86eadbb772f/plugins/libimhex/include/hex/lang/ast_node.hpp#L203 

is auto typing to s32 and overflowing > 0x7FFFFFFF?

**Comment by WerWolv** [comment]
Most issues like this should have been resolved with the refactor of the provider system
