### ISSUE TITLE
new feature for pattern language

### ISSUE THREAD

**Issue by YouKnow-sys** [WerWolv/ImHex#228]
Hi I love ImHex pattern language and I think its can be very helpful in the future, But at the moment it is very limited and does not have much capability, like:
1. its doesn't support wide Character
2. its need to pass offset for reading every time, its would be great If it was possible to read the file consecutively (also some command to seek in file)
3. its will be very good if Instances of structures can be declared at the same time the structure is defined
4. its doesn't support for example for loop in structure

thank you for great work, please keep it up

**Comment by WerWolv** [comment]
I wouldn't call it very limited, it just doesn't have all the small features yet that things like 010 have been building up for years.

1. More encodings will come eventually
2. In the next version (or the current nightly) you can set the base address of your data and go from there. Personally I find the seek stuff of 010 horribly unreadable. 
3. That's something people do in C a lot but is not possible anymore or discouraged in basically any modern programming language. I think it really hurts readability.
4. Loops will come together with functions and other evaluation things. This is probably something that I'll be working on in the near future

**Comment by htdag** [comment]
[https://github.com/kaitai-io/kaitai_struct](https://github.com/kaitai-io/kaitai_struct)

**Comment by YouKnow-sys** [comment]
> I wouldn't call it very limited, it just doesn't have all the small features yet that things like 010 have been building up for years.
> 
> 1. More encodings will come eventually
> 2. In the next version (or the current nightly) you can set the base address of your data and go from there. Personally I find the seek stuff of 010 horribly unreadable.
> 3. That's something people do in C a lot but is not possible anymore or discouraged in basically any modern programming language. I think it really hurts readability.
> 4. Loops will come together with functions and other evaluation things. This is probably something that I'll be working on in the near future

thank you for new update
in changelog you said program now support utf16 in pattern language, and also you added `base_address` its perfect, but im not sure about how can I use them, can you please update wiki based of latest update?
and something else, ImHex by default use some color pattern, im wondering there is anyway to disable it? I dont want to have color pattern on everything by default (I know I can always use `[[color("color")]];`  for change color, but I think its good to have some option for disable it by default)
thank you for all of your works

**Comment by WerWolv** [comment]
I'll update the wiki when I got time yeah.

About the colors, doesn't that defeat like the whole purpose of the patterns, being able to visualize the data?
If you want to get rid of them, you can just reduce the opacity to 0 in the settings

**Comment by YouKnow-sys** [comment]
> I'll update the wiki when I got time yeah.
> 
> About the colors, doesn't that defeat like the whole purpose of the patterns, being able to visualize the data?
> If you want to get rid of them, you can just reduce the opacity to 0 in the settings

about color yes, but in my opinion its better to just highlight important part of data, its make it easier to work with (and easier to read) (in other word I just rather to choose what part of data should highlight by myself)
one other thing I think its good Idea to highlight selected part of data in hex editor when we select it in pattern data view
![image](https://user-images.githubusercontent.com/17937017/119365032-d2fc9780-bcaf-11eb-970c-d234b105180e.png)
for now its just jump to where is data at, but because of many most of data have same color I cant find it easily 😅

**Comment by Calinou** [comment]
> [kaitai-io/kaitai_struct](https://github.com/kaitai-io/kaitai_struct)

See https://github.com/WerWolv/ImHex/issues/61 as to why ImHex uses its own pattern language.

**Comment by WerWolv** [comment]
@YouKnow-sys I finally created a proper documentation page for everything. It can be found here: https://imhex.werwolv.net/docs

**Comment by YouKnow-sys** [comment]
thank you, its much better, now I can understand how to use it properly.
