### ISSUE TITLE
[FR] Theme color setup/template

### ISSUE THREAD

**Issue by Kein** [WerWolv/ImHex#23]
Yes, I've read the description. I could strongly argue a few points here but it is pointless. What isnt pointless is a choice if visual data representation and I figured it is already valued here. Colors scheme is part of it, some people prefer lighter colors due to physical limitations/issue, whatever.

**Comment by WerWolv** [comment]
I'm going to add themes at some point but for now this is just way too much work for me to hooking everything up properly. There are like 100 different themable things in ImGui alone.

**Comment by Kein** [comment]
Fair point. I'd still appreciate a quickly-thrown together "light" one

**Comment by tautology0** [comment]
I concur on this - dark mode is actively painful to use for people with bad astigmatisms, causing ghosting and leaving after images which eventually results in headaches. Having a lighter selection of colours (my preference is dark grey on light grey to maximise contrast but minimise the ghosting) makes this bareable.

**Comment by WerWolv** [comment]
The default light and classic themes have been added in one of the commits last week. While I find both of them pretty ugly compared to the dark mode, feel free to use that :P

**Comment by tautology0** [comment]
Thank you!
