### ISSUE TITLE
Issue/New Feature Request |  Invert Read Values

### ISSUE THREAD

**Issue by Th3Alic3** [WerWolv/ImHex#235]
Hey all,

How do I invert the values read by ImHex in the Pattern File?

EXAMPLE:

```
struct WeaponStats {
     u8 WeaponStat01;
     u16 WeaponStat02;
     u16 WeaponStat03;
     u16 WeaponStat04;
};
```
The values are stored inverted (aka FF becomes 0 and 00 becomes 255). I would prefer not to enum the u16 values just to display the correct value in the Pattern Data.

From all of my testing, the Inverse function can only be used in calculations. There does not appear to be anyway to apply the inverse to the self-reference of the read value. 

I have tired a bunch of obvious stuff like (without success):
```
~

     u8 ~WeaponStat01;
     ~u8 WeaponStat01;
     ~(u8 WeaponStat01);
     ~(u8) WeaponStat01;
     u8 ~(WeaponStat01);
```
_(The majority of which produce invalid struct call errors or looking for ";" errors.)_

I am trying to confirm if there's a way to SELF-REFENCE the value to output the VALUE as the inverse? _(I would rather not deal with a enum for some 65000 outputs.) Nor do I want to repeat the data as another set of variables just to point back at the originals as I still want to be able to edit values by click on the OG variable._ 

For the u16 it will take forever to complete this enum (assuming ImHex can support a Pattern File with an extra 65000 lines):
```
enum Values : u16{
	Is00	= 0xFFFF,
	Is01	= 0xFFFE,
	Is02	= 0xFFFD,
	Is03	= 0xFFFC,
	Is04	= 0xFFFB,
	Is05	= 0xFFFA,
	Is06	= 0xFFF9,
	Is07	= 0xFFF8,
	Is08	= 0xFFF7,
	Is09	= 0xFFF6,
	Is10 	= 0xFFF5,
	Is11	= 0xFFF4,
	Is12 	= 0xFFF3,
	Is13	= 0xFFF2,
	Is14	= 0xFFF1,
	Is15	= 0xFFF0,
	Is16	= 0xFFEF,
	Is17	= 0xFFEE,
	Is18	= 0xFFED,
	Is19	= 0xFFEC,
	Is20	= 0xFFEB,
};
```

Is this possible within ImHex currently OR is this a feature request?

**Comment by Th3Alic3** [comment]
@WerWolv ?

**Comment by WerWolv** [comment]
I'm sorry, I don't have a lot of time right now.

This is currently not possible but I plan on adding "transformation functions" that modify values in some way before they are displayed. This is quite a big feature though so it might take a while still.

**Comment by WerWolv** [comment]
This can be done now through the `[[transform]]` or `[[format]]` attribute

**Comment by Th3Alic3** [comment]
I am unable to find anything in the Wiki on these features or usage.
