### ISSUE TITLE
libimhex.dll missing from Windows build 1.8.0

### ISSUE THREAD

**Issue by mrdaemon** [WerWolv/ImHex#239]
Upon launch on Windows 10, I get an error complaining that libimhex.dll could not be found.

![image](https://user-images.githubusercontent.com/461308/119233774-828f0980-baf8-11eb-985d-76101b19e705.png)

(Pardon my french)

And indeed, upon looking at the install directory, it is nowhere to be found:

```
    Directory: C:\Program Files\ImHex

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2021-05-22    12:12                magic
d----          2021-05-22    12:12                resources
-a---          2021-04-13    21:43         307868 glfw3.dll
-a---          2021-05-18    19:36        5975665 imhex.exe
-a---          2020-10-25    08:03         143395 libbrotlicommon.dll
-a---          2020-10-25    08:03          52874 libbrotlidec.dll
-a---          2020-12-22    16:31          99146 libbz2-1.dll
-a---          2020-05-09    19:34        5033472 libcapstone.dll
-a---          2021-04-11    09:02        2789703 libcrypto-1_1-x64.dll
-a---          2020-10-21    12:41         723628 libfreetype-6.dll
-a---          2021-04-08    07:12          82097 libgcc_s_seh-1.dll
-a---          2021-04-11    09:53        1304351 libglib-2.0-0.dll
-a---          2020-09-10    00:45         154163 libgraphite2.dll
-a---          2021-03-17    07:23        1006724 libharfbuzz-0.dll
-a---          2020-12-17    21:29        1058528 libiconv-2.dll
-a---          2020-12-22    19:49         133659 libintl-8.dll
-a---          2020-06-17    08:24         216355 libmagic-1.dll
-a---          2021-03-16    07:57         412930 libmbedcrypto.dll
-a---          2021-03-16    07:57         192789 libmbedtls.dll
-a---          2021-03-16    07:57         147519 libmbedx509.dll
-a---          2021-04-13    21:40         281183 libpcre-1.dll
-a---          2019-04-23    09:24         231911 libpng16-16.dll
-a---          2021-04-13    15:55        2883515 libpython3.8.dll
-a---          2021-04-13    21:19         264418 libssh2-1.dll
-a---          2021-04-08    07:12        1752711 libstdc++-6.dll
-a---          2018-01-17    08:00          18240 libsystre-0.dll
-a---          2018-01-17    07:54          92313 libtre-5.dll
-a---          2021-04-09    03:32          58539 libwinpthread-1.dll
-a---          2021-01-05    15:54         116428 zlib1.dll
```

Unpacking the msi installer archive, however, reveals the the library _is_ included, it's just apparently not installed.

![image](https://user-images.githubusercontent.com/461308/119233816-ac483080-baf8-11eb-9f7b-a41b196891fd.png)

**Comment by WerWolv** [comment]
@roblabla Could you look into this maybe when you got some time?

**Comment by mrdaemon** [comment]
As a minor update, I extracted the library from the archive and placed it in the directory.

imhex now launches, but dies immediately after the splash screen with no error message.

**Comment by WerWolv** [comment]
This has been fixed in one of the latest commits but didn't yet make it into a release. The workaround right now is to launch ImHex as admin the first time. After that launching it normal should work fine

**Comment by mrdaemon** [comment]
Ah, yes, this does work! Thank you!

**Comment by WerWolv** [comment]
Something seems to have gone wrong with your installation. Both me and Roblabla tried installing ImHex through the installer now and libimhex was there. Maybe your anti-virus software messed with it during install? Try uninstalling and reinstalling maybe.
