### ISSUE TITLE
crash when using pattern language

### ISSUE THREAD

**Issue by YouKnow-sys** [WerWolv/ImHex#242]
I was checking around with a simple file in ImHex pattern language
I come up with this pattern
```c++
u32 version @ 0x00;
char unknow[64] @ 0x04;
u32 sizeOfRest @ 0x44;
char zero[4] @ 0x48;
u32 sizeOfStrings @ 0x4C;

struct StringTable {
	char str[];
};

StringTable strTable[53] @ 0x50;

u32 count @ 76+sizeOfStrings;
struct information {
	u32 un1;
	u32 un2;
	u32 un3;
};

information info[count] @  0x644;
```
but this make program crash (I saw its used like 5GB ram for a less then 5KB file before crash)
when program crashed, I could not close the program at all (or even work with my pc), so I had to shutdown the computer manually
what is the problem? pattern look normal to me, I'll attach the file I was working on
[en.zip](https://github.com/WerWolv/ImHex/files/6533849/en.zip)

**Comment by WerWolv** [comment]
Crashes like that are an issue that I not yet really know how to deal with.
Most likely one of the arrays who's size depends on another variable blew up to a really big number causing ImHex to run out of memory and crashing

**Comment by YouKnow-sys** [comment]
> Crashes like that are an issue that I not yet really know how to deal with.
> Most likely one of the arrays who's size depends on another variable blew up to a really big number causing ImHex to run out of memory and crashing

I think its good to have some Limitations based of input file size
in my pattern my file size was ~3KB, and my information structure size was 12b, so maximum size for information structure array should be less then 250, its not very Accurate (null-terminated char in structure for example) but its reduce chance of crash of the program, at least it will crash in peace with not eating too much memory :))

**Comment by YouKnow-sys** [comment]
hey, Im still waiting for wiki to update (especially for base_address)
are you still working on it?

**Comment by WerWolv** [comment]
@YouKnow-sys 
You basically just put `#pragma base_address 0x80000000` at the top of your file and the base address will automatically be set to 0x80000000 when running the pattern.

I have to write a ton of documentation and stuff for uni right now so I'd rather not also spend all my free time doing that too. Most likely it will be updated together with the next release

**Comment by WerWolv** [comment]
This should be fixed now
