### ISSUE TITLE
pattern language crash

### ISSUE THREAD

**Issue by giltabibian** [WerWolv/ImHex#243]
Hi @WerWolv,
once loading a pattern, and trying to open a new hex file, the pattern language doesn't refresh for the new hex editor.
meaning, the pattern doesn't apply for the new hex file loaded.
therefore I'm loading the pattern again and the app crash. any idea why?
attached a gif explaining the sequence. 

![pattern_crash](https://user-images.githubusercontent.com/16066829/119467295-0c83e000-bd4e-11eb-801c-48300bea8bb6.gif)

**Comment by WerWolv** [comment]
This should be fixed now
