### ISSUE TITLE
Remove splash screen

### ISSUE THREAD

**Issue by mehlian** [WerWolv/ImHex#244]
Why:
1. By adding splash screen you telling me that your application is slow (or will get slow in future) and requires additional time to launch. Instead, try optimizing the code.
2. At the moment app starts so quickly that splash screen is seen only for a split second.
3. If you want to add some fancy image, put it on welcome screen.

**Comment by jakibaki** [comment]
You might want to try not opening completely unproductive issues on projects people do for free. This is an incredible piece of software that the author is making open source and free of charge so telling them to "try optimizing the code" is beyond unhelpful.
