### ISSUE TITLE
Failed to compile with `clang++`

### ISSUE THREAD

**Issue by Kibouo** [WerWolv/ImHex#245]
Trying to compile ImHex 1.8 using `clang++`. It fails with the error: `/var/tmp/pamac-build-kibouo/imhex/src/imhex/source/views/view_hexeditor.cpp:305:32: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]`. (See attached log for complete output.)

Info: 
- [AUR package 1.8.1-1](https://aur.archlinux.org/packages/imhex),
- `clang++`: 
![image](https://user-images.githubusercontent.com/25766329/119659648-a7ec8200-be2e-11eb-8c5e-2be524d98a3f.png)

[compile.log](https://github.com/WerWolv/ImHex/files/6546632/compile.log)

**Comment by roblabla** [comment]
The relevant error:

```
/var/tmp/pamac-build-kibouo/imhex/src/imhex/source/views/view_hexeditor.cpp:305:32: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
            ImGui::TextWrapped("hex.view.hexeditor.script.desc"_lang);
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/pamac-build-kibouo/imhex/src/imhex/source/views/view_hexeditor.cpp:305:32: note: treat the string as an argument to avoid this
            ImGui::TextWrapped("hex.view.hexeditor.script.desc"_lang);
                               ^
                               "%s", 
```

You can safely ignore that error (by passing `-Wno-error=format-security` to the end of the CFLAGS). In practice it might make sense to apply clang's suggestion to use `%s`.
