### ISSUE TITLE
Kubuntu 

### ISSUE THREAD

**Issue by RatedR9** [WerWolv/ImHex#246]
kubuntu 20.04 can’t build,could you tell me full steps¿

**Comment by WerWolv** [comment]
With the amount of information you provided it's basically impossible to help you at all.

You can check the workflow here though which works on normal Ubuntu 20.04:
https://github.com/WerWolv/ImHex/blob/master/.github/workflows/build.yml#L12-L40

**Comment by RatedR9** [comment]
Yes I follow the GitHub action’s workflow , first I
Git clone the repo and install the depends then cd in the dictionary,do this
MAGICDB_PATH=$(file --version | grep -oP "(?&lt;=magic file from ).+")        mkdir build        cd build        CC=gcc-10 CXX=g++-10 cmake \          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \          -DCMAKE_INSTALL_PREFIX="$PWD/install" \          -DEXTRA_MAGICDBS="$MAGICDB_PATH" \          ..        make -j 4 install
