### ISSUE TITLE
missing libcapstone.so

### ISSUE THREAD

**Issue by 2439905184** [WerWolv/ImHex#247]
I use opensuse and I used yast to search this lib ,but i can't find this lib.
so where to find this lib and install it.
I found a source coude at here:
https://github.com/libcapstone/libcapstone.
But I don't know how to build it.
I have build 2 opensource thing.One is Godot engine (Game Engine),the other is saba ，a software to show mmd (miku miku dance)model.

**Comment by 2439905184** [comment]
![image](https://user-images.githubusercontent.com/29478722/120194446-30fd2200-c250-11eb-97c1-7eaffdbfdede.png)

**Comment by WerWolv** [comment]
You can probably install it with your distros package manager. Looking at the results online it might be `libcapstone-devel` for opensuse so you don't need to build it yourself necessarily

**Comment by 2439905184** [comment]
https://opensuse.pkgs.org/tumbleweed/opensuse-oss-x86_64/libcapstone4-4.0.2-1.5.x86_64.rpm.html
I installed version4 from this web. but I don't find version3
![image](https://user-images.githubusercontent.com/29478722/120196737-c7324780-c252-11eb-8d41-06c2b310ceb2.png)
![image](https://user-images.githubusercontent.com/29478722/120196792-d7e2bd80-c252-11eb-937e-38ee337677fe.png)

**Comment by WerWolv** [comment]
You might have to recompile ImHex again now with the new libcapstone present. ImHex works with either but when being compiled with capstone 4 it has a lot more features too.
