### ISSUE TITLE
fatal error: concepts: 没有那个文件或目录

### ISSUE THREAD

**Issue by 2439905184** [WerWolv/ImHex#252]
![image](https://user-images.githubusercontent.com/29478722/120493005-26c45a80-c3ed-11eb-9914-30a1932d8246.png)

**Comment by WerWolv** [comment]
Please use English when reporting errors, otherwise it's hard for me to help you.

From the picture it seems though that you're not using a up-to-date compiler that supports C++20 concepts. I personally use gcc 10.2.0 under mingw to develop ImHex but everything above that will work. As for clang, I think the lowest is about clang 11.

**Comment by 2439905184** [comment]
It says <concepts> this file could not be found.
I have installed gcc10.0.2 ,in readme.md you says it can compile c++20.Should I install libstdc++20 to comile it. Your software use C++20 standard . But I don't know is the computer installed C++20 file ,include file(C++20) and C++20's library.

**Comment by 2439905184** [comment]
But I can't find libstdc++20 in software package manager

**Comment by WerWolv** [comment]
Having gcc 10.0.2 installed doesn't necessarily mean that it's automatically used if you have others installed. You should be able to set the CC/CXX env var though

**Comment by 2439905184** [comment]
So ,you use windows to develop imhex ,not in linux?. and you use github actions to compile other versions for other OS.
Do you know Appimage , I know it can solve problems in linux( such as glibc version is not heigh enough).
I think ,Appimage put all the librarys together and into one file to improve the compatibility。But I havent use thist echnology。
So you can try to use appimage to distribute the software。
I think the main problem is you use ubuntu-20.04 to compile imhex,but the glibc is too height,that I have to compile it for myself.And there is not package called build-essential on opensuse .
So I should find a dev-lib and headers(C++20) to comile imhex.
I really interested in your work.
I tryed imhex on windows. I like it.I like the pattern code in imhex. It can help me to get value from a bin data file.
