### ISSUE TITLE
[Feature Request] Binary Template Support

### ISSUE THREAD

**Issue by MarioPossamato** [WerWolv/ImHex#259]
A nice addition, if possible to implement, would be support for [010 Editor's Binary Templates](https://www.sweetscape.com/010editor/templates.html).  Not sure if implementing support for this is a feasible task, but it would definitely be useful!

**Comment by WerWolv** [comment]
ImHex has its own pattern language for this task. Please use it instead

**Comment by MarioPossamato** [comment]
Ah, ok, my apologies!
