### ISSUE TITLE
respect multilib structure

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [WerWolv/ImHex#262]
currently these two files
```
   usr/lib/builtin.hexplug                                                                                            
   usr/lib/libimhex.so
```
get installed in `lib` while they must be in `lib64` for 64 bit architectures

**Comment by iTrooz** [comment]
/usr/lib64 seems to be a good choice, but I don't see why /usr/lib is a *bad* choice

According to this post https://unix.stackexchange.com/questions/74646/difference-between-lib-lib32-lib64-libx32-and-libexec
/usr/lib should contains "Libraries for programming and packages.", and I don't see any particular mention of architecture.
If every library was put in lib64/lib32/etc... according to it's architecture, wouldn't there be nothing in /usr/lib then ?

Plus, AFAIK CMake generates the directory structure like this, and.. Shouldn't CMake's defaults be the right ones ?

Could you elaborate on this issue please ?
