### ISSUE TITLE
shared library bundling for macOS binary distribution doesn't work correctly

### ISSUE THREAD

**Issue by comex** [WerWolv/ImHex#268]
In the macOS binary distribution, various dylib files are embedded into `imhex.app`:
```
% find /Volumes/imhex-1.8.1-Darwin/imhex.app/Contents/Frameworks 
[snip]
/Volumes/imhex-1.8.1-Darwin/imhex.app/Contents/Frameworks/libfreetype.6.dylib
/Volumes/imhex-1.8.1-Darwin/imhex.app/Contents/Frameworks/libglfw.3.3.dylib
/Volumes/imhex-1.8.1-Darwin/imhex.app/Contents/Frameworks/libglfw.3.dylib
/Volumes/imhex-1.8.1-Darwin/imhex.app/Contents/Frameworks/libimhex.dylib
/Volumes/imhex-1.8.1-Darwin/imhex.app/Contents/Frameworks/libmagic.1.dylib
/Volumes/imhex-1.8.1-Darwin/imhex.app/Contents/Frameworks/libmbedcrypto.2.26.0.dylib
/Volumes/imhex-1.8.1-Darwin/imhex.app/Contents/Frameworks/libmbedcrypto.6.dylib
[snip]
```
And the main executable has its LC_LOAD_DYLIB commands rewritten to reference those paths:
```
% otool -L /Volumes/imhex-1.8.1-Darwin/imhex.app/Contents/MacOS/imhex
/Volumes/imhex-1.8.1-Darwin/imhex.app/Contents/MacOS/imhex:
[snip]
	@executable_path/../Frameworks/libfreetype.6.dylib (compatibility version 24.0.0, current version 24.4.0)
	@executable_path/../Frameworks/libglfw.3.dylib (compatibility version 3.0.0, current version 3.3.0)
	@executable_path/../Frameworks/libmbedcrypto.6.dylib (compatibility version 6.0.0, current version 2.26.0)
[snip]
```

However, `builtin.hexplug` and `libimhex.dylib` both reference the same libraries at absolute paths, where they would be installed by the Homebrew package manager.  For example:
```
% otool -L /Volumes/imhex-1.8.1-Darwin/builtin.hexplug 
/Volumes/imhex-1.8.1-Darwin/builtin.hexplug:
[snip]
	/usr/local/opt/freetype/lib/libfreetype.6.dylib (compatibility version 24.0.0, current version 24.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
	/usr/local/opt/glfw/lib/libglfw.3.dylib (compatibility version 3.0.0, current version 3.3.0)
	/usr/local/opt/mbedtls/lib/libmbedcrypto.6.dylib (compatibility version 6.0.0, current version 2.26.0)
[snip]
```
`libimhex.dylib` is similar.

If you don't have Homebrew installed to the default path, or don't have those packages installed, then those paths won't exist.  In my testing, for whatever reason, the main executable was still able to load `libimhex.dylib`, but it failed to dlopen the builtin plugin even when it was put in the right place.

It looks like `builtin.hexplug` and `libimhex.dylib` are missing the rewriting step that's applied to `imhex`.

Possibly related to #157, which asks why these two files are outside the app bundle in the first place.

**Comment by Sn0wfreezeDev** [comment]
@comex do you have any tipps on installing the app on macOS? 
I placed all files in the DMG to 
~/Library/Application\ Support/imhex 
```
ls
builtin.hexplug config          libimhex.dylib  magic           patterns        plugins         resources
```

The app launches, but crashes immediately. I also made sure that all relevant libraries are installed through homebrew. 

I think this issue might occur to the others in this issue here: https://github.com/WerWolv/ImHex/issues/284
