### ISSUE TITLE
Dynamic arrazy size doesn't work for me

### ISSUE THREAD

**Issue by Examnes** [WerWolv/ImHex#270]
I used built-in pattern for pcap files, but it doesnt work, because for some reason my instance of imhex can't use patterns, where expressions in struct refer to fields of this struct.
for example:
`struct pcaprec_hdr_t {
        u32 ts_sec;         /* timestamp seconds */
        u32 ts_usec;        /* timestamp microseconds */
        u32 incl_len;       /* number of octets of packet saved in file */
        u32 orig_len;       /* actual length of packet */
        u8  data[incl_len];
};`
doesn't works: compiler says " no member found with identifier 'incl_len' ".

**Comment by jam1garner** [comment]
@Examnes can you test the lastest master, bca7f738 should fix this issue
