### ISSUE TITLE
Feature request: Search tool should highlight the found results

### ISSUE THREAD

**Issue by russkel** [WerWolv/ImHex#271]
When using the Search tool, upon pressing find, the editor window shifts to the position but I am not instantly able to see where the value was found in the editor window. If the search results were highlighted I think this would make it much easier to see.

**Comment by Mikaz-fr** [comment]
I have the feeling this is implemented but bugging. When clicking "Find" I can see the result being highlighted for a split second before going back to normal text. Clicking many time "Find" help to see it.

**Comment by WerWolv** [comment]
The value should be highlighted much better now

**Comment by russkel** [comment]
Thanks @WerWolv
