### ISSUE TITLE
enable anti-aliasing for custom fonts

### ISSUE THREAD

**Issue by everything411** [WerWolv/ImHex#272]
https://github.com/WerWolv/ImHex/blob/07ad9ed7725a99a70aa8ce1045e81bacb8b86491/source/window.cpp#L239
my custom font: Fira Code Regular
when flags set to 0 (default)
![enable](https://user-images.githubusercontent.com/32010059/127310390-437f2954-eb1b-457c-b2c0-ff0415ee3f0f.PNG)

when flags set to ImGuiFreeType::Monochrome
![disable](https://user-images.githubusercontent.com/32010059/127310409-0c274bbd-9f10-4312-bf43-062f273bf47a.PNG)

compare
![compare](https://user-images.githubusercontent.com/32010059/127310452-d1990488-fe85-4a5a-b790-dc78cb3ee23a.PNG)

see https://github.com/ocornut/imgui/blob/6d5388448794f76cc92576a74ad3cb17da2fca84/misc/freetype/imgui_freetype.h#L15

**Comment by WerWolv** [comment]
Antialiasing is now on by default
