### ISSUE TITLE
Built-in functions `readUnsigned` and `readSigned` have platform-dependent behavior

### ISSUE THREAD

**Issue by jam1garner** [WerWolv/ImHex#276]
Both use `reinterpret_cast` internally and thus have no way to specify endianess, resulting in using the system endianess. I highly doubt any big endian systems are supported by imhex, but reading big endian integers _is_ useful nonetheless

**Comment by iTrooz** [comment]
Do you think a fix could be to add an optional argument "Endianess" to the functions, defaulted to "System" (to still have this plateform-dependent behaviour) ?
