### ISSUE TITLE
Documentation Issues in Pattern-Language Guide

### ISSUE THREAD

**Issue by jam1garner** [WerWolv/ImHex#277]
* Bit shift left and Bit shift right are mislabeled
![image](https://user-images.githubusercontent.com/8260240/127802831-278e6048-6934-4591-b994-7ae7c4c5e235.png)
* Built-in function calls contains two non-existent functions:
  * nextAfter
  * addressof
* Built-in function calls that are missing:
  * assert
  * warnAssert
  * print
  * dataSize

I would make all the needed edits myself, but there's not really a way to PR to github wiki.

**Comment by WerWolv** [comment]
Fixed in the new documentation found at https://imhex.werwolv.net/docs
