### ISSUE TITLE
LLVM library path ignored, causing linking to fail on Debian

### ISSUE THREAD

**Issue by jtsiomb** [WerWolv/ImHex#28]
`LLVM_LIBRARY_DIRS` is ignored, causing the build to fail on debian, because LLVMDemangle is installed in a subdirectory of `lib/` somewhere.

Adding the following line to your `CMakeLists.txt` made it build correctly here:

    link_directories(${LLVM_LIBRARY_DIRS})

**Comment by Thog** [comment]
What is your version of LLVM?

**Comment by jtsiomb** [comment]
according to CMakeCache.txt: llvm 9 is getting picked up. But I also have LLVM 11 installed and the library is also installed in a similarly inaccessible place, so the need for using `LLVM_LIBRARY_DIRS` does not change:

    $ find /usr/lib -name libLLVMDemangle*
    /usr/lib/llvm-9/lib/libLLVMDemangle.a
    /usr/lib/llvm-11/lib/libLLVMDemangle.a
