### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by bykolodny** [WerWolv/ImHex#282]
When will a new release be available?
When will you update the pattern language guide?

**Comment by WerWolv** [comment]
When it's done

**Comment by jam1garner** [comment]
> When will you update the pattern language guide

The one on the wiki is pretty up to date, excluding minor unfinished features. And as for the cheat sheet, there's already a PR for fixing that (#278). I'd recommend just waiting, as even public information shows the things you're requesting aren't that far off
