### ISSUE TITLE
Request: Font Size/Display Scale

### ISSUE THREAD

**Issue by Th3Alic3** [WerWolv/ImHex#283]
Hello @WerWolv!

I just switched the display that I am running ImHex from and would like to request an option in the future to increase the size of the display/menu font.

I just switched to a rather large 2160p monitor. Due to its size, the majority of my apps and games operate smoother with Windows set to 100% scale. I have to set some apps to 125% magneficiation but otherwise ImHex right now is the only app that doesn't have support for any display size scaling.

If you could add some kind of option, even if its just simple as SMALL 100%/MEDIUM 150%/LARGE 200%, that would be incredible. 

Thanks

**Comment by WerWolv** [comment]
Latest commit finally adds this :)

**Comment by Th3Alic3** [comment]
Okay! Just waiting on a release.... SWEET!
