### ISSUE TITLE
FeatReq: Direct edit hard drive & I18n

### ISSUE THREAD

**Issue by xtexChooser** [WerWolv/ImHex#285]
1. May be direct edit hard dirve?
2. Are there an I18n framework? I can help to translate

**Comment by WerWolv** [comment]
Hi!

Physical Disk editing is on my list and is something I'll try to implement soon.

About translations, there is a custom framework in place and the language definitions can be found here: https://github.com/WerWolv/ImHex/tree/master/plugins/builtin/source/lang. There are quite a few strings so be warned but thanks a lot of you want to help :)

**Comment by xtexChooser** [comment]
> Hi!
> 
> Physical Disk editing is on my list and is something I'll try to implement soon.
> 
> About translations, there is a custom framework in place and the language definitions can be found here: https://github.com/WerWolv/ImHex/tree/master/plugins/builtin/source/lang. There are quite a few strings so be warned but thanks a lot of you want to help :)

Thanks
