### ISSUE TITLE
Could not renderering Chinese

### ISSUE THREAD

**Issue by xtexChooser** [WerWolv/ImHex#286]
Forked repository: [xtexChooser/ImHex](https://github.com/xtexChooser/ImHex/)

Downloaded Windows Portable ZIP from [Build #3](https://github.com/xtexChooser/ImHex/actions/runs/1181169762)

![image](https://user-images.githubusercontent.com/46394906/131298682-b8ec4f79-1a64-46f4-9a00-2a906107111a.png)

**Comment by WerWolv** [comment]
You need to provide your own font that supports these characters since ImGui's default font is limited to pretty much just ASCII.
To do this download e.g unifont and place it in imhex' resource folder with the name font.ttf

**Comment by WerWolv** [comment]
Nevermind what I said in that last comment, the latest commit adds the first unicode page from the unifont font by default so all characters, including most Chinese characters, from U+0x0000 to U+0xFFFF are now supported
