### ISSUE TITLE
App crashes whenever I try to call "readUnsigned"

### ISSUE THREAD

**Issue by nk521** [WerWolv/ImHex#287]
Hey,
I was trying to write a pattern for [zstd](https://github.com/facebook/zstd). Everything went kind of smooth untill I had to call `readUnsigned` to read from a specific memory region which was given by `addressof`.  Upon executing this script the program will just crash. Is there anything that I'm doing wrong or this is just a known bug?

I'm pasting the script that I wrote. (The problematic line is at the very end.) 

```C
#pragma MIME application/zstd

struct Header {
	u32 Magic;
};

bitfield FrameHeaderDescriptorBitfield {
	dictonary_id_flag : 2;
	content_checksum_flag : 1;
	reserved : 1;
	unused : 1;
	single_segment_flag : 1;
	frame_content_size_flag : 2;
};

union FrameHeaderDescriptor {
	u8 value;
	FrameHeaderDescriptorBitfield bits;
};

bitfield WindowDescriptorBitfield {
	mantissa : 3;
	exponent : 5;
};

union WindowDescriptor {
	u8 value;
	WindowDescriptorBitfield bits;
};

bitfield BlockBitfield {
	last_block : 1;
	block_type : 2;
	block_size : 21;
};

struct ZSTD {
	u32 zstdHeader;

	// https://datatracker.ietf.org/doc/html/rfc8878#section-3.1.1.1.1
	FrameHeaderDescriptor frameHeaderDescriptor;
	
	// https://datatracker.ietf.org/doc/html/rfc8878#section-3.1.1.1.1.1
	if ((frameHeaderDescriptor.value >> 6) == 3) {
		u64 fcsFieldSize;
	} else if ((frameHeaderDescriptor.value >> 6) == 2) {
		u32 fcsFieldSize;
	} else if ((frameHeaderDescriptor.value >> 6) == 1) {
		u16 fcsFieldSize;
	} else {
		if ((frameHeaderDescriptor.value & 32) == 1) {
			u8 fcsFieldSize;
		}
	}

	// https://datatracker.ietf.org/doc/html/rfc8878#section-3.1.1.1.1.6
	if ((frameHeaderDescriptor.value & 3) == 1) {
		u8 didFieldSize;
		padding[readUnsigned(didFieldSize)];
	} else if ((frameHeaderDescriptor.value & 3) == 2) {
		u16 didFieldSize;
		padding[readUnsigned(didFieldSize)];
	} else if ((frameHeaderDescriptor.value & 3) == 3) {
		u32 didFieldSize;
		padding[readUnsigned(didFieldSize)];
	} else {
	}

	// https://datatracker.ietf.org/doc/html/rfc8878#section-3.1.1.1.2
	if ((frameHeaderDescriptor.value & 32) == 1) {
		WindowDescriptor windowDescriptor;
	}

	BlockBitfield block;
};

ZSTD zstd @ $;
print(readUnsigned(addressof(zstd.block)+2));
```

**Comment by WerWolv** [comment]
Hi thanks for the bug report. Are you using 1.8.1 or a dev build? I just tried it on my local dev version where it works fine.
It's possible that there's an issue with error checking in that function in 1.8.1 because readUnsigned expects two parameters: the address and the size you want to read. Does it work if you provide a size? This can be either 1, 2, 4, 8 or 16

**Comment by nk521** [comment]
I'm indeed using 1.8.1 on my Windows 10 machine. Oh an I must've forgotten to add that second param while I was cleaning this code. But in the testing I had that second size param.

I will try to run the nightly dev build to see if that will fix this :)

**Comment by nk521** [comment]
@WerWolv I tried running it on the latest dev build but now I got into some other issue where the application fails to recognize any inbuilt function.
![image](https://user-images.githubusercontent.com/30789322/132245679-89c3ed93-c3cf-4cb1-92a9-b83e4b1a3797.png)
![image](https://user-images.githubusercontent.com/30789322/132245697-f4376378-d7e0-4698-8daa-fcd5b15115cd.png)

**Comment by WerWolv** [comment]
I forgot to mention, sorry. The newer versions added namespaces so print and readUnsigned now live in the std namespace.

Example:
```cpp
std::print(std::readUnsigned(address, size));
```

**Comment by nk521** [comment]
Its okay :)
It worked just fine! Thanks again!
