### ISSUE TITLE
[REQUEST] Add some of 65xxx Family processors (both 8 and 16 bit)

### ISSUE THREAD

**Issue by TheRealHamtaro126** [WerWolv/ImHex#288]
Can you please add the following processors to the program, It'll help a lot:

- 6502 (official opcodes only, various systems)
- 6502 (unofficial opcodes, various systems)
- 2A0x (NES/Famicom version of 6502, official opcodes only, has no Binary coded decimal!)
- 2A0x (NES/Famicom version of 6502, unofficial opcodes, has no Binary coded decimal!)
- 65c02
- 6507 (Atari 2600)
- 6510 (Commodore 64)
- Hu6280 (PC-Engine/TurboGraphix-16 enhanced variant of 65c02)
- 65(c)816 (Various, Example: Apple IIGS)
- 5A22 (the SNES/Super Famicom version of 65(c)816, has no Binary coded decimal!)

Thanks for your time!

**Comment by WerWolv** [comment]
Hi. I'm curreny using the capstone disassembler for disasembling the various architectures supported and I don't think it supports any of these right now.
Is there a different disassembler that supports more that I don't know of? Just making one myself would be a tremendous amount of work, let alone for 10 different architectures.

**Comment by TheRealHamtaro126** [comment]
It at least supports 6502/2A03 (they are kinda the same processor) disassembly as of recent, so it may be time to update capstone then!!!

6502/2a03 only it is then, for right now...

**Comment by WerWolv** [comment]
I will absolutely add the new architectures once capstone releases a new version :)

**Comment by TheRealHamtaro126** [comment]
That is fine with me, But note that TuboGraphix/PCEngine and also 65816-based systems will not be supported at all unless added by capstone disassembler team by request, This will take some undertaking. so I will not the request to the team at capstone to do it unless someone else does want it and references me too.

**Comment by WerWolv** [comment]
As of last version, all architectures that are supported by capstone are now also supported by ImHex.
