### ISSUE TITLE
Data inspector stuck the app

### ISSUE THREAD

**Issue by giltabibian** [WerWolv/ImHex#289]
Hi @WerWolv,
Seems like the data inspector view cause the app to stuck.
Tested on the latest commit of master branch.

**Comment by WerWolv** [comment]
Hi. Could you explain a bit more precise what you mean? 
What exactly is happening? How can I reproduce it?

**Comment by giltabibian** [comment]
Sure. Thanks for the quick response. 
I'm loading a Binary file. Open the data inspector view. Mark some data on the hex view and from now on the app is not responding anymore.

**Comment by WerWolv** [comment]
Could you upload the file you encountered the issue with and tell me the address of the bytes you selected to cause the crash?

**Comment by giltabibian** [comment]
![data](https://user-images.githubusercontent.com/16066829/132843121-a43c20e1-4617-4144-a1f2-0ee02e0cd638.gif)
file attached. the suck was caused anywhere on hexview.



**this is the error log message:**
 spawning command line “dbus-launch --autolaunch= --binary-syntax --close-stderr”: Child process exited with code 1

(imhex:19176): dconf-WARNING **: 13:58:37.602: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch= --binary-syntax --close-stderr”: Child process exited with code 1

(imhex:19176): dconf-WARNING **: 13:58:37.633: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch= --binary-syntax --close-stderr”: Child process exited with code 1

(imhex:19176): dconf-WARNING **: 13:58:37.656: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch= --binary-syntax --close-stderr”: Child process exited with code 1

(imhex:19176): dconf-WARNING **: 13:58:37.681: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch= --binary-syntax --close-stderr”: Child process exited with code 1

(imhex:19176): dconf-WARNING **: 13:58:37.702: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch= --binary-syntax --close-stderr”: Child process exited with code 1

(imhex:19176): dconf-WARNING **: 13:58:37.707: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch= --binary-syntax --close-stderr”: Child process exited with code 1

(imhex:19176): dconf-WARNING **: 13:58:37.707: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch= --binary-syntax --close-stderr”: Child process exited with code 1
terminate called after throwing an instance of 'std::range_error'
  what():  wstring_convert::to_bytes
Killed

**Comment by giltabibian** [comment]
![screengif](https://user-images.githubusercontent.com/16066829/132843853-cd65a90a-cf96-4898-af99-c0c2e99cfb8c.gif)

**Comment by WerWolv** [comment]
That looks like some sort of issue with InGui. Does it still happen in you dock the inspector window instead of having it floating?

Also are you using Wayland? GLFW and InGui seem to have some problems there

**Comment by giltabibian** [comment]
Also when docking the view its stuck.
Not sure what is Wayland .
Just complied and used the builtin plugin.

**Comment by WerWolv** [comment]
Wayland is your screen compositor. 
I tried to replicate the behaviour you're seeing inside WSL (which uses Wayland and Weston which looks very similar to your setup) and I can't get it to happen. So I think there might be something wrong with your Linux setup

![](https://i.imgur.com/jaeql1g.gif)

**Comment by giltabibian** [comment]
Thanks for checking this! 
As you said, I'm using Windows 11 Subsystem for Linux WSLg Preview - 1.0.26. Something might be broken. The thing is that it worked for me properly on version 1.8.1.
I will double check it on another VM I have.

Congrats on the new release and new features! Thanks a lot for your time and dedication.

**Comment by WerWolv** [comment]
Why not just use the Windows release btw? There's an installer and a portable version. That one definitely works fine ^^

Thank you :)

**Comment by giltabibian** [comment]
I subscribed to windows insider program - develop branch. I'll try the formal release. Thanks 🙂
