### ISSUE TITLE
[Bug] Reload button in content store constants tab doesn't function correctly

### ISSUE THREAD

**Issue by jakibaki** [WerWolv/ImHex#290]
### Operating System

Windows

### What's the issue you encountered?

It seems the old items don't get cleared on reload. 

![image](https://user-images.githubusercontent.com/5159436/132905150-89a9872d-a837-4133-82b7-360640d16c05.png)

### How can the issue be reproduced?

Open content store

Click on "constants"

Click reload

### ImHex Version

1.9.0

**Comment by WerWolv** [comment]
Thank you!
