### ISSUE TITLE
[Bug] Patterns bitfield only with 8bit resolution 

### ISSUE THREAD

**Issue by giltabibian** [WerWolv/ImHex#292]
### Operating System

Linux

### What's the issue you encountered?

seems like bitfield is good only for 8-bit resolution.
the pattern data parse the first LSB and then the MSB, so if using bit field for more than 8 bits, the data is not consecutive. 
in my example, I've tried to use bitfield with 16bits and the data is not in order.

### How can the issue be reproduced?

simple pattern like that:

bitfield Header {
	stripped : 1;
	executableImage : 1;
	lineNumsStripped : 1;
	localSymsStripped : 1;
	aggressiveWsTrim : 1;
	largeAddressAware : 1;
	reserved : 1;
	bytesReversedLo : 1;
	is32BitMachine : 1;
	debugStripped : 1;
	removableRunFromSwap : 1;
	netRunFromSwap : 1;
	system : 1;
	dll : 1;
	upSystemOnly : 1;
	bytesReversedHi : 1;
};

Header header @ 0x4;

### ImHex Version

1.9.0

**Comment by giltabibian** [comment]
here is an example:
![image](https://user-images.githubusercontent.com/16066829/132973762-4a4ae69b-27cc-4cbe-90cd-d5f204e7ab25.png)

**Comment by WerWolv** [comment]
Hi! Thanks for the bug report.
I can see how this might be confusing, however this is actually the same behaviour as in C/C++. Here's an example showing the same result as you get from the pattern language. https://godbolt.org/z/1sabzbT5W

**Comment by giltabibian** [comment]
Thanks for the example.
i think the issue is bitfield not supported endianess.
i've attached two photos. the first one is big endian, which seems to work fine as you mention.
![be-bitfield](https://user-images.githubusercontent.com/16066829/132984580-c47f4ba3-f019-40fc-94d8-7b06b09b87f0.PNG)

the second one is little endian, which the bits not reperesnt corectly.
![le-bitfield](https://user-images.githubusercontent.com/16066829/132984578-b8c1d675-b92f-411d-80ab-73bbd09778d8.PNG)

in little endian i've expected the bit fields will be different.
expected: https://godbolt.org/z/bsndYxz5n
the issue is when trying to reperesnt non aligned data, when some fields are combined bits that are no consequtive.

**Comment by WerWolv** [comment]
That is indeed an oversight, give me a few minutes and it should be fixed

**Comment by giltabibian** [comment]
thanks for the quick fix! highly appreciated! 
I think something went wrong with that fix - for a case when the bit fields are not aligned. 
for example, i use 5 bytes header bitfield and I got zero data on all fields:
![le zero](https://user-images.githubusercontent.com/16066829/132985899-fe211ab5-3f96-4a5d-a956-6dc763df40a7.PNG)

**Comment by WerWolv** [comment]
Now it should work for all sizes. Apologies!

**Comment by giltabibian** [comment]
no need for apologies... your work and dedication are highly appreciated! :)
thanks for the quick response!

just checked and it looks great! :)
