### ISSUE TITLE
[Bug] content store: bug, tty console: crash

### ISSUE THREAD

**Issue by xtexChooser** [WerWolv/ImHex#293]
Win10 64bits, msys mingw64, code: [https://github.com/xtexChooser/ImHex](xtexChooser/ImHex)
```
$ mingw32-make -j
...................................................
xtex@xtex MINGW64 /f/Project/ImHex/build
$ mingw32-make install
[  0%] Built target magic_dbs
[ 54%] Built target libcurl
[ 58%] Built target imgui
[ 58%] Built target nfd
[ 66%] Built target libimhex
[ 70%] Built target windows
[ 70%] Built target LLVMDemangle
[ 83%] Built target libyara
[ 87%] Built target builtin
[100%] Built target imhex
[100%] Built target fmt
Install the project...
-- Install configuration: "Release"
-- Up-to-date: F:/Project/ImHex/build/install/plugins/builtin.hexplug
-- Up-to-date: F:/Project/ImHex/build/install/plugins/windows.hexplug
-- Up-to-date: F:/Project/ImHex/build/install/./libimhex.dll
CMake Error at cmake_install.cmake:100 (get_filename_component):
  get_filename_component unknown component Files/Python/libs/python39.lib


mingw32-make: *** [Makefile:114: install] Error 1

```

CMake with `cmake -G "MinGW Makefiles"  -DCREATE_PACKAGE=ON -DCMAKE_INSTALL_PREFIX="$PWD/install" ..`

**Comment by xtexChooser** [comment]
It looks like because the space in `Program Files`

**Comment by WerWolv** [comment]
Hey, I have Python installed in a different location so I can't test myself right now but can you try to replace https://github.com/WerWolv/ImHex/blob/master/cmake/build_helpers.cmake#L179 
with
`INSTALL(CODE "get_filename_component(PY_PARENT \"${Python_LIBRARIES}\" DIRECTORY)")`
and see if that works?

**Comment by xtexChooser** [comment]
> Hey, I have Python installed in a different location so I can't test myself right now but can you try to replace https://github.com/WerWolv/ImHex/blob/master/cmake/build_helpers.cmake#L179
> with
> `INSTALL(CODE "get_filename_component(PY_PARENT \"${Python_LIBRARIES}\" DIRECTORY)")`
> and see if that works?

Yes it works and I pushed a same patch to my fork so there are another problem:
`There were unresolved dependencies for binary`
I found listed files in `mingw64/bin` and python installation directory.
I tried to add `-DDEP_FOLDERS="xxx"` to cmake but no effect

**Comment by xtexChooser** [comment]
Er. That, I added these folders to cmake_install.cmake manully and I `make install` successful but I could not launch ImHex.

After `Loading settings`, the windows closed and no main windows shown

**Comment by xtexChooser** [comment]
[video.zip](https://github.com/WerWolv/ImHex/files/7192210/video.zip)


This is the video for crashing.

Just now, I found some dump files generated by Windows and I found that it looks like external\nlohmann_json\include\nlohmann\json.hpp#get_arithmetic_value throwing an exception(calling libstdc___6!_cxa_throw)

calling stack:
```
[0x10]   libimhex!ZN3hex15ContentRegistry8Settings4readESt17basic_string_viewIcSt11char_traitsIcEES5_x + 0xf3   
```

**Comment by WerWolv** [comment]
Hey, try deleting `C:\Users\username\AppData\Local\imhex\config\settings.json` and see if it works then.
Also you can upgrade to latest master where I fixed this issue

**Comment by xtexChooser** [comment]
> Hey, try deleting `C:\Users\username\AppData\Local\imhex\config\settings.json` and see if it works then.
> Also you can upgrade to latest master where I fixed this issue

Oh!!!! I successful! But why the latest release installed(1.8.1) could open before I do this? and now 1.8.1 crashes when I close the window and windbg could not open 
![image](https://user-images.githubusercontent.com/46394906/133930267-8a772284-f8be-4b64-9586-a36848c7d874.png)

**Comment by xtexChooser** [comment]
![image](https://user-images.githubusercontent.com/46394906/133930775-b3c8cb1b-cfbe-424f-ab51-0d0023e95cd9.png)
I add an custom font and I ensure that it supported Chinese but ImHex could not  display it
![image](https://user-images.githubusercontent.com/46394906/133930811-cbf1cf17-f0c9-4d0f-af32-acd98fcd66c3.png)

**Comment by WerWolv** [comment]
Because it doesn't add the characters by default. I changed that with 1.9.0 though which also loads unifont by default (which supports chinese). Please use that instead of your current old build

**Comment by xtexChooser** [comment]
hrrr, the languages list is being empty and it crashes when I click the list
![image](https://user-images.githubusercontent.com/46394906/133932254-3e181d33-5f2d-4133-b897-dada7fcd80f9.png)

**Comment by xtexChooser** [comment]
This languages list was broken but I can switch to Chinese by editing configuration file now!

**Comment by xtexChooser** [comment]
![image](https://user-images.githubusercontent.com/46394906/133951953-22e9f251-4b9a-4ba6-a477-27f4e305ec23.png)

I found that ImHashStr crashed from the dump file and I am trying to add log to ImHashStr but I got an empty string.

**Comment by xtexChooser** [comment]
I deleted my repository and forked again and copied files but the language list was still broken

**Comment by xtexChooser** [comment]
I found that this is a upstream bug. The latest actions build on this repoistory could not display languages list, either. And crashes if I click the list.

**Comment by WerWolv** [comment]
I have to say, I have absolutely NO clue how this ever worked lol.

Fixed the issue with the language list though and now it displays chinese fine :)
![image](https://user-images.githubusercontent.com/10835354/133989952-f2891866-89d4-4049-afd8-b44f39de81dc.png)

**Comment by xtexChooser** [comment]
Nice!, and why is the text display at right(anywhere)?
It looks like "Mon Sep xxxxxxxx            Created Time"
![image](https://user-images.githubusercontent.com/46394906/133994383-dffdce8a-7a8d-43d9-911d-ce262f32dca9.png)

**Comment by WerWolv** [comment]
That's just how ImGui does it. I agree it's a little weird. I should probably replace those ancient lists with tables

**Comment by xtexChooser** [comment]
![Exp](https://user-images.githubusercontent.com/46394906/133995269-83b60d85-c4f6-4e24-ab64-99614eb1662b.gif)

How to use the reg-ex replacer? I could not type text by pressing keyboard. I tried to press my keyboard for a lot of times but only type one character

**Comment by xtexChooser** [comment]
And it looks like display wrong translation
![image](https://user-images.githubusercontent.com/46394906/133995447-675954ca-ebb4-48e3-a481-ea673b0d5e2a.png)

And it looks like that wikipedia explain is not loaded with proxy. For some reasons(GFW), I could not access wikipedia directly but I configured a proxy to windows and I can access wikipedia with this proxy.

**Comment by xtexChooser** [comment]
1. I found that I can click download or remove button when I closed the content store window and open it again..
2. crashes when I click `Connect` with no COM port in TTY console
