### ISSUE TITLE
[Bug] unsized array for custom struct not supported

### ISSUE THREAD

**Issue by giltabibian** [WerWolv/ImHex#294]
### Operating System

Linux

### What's the issue you encountered?

I can't use an unsized array for a custom struct.

### How can the issue be reproduced?

pattern used to recusntruct:

bitfield Header {
    a 	: 5;
    b  : 16;
    c   : 4; 
    d  : 1;
    e 	: 1;
    f 	: 1;
    g 	: 1;  
    h 	: 1;
    i	: 3;
    j 	: 4;
    k 	: 1;
    l   : 1;
    m : 1;   
    };

struct Packet {
	Header header[];
	float headerLoopArray[while(header.a)];
};

Packet packet @ 0x00;

### ImHex Version

1.9.0

### Additional context?

![unsized array of custom struct](https://user-images.githubusercontent.com/16066829/132988622-69e4ddf2-6e4a-4c8a-bd27-8185236edea0.PNG)

**Comment by WerWolv** [comment]
This is actually intended behaviour. For built-in types, it's easy to make an unbounded array by interpreting a zero value as the end of the array. But what should be checked for in an array of structs? That all members are zero? I think it makes more sense to explicitly use a `while` loop there to check for whatever end condition is needed.
