### ISSUE TITLE
[Bug] Cant download from content sore

### ISSUE THREAD

**Issue by MeitarR** [WerWolv/ImHex#297]
### Operating System

Windows

### What's the issue you encountered?

When I'm trying to download anything from the content store it immediately returns to the download button (probably failed)

I looked at procmon while trying to download and understood that:
1. it doesn't have the folder `C:\Program Files\ImHex\pattern_language` or any other options
2. it doesn't have permission to write to its own folder

### How can the issue be reproduced?

- install the program using the installer
- `Help` -> `Content Store`
- find something to download then click on the `download` button

### ImHex Version

1.9.0

### Additional context?

- Installer version

**Comment by xtexChooser** [comment]
Oops, I could not load the list from content store.

**Comment by WerWolv** [comment]
Fixed already in latest master. Thanks
