### ISSUE TITLE
[Bug] Crash after changing the interface scaling to 1.5x

### ISSUE THREAD

**Issue by d-serj** [WerWolv/ImHex#298]
### Operating System

Windows

### What's the issue you encountered?

Hi,
I experienced ImHex crash when I tried to change interface scaling to 1.5x. 
After that ImHex is not starting and crashing on the font loading stage.
I tried to remove the .ini file but it did not help to solve the crash. Reunpacking the portable version of ImHex did not help either.

### How can the issue be reproduced?

Go to settings and change scaling to 1.5x

### ImHex Version

1.9.0 Portable

### Additional context?

The loading stage where ImHex is crashing

![ImHex](https://user-images.githubusercontent.com/23031305/133328124-b9a5455b-2b96-4082-a516-f1140149c250.png)

**Comment by WerWolv** [comment]
Hey, it's not actually crashing when changing the interface scaling, it's restarting ImHex.
Also for me at least it's working fine on all scale settings but I guess it might fail on smaller displays than mine (3000x2000), need to investigate though.

To fix your crash though, delete the `%appdata%/Local/imhex/config/settings.json` file instead of the ini. The ini is only for imgui configs

**Comment by d-serj** [comment]
@WerWolv Thanks for your reply!
I found out that the reason for crashing is the old settings for previous versions of ImHex. They must be cleared after the new version had been installed. Otherwise changing of scaling setting will cause ImHex to crash until you delete settings from `%appdata%/Local/imhex/config/settings.json`

**Comment by WerWolv** [comment]
Good to know, thank you!
I fixed an issue a few commits back that caused config loading and storing issues if there were invalid / missing entries in there. That should be fixed in the next version

**Comment by d-serj** [comment]
Yes seems like you have fixed this issue within the last commits you made after 1.9.0 release. Last `master` doesn't have this issue but 1.9.0 has.
Just for your info: I tried to build 1.9.0 and here is the exception which is thrown when I try to change scaling:
`PS C:\ImHex> terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be number, but is null`
