### ISSUE TITLE
For Linux beginners, too difficult to build, it is recommended that provides appimage

### ISSUE THREAD

**Issue by davidricardo1026** [WerWolv/ImHex#300]
thanks for your great work

**Comment by WerWolv** [comment]
I'd argue it can't get much easier.
There are dependecy installer scripts in the `/dist` folder for various distros, it uses standard cmake like many other C++ tools too, there's pre-built nightlies available as zip and as flatpak available on my GitHub Actions. Plus on a few distros ImHex already landed in their repository.
I'll see if I can make an appimage eventually but right now I don't think it's really necessary given all the options that already are available.
