### ISSUE TITLE
[Bug] Content store

### ISSUE THREAD

**Issue by xtexChooser** [WerWolv/ImHex#301]
### Operating System

Windows

### What's the issue you encountered?

![image](https://user-images.githubusercontent.com/46394906/133954758-d6a21e90-aa98-4ce3-b96d-0df011c6bc3c.png)

Why there are two Http Error/ Linux Error/Crc16 and crc32?

### How can the issue be reproduced?

idk, the latest 1.9.0 release, windows installer

### ImHex Version

1.9.0

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by xtexChooser** [comment]
I restarted ImHex and now
![image](https://user-images.githubusercontent.com/46394906/133954846-bcaf2770-359a-4a31-916d-de37f2ae023c.png)
Where are the three constants I installed before

**Comment by WerWolv** [comment]
Has been fixed after 1.9.0. See #290
