### ISSUE TITLE
[Bug] cannot start on windows 11 

### ISSUE THREAD

**Issue by LeiYangGH** [WerWolv/ImHex#307]
### Operating System

Windows

### What's the issue you encountered?

I'm using windows 11(preview). 

But when invoking(tried both double click and run by cmd) the imhex.exe(tried both msi installer and portable zip), there's no error or gui shown. check the task manager and no such process named `imhex*`.

### How can the issue be reproduced?

download today's latest release and try to run on windows 11.

### ImHex Version

v1.10.0

### Additional context?

in cmd, `systeminfo` will get

> 主机名:           DESKTOP-1SLBP5D
> OS 名称:          Microsoft Windows 11 专业版
> OS 版本:          10.0.22000 暂缺 Build 22000
> OS 制造商:        Microsoft Corporation
> OS 配置:          独立工作站
> OS 构建类型:      Multiprocessor Free
> 注册的所有人:     LeiYang
> 注册的组织:
> 产品 ID:          00331-20300-00000-AA507
> 初始安装日期:     2021/8/17, 0:19:21
> 系统启动时间:     2021/9/23, 18:02:08
> 系统制造商:       Intel(R) Client Systems
> 系统型号:         NUC8i7HVK
> 系统类型:         x64-based PC
> 处理器:           安装了 1 个处理器。
>                   [01]: Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~3096 Mhz
> BIOS 版本:        Intel Corp. HNKBLi70.86A.0064.2020.1028.1438, 2020/10/28
> Windows 目录:     C:\WINDOWS
> 系统目录:         C:\WINDOWS\system32

**Comment by WerWolv** [comment]
Hi! I've been developing a big part of ImHex on Windows 11 where for me it runs without any issues.
Looking at your provided information it seems like you computer is set to Chinese? Did you put ImHex in a path containing Chinese or other non-standard characters? That might mess things up.

**Comment by LeiYangGH** [comment]
the directory is D:\dl\thezip. no special or space at all. i also tried C:\ root. can you give more steps to help investigate?

**Comment by WerWolv** [comment]
If you're starting imhex.exe though the command line, does it print any log?

**Comment by LeiYangGH** [comment]
i've already said that in the very first steps: But when invoking(tried both double click and **run by cmd**, there's **no error or gui shown** )

**Comment by LeiYangGH** [comment]
> I had an issue too with ImHex closing without error message, it was an opengl issue. I fixed it by copying `openglsw.dll` (software renderer) from Wireshark next to `ImHex.exe` and renamed it to `opengl.dll`. Works fine with Intel integrated graphics on a potatoe ;)
> 
> Logmessages in cmd.exe don't work for me too. (only in VS Code) I'll try to fix it in a PR later, I've done something like this (cli and gui) before in an own tool, but on a different way as implemented in InHex.

The solution doesn't work for me. maybe I copied the wrong file. could you share the dll somewhere?

**Comment by Unknown78** [comment]
> Sure, I attached it: [opengl32.zip](https://github.com/WerWolv/ImHex/files/7374581/opengl32.zip) And sorry, I just saw it has to be named `opengl32.dll`, I edited my post so the filenames are correct now.

I could confirm that this problem is still exists and not fixed on **imhex-1.25.0-Windows-Portable**.

This Issue must not be closed yet!

**Comment by WerWolv** [comment]
Try [imhex-1.25.0-Windows-Portable-NoGPU.zip](https://github.com/WerWolv/ImHex/releases/download/v1.25.0/imhex-1.25.0-Windows-Portable-NoGPU.zip) instead. ImHex works just fine for me on Windows 11.
