### ISSUE TITLE
[Bug] Little endian comparison in conditionals

### ISSUE THREAD

**Issue by SMUsamaShah** [WerWolv/ImHex#310]
### Operating System

Windows

### What's the issue you encountered?

Conditionals are not behaving correctly. `if (n < 0x8000)` evaluates to true on ` n < 0x0080`
Pattern I wrote
```
#pragma endian big
struct Var {
	u16 n;
	if (n < 0x8000) {
		u8 val;
	}
	else {
		u32 val;
	}
};
struct Variables {
	Var var[];
};
```
Condition satisfies on `n < 0x0080`
![image](https://user-images.githubusercontent.com/385283/135005913-5e676d2d-1d27-418a-a7d2-23e3afd788ff.png)

### How can the issue be reproduced?

Using the code snippet

### ImHex Version

1.10.0

**Comment by pointlessone** [comment]
I have the same issue.

### Operating System

MacOS

### What's the issue you encountered?

I set global endianness in my patter but it's not respect. Not in the UI, nor in my functions.

Pattern:

```
#pragma endian big

#pragma MIME font/otf

#include <std/io.pat>

enum SFNTVersion : u32 {
  otf1 = 0x00010000,
  otto = 0x4F54544F,
};

using uint8 = u8;
using int8 = s8;
using uint16 = u16;

fn sfnt_version(SFNTVersion version) {
  if (version == SFNTVersion::otf1) {
    return "OpenType (1.0)";
  }
  else if (version == SFNTVersion::otto) {
    return "OpenType (OTTO)";
  }
  else {
    return std::format("0x{0:08X}", version);
  }
};

struct TableDirectory {
  SFNTVersion sfntVersion [[format("sfnt_version")]];
  uint16 numTables;
  uint16 searchRange;
  uint16 entrySelector;
  uint16 rangeShift;
};

be TableDirectory Directory @0x00;
```

Screenshot:
<img width="1904" alt="Screenshot 2022-05-22 at 12 37 48" src="https://user-images.githubusercontent.com/7405/169689297-a532eb99-3e3b-4689-9c5a-5c42fb663541.png">

I'd expect literals in the enum to be interpreted in big endian format. Also I'd expect UI to pick the specified endianness. Likewise, I'd prefer my functions to use the specified endianness when comparing values from the file with enum values.

### How can the issue be reproduced?

Use the pattern above with any .otf file.

I understand this is not a minimal reproduction example but it's relatively easy to come by an OTF on pretty much any modern OS so probably not too much trouble.

### ImHex Version

1.17.0 nightly (3595a94b)

**Comment by WerWolv** [comment]
This issue seems to be fixed.

@pointlessone your issue is that you added the `be` keyword in front of `Directory` variable placement. So it and all of its children will always be big endian, no matter of what the global endian setting says.

**Comment by pointlessone** [comment]
Sorry, that is a leftover from a few things I tried to maybe fix it. I just removed it and the result is exactly the same.

<img width="1904" alt="Screenshot 2022-05-22 at 13 04 26" src="https://user-images.githubusercontent.com/7405/169690176-5f0e7aab-129a-4e99-ab78-df4d49033eea.png">

**Comment by WerWolv** [comment]
Yes, now the global setting applies which also sets everything to big endian

**Comment by pointlessone** [comment]
Through experiments I've found a pattern that achieves what I want. However, I don't understand why it works and it doesn't look right on the intuitive level (my intuition definitely can be contrary to how ImHex but…).

Pattern:
```
#pragma endian big

#include <std/io.pat>

enum SFNTVersion : u32 {
  otf1 = 0x00010000,
  otto = 0x4F54544F,
};

using uint16 = u16;

fn sfnt_version(SFNTVersion version) {
  if (version == SFNTVersion::otf1) {
    return "OpenType (1.0)";
  }
  else if (version == SFNTVersion::otto) {
    return "OpenType (OTTO)";
  }
  else {
    return std::format("0x{0:08X}", version);
  }
};

struct TableDirectory {
  le SFNTVersion sfntVersion [[format("sfnt_version")]];
};

TableDirectory Directory @0x00;
```

Notice `le` for the version field.

And here's it working in ImHex:

<img width="1904" alt="Screenshot 2022-05-22 at 15 18 42" src="https://user-images.githubusercontent.com/7405/169694918-52d484eb-788b-4697-a8f2-de87522a3218.png">

OpenType (and SFNT in general) is inherently a big endian format. All fields and constants are big endian. I'd imagine stating that in the pragma would let me use constants in big endian format and all values from the file would be interpreted with that endianness.
