### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sosingle** [WerWolv/ImHex#311]
### Operating System

Windows

### What's the issue you encountered?

When I defined a variable, an error occurred

![image](https://user-images.githubusercontent.com/17985309/135465503-31685a09-60c5-4c8e-8fc4-8080431e312d.png)
Pattern I wrote
`u32 i;
while (i < 100){
	i = i+1;
	}`

### How can the issue be reproduced?

Using the code snippet

### ImHex Version

1.10.0

**Comment by WerWolv** [comment]
Hi. Similar to languages like C you need to define a function and run your code in there. Outside of functions you're only allowed to define types and functions, place variables in memory or call functions. Your small example here would look like this:

```rust
fn your_function() {
    u32 i;
    while (i < 100) {
        i = i + 1;
    }
};

your_function();
```

**Comment by sosingle** [comment]
thanks!
