### ISSUE TITLE
[Bug] pattern language make the window freeze on some operation 

### ISSUE THREAD

**Issue by Detector-I** [WerWolv/ImHex#313]
### Operating System

Windows

### What's the issue you encountered?

if the pattern read so much data (and maybe because a mistake it read more then it need into a big array) its make the program eat up the whole system memory, and make the windows freeze... and the bad part is I cant even close the program...
I think its very bad, because mistake happen when working on a binary file...
it would be nice if the program have some kind of crash handling and warning when its try to use and read so much data into memory (like the 010 editor warning when try to read a big file)

### How can the issue be reproduced?

I'm not going to test it again 😅
but biusicly what I done was open up a binary file and write a pattern for it, I think I done some parts wrong and thats make the program eat the whole memory when trying to read and process the file...

### ImHex Version

1.10.1

**Comment by WerWolv** [comment]
Hi
There's checks in place to abort pattern evaluation when 
a) Types with too deep recursion are evaluated (32 by default, can be changed)
b) Arrays that are too large are evaluated (4096 entries by default, can be changed)

These checks help preventing a lot of common errors and usually stop evaluation (at least on my computer) before ImHex crashes. However they don't make the language fool-proof, it's always possible to shoot yourself in the foot (which is true for basically any language that exists).

That said, without any source code, it's hard to reproduce and fix anything that might potentially be wrong.
If your computer isn't as powerful, I suggest you lower the maximum values mentioned above using the `array_limit` and `eval_depth` pragma: [Documentation](https://imhex.werwolv.net/docs/pattern_language/preprocessor.html)

**Comment by Detector-I** [comment]
> Hi There's checks in place to abort pattern evaluation when a) Types with too deep recursion are evaluated (32 by default, can be changed) b) Arrays that are too large are evaluated (4096 entries by default, can be changed)
> 
> These checks help preventing a lot of common errors and usually stop evaluation (at least on my computer) before ImHex crashes. However they don't make the language fool-proof, it's always possible to shoot yourself in the foot (which is true for basically any language that exists).
> 
> That said, without any source code, it's hard to reproduce and fix anything that might potentially be wrong. If your computer isn't as powerful, I suggest you lower the maximum values mentioned above using the `array_limit` and `eval_depth` pragma: [Documentation](https://imhex.werwolv.net/docs/pattern_language/preprocessor.html)

thank you for fast reply, but Its worth mention that I tested the exact pattern in 010 editor, and its worked without any problem, or any kind of memory eating, I'm not looking for anything fool-proof as you say, but it was a little strange for me that instead of showing me a crash or anything else its just continue to eating up the memory

**Comment by WerWolv** [comment]
It's very possible that you discovered a bug and I'm more than happy to look into it if you can provide some code to reproduce it.

Also one thing maybe to keep in mind, ImHex supports arrays of custom types which may not all have the same size. 010 has that too but it's locked behind their <optimize> attribute to explicitly enable it. In ImHex you explicitly say that the size and layout of a custom type will always be the same with the `[[static]]` attribute which will enable some drastic optimizations. Maybe try that?

**Comment by Detector-I** [comment]
> It's very possible that you discovered a bug and I'm more than happy to look into it if you can provide some code to reproduce it.
> 
> Also one thing maybe to keep in mind, ImHex supports arrays of custom types which may not all have the same size. 010 has that too but it's locked behind their attribute to explicitly enable it. In ImHex you explicitly say that the size and layout of a custom type will always be the same with the `[[static]]` attribute which will enable some drastic optimizations. Maybe try that?

another thing that I found out right now is if I use the `Dollar Operator` to get the current offset of file, in each evaluate it use offset from previous evaluate! i mean if I use this pattern
```c
#pragma base_address 0x00

u32 test @ $;
```
at first its start from offset 0x00 and read the test but if I run it again this time its start from 0x04 and so on... I believe its a bug
I will also try to upload a file example and the pattern I created for it soon.

**Comment by WerWolv** [comment]
Heh yep, forgot to reset the offset. Thank you
