### ISSUE TITLE
[Bug] Program does not start under Windows 10 21H1

### ISSUE THREAD

**Issue by 0xBEEEF** [WerWolv/ImHex#324]
### Operating System

Windows

### What's the issue you encountered?

No matter if I download the zip version or the installer. The program simply does not start under Windows 10. When double-clicking on the exe file, nothing happens. There is neither an error message nor any sign that the program is running.

### How can the issue be reproduced?

The problem is relatively easy to recreate. Just download the free development machine from Microsoft [here](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/), and try to run ImHex there. 

### ImHex Version

1.10.1

**Comment by 0xBEEEF** [comment]
I have tried many things as already written. Unpacked it in only one subfolder on C:\, used the official installer. The demo VM from Microsoft does not have any special characters or similar in the path (English-only version). 

Is there any log or way to determine why the launch is impossible?

**Comment by WerWolv** [comment]
If you start `imhex.exe` through the console, it will output the log to that.

**Comment by LFriede** [comment]
Maybe the same problem -> https://github.com/WerWolv/ImHex/issues/307#issuecomment-946072032
