### ISSUE TITLE
[Bug] Could not load splash screen image!

### ISSUE THREAD

**Issue by pjalsGit** [WerWolv/ImHex#341]
OS: Linux

# Issue

When I try to run my freshly built ImHex, it complains that it can't load the splash screen image.

# Steps to reproduce

1. Compile ImHex
2. Wait
3. Run ImHex
4. See Error

# Version

cb583b5d6c136477ee9267df5cccbe4770260d4f

- [x] Built from source

# Logs
```
[FATAL] Could not load splash screen image!
```
(thats it)

## `uname -a`
`Linux fedora 5.14.16-302.fsync.fc35.x86_64 #1 SMP Sat Nov 6 19:37:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by WerWolv** [comment]
The splash screen gets embedded into the application with an `.incbin` pseudo assembler instruction. It can be found in `/res/resources/splash.png`. Make sure that file isn't corrupt in some way

**Comment by pjalsGit** [comment]
Interestingly enough, it worked some commits back, and the `res` folder is/was in `(build dir)/../res`

**Comment by WerWolv** [comment]
I built ImHex yesterday on both Windows and Arch Linux where it worked fine so I'd guess something's up with your setup

**Comment by jpsyri** [comment]
I encounter same problem when building from source on Fedora (I had to use the workaround in #340)

`Linux mandelbrot 5.14.15-200.fc34.x86_64 #1 SMP Wed Oct 27 15:53:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
