### ISSUE TITLE
[Bug] symbol lookup error

### ISSUE THREAD

**Issue by pjalsGit** [WerWolv/ImHex#342]
**OS: Linux**

# Issue

When I try to run ImHex, it complains with a symbol lookup error

# Reproduction steps

1. Get/Compile ImHex
2. Run ImHex
3. Get a symbol lookup error

## Version

*varies*

## Logs
```
(base) me@fedora:~/ImHex/build$ /usr/local/bin/imhex 
/usr/local/bin/imhex: symbol lookup error: /usr/local/bin/imhex: undefined symbol: yr_free
(base) me@fedora:~/ImHex/build$ sudo /usr/local/bin/imhex 
[sudo] password for me: 
/usr/local/bin/imhex: symbol lookup error: /usr/local/bin/imhex: undefined symbol: yr_free
(base) me@fedora:~/ImHex/build$
```

### `uname -a`
`Linux fedora 5.14.16-302.fsync.fc35.x86_64 #1 SMP Sat Nov 6 19:37:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by WerWolv** [comment]
Did you compile ImHex with the cmake `USE_SYSTEM_YARA` flag? Otherwise I have no idea how this could even happen, libyara is linked into ImHex statically.

**Comment by pjalsGit** [comment]
Tried with `USE_SYSTEM_YARA`, same error.

**Comment by WerWolv** [comment]
I feel like your system is messing with your compiler or with some flags that are enabled by default now. I never used Fedora myself before so I can't really help either, sorry.
