### ISSUE TITLE
Dependency Problem while compiling

### ISSUE THREAD

**Issue by LCRERGO** [WerWolv/ImHex#350]
I've been trying to build ImHex on Debian Testing(Bookworm) but I've found a problem I've run all scripts of getting dependencies and updated the submodules, but when I try  to compile I get an error in the import of a library:
![pic-211126-0055-26](https://user-images.githubusercontent.com/36491033/143526422-198c365b-c93c-4ceb-b2ec-9c3e5a4076da.jpg)

**Comment by iTrooz** [comment]
Hi @LCRERGO , I've just tried to compile Imhex from debian testing (docker container) and I didn't have any error

Would you mind to re-try now ?

**Comment by LCRERGO** [comment]
Hi, I just tried rebuilding it, and it went just fine.
