### ISSUE TITLE
macOS Needs More Love

### ISSUE THREAD

**Issue by utkonos** [WerWolv/ImHex#351]
### Operating System

MacOS

### What's the issue you encountered?

The ImHex window is locked in one position per monitor. It can be moved from one monitor to another using the Window menu, but cannot be moved around or resized. Not sure if this is by design.

Also, the "Native" scaling is absurdly large with only a small part of the window showing.

### How can the issue be reproduced?

Install using the package for macOS and run the software.

### ImHex Version

1.11.0

### 

- [ ] Nightly or built from sources

### Additional context?

MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version 11.6.1 (20G224)

**Comment by WerWolv** [comment]
Hi. Sorry about that, a fix for Windows I pushed today accidentally turned off window decorations for all platforms and not just Windows. 1.11.1 is building right now and will be released soon.
