### ISSUE TITLE
[Bug] Pattern applying when more than one file open

### ISSUE THREAD

**Issue by r3verseer** [WerWolv/ImHex#357]
### Operating System

Windows

### What's the issue you encountered?

Patterns are not working correctly when more than one file is opened. Loading patterns is working as expected, but after selecting other file in menu, pattern is (still) displayed w/o reanalyzing on second file. Its even more problematic when you are analyzing different file types at the same time. ImHex should apply and remember patterns on file level, not app level.

### How can the issue be reproduced?

1. Open any file (example bitmap type)
2. Apply pattern
3. Open other file (example executable type) and if asked dont load other pattern.

### ImHex Version

1.11.1

### 

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by WerWolv** [comment]
Patterns are now being stored and evaluated per-provider
