### ISSUE TITLE
[Bug] Bookmark colors all default to #010177 after project close and program close

### ISSUE THREAD

**Issue by limajdaas** [WerWolv/ImHex#362]
### Operating System

Windows

### What's the issue you encountered?

Thanks a ton for this software! It's amazingly helpful. I was having a bug with the bookmarks, however.

Every time I save my project, close ImHex, and reopen the project all of my bookmarks change colors to #010177. If I close my project and reopen it while keeping ImHex open then each of my bookmarks will have a duplicate. All of these duplicated will also have the color #010177.

### How can the issue be reproduced?

Open a file, create bookmarks, assign some colors, save project, close ImHex, and reopen it. The bookmarks should be intact but all of their colors should be #010177.

The other bug was to simply open a file, create bookmarks, assign colors, save project, close project and _not_ ImHex, and reopen project. There should now be duplicates of all bookmarks. One with the original color and another with #010177 as the color.

### ImHex Version

1.11.2

### 

- [ ] Nightly or built from sources

**Comment by WerWolv** [comment]
Hi! Sorry about that, colors so far just weren't saved to projects. Colors were added later on and just never added to the project serialization.
Also when loading closing a file or when loading a new project, things are now more thoroughly cleaned up so duplicated bookmarks and other things shouldn't happen anymore in the future :)

**Comment by limajdaas** [comment]
Thank you so much! Appreciate the quick response. Cheers!
