### ISSUE TITLE
BitFlag in pattern language

### ISSUE THREAD

**Issue by Guekka** [WerWolv/ImHex#369]
Hello, I was looking for a way to make DDS header easier to read and found this tool.
I was able to quickly get started and write a struct definition for [DDS header](https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dds-header)
However, there's one thing I haven't found. Some values are flags, combinations of several values. See `dwFlags` for example
Is there a way for ImHex to read these values, and decrypt the result into the separate flags?

**Comment by WerWolv** [comment]
Hi! Yeah there's `bitfield` types available as described here in the documentation: https://imhex.werwolv.net/docs/pattern_language/bitfields.html

**Comment by Guekka** [comment]
Thanks, this looks what I want. Love the tool!
