### ISSUE TITLE
Stray dylib?

### ISSUE THREAD

**Issue by utkonos** [WerWolv/ImHex#370]
In the macOS DMG, there is an additional dylib that is not inside the .app tree. The one inside and the stray have different hashes.

Is this intentional?

<img width="671" alt="stray_dylib" src="https://user-images.githubusercontent.com/2775739/146466280-0e5ba644-593c-4e9c-9dd3-ec84006e9693.png">

SHA1 of dylib in app: ebfd68257aaeefe59486a5379aff680b44cbaae8
![image](https://user-images.githubusercontent.com/2775739/146466076-3e367250-f6ee-4e11-af6a-d75d2f70bd80.png)

Stray SHA1: f8e5db1444fce9945b408df7dfa3cf3543c38f70
![image](https://user-images.githubusercontent.com/2775739/146466165-05dfb4fc-07c7-4994-aa30-7a577460c765.png)

**Comment by utkonos** [comment]
The two files have some differences. Here is a very meta screenshot:

![image](https://user-images.githubusercontent.com/2775739/146467499-d9769ebe-6087-426a-b865-1574018b408d.png)

And a few sacrilegious screenshots (sorry, still getting used to ImHex; can't do this stuff in it yet):
<img width="1041" alt="parsed" src="https://user-images.githubusercontent.com/2775739/146467644-b8db0853-8ee4-4b75-a61e-4286c06409f6.png">
 
<img width="990" alt="more_diff" src="https://user-images.githubusercontent.com/2775739/146467666-891e067b-3d0b-411e-af76-cb04ca02df2b.png">

**Comment by WerWolv** [comment]
Hi, thanks for investigating!
This is definitely not intentional. Could you compile ImHex yourself to maybe figure out where it's coming from? It's a bit difficult for me to debug mac builds without a mac.

I assume the difference comes from one getting "fixed up" so the library paths point to the right locations and the stray one doesn't.

**Comment by utkonos** [comment]
Yes, I can do that. I haven't done this type of project compilation on macOS before, so it may take me a moment to figure it out and get back to you.

**Comment by oxoocoffee** [comment]
Also little note. Maybe it would be good to include a simple README file in the dmg package describing where to put any extra files for the new Mac users? perhaps the purpose? 
Should libimhex.dylib got to ~/Library/Application Support/imhex/plugins ? There is where I did put it to. But I am not 100% sure if this is the correct location.

**Comment by utkonos** [comment]
@oxoocoffee I don't think that file belongs anywhere. It shouldn't be created in the first place. Unfortunately, the incident response season (what I call holiday season) was particularly busy this year. I have not allotted time to review the compile process to determine how that file is being generated. Bear with me, it is on my todo list.

**Comment by WerWolv** [comment]
Yeah the file should definitely not be there and doesn't go anywhere.
But other than that I know literally nothing about MacOS. I don't have a Mac and everything Mac related only exists because some amazing people contributed it.

**Comment by utkonos** [comment]
I just don't have time to work on this. I thought I'd have some time to stand up an environment and figure out how to build it, but I just don't have spare time.

I hope someone else can determine the origin of that stray file. It doesn't seem to harm anything, so I've just ignored it.

Also, just noted that the newest build doesn't run. There are lots of folders all over the DMG that were not there in the previous build. And the program says there are no plugins even default ones.

**Comment by WerWolv** [comment]
The new folders are probably me bundling all the resources from the pattern repo with the releases now. 
I'm really sorry but I have no idea what to do with the dmg. Apple's stance on this stuff is mostly "YeAh JuSt Go GeT a MaC aNd UsE oUr PrOgRaMs To Do It FoR yOu". Would it maybe be better to just release a zip instead and let the user figure it out instead of shipping a completely fucked dmg?
