### ISSUE TITLE
[Bug] Crash to Desktop when attempting to download from Content Store

### ISSUE THREAD

**Issue by propagating** [WerWolv/ImHex#371]
### Operating System

Windows 10 - 2152 - 19044.1415 x64 - Ryzen Processor

### What's the issue you encountered?
Attempting to download from Content Store results in crash to desktop.

### How can the issue be reproduced?

Open Application
Navigate to content store
Attempt to download any resource from content store

### ImHex Version

1.12.1 Release (not built from sources)

### Additional context?
There was no binary loaded when attempting to download from the content store. Additionally, associated directories had to be created by hand and were not created on installation. Despite adding those directories and ensuring they were recognized in ImHex, crash still occurs when attempting to download some items from the content store. On the rare occasion where it does not crash, no download occurs

**Comment by propagating** [comment]
Apologies for the rough formatting

**Comment by WerWolv** [comment]
Hi! I just tested it myself and it seems to work fine for me on Windows 10 19043.1348.

It seems weird to me that it wouldn't create the right folder structure automatically. Where did you install it? ImHex on Windows first tries to put stuff next to the executable in the folder structure there and if that fails it will try `%LOCALAPPDATA%/imhex`, one of which should work.
Do you maybe have some aggressive Antivirus installed? I know at least Windows Defender really doesn't like the official yara rules zip because it contains "malware code" to identify malware.

**Comment by propagating** [comment]
I used the default installation path through the installer. I didn't get any AV notifications or triggers, i only use the built in windows AV. It didn't create folders in the executable location or in the my local app data (which is just the windows default) and no folders were initially assigned on install. There were blank paths in the help window displaying folder locations until I manually created them in the executable folder.

I can try to reinstall and create the folders in my local app data and see if that works in the morning.

Regards,

Ryan Richardson
________________________________

**Comment by propagating** [comment]
So a couple of things during the process of uninstalling and reinstalling, minor issues but still just wanted to point them out. Reinstalling and creating the folders in my local app data path allowed the downloads to work successfully.

1. Uninstallation doesn't remove folders present in the executable folder. 
2. ImHex did not create default folders in either executable folder or the app data
3. This CTD still presents itself on both portable and installation versions 
4. Creating folders manually in the local app data path allowed the downloads to succeed successfully, but creating them in the executable path did not work for installation or portable versions
