### ISSUE TITLE
[Bug] [Debian 11] libpython3.8.so.1.0 not found (with workaround)

### ISSUE THREAD

**Issue by kittennbfive** [WerWolv/ImHex#374]
Hi,

Debian 11.1 with release v1.12.1 installed from the .DEB with apt inside a fresh VM.

When trying to start ImHex i get a message that libpython3.8.so.1.0 cannot be found. It looks like this file does no longer exist on Debian 11.1, but there is one for python 3.9.

Workaround: Create a symbolic link:
```
# cd /usr/lib/x86_64-linux-gnu/
# ln -s libpython3.9.so.1.0 libpython3.8.so.1.0
```

ImHex fires up fine after that.

edit: BTW, maybe you should mention somewhere that ImHex needs at least libc2.30 (iirc) so it won't start on Debian 10 for example.

**Comment by WerWolv** [comment]
Thanks!
ImHex uses whatever libraries are used by the GitHub Actions CI which builds all releases so it's pretty difficult to pin that down somewhere. I just assumed whatever's installed on Ubuntu 20.04 LTS will most likely be available on most other distros too
