### ISSUE TITLE
Row spacing in diff view does not align with hex view

### ISSUE THREAD

**Issue by zvodd** [WerWolv/ImHex#381]
Currently the _hexview_ and the _diffview_ have vastly different row spacing, which means if you line the views up you can't easly compare lines with the _hexview_, i.e. where you might want to click on a byte selection to inspect the data, or run pattern matching.
![ImHex sceencap _hexview_ and _diffview_ side by side](https://i.imgur.com/g45krar.png)
As you can see the ratio is off by about 4 : 3 - _hexview_ rows to _diffview_ rows.

It is also offset by ~ 2 rows, but I don't know think that is as much of an issue.

It would be pretty convenient to have these view share the same visual spacing as this would allow you to read the ascii data when inspecting a diff view.

Another possible remedy, would be to allow clicking an address position in the diffview to cause the hexview to goto that position.
Personally I would prefer both remedies.

**Comment by qxxxb** [comment]
This patch removes the line spacing in the diff view (but maybe it would look nicer to instead add line spacing to the hex editor view):

![image](https://user-images.githubusercontent.com/46016483/147027076-21a63779-6d19-498a-851e-ed2409b12860.png)

```patch
diff --git a/plugins/builtin/source/content/views/view_diff.cpp b/plugins/builtin/source/content/views/view_diff.cpp
index f6eea2b..aaef1ed 100644
--- a/plugins/builtin/source/content/views/view_diff.cpp
+++ b/plugins/builtin/source/content/views/view_diff.cpp
@@ -187,7 +187,7 @@ namespace hex::plugin::builtin {
             ImGui::PopID();
             ImGui::Separator();
 
-            ImGui::PushStyleVar(ImGuiStyleVar_CellPadding, ImVec2(20, 1));
+            ImGui::PushStyleVar(ImGuiStyleVar_CellPadding, ImVec2(20, 0));
             if (ImGui::BeginTable("diff", 3, ImGuiTableFlags_ScrollY | ImGuiTableFlags_BordersInnerV | ImGuiTableFlags_SizingFixedFit)) {
                 ImGui::TableSetupScrollFreeze(0, 1);
 
@@ -211,7 +211,7 @@ namespace hex::plugin::builtin {
                 if (this->m_providerA >= 0 && this->m_providerB >= 0) {
                     auto &providers = ImHexApi::Provider::getProviders();
                     ImGuiListClipper clipper;
-                    clipper.Begin(std::max(providers[this->m_providerA]->getSize() / this->m_columnCount, providers[this->m_providerB]->getSize() / this->m_columnCount) + 1, ImGui::GetTextLineHeightWithSpacing());
+                    clipper.Begin(std::max(providers[this->m_providerA]->getSize() / this->m_columnCount, providers[this->m_providerB]->getSize() / this->m_columnCount) + 1, ImGui::GetTextLineHeight());
 
                     // Draw diff lines
                     while (clipper.Step()) {
@@ -234,4 +234,4 @@ namespace hex::plugin::builtin {
 
     }
 
-}
\ No newline at end of file
+}
```

**Comment by WerWolv** [comment]
Implemented @qxxxb's patches and added some extra changes to make it look more like the normal hex view. Thanks a lot!
