### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by eliya305** [WerWolv/ImHex#390]
### Operating System

Windows

### What's the issue you encountered?

when ImHex open a file its locked (the file), and if you try to write to this file while its opened - you can't.

### How can the issue be reproduced?

open a bin file by ImHex.
open it by another editor, try to change something and save - you will get the error.

### ImHex Version

Every version including latest 

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by iTrooz** [comment]
@eliya305 I don't think this is possible, see https://serverfault.com/questions/585734/force-edit-txt-file-that-is-in-use-windows

**Comment by iTrooz** [comment]
@WerWolv I think this should be closed
