### ISSUE TITLE
[Bug] Scaling issue on Mac OSX M1 Pro

### ISSUE THREAD

**Issue by oxoocoffee** [WerWolv/ImHex#391]
### Operating System

MacOS

### What's the issue you encountered?

The application starts with really large fonts. Trying to open Help/Settings it looks like opens window in full screen size but it is empty (No contents in Settings window)

### How can the issue be reproduced?

1. Just install imhex to /Application folder and copy libimhex.dylib from dmg to ~/Library/Application Support/imhex/plugins
2. Start Application

### ImHex Version

1.12.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by menglong2234** [comment]
having the same issue

**Comment by oxoocoffee** [comment]
I just updated to the latest 1.14.0 and looks great :). The only thing so far I noticed is that the application icon has changed. But it looks almost white and it is hard to see what is on a white background? 
<img width="93" alt="Dock Icon" src="https://user-images.githubusercontent.com/2259575/151721706-5d53a79c-529c-4dcb-b5bd-1431d8d7e38f.png">

**Comment by oxoocoffee** [comment]
One more question. On the main README.md under the Mac OSX section, there is the text as such
"Install the ImHex executable as well as libimhex.dylib to wherever ImHex should be installed."

1. Should it be always installed to /Applications where imhex.app is installed?
2. ~/Library/Application Support/imhex/?
3. ~/Library/Application Support/imhex/plugins?

Can someone please clarify this? I did not build from the source. I just downloaded DMG from the Release page. 
After opening I replaced imhex.app in /Applications and drop all other folders (per main README.md) to ~/Library/Application Support/imhex/ 
I am just not clear about libimhex.dylib. Also how do you verify that everything is in the correct place? Is there some in-app option to verify what was loaded?

Tx

**Comment by WerWolv** [comment]
@oxoocoffee 

As far as I know, the only thing that's really necessary is the imhex.app file that you need to install in the standard location. The rest is optional but probably goes in `~/Library/Application Support/imhex`. You can go to `Help -> About` to find what the paths to all those locations are

**Comment by oxoocoffee** [comment]
@WerWolv 

Ok cool. I also realized that libimhex.dylib is already part of app like you stated
```
imhex.app tree
.
└── Contents
    ├── Frameworks
    │   ├── Python.framework
    │   │   ├── Python -> Versions/Current/Python
    │   │   ├── Resources -> Versions/Current/Resources
    │   │   └── Versions
    │   │       ├── 3.9
    │   │       │   ├── Python
    │   │       │   └── Resources
    │   │       │       ├── Info.plist
    │   │       │       └── Python.app
    │   │       │           └── Contents
    │   │       │               ├── Info.plist
    │   │       │               ├── MacOS
    │   │       │               │   └── Python
    │   │       │               ├── PkgInfo
    │   │       │               └── Resources
    │   │       │                   ├── PythonApplet.icns
    │   │       │                   └── PythonInterpreter.icns
    │   │       └── Current -> 3.9
    │   ├── libcrypto.1.1.dylib
    │   ├── libfreetype.6.dylib
    │   ├── libglfw.3.3.dylib
    │   ├── libglfw.3.dylib -> libglfw.3.3.dylib
    │   ├── libimhex.dylib                    <------------------------------
    │   ├── libmagic.1.dylib
    │   ├── libmbedcrypto.11.dylib -> libmbedcrypto.3.1.0.dylib
    │   ├── libmbedcrypto.3.1.0.dylib
    │   ├── libmbedtls.17.dylib -> libmbedtls.3.1.0.dylib
    │   ├── libmbedtls.3.1.0.dylib
    │   ├── libmbedx509.3.1.0.dylib
    │   ├── libmbedx509.4.dylib -> libmbedx509.3.1.0.dylib
    │   ├── libpng16.16.dylib
    │   ├── libssh2.1.dylib
    │   └── libssl.1.1.dylib
    ├── Info.plist
    ├── MacOS
    │   ├── imhex
    │   └── plugins
    │       └── builtin.hexplug
    └── Resources
        ├── AppIcon.icns
        └── imgui.ini
````
