### ISSUE TITLE
[Bug] FPS drops to about 2 when expanding a very large pattern data node

### ISSUE THREAD

**Issue by pitoriex** [WerWolv/ImHex#393]
### Operating System

Windows

### What's the issue you encountered?

When you have a very large Pattern Data node and expand it, FPS drop to very low numbers.
For example, when expanding this node FPS drop to 2 for me: https://i.imgur.com/cdXgfHz.png

I'm no expert at C/C++ but I have some experience with dear imgui and there is a `ImGuiListClipper` which helps you only render the list entries that are currently on the screen.

### How can the issue be reproduced?

Make an array with many entries, open the corresponding Pattern Data node and you'll notice the drop in FPS.

### ImHex Version

1.12.1

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by WerWolv** [comment]
Hi
Yeah that's an issue currently. The problem is that we're having a tree structure here so ImGuiListClipper can't be used. I couldn't yet figure out how to make my own list clipper that works well for what we're doing here sadly
