### ISSUE TITLE
[Bug] Pattern evaluation consumes significantly more memory than comparable hex editors

### ISSUE THREAD

**Issue by pitoriex** [WerWolv/ImHex#394]
### Operating System

Windows

### What's the issue you encountered?

I've noticed that patterns that consume almost no memory in 010 Editor consume many gigabytes of RAM in ImHex.
For example I have this template in 010 Editor:

```
struct ContentContainerInformation {
	uint32 index;
	uint32 hash;
	uint32 size;
};

struct ContentBlockInformation {
	uint32 hash;
	uint32 directory_index;
	uint32 file_index;
	uint32 content_container_index;
	uint32 file_offset;
	uint32 compressed_size;
	uint32 uncompressed_size;
};

struct MetaContainer {
	uint32 version;
	uint32 content_container_information_count;
	ContentContainerInformation content_container_informations[content_container_information_count];
	uint32 content_block_information_count;
	ContentBlockInformation content_block_informations[content_block_information_count];
};

MetaContainer meta_container;
```

This is the pattern I made for ImHex which should do the same as the one for 010 Editor:

```
#pragma array_limit 0xFFFFFF
#pragma pattern_limit 0xFFFFFF

struct ContentContainerInformation {
	u32 index;
	u32 hash;
	u32 size;
};

struct ContentBlockInformation {
	u32 hash;
	u32 directory_index;
	u32 file_index;
	u32 content_container_index;
	u32 file_offset;
	u32 compressed_size;
	u32 uncompressed_size;
};

struct MetaContainer {
	u32 version;
	u32 content_container_information_count;
	ContentContainerInformation content_container_informations[content_container_information_count];
	u32 content_block_information_count;
	ContentBlockInformation content_block_informations[content_block_information_count];
};

MetaContainer meta_container @ 0x00;
```

The `content_block_informations` array has 568977 entries, and when running this pattern ImHex consumes 7.1 GB.
010 Editor's memory usage is around 50 MB.

Please tell me if I made a mistake in converting the template to the ImHex pattern or if there's a bug that causes this because I'd really love to use ImHex instead of 010 Editor.
Many thanks!

### How can the issue be reproduced?

Use this pattern on the attached file:
```
#pragma array_limit 0xFFFFFF
#pragma pattern_limit 0xFFFFFF

struct ContentContainerInformation {
	u32 index;
	u32 hash;
	u32 size;
};

struct ContentBlockInformation {
	u32 hash;
	u32 directory_index;
	u32 file_index;
	u32 content_container_index;
	u32 file_offset;
	u32 compressed_size;
	u32 uncompressed_size;
};

struct MetaContainer {
	u32 version;
	u32 content_container_information_count;
	ContentContainerInformation content_container_informations[content_container_information_count];
	u32 content_block_information_count;
	ContentBlockInformation content_block_informations[content_block_information_count];
};

MetaContainer meta_container @ 0x00;
```

### ImHex Version

1.12.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

This is the file I'm running the pattern on: https://1drv.ms/u/s!Aj80vyFCtUjigSZMLzoONFhyHYjk?e=UDgjQE

**Comment by WerWolv** [comment]
Make sure to mark structs that are static (e.g their layout and size will always be the same no matter where they're placed in memory) with the `[[static]]` attribute. 010 has something similar to this attribute as well, it just works in the other direction, there you need to mark non-static structs with it.

Example:
```rust
struct MyStaticStruct {
    u32 x, y, z;
} [[static]];
```

**Comment by pitoriex** [comment]
Sadly this doesn't fix it for me.
Using pattern
```
#pragma array_limit 0xFFFFFF
#pragma pattern_limit 0xFFFFFF

struct ContentContainerInformation {
	u32 index;
	u32 hash;
	u32 size;
} [[static]];

struct ContentBlockInformation {
	u32 hash;
	u32 directory_index;
	u32 file_index;
	u32 content_container_index;
	u32 file_offset;
	u32 compressed_size;
	u32 uncompressed_size;
} [[static]];


struct MetaContainer
{
	u32 version;
	u32 content_container_information_count;
	ContentContainerInformation content_container_informations[content_container_information_count];
	u32 content_block_information_count;
	ContentBlockInformation content_block_informations[content_block_information_count];
};

MetaContainer meta_container @ 0x00;
```
on said input file still consumes upwards of 7 GB RAM where's 010 Editor needs 50 MB.
Could you try if you can replicate this?
Thanks!

**Comment by WerWolv** [comment]
Hey, I looked into this again and noticed that the `[[static]]` attribute just wasn't working at all.
Besides that, I made a bunch of optimizations so the color highlight data isn't cached anymore.

Ultimately, this took down the memory usage from > 20GB to less than 10kB in my test file lmao

**Comment by TheGreatRambler** [comment]
When I casually reduce memory usage to less than a thousand of a percent
