### ISSUE TITLE
[Bug] Settings screen shows up blank/black, but is actually scaled larger than the containing ImHex window

### ISSUE THREAD

**Issue by rubin55** [WerWolv/ImHex#397]
### Operating System

Linux

### What's the issue you encountered?

The settings screen shows up as black, but is actually sized larger than the main ImHex window, look:
https://youtu.be/qcRoWTfE44M 

### How can the issue be reproduced?

I git clone'd the source repository, stayed on master, followed build instructions. To be precise:

```shell
git clone https://github.com/WerWolv/ImHex.git --recurse-submodules
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j8

mkdir -p /opt/imhex/imhex1/bin 
mkdir -p /opt/imhex/imhex1/lib
mkdir -p /opt/imhex/imhex1/share/imhex/plugins

cp build/ImHex/build/imhex imhex1/bin/
cp build/ImHex/build/plugins/libimhex/libimhex.so imhex1/lib/
cp build/ImHex/build/plugins/builtin/builtin.hexplug imhex1/share/imhex/plugins/

# Created custom launcher script to handle locations of things:
cd /opt/imhex/imhex1
export LD_LIBRARY_PATH=/usr/lib:/opt/imhex/imhex1/lib
export XDG_DATA_DIRS=/usr/share:/opt/imhex/imhex1/share
/opt/imhex/imhex1/bin/imhex-bin "$
```

### ImHex Version

1.12.1, master@f45cc3f

### ImHex Build Type

- [X] Nightly or built from sources

### Additional context?

I'm running on Void Linux, Kernel 5.15.12, on a ThinkPad P14s Gen2 AMD, with a 4K display, Gnome 40.4 on Wayland.

**Comment by WerWolv** [comment]
This should be fixed
