### ISSUE TITLE
[Bug] Content Store is empty

### ISSUE THREAD

**Issue by KillyMXI** [WerWolv/ImHex#408]
### Operating System

Windows

### What's the issue you encountered?

All tabs in Content Store are empty. (as mentioned in #407 ([comment](https://github.com/WerWolv/ImHex/issues/407#issuecomment-1024893798)))

![image](https://user-images.githubusercontent.com/13851064/151661594-380c2515-35d1-4dc1-bcd3-65f12a75ade3.png)

### How can the issue be reproduced?

I don't know.

- downloaded https://github.com/WerWolv/ImHex/releases/download/v1.13.2/Windows.Portable.ZIP.zip
- unpacked
- running imhex.exe
- Choosing Help > Content Store
- Switching tabs and clicking Reload to make sure it persists
- Checking network settings to make sure it's not a network issue - no effect

### ImHex Version

1.13.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

Windows 10 Pro
Version	20H2
OS build 19042.1466

**Comment by KillyMXI** [comment]
Version 1.14.0:

- now shows the store entries;
- but descriptions are empty;
- allows to download;
- "Remove" button does delete the file but does not update the status in the app - can't redownload without restarting the app.

I also suggest to put a "Contribute" link into the Store window, with a link to https://github.com/WerWolv/ImHex-Patterns repo.

**Comment by WerWolv** [comment]
Remove button should work again now. Descriptions still haven't been implemented server side yet because I didn't find a good way to store that information.
