### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SBAPKat** [WerWolv/ImHex#412]
### Operating System

Windows

### What's the issue you encountered?

Scaling issue on windows 10; 
input is offset with display and black band on top
![image](https://user-images.githubusercontent.com/50132527/152317593-7d1bdd49-6482-4936-87aa-d162a1268d0b.png)

### How can the issue be reproduced?

Just installing and opening it on windows produced this issue

### ImHex Version

1.14.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

Windows 10 laptop 
i5 3360m using integrated graphics, drivers up to date

**Comment by WerWolv** [comment]
Hi

This is most likely an issue with Intel's integrated graphics hardware or its drivers. I cannot reproduce it on my machine with a AMD Ryzen and an NVIDIA GPU but a lot of other people with integrated Intel graphics have the same issue.

You can solve it by downloading the Mesa3D opengl.dll from here: https://fdossena.com/?p=mesa/index.frag and placing it next to the executable
