### ISSUE TITLE
Better font for CJK

### ISSUE THREAD

**Issue by gnuhead-chieb** [WerWolv/ImHex#420]
ImHex seems using unifont for displaying text.but it too jaggy of displaying Japanese text.
Noto Sans CJK can display CJK text more beautifully.

**Comment by WerWolv** [comment]
Yeah, unifont is used by default to ensure absolutely every unicode character can be displayed in some way. The default ImGui font only supports ASCII characters and a few extra ones but not many.

You can easily replace the standard font though by placing your font file named `font.ttf` in the ImHex Resource folder. The location of that folder on your system can be found in the About page. This will load all glyphs from that font and use all remaining glyphs from unifont
