### ISSUE TITLE
[Bug] Strange behavior with panel docking

### ISSUE THREAD

**Issue by mrspirytus** [WerWolv/ImHex#429]
### Operating System

MacOS

### What's the issue you encountered?

I start ImHex in fullscreen mode. I always run it in fullscreen. 
Next, I open any file and I am presented with a hex window, Now if I click the title bar of that window and try to drag it to the top (to dock it) it works fine. But when I try to dock to let's ay right side, I have automatically switched to MacOSX next workspace. No matter what I do I can not dock to the right inside ImHext application.
I can "sometimes" dock to the top. Everything other direction switches me to a new workspace.

### How can the issue be reproduced?

1. Start ImHex and enter the full screen.
2. Open any file
3. Click on the newly opened window and try to dock it to the right side

### ImHex Version

1.14.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by WerWolv** [comment]
Hey, I don't have a mac myself so I can't really test but I honestly think this is an issue with your setup. On macOS, ImHex simply uses GLFW to create a plain old window and draws to it. It doesn't do anything else with it.

Do other applications work fine? Do GLFW applications work?

**Comment by mrspirytus** [comment]
I do not have any GLFW based apps. This is a new machine so I do know. Anything to try from homebrew?
