### ISSUE TITLE
No interaction in OpenSUSE

### ISSUE THREAD

**Issue by kalwalt** [WerWolv/ImHex#43]
Hi! :slightly_smiling_face:  My name is Walter and i'm testing your app under OpenSuse Tumbleweed. I downloaded your package from https://github.com/WerWolv/ImHex/releases/download/v1.4.0/ImHex_1.4.0_Linux.zip i installed the required libs, but when i try yo open the open tab nothing happens. The same with the other buttons (import and so on...). Maybe is required to install other libs packages?

**Comment by WerWolv** [comment]
Hi! This is a bug that will be fixed in the next version. Please check out issue #14 for an easy workaround

**Comment by kalwalt** [comment]
Ok thank you @WerWolv i will try it!
