### ISSUE TITLE
[Bug] Issue with About dialog box

### ISSUE THREAD

**Issue by mrspirytus** [WerWolv/ImHex#430]
### Operating System

MacOS

### What's the issue you encountered?

When I was trying to open the previous bug, I am asked here about the version I am running. I did go to the menu "Help / About" and the contents of ImHex tab. See attached screenshot

<img width="648" alt="ImHex 2022-02-09 12-13-44" src="https://user-images.githubusercontent.com/60390416/153264307-bd61951d-b122-4874-af3b-342264ca8e71.png">
 

### How can the issue be reproduced?

1. Start application
2. Click Help / About

### ImHex Version

1.14.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by WerWolv** [comment]
I'm _pretty_ sure this is fixed on master. At least I fixed a similar bug with that and it hasn't happened anymore on Windows and Linux since

**Comment by Doc-4** [comment]
I had this happen in 1.14 upon launching the first time since boot, closing the program and reopening it fixed it. Haven't seen it in 1.15 just yet

**Comment by WerWolv** [comment]
This has been fixed in 3b4d6d465bf8aaa4cc39646a5d292127ec640763
