### ISSUE TITLE
[Bug] Crash when to_string is used in pattern

### ISSUE THREAD

**Issue by Diadlo** [WerWolv/ImHex#432]
### Operating System

Linux

### What's the issue you encountered?

ImHex crashes

### How can the issue be reproduced?

Install stdlib. Open any file and use this pattern

```
#include <std/io.pat>
#include <std/string.pat>

struct nvram_dataset_t {
  u8 data;
};

fn get_dataset_type(nvram_dataset_t dataset) {
  return std::string::to_string(dataset.data);
};

struct nvram_t {
  nvram_dataset_t dataset [[format("get_dataset_type")]];
};

nvram_t nvram @ 00;
```

### ImHex Version

1.14.0-2

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by WerWolv** [comment]
This should now work with the latest commit.
