### ISSUE TITLE
Add some CI tool like CircleCI

### ISSUE THREAD

**Issue by benjioh5** [WerWolv/ImHex#44]
There are many options but I recommend this two services.
- [Circle CI](https://circleci.com/)
- [Travis CI](https://travis-ci.org/)

Using CI tool, you can easily deliver compiled version.
+ How about add this project on apt & snap & yum & choco & brew?

**Comment by WerWolv** [comment]
Hi! Nightly builds are being worked on right now by @Thog. Also if you look at the other issues / PRs, there's many awesome people working on getting this into their favorite distro's package manager :)
Notably, there's already Arch and OpenSUSE that's done and Thog made it build on Ubuntu so there's nothing in the way there anymore either

**Comment by Calinou** [comment]
There's now continuous integration using GitHub Actions: https://github.com/WerWolv/ImHex/tree/master/.github

This issue can probably be closed.

**Comment by benjioh5** [comment]
Thanks a lot!
