### ISSUE TITLE
[Bug] GUI misalignment.

### ISSUE THREAD

**Issue by daninsky1** [WerWolv/ImHex#442]
### Operating System

Windows

### What's the issue you encountered?

The entire window displays misaligned. The application capture the mouse position on the right window area. But what you see is misaligned. This print is from the entire window take with the Windows Sniping tool in window mode.
![image](https://user-images.githubusercontent.com/4410465/154155841-82dc90c2-c98e-4ea7-abbd-30bae1736d78.png)

### How can the issue be reproduced?

Just download and open the 1.15 version.

### ImHex Version

1.15.0

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by WerWolv** [comment]
Hi. This is a bug mainly with Intel's OpenGL driver. You can use the Mesa3D OpenGL Software Renderer which should fix the issue.
https://fdossena.com/?p=mesa/index.frag

Also the last few commits just addressed this a little bit by disabling the borderless window when detecting a Intel GPU which fixes this bug but still doesn't make everything work as well as on dedicated GPUs.

**Comment by daninsky1** [comment]
Ye, I was thinking that maybe was related to my INtel HD graphics, but I didn't put that info. For sure it is. Thank you.

**Comment by Vort** [comment]
With Mesa driver, main misalignment problem disappeared, however minimize and maximize buttons still work incorrectly:
If I click on lower right part of minimize button, no minimization happen, but strange extra button appear instead:
![image](https://github.com/user-attachments/assets/abb7ede0-b2f4-4fe2-8f11-11c01d68c501)
Also tooltip says "maximize" while I'm hovering cursor over minimize button instead.
