### ISSUE TITLE
Non functional under Windows

### ISSUE THREAD

**Issue by PELock** [WerWolv/ImHex#45]
Did you even run it once under Windows?

It opens, console window stays behind it (compile it in UI mode).

Open File in menu doesn't work at all.

**Comment by WerWolv** [comment]
Hi!
I actually developed the entire thing under Windows :)
If you go through the issues here, you can see both of those issues have been fixed already in the latest master.
Check out #14 for the files not opening workaround

**Comment by team-200114** [comment]
Sorry I don't understand very well how this app works

**Comment by PELock** [comment]
It could be in the master, but in releases it's non functional version. No wonder ppl don't know how it works :)
