### ISSUE TITLE
[Bug] First run dumps strings and other weird behavior

### ISSUE THREAD

**Issue by tilkinsc** [WerWolv/ImHex#454]
### Operating System

Windows

### What's the issue you encountered?

![image](https://user-images.githubusercontent.com/7494772/155732438-bc553f3a-97d7-4a2f-9104-02179fc5cf96.png)

### How can the issue be reproduced?

Install on latest windows 10
Rx 6900 XT
Ryzen 9 3900x

First run from windows menu > ImHex

### ImHex Version

1.15.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

second run is fine

**Comment by WerWolv** [comment]
What a stupid bug. e3fbb490dfc86bde0e3835a19f0469f1b437a005 fixes this now. Thank you
