### ISSUE TITLE
Cusutomize location of `imgui.ini`

### ISSUE THREAD

**Issue by Stupremee** [WerWolv/ImHex#46]
It would be nice to modify the location where the `imgui.ini` file wil be saved.
Either a environment variable or a command line option would be a good choice to configure the location.

The location of the file can be modified by changing the `IniFilename` pointer of the `ImGuiIO` struct before any call to `NewFrame()`.

**Comment by MatejKafka** [comment]
Also, currently, the `imgui.ini` is stored in the working directory (at least on Windows in v1.5.0), so by starting ImHex from terminal in different directory, I'm leaving random `imgui.ini` files around the filesystem.

**Comment by its0x08** [comment]
I was about to open an issue about this too..
Its not comfy to have config file laying around and not even being hidden.. 
At leas make it hidden :D

**Comment by WerWolv** [comment]
The .ini file is now correctly placed in `$CONFIG_LOCATION/configs/interface.ini`
