### ISSUE TITLE
[Bug] Crash when opening a file on macOS Monterey (Intel)

### ISSUE THREAD

**Issue by kistlin** [WerWolv/ImHex#465]
### Operating System

MacOS

### What's the issue you encountered?

Segmentation fault: 11

From the diagnostics log: Exception: EXC_BAD_ACCESS

### How can the issue be reproduced?

Start ImHex and open a file.
Crash happens immediately.

Same with saving a file. Others operations may fail too.

### ImHex Version

1.16.2

### Additional context?

In addition I then tried to build ImHex myself.

In `addToolbarItems` `auto provider` is most of the time NULL, that's when it crashes, as it is accessed later. Sometimes it is set and then opening files works fine.

Looks like a race condition?
I didn't look into how the logic works exactly yet.

**Comment by WerWolv** [comment]
Hey, where exactly is the crash happening?
`addToolbarItems` looks fine to me. This code is run once every frame so all the stuff in there is done synchronously. The provider shouldn't ever be able to change in that time

**Comment by kistlin** [comment]
I tried to open a file (orange folder icon) and the debugger is at line 102. (327e904dbc924e452ffa1220f979c28d003b85a1)
```
            // Save file
            ImGui::Disabled([&provider] {
                if (ImGui::ToolBarButton(ICON_VS_SAVE, ImGui::GetCustomColorVec4(ImGuiCustomCol_ToolbarBlue)))
                    provider->save();
            },
>>>>>>                !ImHexApi::Provider::isValid() || !provider->isWritable() || !provider->isSavable());

```
If I go through `File` => `Open File...` it works. After that the orange folder also works.

If after startup I try to open the file with the orange folder it pretty much always crashes.
I did not debug any further for now, as I'm currently not using the MacBook that often.
