### ISSUE TITLE
Save layout

### ISSUE THREAD

**Issue by giltabibian** [WerWolv/ImHex#473]
### Operating System

Linux

### What's the issue you encountered?

It's not a bug but I'd like to know how can i save a specific layout. 
And also, is there any way to change the default layout? 
If i remember correctly, older versions kept the last layout and opened with it the next loading. 

### How can the issue be reproduced?

Change the default layout. Close app and open again, will open to default layout. 

### ImHex Version

1.16.2

### ImHex Build Type

- [X] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by WerWolv** [comment]
Hey!
That should not be happening. If you close ImHex correctly (that is closing it without it crashing), it should save the current configuration to a file through ImGui's logic. This worked fine for me yesterday but maybe I'm missing some edge case

**Comment by giltabibian** [comment]
OK I'll double check that.
What about creating custom layouts? Is there any documentation about it? Or an example.
The best thing will be an option to save the current layout once the user customize all the windows he needed. Do you think it's possible?

**Comment by WerWolv** [comment]
That is absolutely planned yeah. Currently the only way to create new layouts is programmatically through a plugin which is kinda... awkward. I'd like to have an option where you can setup your own layout the way you want it and then hit save in the layouts menu and it will add a new entry there directly for it. (Possibly even with support for community layouts through the content store)

**Comment by giltabibian** [comment]
Great. Thanks for the update!
By the way, I've checked now if the layout saved once quiting properly and it fail to load the latest layout. Always loading with default one.
Is there any configuration files i should erase to initialize that?
Happens to me both in linux and windows.

**Comment by WerWolv** [comment]
Try again with the latest nightly once it's built (or build it yourself). That should hopefully correct the issue

**Comment by giltabibian** [comment]
Tried latest nightly build on linux. It's better. My plugin still located but the hex builtin always pop uo in front although i removed it in the last session.
