### ISSUE TITLE
[Bug] imhex: /usr/lib/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /tmp/.mount_imhex.gxqm3d/usr/lib/librt.so.1)

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [WerWolv/ImHex#476]
### Operating System

Linux

### What's the issue you encountered?

imhex.AppImage wouldn't run

### How can the issue be reproduced?

Right-click imhex.AppImage and go into Actions menu and select 'Run in Konsole'

### ImHex Version

1.16.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.
Manjaro Pavhlo version (only 64bit) Using AMD Threadripper and Nvidia GPU KDE Plasma 5.somethingWhatDoesItMatter
[Linux.AppImage.zip](https://github.com/WerWolv/ImHex/files/8310570/Linux.AppImage.zip)

**Comment by mcejp** [comment]
Same on Fedora 35 over here. ImHex 1.16.2.

**Comment by presianbg** [comment]
+1 on Solus / Kali

**Comment by WerWolv** [comment]
Multiple AppImage issues have been fixed in the past few weeks. Please reopen an issue if it still doesn't work
