### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Jak-o-Shadows** [WerWolv/ImHex#485]
### Operating System

Windows

### What's the issue you encountered?

Fresh install of ImHex 1.16.2

Triggers Windows Security:
![image](https://user-images.githubusercontent.com/12681960/160267652-e1709517-d7bc-45c9-9347-fbf986fe418c.png)

### How can the issue be reproduced?

Install. Tried to install the extra bits.

### ImHex Version

1.16.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by WerWolv** [comment]
Hey, yara rules are there to analyze malware. They do contain small, harmless snippets from the malware they're identifying.

For that reason there's not much I can do. I'd suggest adding an exception for that folder to your antivirus tool.
