### ISSUE TITLE
Crashes when setting an invalid font on Windows [Bug] 

### ISSUE THREAD

**Issue by fredheidrich** [WerWolv/ImHex#486]
### Operating System

Windows

### What's the issue you encountered?

Typing error led to incorrect font path in settings menu. Upon restarting lmhex crashes when trying to load the invalid font. I'm unable to find how to reset the settings of find the config file to manually revert the change.

### How can the issue be reproduced?

Put in an invalid font path in settings, relaunch.

### ImHex Version

1.16.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

Windows 10.
I used a font name instead of custom font path

**Comment by WerWolv** [comment]
Hey! This bug has been fixed in 97bfb4004b3928e5170c3565502b37f910681967. You can use the latest nightly version or wait until the next version has been released.
