### ISSUE TITLE
[Bug] Pattern editor parser not working correctly

### ISSUE THREAD

**Issue by Yoshimaster96** [WerWolv/ImHex#488]
### Operating System

Windows

### What's the issue you encountered?

I get unexpected syntax errors when running seemingly simple code in the Pattern editor. Here are some examples:

```
u32 z = 100;
```
Error at line 1:
Parser: missing ';' at end of expression

```
u8 a @ 0;
u8 b = (a&0x40)>>6;
```
Error at line 2:
Parser: missing ';' at end of expression

```
fn foo() {
	return 100;
};
u8 x = foo();
```
Error at line 4:
Parser: missing ';' at end of expression

Even this example from the wiki doesn't work:
```
// Declare a variable called i available only inside the for
for (u8 i = 0, i < 10, i = i + 1) {
    // Keeps on executing as long as i is less than 10

    // At the end, increment i by 1
}
```
Error at line 2:
Parser: invalid sequence

What's going on?

### How can the issue be reproduced?

Run any of the example code snippets above, and it should produce an unexpected error.

### ImHex Version

1.16.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

OS: Windows 10 64-bit

**Comment by MulleDK19** [comment]
All of that needs to be inside a function to compile.

`u32 z = 100;` makes no sense as a pattern.

**Comment by Nemoumbra** [comment]
All these examples are valid code in the latest Nightly (likely fixed a long time ago).
