### ISSUE TITLE
[Bug] Wayland: Failed to connect to display

### ISSUE THREAD

**Issue by Alirezamn93** [WerWolv/ImHex#492]
### Operating System

Linux

### What's the issue you encountered?

when I run ImHex I get these errors
```
[INFO]  [main] Welcome to ImHex!
[ERROR] [main] GLFW Error [65544] : Wayland: Failed to connect to display
[FATAL] [main] Failed to initialize GLFW!
```

### How can the issue be reproduced?

No idea

### ImHex Version

1.17.0-1

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

I'm using Manjaro + gnome

**Comment by WerWolv** [comment]
Hey
You most likely accidentally installed the `glfw-wayland` package instead of hte `glfw-x11` one. Reinstall the right one with pacman and it should work.

**Comment by Alirezamn93** [comment]
> Hey You most likely accidentally installed the `glfw-wayland` package instead of the `glfw-x11` one. Reinstall the right one with pacman and it should work.

I'm using wayland, should I install `glfw-x11` ?
