### ISSUE TITLE
[Bug] Freeze When Quitting ImHex on MacOS

### ISSUE THREAD

**Issue by KSashaDF** [WerWolv/ImHex#495]
### Operating System

MacOS

### What's the issue you encountered?

ImHex freezes and starts using a significant amount of CPU when attempting to quit the application.

### How can the issue be reproduced?

Open ImHex, wait for it to initialize, and close it again.

### ImHex Version

1.17.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

An Activity Monitor process sampling yields this after ImHex has frozen:

<img width="1792" alt="Screenshot" src="https://user-images.githubusercontent.com/40648165/164568699-0341f521-c88d-4f2e-a6cd-d18a0789b91a.png">

**Comment by zer0pwned** [comment]
I just tried the most recently release and I think this issue has been fixed.
