### ISSUE TITLE
[Bug] Opening empty file crashes ImHex if other files are opened

### ISSUE THREAD

**Issue by sdasda7777** [WerWolv/ImHex#496]
### Operating System

Linux

### What's the issue you encountered?

It's exactly as title says - opening empty file results in somewhat unhelpful message box that opening failed. Unless, of course, you already have files open ("on other tabs"), which of course you do.

### How can the issue be reproduced?

Create non empty file besides an empty file. Open non empty file then the empty file.

### ImHex Version

1.17.0

### ImHex Build Type

- [X] Nightly or built from sources

### Additional context?

- Linux, XFCE

**Comment by sdasda7777** [comment]
Now that I think about it - it is really suspicious that ImHex doesn't allow editing of empty files anyways.

**Comment by WerWolv** [comment]
Hey
This does work fine for me on Windows. 
The expected behaviour would be that it opens the file but automatically resizes it to one byte.

Can you attach gdb and get me a stack trace for where it's crashing?

**Comment by sdasda7777** [comment]
Huh, okay, nevermind, when building from this repository it doesn't crash, it just shows the messsage box in both cases.

**Comment by birorobi** [comment]
OK.

pet, 22. tra 2022. u 17:33 sdasda7777 ***@***.***> napisao je:
