### ISSUE TITLE
Zero length arrays

### ISSUE THREAD

**Issue by Red-3D** [WerWolv/ImHex#50]
I am working with a file format that uses the same structure for many things,
this can lead to variables that indicate arrays of length 0 / no array for that element.
ImHex will crash as soon as it encounters such an array.

It would be awesome if ImHex would skip reading arrays of size 0.

[example files.zip](https://github.com/WerWolv/ImHex/files/5649570/example.files.zip)
```cpp
//setting the length to 0 with a variable will crash ImHex
//manually setting the length to 0 will create a array of length one

struct ZeroArray{
	u8 size1;
	u8 size2;
	
	//size1 will cause a crash: [terminate called after throwing an instance of 'std::bad_optional_acces']
	u8 array[size2];
	u8 a2[0];
};

ZeroArray data @0x00;
```

Version: 1.4.0 & 1.5.0
Os: Windows

**Comment by WerWolv** [comment]
Hi!
Damn, I thought I fixed this but I actually only fixed it for unions, not for structs. Give me a few minutes and I'll post a fix
