### ISSUE TITLE
request: create source tarballs with submodules included for releases

### ISSUE THREAD

**Issue by classabbyamp** [WerWolv/ImHex#504]
As a downstream distro packager, it would be really handy if releases had a tarball that included all the submodules as they're pinned in the repo at release time

**Comment by iTrooz** [comment]
This seems to be easily possible using something like https://github.com/marketplace/actions/upload-files-to-a-github-release

I've already done a test here, and it can indeed add a file automatically to the release: 
https://github.com/iTrooz/Test/blob/44683ceb30ec7082f3b4759c154333076ed99f7f/.github/workflows/release.yml
https://github.com/iTrooz/Test/releases/tag/4.0

@WerWolv Would you be okay with an action to bundle a .tar.gz with the source code of all submodules (+ImHex) ?

**Comment by WerWolv** [comment]
@iTrooz I'm technically fine with that, however for this to be useful at all, it would have to also upload the created artifacts then.
And this all can only happen when a new version should actually be released, not sure exactly how to test for that

**Comment by iTrooz** [comment]
Github actions can be triggered on release, and automatically add an artefact to the ones you upload

I'm going to send a PR for this
