### ISSUE TITLE
[Bug] Not possible to run on Debian stable with KDE.

### ISSUE THREAD

**Issue by markasoftware** [WerWolv/ImHex#506]
### Operating System

Linux

### What's the issue you encountered?

Apart from Flatpak (which I refuse to use and therefore didn't try), none of the installation options work.

### How can the issue be reproduced?

AppImage: I get a fatal error due to missing icons when clicking "open file":

```
Gtk-Message: 23:31:39.692: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 23:31:39.693: Failed to load module "colorreload-gtk-module"

(imhex:604363): Gtk-WARNING **: 23:31:39.728: Could not find the icon 'user-home-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

(imhex:604363): Gtk-WARNING **: 23:31:39.728: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted
```

However, I have hicolor and adwaita icon themes both installed on my system, which contain the image-missing.png the error message complains about.

.deb file and ELF: I get a runtime error because libpython 3.8 seems to be required, but Debian only ships 3.9 these days.

Building from source: Requires a newer CMAKE version than Debian provides (3.21 vs 3.18)

### ImHex Version

1.17.0

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by iTrooz** [comment]
@markasoftware Hey, could you try building from source now ?

**Comment by markasoftware** [comment]
Master branch builds fine now!
