### ISSUE TITLE
ImHex Icon and Banner need a overhaul

### ISSUE THREAD

**Issue by WerWolv** [WerWolv/ImHex#51]
As the project's getting more and more attention, I feel like it's time for a proper icon (that wasn't just taken from iconshock) and a proper banner (that wasn't just made in GIMP in 2 minutes)

![Icon](https://i.imgur.com/Gi6sGby.png)
![Big Icon](https://werwolv.net/content/assets/_projects/imhex.jpg)
![Banner](https://i.imgur.com/LpOmxPR.png)

Icon: 72x72px
Big Icon (for my Website): 256x256px
Banner: 1280x640px

Ideas, concepts and generally feedback are highly welcomed!

**Comment by umarcor** [comment]
@WerWolv since it's your own tool, you should feel free to pick whatever design you want. However, please be careful with contrast. The 256x256 version is very difficult to read, specially the dark blue close to the gray background.

**Comment by 7heaven** [comment]
For your consideration, basically it's two characters 'IM' with a '10' mask on it. https://imgur.com/l1lmH54. I'll update with a formal PS image later

**Comment by Red-3D** [comment]
Your idea looked pretty interesting, here is a quick mock up.

![IM_HEX_icon](https://user-images.githubusercontent.com/42870774/102017948-3af69b80-3d6a-11eb-81f6-fa10d39875e4.png)

**Comment by WerWolv** [comment]
Wow thanks a lot for your contribution! I really like the direction this is going already!
However, right now the mixing of the `0` and the `M` makes both of the letters kinda blend together in a way where you can't see either of them anymore very well unless you know the intention behind it. I'm not entirely sure though what to do about this. The idea is great though

**Comment by MaybeNotABob** [comment]
Just a few ideas I've thrown around to maybe help the creative process.

![IM_HEX](https://user-images.githubusercontent.com/69116075/102781337-6d6a4f00-438f-11eb-8900-463915b3d753.png)

![IM_HEX-10](https://user-images.githubusercontent.com/69116075/102781357-73603000-438f-11eb-8a36-d30876055301.png)

![bw-IMHEX](https://user-images.githubusercontent.com/69116075/102781374-778c4d80-438f-11eb-8a35-8627b7e18639.png)

**Comment by NicholeMattera** [comment]
Just an idea I had of mixing "Im" with hex.

![Icon-72x72](https://user-images.githubusercontent.com/697668/102783165-857aa800-4368-11eb-92a9-8cc5cd4d0a0b.png)

**Comment by iwakuramarie** [comment]
![imhex](https://user-images.githubusercontent.com/76962470/103903558-0d331700-50ca-11eb-86a9-8890cef3bc62.png)
i tried my best but it doesn't look that good; i took the portrait from another image i made and it's somewhat artifacted so the colors may mismatch a bit

**Comment by inspier** [comment]
Keeping Nichole's color scheme and idea I came up with these two ideas for the icon.

![ImHexSample1](https://user-images.githubusercontent.com/63922661/103928994-352e7480-50e2-11eb-9b55-d69d4d1edc92.png)

![ImHexSample2](https://user-images.githubusercontent.com/63922661/103929001-38296500-50e2-11eb-95b0-282b072f44f7.png)

As well as the following for the banner.

![ImHexBannerSample1](https://user-images.githubusercontent.com/63922661/103929053-47a8ae00-50e2-11eb-9815-e7fb35625c9c.png)

**Comment by heavyweathersystem** [comment]
![imhex](https://user-images.githubusercontent.com/75656694/103930133-47151500-50ec-11eb-97c6-a3557ad07e5c.png)
it's not very relevant but i spent some time on it, hopefully the letters don't look too bad lol

**Comment by Burner61** [comment]
These are focused on making the assets more modern while still taking inspiration from the pixelated, square style.
![icon](https://user-images.githubusercontent.com/72722334/104851751-e7551000-591c-11eb-9163-cfe1fe0612e4.png)
![banner](https://user-images.githubusercontent.com/72722334/104851778-081d6580-591d-11eb-88fe-8153711f5e21.png)
