### ISSUE TITLE
[Bug] Text color unreadable in pattern error prompt

### ISSUE THREAD

**Issue by p0358** [WerWolv/ImHex#517]
### Operating System

Windows

### What's the issue you encountered?

When encountering an error in Pattern editor and trying to hover over it to see the error, the error text is in light yellow font, making it absolutely unreadable (idk maybe it's readable on OLEDs or something but I don't have one xd):
![image](https://user-images.githubusercontent.com/5182588/170888833-72dd4754-8f1c-4479-a233-80d5806109e7.png)

### How can the issue be reproduced?

Using light mode...

### ImHex Version

1.18.1

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by WerWolv** [comment]
Thanks for the report! That color is hardcoded in the text editor library I'm using for some reason so it didn't use my custom color

**Comment by p0358** [comment]
Thanks for swift fix
