### ISSUE TITLE
[Bug] Imhex doesn't find default plugin when compiling

### ISSUE THREAD

**Issue by iTrooz** [WerWolv/ImHex#536]
### Operating System

Linux

### What's the issue you encountered?

When compiling ImHex, the default plugin is put in `build/plugins/builtin/builtin.hexplug`, and Imhex searchs in `build/plugins/builtin.hexplug` (see the last path searched in the screen)

![image](https://user-images.githubusercontent.com/42669835/173933063-6f9abf98-7b25-4fb9-b36c-beb1f77837e2.png)

### How can the issue be reproduced?

- Clone ImHex
- Compile
- cd to build directory
- ./ImHex

### ImHex Version

6266883 (latest commit at time of writing)

### ImHex Build Type

- [X] Nightly or built from sources

**Comment by WerWolv** [comment]
Latest commit _should_ fix the issue. Can you try when you have time?

**Comment by iTrooz** [comment]
It works indeed ! Thanks !
