### ISSUE TITLE
The MacOS bundle places the builtin.hexplug file in the wrong subfolder

### ISSUE THREAD

**Issue by somaen** [WerWolv/ImHex#539]
### Operating System

MacOS

### What's the issue you encountered?

I just downloaded the most recent DMG from here, and had ImHex immediately complain about missing plugins. Looking inside the .app, it seems that the builtin.hexplug file had been placed in Contents/MacOS/plugins, instead of Contents/plugins, and ImHex seemed to be searching in Contents/plugins for plugins. Moving the plugin file from Contents/MacOS/plugins to Contents/plugins immediately made ImHex work.

### How can the issue be reproduced?

Download the MacOS DMG, try to launch the app, immediately an error message complaining about not being able to find plugins should show up.

### ImHex Version

1.18.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by WerWolv** [comment]
Thanks for the report! The last commit should hopefully make ImHex look inside of the correct path now. Could you check if that's the case? You can find the latest nightly build in the Actions tab

**Comment by iTrooz** [comment]
The same issue is also at #494 (linked so can be closed once resolved)
