### ISSUE TITLE
Customize location of data directories

### ISSUE THREAD

**Issue by Stupremee** [WerWolv/ImHex#54]
Similair to #46, it would be nice to modify the location where the `patterns` `include` and `magic` folders are searched.

This could be achieved by either a command line flag or an environment variable

**Comment by abrasive** [comment]
To make packaging easier and more Unixy, it would be nice for these, and the Python `lib` directory, to default to `/usr/share/ImHex` when compiling on Unix.

This would also resolve the issue where they're not found if you run ImHex from the commandline outside the install dir, as currently they're searched relative to the cwd.

**Comment by tuxuser** [comment]
> to default to `/usr/share/ImHex` when compiling on Unix.

While at it, maybe even change the casing in general from ˋImHexˋ to ˋimhexˋ.

> it would be nice to modify the location where the patterns include and magic folders are searched.

Global location could be ˋ/usr/share/{appname}ˋ

Personal aka. per-user location ˋ$HOME/.config/imhexˋ or ˋ$HOME/.imhexˋ

**Comment by Calinou** [comment]
> While at it, maybe even change the casing in general from ˋImHexˋ to ˋimhexˋ.

This is done by https://github.com/WerWolv/ImHex/pull/70.

**Comment by wardwouts** [comment]
Isn't this issue solved already? Looking at https://github.com/WerWolv/ImHex/blob/master/plugins/libimhex/source/helpers/paths.cpp it seems that sensible paths are searched.
