### ISSUE TITLE
[Bug] Hovering over array don't show correct value

### ISSUE THREAD

**Issue by Grille** [WerWolv/ImHex#540]
### Operating System

Windows

### What's the issue you encountered?

Hovering over an array shows the same wrong value for the whole array.
Same with struct arrays, the name of the hovered field is correct, but the value is not.
![Capture](https://user-images.githubusercontent.com/26384012/174290338-b02518f9-5f83-468e-9d54-a7247438529a.PNG)
.

### How can the issue be reproduced?

^

### ImHex Version

1.18.2

### ImHex Build Type

- [X] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by WerWolv** [comment]
Thanks for the report! Latest commit should fix the issue
