### ISSUE TITLE
[Bug]  After doubleclicking a hex value its initially-displayed editing state corresponds to the value of the next byte

### ISSUE THREAD

**Issue by galkinvv** [WerWolv/ImHex#541]
### Operating System

Linux

### What's the issue you encountered?

After fixing #538 - different problem with editing appears: after doubleclicking a hex value its initially-displayed editing state corresponds not to its value but to the value of the next byte

Fortunately this behavior doesn't interfere if a new value is immediately entered (so I keep this nighty for my usage, thanks for fixing #538).
However if editing is "cancelled" by clicking to another byte - the editied value stays equal to the next byte, so the byte changes even was not edited.

### How can the issue be reproduced?

open any file with wo first bytes are different, for example
30 31 32 33 34 35 36 37 38 39 41 42 43 44 45 46 0123456789ABCDEF

[h.txt](https://github.com/WerWolv/ImHex/files/8927116/h.txt)

* double-click starting byte (30)
  * editing starts, but the displayed byte is 31 - the value taken from next
  * ![image](https://user-images.githubusercontent.com/1609972/174293627-0a7a493c-b8e5-4d5a-9acb-f55654f30158.png)
* click the next byte (to cancel editing - expected keep edited value unchanged)
  * the *changed* value is kept in initial byte, now it is equal to next byte

### ImHex Version

latest nigtly https://github.com/WerWolv/ImHex/commit/6b7ade8d61a80e563722ef96a565f0cb0bf3caa8

### ImHex Build Type

- [X] Nightly or built from sources

### Additional context?

Linux DEB nigtly build.

**Comment by WerWolv** [comment]
My god how can this be so hard to get right? I'll look into it again

**Comment by WerWolv** [comment]
Now it should _really_ be fixed
