### ISSUE TITLE
[Bug] Random crashes on Windows build of ImHex when run on ARM

### ISSUE THREAD

**Issue by zaafonin** [WerWolv/ImHex#542]
### Operating System

Windows

### What's the issue you encountered?

Two similar problems I've noticed when using x86_64 ImHex on ARM Windows:

- ~~More often than not, copying (Ctrl+C, Cmd+C, doesn't matter) makes the application crash instantly.~~ — not related to ARM Windows
- Clicking on some bytes makes the application unresponsive until terminated. If the info is of any use, ImHex fully utilizes a single CPU core/thread after entering the unreponsive state. Auto-restore prompt does not appear on restart.

### How can the issue be reproduced?

Reproducible on M1 Macs.
- Use Windows 11 on Parallels Desktop or other ARM virtual machine
- Install ImHex 1.18.2
- Open any file, patterns do not matter

### ImHex Version

1.18.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

Example file: [test.txt](https://github.com/WerWolv/ImHex/files/8935038/test.txt)

**Comment by zaafonin** [comment]
> Clicking on some bytes makes the application unresponsive until terminated. If the info is of any use, ImHex fully utilizes a single CPU core/thread after entering the unreponsive state. Auto-restore prompt does not appear on restart.

This bug disappears when Data Inspector is disabled. Might help localize the issue

**Comment by iTrooz** [comment]
Hey, could you try to run imhex from the command line to see if there is any interesting error ?

Also, would you mind trying to build from source ?

**Comment by zaafonin** [comment]
> More often than not, copying (Ctrl+C, Cmd+C, doesn't matter) makes the application crash instantly.
UPD: not Windows exclusive, bug present on Mac version as well.

**Comment by zaafonin** [comment]
> Hey, could you try to run imhex from the command line to see if there is any interesting error ?
Does not show anything for the data inspector bug, just a hangup.

**Comment by WerWolv** [comment]
Hey, ImHex isn't really supported on ARM at all. Also I don't have a Mac or any ARM device to test this on.

If possible, can you attach a debugger and tell me where exactly the crash happens? Otherwise I can't really do much, sorry. The issue doesn't seem to be present on x86 Windows

**Comment by iTrooz** [comment]
Hey @zaafonin, any news on this ?

**Comment by WerWolv** [comment]
Cool thanks
