### ISSUE TITLE
[Bug] AppImage conflicting with deb installation

### ISSUE THREAD

**Issue by Rohethan** [WerWolv/ImHex#544]
### Operating System

Linux

### What's the issue you encountered?

When launching the AppImage file, a message appears.
![image](https://user-images.githubusercontent.com/40922773/174500471-8b94a149-1b58-4b37-b20f-0f4217fa431c.png)
It seems the two are conflicting between each other, even though they are the same versions.

### How can the issue be reproduced?

- First install the deb, and launch it at least one.
- Close this installation
- Download the AppImage (give it exection permissions with chmod)
- Launch the AppImage
- *Voila !*

### ImHex Version

1.18.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

Using a Ubuntu-based Linux distro (Elementary OS 6.1, based on Ubuntu 20.04.3)

**Comment by iTrooz** [comment]
Even if the screenshot suggests it's a intended behavior, I think fixing it shouldn't be too hard
Suggestion : order the path from the more local to the more global one, and make ImHex use the first one it finds

**Comment by iTrooz** [comment]
As discussed on Discord, this will not be entirely fixed because it would be too hard to differentiate between installed version

That said, I will try to add a switch/warning message in debug mode so we can still *somewhat* launch both versions, in case we really need it

**Comment by iTrooz** [comment]
As of recent changes, I *think* it got entirely fixed :)
