### ISSUE TITLE
[Bug] Crashes on copying non-ASCII text from pattern editor

### ISSUE THREAD

**Issue by zaafonin** [WerWolv/ImHex#549]
### Operating System

Windows

### What's the issue you encountered?

ImHex crashes when copying non-ASCII text from the pattern editor, probably from other text fields as well. Debugger shows a failure on TextEditor::Copy() method. Possibly an ImGui bug.
<img width="243" alt="image" src="https://user-images.githubusercontent.com/21102341/174879898-68b7d96a-1cd8-47b2-8a24-1c5409126b44.png">

### How can the issue be reproduced?

Bug found both on macOS and Windows. To reproduce:
- Open any file
- Switch to pattern editor
- Paste a non-ASCII character (like `ь`)
- Select text and copy

### ImHex Version

1.18.2, also on nightly b89490b

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by WerWolv** [comment]
This should be fixed in the latest release. I replaced the glfw copying function with a native Windows one
