### ISSUE TITLE
CTRL + F, CTRL + G don't work in "Hex Editor", crash after entering an empty string in Search->Hex

### ISSUE THREAD

**Issue by 4B4DB4B3** [WerWolv/ImHex#56]
Hello. I found several bugs in ImHex.
1. CTRL + F, CTRL + G don't work in "Hex Editor"
2. If open Edit->Search->Hex and enter (null string) - ImHex crashed
![GIF 07 12 2020 17-06-23](https://user-images.githubusercontent.com/72896991/101360333-6aeafe00-3895-11eb-9fc5-afe5d0d3c2ab.gif)

**Comment by WerWolv** [comment]
This has been fixed a while ago
