### ISSUE TITLE
[Bug] Faild to open project

### ISSUE THREAD

**Issue by aixcyi** [WerWolv/ImHex#560]
### Operating System

Windows

### What's the issue you encountered?

Faild to open project sometime.

### How can the issue be reproduced?

- Click "Open Project" menu
- Choose a project profile (`“C:\WorkSpaces\binary\analysis\analysis.hexproj”`)
- A dialog is popup and tell me "Faild to open file!"
- If no files opened
  - ImHex will exit automatically in a short time
- else
  - Nothing. It seem to successed, because bookmarks was fully loaded.

### ImHex Version

1.18.2

### ImHex Build Type

- [ ] Nightly or built from sources

### System Info
- Windows: 10 21H2 (19044)
### Project Profile
```json
{
    "bookmarks": [
        {
            "address": 1,
            "color": 1341661682,
            "comment": "",
            "locked": false,
            "name": "内容长度",
            "size": 4
        },
        {
            "address": 5,
            "color": 1326447615,
            "comment": "",
            "locked": false,
            "name": "块长度",
            "size": 2
        },
        {
            "address": 7,
            "color": 1329760762,
            "comment": "",
            "locked": false,
            "name": "块",
            "size": 26
        }
    ],
    "dataProcessor": "{\"links\":{},\"nodes\":{}}",
    "filePath": "C:\\WorkSpaces\\binary\\analysis\\configs.dat",
    "patches": [],
    "pattern": "\n"
}
```

**Comment by iTrooz** [comment]
Hey, we have changed the way projects work a lot during the last year, and I remember specifically taking care of this in  #1135

so I'm going to close this, feel free to ping me if you can reproduce it again
