### ISSUE TITLE
[Suggestion] Could  we change a minor behavior of hex edit ?

### ISSUE THREAD

**Issue by techz1** [WerWolv/ImHex#565]
I found that when I'm doing a hex edit, the edited byte value move back when I'm done editing, which can cause some interference with multi bytes edits .Could we change this behavior to do not move back ? 

For example： change offset 0x80 from 4D to 4E
 
![1](https://user-images.githubusercontent.com/106645798/176827973-1f21f5e5-982d-4853-80f0-c0c7c0f77af6.png)

the it shows:
![2](https://user-images.githubusercontent.com/106645798/176828029-06efd415-d85c-449d-b974-345182dd28d3.png)

I'm not sure if this is a feature or a bug, so I post here

**Comment by techz1** [comment]
#538 

sorry , I  didn't see the closed issue.

**Comment by WerWolv** [comment]
Hey, yeah sorry that's a bug in the current release. You can use one of the nightlies if you want that contains a fix for it. Otherwise, there should be a new release coming out soon
