### ISSUE TITLE
[Bug] can't open file with spaces in name

### ISSUE THREAD

**Issue by bsdf** [WerWolv/ImHex#568]
### Operating System

Linux

### What's the issue you encountered?

when opening a file with a space in the name, the NFD library returns a url-encoded filename which std::fs doesn't seem to like. (`/home/bsdf/hello world.txt` becomes `/home/bsdf/hello%20world.txt`)

### How can the issue be reproduced?

open a file with a space in the name on Linux

### ImHex Version

master and 1.19.0

### ImHex Build Type

- [X] Nightly or built from sources

**Comment by iTrooz** [comment]
Hey, could you test if this problem was present in the last release ?

**Comment by bsdf** [comment]
appears to work as expected in v1.18.2
