### ISSUE TITLE
placing a struct wrong crashes

### ISSUE THREAD

**Issue by shakesoda** [WerWolv/ImHex#58]
in 1.5, entering something to the effect of
```
struct H {};
struct H h @ 0x0;
```
will crash as soon as it recognizes the placement as an expression.

I tried it this way since `H h @ 0x0;` didn't work on my first attempt for some reason, so I figured I'd try C syntax. It works fine with `struct H { u32 foo; }; H h @ 0x0;`

**Comment by WerWolv** [comment]
Thanks! This bug was introduced with the new be/le syntax and me failing to verify keywords properly
