### ISSUE TITLE
[Bug] Doesn't uninstall/install correctly

### ISSUE THREAD

**Issue by Calcoph** [WerWolv/ImHex#585]
### Operating System

Windows

### What's the issue you encountered?

(windows 11)

After uninstalling v1.19.1 and installing v1.19.2, the program would open, but just show a blank screen.

Deleting %localappdata%/imhex, then, installing v1.19.2 solved the issue and works fine now.

### How can the issue be reproduced?

1. Install v1.19.1 (probably any other version too).
2. uninstall imhex
3. install v1.19.2

### ImHex Version

1.19.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

My `%localappdata%/imhex/includes` and `%localappdata%/imhex/patterns` were links to another directory. I tried just deleting those 2 folders and the issue persisted. deleting the entire `%localappdata%/imhex` worked.

**Comment by Flamaros** [comment]
Just got similar issue when updating from 1.9.2 to 1.9.3. It seems that the user settings cause the issue.

I have erased my %localappdata%/imhex to test to load the version 1.9.3 and it works, but if I just let the config folder ImHex startup incorrectly. I absolutely nothing in the GUI (no menus, no tabs,...).

**Comment by WerWolv** [comment]
One of the latest commits should now automatically erase the settings if it can't be loaded anymore and recreate it instead of failing to start up properly.

**Comment by Flamaros** [comment]
So there is no back compatibility implemented in the configuration loader? Each time we update ImHex we may loose our configuration?

**Comment by WerWolv** [comment]
No, absolutely not. Only if I have to make certain setting format changes that would cause issues like that in the future, settings will be erased. This will not be something I'll be doing every single release.
