### ISSUE TITLE
[bug] can not close tools window sometime

### ISSUE THREAD

**Issue by Jhinxs** [WerWolv/ImHex#599]
![image](https://user-images.githubusercontent.com/79248856/181797531-59deb4a3-7963-4d59-8046-aabcf1e40bd3.png)

**Comment by WerWolv** [comment]
Please fill out the issue template next time.

It works completely fine for me on Windows 11. Do you have a hidpi screen or something? Otherwise it's probably rather a ImGui issue and should be reported on their [issue tracker](https://github.com/ocornut/imgui/issues)
