### ISSUE TITLE
[FR] Insert mode and Editing multiple bytes

### ISSUE THREAD

**Issue by eybisi** [WerWolv/ImHex#60]
FR1 - Currently, you can edit files by clicking the byte and writing/pasting one byte there. Pasting (CTRL+V) multiple bytes at once and changing as much as bytes ( 112233  should edit 3 cells) from the cursor would be nice to have as a feature.
FR2- a mode that inserts bytes from certain offset / cursor is must-have feature.

**Comment by stong** [comment]
+1

**Comment by WerWolv** [comment]
This has been implemented
