### ISSUE TITLE
[Bug] Enums seem to lose which variant they are when passed to a function.

### ISSUE THREAD

**Issue by JohnPeel** [WerWolv/ImHex#601]
### Operating System

Linux

### What's the issue you encountered?

```rust
#include <std/io.pat>

enum E : u8 {
	A
};

fn print_enum(E e) {
	std::print("e = {}", e);
	std::print("e == E::A => {}", e == E::A);
	return false;
};

struct S {
	E e;
	std::print("e = {}", e);
	std::print("e == E::A => {}", e == E::A);
	if (print_enum(e)) {}
};

S s @ 0x16; // Modify location to any 0x00.
```

Seems to print out the following
```
e = E::A
e == E::A => true
e = E::???
e == E::A => false
```

If I use a union to show the u8 value, it is still 0.

### How can the issue be reproduced?

See above.

### ImHex Version

1.19.3

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by JohnPeel** [comment]
```rust
#include <std/io.pat>

enum E : u8 {
	A = 1,
	B
};

fn print_enum(E e) {
	std::print("e = {}, E::A? {}, E::B? {}", e, e == E::A, e == E::B);
	return false;
};

print_enum(E::A);
print_enum(E::B);
```

This gives the following output:

```
e = E::???, E::A? false, E::B? false
e = E::A, E::A? true, E::B? false
```

**Comment by JohnPeel** [comment]
Weirdly enough, adding a prefix and printing it changes the behavior...

```rust
#include <std/io.pat>

enum E : u8 {
	A = 1,
	B
};

fn print_enum(str prefix, E e) {
	std::print("{} => e = {}, E::A? {}, E::B? {}", prefix, e, e == E::A, e == E::B);
	return false;
};

print_enum("E::A", E::A);
print_enum("E::B", E::B);
```
```
E::A => e = E::???, E::A? false, E::B? false
E::B => e = E::???, E::A? false, E::B? false
```

**Comment by WerWolv** [comment]
This has been fixed in master.
You can either wait for the next release to come out or download the latest nightly from https://imhex.werwolv.net
Thanks for the report!
