### ISSUE TITLE
[Bug] Ctrl+O shortcut key doesn't work when no files are open

### ISSUE THREAD

**Issue by ssg** [WerWolv/ImHex#606]
### Operating System

Windows

### What's the issue you encountered?

Ctrl+O shortcut key doesn't work for File->Open when no files are open. Pressing the shortcut key does nothing. Clicking on File->Open or Open file shortcut link works fine.

### How can the issue be reproduced?

Open ImHex. Make sure no file is open yet. Press Ctrl+O. Observe that nothing happens.

### ImHex Version

1.19.3

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- 150% DPI setting
- Windows 11 Pro insider build

**Comment by WerWolv** [comment]
Latest commit makes these shortcuts now correctly work if no files are loaded.
You can download the latest nightly once the CI finished building it or wait for the next release
