### ISSUE TITLE
[Bug] Pattern and data view out of sync

### ISSUE THREAD

**Issue by bjorn3** [WerWolv/ImHex#618]
### Operating System

Linux

### What's the issue you encountered?

When opening an archive file with the builtin archive file pattern, the third entry in the Pattern Data view gives as filename field "//              ", but when I click on it, a completely different part of the file is highlighted in the Hex editor.

### How can the issue be reproduced?

1. Open the .rlib file in [libcfg_if.rlib.tar.gz](https://github.com/WerWolv/ImHex/files/9228840/libcfg_if.rlib.tar.gz).
2. Load the builtin ar.hexpat pattern.
3. Click on the `[2]` entry in the Pattern Data view.
4. The filename field shows "//              ".
5. Click on the filename field.
6. The Hex editor view shows "30d004276c898f9.".

![image](https://user-images.githubusercontent.com/17426603/182026741-4d8efc90-7c67-45b8-a134-308ee32e62e4.png)

### ImHex Version

1.19.3

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

First time user

**Comment by bjorn3** [comment]
Looks like the file_size field is incorrectly parsed. Sometimes it bugs out with showing 8 instead of 54 as size for entry [1], in other cases it correctly shows 54, but still parses 8 bytes of data.

**Comment by bjorn3** [comment]
Using separate `ARFile file_1 @ $; ARFile file_2 @ $; // ...` instead of the original `ARFile files[while($ < std::mem::size())] @ $` seems to work around the issue.

**Comment by WerWolv** [comment]
Oh it's a supper small thing actually. Remove the `[[static]]` attribute from the struct and it should be working again. I'll remove it from the pattern as well.

Thank you!

**Comment by bjorn3** [comment]
That was indeed the issue. Thanks!
