### ISSUE TITLE
[Bug] Program crashes if folder specified as custom font path

### ISSUE THREAD

**Issue by DervishD** [WerWolv/ImHex#626]
### Operating System

Windows

### What's the issue you encountered?

In the font configuration, in `Custom Font Path`, if the user enters a folder name by editing the text box, the program crashes in the next run and keeps crashing until the `settings.json` file is fixed or removed.

The crash happens when on the splash screen the message "Loading fonts" is shown.

### How can the issue be reproduced?

In the menu, `Help > Settings > Font > Custom Font Path`, enter `C:\Windows\Fonts` (this is in fact how I discovered this) and close the configuration dialog.

I know that using the file chooser is IMPOSSIBLE to set a folder as custom font path, but the end user can write freely on the box and cause this problem. In my case, when I was going to type the TTF name after `C:\Windows\Fonts` I hit `Enter` by mistake and caused the problem.

### ImHex Version

1.19.3

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occured.

**Comment by DervishD** [comment]
WOW, that was FAST 😲 😄 Thanks a lot! 👍🏼

**Comment by WerWolv** [comment]
You're welcome :) Thanks for the report
