### ISSUE TITLE
[Bug] in/out variables outside the pattern editor are ignored

### ISSUE THREAD

**Issue by Calcoph** [WerWolv/ImHex#629]
### Operating System

Linux

### What's the issue you encountered?

If there is an in/out variable in an included pattern it doesn't show up.

However, if you use that variable directly in the pattern editor it does, even if it was declared in an included pattern.

### How can the issue be reproduced?

a.pat:
```c
u8 out_var out;
out_var = 1;
```

pattern editor:
```c
#include<a.pat>
// out_var doesn't show up.
```

```c
#include<a.pat>
u8 b;
b = out_var;
// out_var shows up.
```

EDIT:
It seems to be a problem with the global variables viewer updating when text in the pattern editor changes, instead of when clicking the "run" button. I don't think using the variable or not is relevant.

### ImHex Version

1.19.3

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by Calcoph** [comment]
In fact, you don't even have to use the out variable in the pattern editor.
Just declaring any global variable will make all in/out variables appear
```c
#include<a.pat>
u8 b;
// out_var shows up
```

**Comment by WerWolv** [comment]
Could you try the latest nightly? This seems to work fine for me on master

**Comment by Calcoph** [comment]
I have tried the nightly and it still persists, however it's less of an issue than I initially thought, editing the pattern editor at all fixes it.

In case you still can't reproduce it and think it's worth the effort:

1. create empty a.pat
2.`#include<a.pat>` in pattern editor
3. add in a.pat:
```C
u8 out_var out;
out_var = 1;
```
4. click run -> out_var doesn't show up.
5. just add a newline in pattern editor and out_var shows up.

Even if you remove out_var from a.pat, as long as you don't touch the pattern editor it will still show up, even if you click "run".

**Comment by WerWolv** [comment]
Thanks for that hint. The latest commit should now actually fully fix it.
