### ISSUE TITLE
Some experience in successfully compiling the Apple Silicon version

### ISSUE THREAD

**Issue by n0thing2speak** [WerWolv/ImHex#640]
```shell
brew install gcc@12
brew install glfw
brew install libmagic
brew install ccache

git clone https://github.com/WerWolv/ImHex.git --recurse-submodules
cd ImHex
mkdir build && cd build
CC=$(brew --prefix gcc@12)/bin/gcc-12     \
CXX=$(brew --prefix gcc@12)/bin/g++-12    \
OBJC=$(brew --prefix llvm)/bin/clang      \
OBJCXX=$(brew --prefix llvm)/bin/clang++  \
PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig":"$(brew --prefix)/lib/pkgconfig" \
MACOSX_DEPLOYMENT_TARGET="12.3"          \
cmake                                     \
  -DCMAKE_BUILD_TYPE=$BUILD_TYPE          \
  -DCREATE_BUNDLE=ON                      \
  -DCREATE_PACKAGE=ON                     \
  -DCMAKE_C_COMPILER_LAUNCHER=ccache      \
  -DCMAKE_CXX_COMPILER_LAUNCHER=ccache    \
  -DCMAKE_OBJC_COMPILER_LAUNCHER=ccache   \
  -DCMAKE_OBJCXX_COMPILER_LAUNCHER=ccache \
  -DIMHEX_PATTERNS_PULL_MASTER=ON         \
  ..

make -j4 package
```

<img width="236" alt="image" src="https://user-images.githubusercontent.com/19668794/182507956-cbf35a5b-3f69-4462-b6eb-aee073107ea8.png">

<img width="864" alt="image" src="https://user-images.githubusercontent.com/19668794/182508082-59df072c-c6ec-42a4-80fc-49fde52410d3.png">

**Comment by WerWolv** [comment]
Cool thank you for testing!
For the most part it looks the same as building it for regular x86 macOS so it probably doesn't need its own section in the build instructions. If GitHub Actions ever gets Apple Silicon support, I'll surely add support for it as well.

**Comment by tavdog** [comment]
This should be added to the install instructions of MacOS.  I wasted a lot of time following the ones that did not work.

**Comment by WerWolv** [comment]
@tavdog These instructions are available almost 1:1 here: https://github.com/WerWolv/ImHex/blob/master/dist/compiling/macos.md, linked in INSTALL.md as well

**Comment by tavdog** [comment]
Those are the standard no apple silicon instructions.  I followed those first and it didn't work.  The extra brew install gcc@12
brew install glfw
brew install libmagic
brew install ccache
at the top is what made it work.
