### ISSUE TITLE
[Feature] String extraction of all strings (ASCII, UTF16-BE, UTF16-LE) in one step

### ISSUE THREAD

**Issue by Neo23x0** [WerWolv/ImHex#641]
### What feature would you like to see?

Is a dropdown option for `ASCII + UTF16-LE + UTF16-BE` (and `UTF16-LE + UTF16-BE`) a low hanging fruit? 
If yes, I'd like to have it as well.

![Screenshot 2022-08-03 at 10 39 10](https://user-images.githubusercontent.com/2851492/182564084-4a5063e1-e7c8-4586-aac6-756cac407542.png)

### How will this feature be useful to you and others?

Users that just want all strings extracted could do it in one step. 
They wouldn't have to extract the ASCII strings, then the UTF-16-LE strings and then the UTF-16-BE strings.

**Comment by WerWolv** [comment]
Hey
I could imagine `ASCII + UTF16-LE` and `ASCII + UTF16-BE` should be simple enough to implement. `ASCII + UTF16-LE + UTF16-BE` will most likely produce a lot of duplicates though which probably isn't desired

**Comment by Neo23x0** [comment]
Yes, sound's good

**Comment by WerWolv** [comment]
Required some refactoring after all to handle decoding correctly.
In any case, the latest commit adds the bottom two entries to the `Strings` finder option in the Find view
![image](https://user-images.githubusercontent.com/10835354/182577378-fb26d175-7682-4d23-87f8-896b084f362d.png)
