### ISSUE TITLE
[Bug] Wrong path for plugins (and other support folders)

### ISSUE THREAD

**Issue by raff** [WerWolv/ImHex#646]
### Operating System

MacOS

### What's the issue you encountered?

On MacOS (Ventura 13.0) when I run imhex after installing from DMG, it says there are no plugins

### How can the issue be reproduced?

I installed from the nightly DMG (1.19.3).
I run the application and it says there are no plugins.

If I look in /Applications/imhex.app/Contents/MacOS I see the following folders:
constants	encodings	imhex		includes	magic		patterns	plugins

The plugins folder contains builtin.hexplug and the other folders contain other file, but it seems the application expects the plugins folder (and all other folders) to be in /Applications/imhex.app/Contents (and during the initialization it creates a bunch of empty folders).

I created some symbolic links from /Applications/imhex.app/Contents/MacOS/* to /Applications/imhex.app/Contents/ and I got the application to work.

### ImHex Version

1.19.3

### ImHex Build Type

- [X] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occurred.

**Comment by WerWolv** [comment]
Hi
Could you try using the latest nightly again? I just fixed an issue that should correct this now

**Comment by raff** [comment]
Yup! The nightly build is working. Thanks!
