### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sam-caldwell** [WerWolv/ImHex#647]
### Operating System

MacOS

### What's the issue you encountered?

In MacOS (Monterey) the installer appears to install builtin.hexplug to the wrong directory.  When the application is launched an error appears preventing the full functionality of the application to load.   (see screenshot with error message and a terminal showing how I found a workaround.)

![image](https://user-images.githubusercontent.com/24298795/182745494-b6e42c2a-a3ba-4142-b639-ad9ceafc0ca0.png)

### How can the issue be reproduced?

1. On MacOS machine (x86_64), download DMG installer
2. Open DMG installer
3. drag IMHEX application to the Applications folder
4. Close DMG installer
5. Open Applications folder and double-click IMHEX to run.
6. Observe error.

### ImHex Version

1.19.3

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

See screenshot.

The work around is to use `find` to find the plugin file and copy it to the appropriate directory.

FWIW...solid work!  I'm loving the application so far.

**Comment by WerWolv** [comment]
This has been fixed in latest master. Please download the latest nightly and it should work once again
