### ISSUE TITLE
[Bug] Binary Pattern Issues

### ISSUE THREAD

**Issue by 0x1F9F1** [WerWolv/ImHex#653]
### Operating System

Windows

### What's the issue you encountered?

I have noticed two issues with the binary pattern searcher (`searchBinaryPattern`):
* A partial match can hide an actual match
* Matches are not found at the very end of the search range

### How can the issue be reproduced?

Create a file with `11 11 22 33`.

* `11 22` cannot be found (due to a partial match with the first `11`).
* `22 33` cannot be found (due to being at the end of the search range).

### ImHex Version

1.20.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occurred.

**Comment by WerWolv** [comment]
Thanks for the report!
The latest two commits should address these issues
