### ISSUE TITLE
[Bug] Crush after doubleclick in hex code area

### ISSUE THREAD

**Issue by hajdam** [WerWolv/ImHex#658]
### Operating System

Linux

### What's the issue you encountered?

Crashes with SIGABRT
/usr/include/c++/12/optional:477: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = long unsigned int; _Dp = std::_Optional_base<long unsigned int, true, true>]: Assertion 'this->_M_is_engaged()' failed.

### How can the issue be reproduced?

Start imhex, open file (test with multiple / different files)
Double click on hex code + single click in the same area

### ImHex Version

1.20.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

Used imhex-1.20.0-Fedora-Latest.rpm from github
Fedora 36

**Comment by WerWolv** [comment]
Thanks for the report. Funnily enough, this is a bug everywhere but somehow only causes a crash on Linux.

You can download the latest nightly from my website as soon as a new one has been built.
