### ISSUE TITLE
Buffer error

### ISSUE THREAD

**Issue by donno2048** [WerWolv/ImHex#660]
### Operating System

Windows

### What's the issue you encountered?

You can cause a buffer error that crashes the app

### How can the issue be reproduced?

Open the disassembler and set the settings as such:
![image](https://user-images.githubusercontent.com/61805754/183269424-e1c0a212-4a59-4046-b0f7-65d7402a0de8.png)
and press _Disassembly_

### ImHex Version

1.20.0

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by donno2048** [comment]
?

**Comment by WerWolv** [comment]
Latest commit fixed the bug so it closed the Issue.

Thanks for the report!
