### ISSUE TITLE
Questions about Outbound Connections

### ISSUE THREAD

**Issue by bocajspear1** [WerWolv/ImHex#667]
### Operating System

Linux

### What's the issue you encountered?

Excuse me for my paranoia. Just installed ImHex for the first time and I noticed during startup that ImHex is trying to connect out: 
```
[03:17:53] [ERROR] [libimhex] Net request failed with error 28: 'Timeout was reached'
```
and it appears to be connecting out to `api.werwolv.net`. It connects and doesn't close until the application closes. What's the purpose of the connection? Also, with this connection, will ImHex work without internet access? 

Thanks,
Jacob Hartman

### How can the issue be reproduced?

Run ImHex

### ImHex Version

1.20.0

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by WerWolv** [comment]
Hey
It does close the connection immediately, it just doesn't log anything. It connects to a plain old REST HTTP API. The source code for it can be found here: https://github.com/WerWolv/WerWolvAPI.

The point of the connection and the API are basically two things: Check if there's a new version available on GitHub and update the content store with the latest files from the database at https://github.com/WerWolv/ImHex-Patterns.

Both of those calls are completely optional. If it can't reach the API, it will simply time out and not populate that information in ImHex but it will work completely fine without an internet connection
