### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [WerWolv/ImHex#67]
Would you like to add more error handling for return values from functions like the following?
- [fseek](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "Reposition a file-position indicator.") ⇒ [Preprocessor::preprocess](https://github.com/WerWolv/ImHex/blob/3827919a32462f49ee882b42db99ec5ae0830c0d/source/lang/preprocessor.cpp#L56)
- [ftell](https://pubs.opengroup.org/onlinepubs/9699919799/functions/ftell.html "Return a file offset.") ⇒ [View::subscribeEvent](https://github.com/WerWolv/ImHex/blob/226169bbbe5d71fab9eea501867c316f4441bbd3/source/views/view_pattern.cpp#L146)

**Comment by WerWolv** [comment]
We replaced the usage of raw file-io a long time ago now with a wrapper that should mostly take care of these issues.

**Comment by elfring** [comment]
:thought_balloon: It seems that a few update candidates were left over.
https://github.com/WerWolv/ImHex/blob/38162c01292513389cdfd6d1cb12e570f8e11b6a/lib/libimhex/source/helpers/net.cpp#L198
