### ISSUE TITLE
[Bug] editing a file not working with nightly version

### ISSUE THREAD

**Issue by iTrooz** [WerWolv/ImHex#671]
### Operating System

Linux

### What's the issue you encountered?

When editing any byte in a file, the others bytes are switched with '??'
See video

https://user-images.githubusercontent.com/42669835/184504492-9e79c144-13c0-4f3e-aa56-9152b5c60bd7.mp4

### How can the issue be reproduced?

- Install the **b580691 nightly** ImHex (tried both ArchLinux pkg and AppImage)
- Open a file
- Double click a byte and edit it
- All other bytes are changed to '??'

### ImHex Version

b580691

### ImHex Build Type

- [X] Nightly or built from sources

### Additional context?

Note :
this only worked in the nightly version (As of now, latest commit is [b580691](https://github.com/WerWolv/ImHex/commit/b580691871a8c80743d75ea4d6b1896c6ed57e15) ), and this issue **doesn't show up in the v1.20 release**

this was tested on ArchLinux KDE

**Comment by iTrooz** [comment]
(Also occuring on Fedora KDE, with both the rpm and the AppImage)

**Comment by WerWolv** [comment]
Should be fixed now
