### ISSUE TITLE
[Bug] std::string::contains does not work

### ISSUE THREAD

**Issue by deanveloper** [WerWolv/ImHex#675]
### Operating System

Windows

### What's the issue you encountered?

std::string::contains does not work for multiple reasons.

1. the while condition should be `<=` instead of `<`, as it does not work when `b` is at the very end of `a`.
2. for some reason, returning from inside of a loop does not work, it acts similarly to `break`.

### How can the issue be reproduced?

```
#include <std/io.pat>
#include <std/string.pat>

fn main() {
    if (std::string::contains("test", "t")) {
        std::print("there is a t inside of test");
    } else {
        std::print("there is not");
    }
};
```

### ImHex Version

1.21.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

We made our own contains function which fixes these two issues. While this worked for us as a temporary fix, the issue is with the interpreter/compiler and should be fixed there.

```
fn contains2(str a, str b) {
    s32 a_len, b_len;
    a_len = std::string::length(a);
    b_len = std::string::length(b);

    s32 i;
    bool ret = false;
    while (i <= a_len - b_len) {
        if (std::string::substr(a, i, b_len) == b) {
            ret = true;
            break;
          }
        i = i + 1;
    }

    return ret;
};
```

Note that two changes have been made to `contains`:
1. Instead of `return true`, we have a variable named `ret` which starts as false and gets set to `true`, and we `break` when we set to `true`.
2. We change the `while` condition from using `<` to `<=`. Otherwise it would return false in cases where the contained string was at the very end of the string, ie `contains("asdf", "df")`

**Comment by WerWolv** [comment]
Thanks for the report! Latest commit should address this
