### ISSUE TITLE
[Bug] v1.21.2 AppImage fails to run on Clear Linux* version 36870

### ISSUE THREAD

**Issue by volkertb** [WerWolv/ImHex#686]
### Operating System

Linux, specifically: Clear Linux* version 36870

### What's the issue you encountered?

When I try to run the AppImage of version 1.21.2 of ImHex on [Clear Linux*](https://clearlinux.org/) (version 36870 of this rolling release distro, the latest version as of this writing), it fails to start.

I try to run it as follows, after making the file executable:

```shell
./imhex-1.21.2.AppImage
```
Ant the result is the following:

```text
[20:34:02] [INFO]  [main] Welcome to ImHex!
/tmp/.mount_imhex-yg7RYm/usr/bin/imhex: symbol lookup error: /tmp/.mount_imhex-yg7RYm/lib/x86_64-linux-gnu/libX11.so.6: undefined symbol: xcb_parse_display
```

I did some searching on this error, specifically the part `undefined symbol: xcb_parse_display`, but I found no clues on-line as to the possible cause.

I also tried the nightly AppImage that I downloaded just a few minutes ago (2022-08-18), which was also named version `1.21.2` inside the ZIP file, although it had a different checksum than the `1.21.2` release. However, the result was the same error when I tried to run it.

Thanks for looking into this.

### How can the issue be reproduced?

- Install Clear Linux*. I was running it on a bare-metal system when I encountered the issue, but there's no fathomable reason why this couldn't be reproduced in a VM running the same OS.
- Run `sudo swupd update` to ensure that it's up-to-date, at least version `36870`.
- Download version 1.21.2 of the ImHex AppImage
- Make the downloaded file executable
- Run it from the shell prompt, in the folder where the file is located, as follows: `./imhex-1.21.2.AppImage`

### ImHex Version

1.21.2

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by iTrooz** [comment]
I'm afraid I can't use Clear Linux as a VM because it freezes a minute after booting, so you will have to answer a few questions :
- Output of `ldd libX11.so.6` ? (you will need to find where the library is installed on your system)
- Is there a `libxcb.so.*` somewhere in your system ?

**Comment by iTrooz** [comment]
Could you also try the AppImage from these two builds, and tell me if one of them work ?
https://github.com/iTrooz/ImHex/actions/runs/2885889692
https://github.com/iTrooz/ImHex/actions/runs/2885888396

**Comment by volkertb** [comment]
Sorry for the (very) late reply!

I just tried version `1.26.1` (the latest `1.26.2` release didn't include an AppImage for some reason).

The good new is that the error I initially reported is gone.

However, it now fails with the following error:

```
[22:20:14] [INFO]  [main] Welcome to ImHex 1.26.1!
[22:20:14] [ERROR] [main] GLFW Error [65542] : GLX: Failed to load GLX
[22:20:14] [FATAL] [main] Failed to create GLFW window!
```

This error is very similar (though not entirely identical) to the on reported in issue #804. I am indeed running Wayland while testing this. Could it be that your AppImages are built in a way that makes them incompatible with Wayland?

I'll log out and retry this in X11 mode and let you know if it works then.

**Comment by volkertb** [comment]
Ah, thanks. I missed that subtle little link. Just retried it with the 1.26.2, but got the same result.

By the way, shouldn't both `glfw-x11` and `glfw-wayland` be bundled in the AppImage? Isn't that the whole point of distro-neutral distribution formats?

I haven't logged out to try the AppImage in X11 mode yet, but I did try installing the Flatpak version with `flatpak install flathub net.werwolv.ImHex` and that one worked fine in a Wayland session.

It's worth noting that when I installed the Flatpak version with `flatpak install flathub net.werwolv.ImHex`, I noticed that only `x11` was in the list of permissions that the ImHex Flatpak required:

```text
Looking for matches…

net.werwolv.ImHex permissions:
    ipc                  network     x11     dri
    file access [1]

    [1] host


        ID                       Branch       Op       Remote        Download
 1. [✓] net.werwolv.ImHex        stable       i        flathub       18.3 MB / 17.2 MB

Installation complete.
```

So I assume the Flatpak version is running as an X11 application in XWayland.

Anyway, let me try the Flatpak in in an X11 session, and get back to you.

**Comment by WerWolv** [comment]
The problem is, you can't bundle both versions of glfw since both need to have the same name to be loaded. Right now I guess the one that's being included is the X11 version but iirc, if another one is installed on the system it will use that one.
In that sense, yeah the AppImage is not completely distro-neutral but there isn't really anything we can do about that

**Comment by volkertb** [comment]
OK, so I tried it again in an X11 session, but surprisingly, the result was exactly the same:

```text
$ echo $XDG_SESSION_TYPE
x11
$ ./imhex-1.26.2.AppImage
[23:18:48] [INFO]  [main] Welcome to ImHex 1.26.2!
[23:18:48] [ERROR] [main] GLFW Error [65542] : GLX: Failed to load GLX
[23:18:48] [FATAL] [main] Failed to create GLFW window!
```

Earlier, I tried looking for GLFW packages in my Clear Linux* installation that I might not have installed:

```text
$ swupd search glfw
Bundle with the best search result:
     devpkg-glfw                    	- All content for pkgconfig file glfw.pc.

This bundle can be installed with:

  swupd bundle-add  devpkg-glfw

Alternative bundle options are
     devpkg-glfw3                   	- All content for pkgconfig file glfw3.pc.  (11MB)
```

I tried installing both the `devpkg-glfw` and `devpkg-glfw3` packages, but that didn't help, so I uninstalled them. However, I only tried it with those packages installed while in a Wayland session. I could try reinstalling those packages and then running it again in an X11 session.

Even if the GLFW variant that gets installed by default is the X11 version, then why doesn't the AppImage fall back to X11 under XWayland? Also, why does the Flatpak version work?

The fact that glfw-x11 and glfw-wayland can't be installed in a system side-by-side does seem like a limitation that the GLFW developers should fix upstream. Wayland is becoming more and more commonplace now, but at the same time, it will take years before X11 compatibility can be completely dropped from desktop distros.

**Comment by volkertb** [comment]
Nope, just tried installing both of does packages and then running it in an X11 session again, then with just one of the two packages installed, then with just the other of the two packages installed, and every time I got exactly the same `Failed to load GLX` error.

And again, the Flatpak version works fine (at least in a Wayland session), so there appears to be something missing from the AppImage that the Flatpak (or one of its dependencies) does have.

If you want, I can figure out what QEMU/KVM command to easily and quickly spin up a Clear Linux* VM for testing purposes, should you want to investigate this further.

Thanks for your help so far!

At least the Flatpak is working for me.

**Comment by WerWolv** [comment]
Might also be some weird interaction between the AppImage and your system's drivers. The same issue often also appears when e.g your systems mesa drivers aren't working correctly.
Glad you can use ImHex now though
