### ISSUE TITLE
[Bug] Crash when using format attribute

### ISSUE THREAD

**Issue by alexander982** [WerWolv/ImHex#695]
### Operating System

Windows

### What's the issue you encountered?

When using `format` attribute with an incorrect function, the application crashes. On Windows ImHex crash on pattern evaluation. On Ubuntu appimage crash happens on pattern editing after evaluation.

### How can the issue be reproduced?

To reproduce:

1. Create new file.
2. Add some bytes.
3. Add following in pattern editor

```
fn test(u8 a) {
	return a ; //must be string
};

struct Test {
	u8 val [[format("test")]];
};

Test data @ 0x0;

```
4. Evaluate the pattern.

### ImHex Version

1.21.2

### ImHex Build Type

- binary distribution

**Comment by WerWolv** [comment]
Hey
I fixed various issues related to the format attribute in the past few days and it seems to work fine for me. Could you check if the latest nightly works for you? Once it's done building (in like 15 minutes from now), you can download it from https://imhex.werwolv.net all the way at the bottom of the page

**Comment by alexander982** [comment]
Yes it's work.
