### ISSUE TITLE
[Bug] imhex crash when one of file for diff  closed

### ISSUE THREAD

**Issue by augustheart** [WerWolv/ImHex#699]
### Operating System

Windows

### What's the issue you encountered?

see the following steps.

### How can the issue be reproduced?

1.open two files.
2.open diff window,then select the two file
3.close any file tab
4.crash :(

### ImHex Version

1.21.2

### ImHex Build Type

- [X] Nightly or built from sources

**Comment by WerWolv** [comment]
Thanks for the report!
Latest commits should fix this issue
