### ISSUE TITLE
[Feature] Dependencies on Debian 11

### ISSUE THREAD

**Issue by polprog** [WerWolv/ImHex#709]
### Operating System

Linux

### What's the issue you encountered?

Installing the .deb file for 1.21.2 is not possible due to missing packages. It appears ImHex uses newer versions that are available in Debian 11 (stable)

The packages missing are 
* `libmbedtls14`- there is `libmbedtls12`
* `libpython3.10` - there is `libpython3.9`

Does ImHex depend on these versions or can the versions of these packages be lowered?

### How can the issue be reproduced?

Download ImHex 1.21.2 release deb on a Debian 11 machine

    # dpkg -i imhex-1.21.2.deb

Dpkg will list errors due to missing packages, two of them are not existent in Debian Stable and `apt --fix-broken install` will only suggest removing imhex.

### ImHex Version

1.21.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

Trying to install ;)

**Comment by iTrooz** [comment]
Hello, this is a known "issue", the .deb is annotated for Ubuntu 22 (which has libmbedtls14 and libpython3.10)

You should use the AppImage in your case :)
