### ISSUE TITLE
[Bug] Documentation: Logarithmic progress bar(??) never ends

### ISSUE THREAD

**Issue by Chealer** [WerWolv/ImHex#712]
### Operating System

Windows

### What's the issue you encountered?

[The documentation section](https://imhex.werwolv.net/docs/) seems to include some weird (horizontal) thin progress bar at the very top. When a page is loaded, the bar gets more and more white.

The bar is most confusing:
- There is no clear indication of what it means.
- Its speed seems to be logarithmic. In other words, it seems to continually slow down.
- It seems to disappear only after an unreasonably long time (maybe 2 minutes).

I am guessing that some resource used by all pages is failing to load, which can be fixed. Nevertheless, I advise reviewing that widget. If the speed truly is logarithmic, the bar is at best worthless.

### How can the issue be reproduced?

Open https://imhex.werwolv.net/docs/

### ImHex Version

N/A

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

Firefox 104

<img width="593" alt="ImHex Documentation — Mozilla Firefox screenshot" src="https://user-images.githubusercontent.com/486141/187546406-899417d4-b345-4159-a007-8448bbefc2aa.png">

**Comment by WerWolv** [comment]
Thanks! This came from an app that was enabled on my cloudflare account from testing around still. I removed it now so the progress bar should be gone
