### ISSUE TITLE
[Bug] Black screen on 1.22.0

### ISSUE THREAD

**Issue by cuerv0s** [WerWolv/ImHex#729]
So, when I install ImHex, and open it, or try to open a file with it this is all what I see

![image](https://user-images.githubusercontent.com/103776652/188332797-2d0cb13f-1c83-4f43-99c3-1fbb71a23565.png)

**Comment by WerWolv** [comment]
Hey
What version of ImHex did you download? Portable? Portable-NoGPU? Also v1.22.2 does not exist, the latest one is v1.22.0.

From the picture it looks like a GPU issue but I need some more information to really help you

**Comment by cuerv0s** [comment]
Yes, sorry, i donwloaded stable release (.MSI installer), ran on Windows 10 Home 21H1 x64, i'm using Intel(R) UHD graphics 620, using standard Intel Corporation driver version 27.20.100

Tried to download Portable non-GPU version, this is the result:
![image](https://user-images.githubusercontent.com/103776652/188335148-f04f5139-f749-4c7c-8713-494a29e94a82.png)

Also tried to download portable GPU version, and result is almost the same
![image](https://user-images.githubusercontent.com/103776652/188335200-ecd71470-035c-4d19-8a5e-3f7dae4c5e8c.png)

**Comment by iTrooz** [comment]
Could you send us the logs you get if you launch ImHex from the terminal ?

**Comment by SmallJoker** [comment]
@ cuerv0s  I suppose your GPU driver sucks. You could try to use software rendering as a workaround by dropping Mesa3D's the opengl32.dll file next to the ImHex executable: https://fdossena.com/?p=mesa/index.frag

**Comment by lpksquall** [comment]
I got the same error.

[10:04:45] [INFO]  [main] Welcome to ImHex!
[10:04:45] [INFO]  [main] Native scaling set to: 3.0
[10:04:47] [ERROR] [libimhex] Net request failed with error 28: 'Timeout was reached'

**Comment by mi-hol** [comment]
MSI installed via winget is the wrong exe!

```
 cat AppData\Local\ImHex\logs\20230115_132755.log
[13:27:55] [INFO]  [main] Welcome to ImHex 1.26.2!
[13:27:55] [ERROR] [main] GLFW Error [65542] : WGL: The driver does not appear to support OpenGL
[13:27:55] [FATAL] [main] Failed to create GLFW window!
```

**Comment by cuerv0s** [comment]
> Could you send us the logs you get if you launch ImHex from the terminal ?

![image](https://user-images.githubusercontent.com/103776652/212763167-f41bb25a-0f17-44d5-b2fe-619f17a767e1.png)

I dropped the mesa3d's opengl32.dll file next to the executable, still black screen, nothing new in the terminal stdout.

**Comment by cuerv0s** [comment]
Tried the 1.26.2 version portable version (GPU), it's fixed now. Thanks.

**Comment by yeetdomain93** [comment]
I am having the same issue. Is there a fix?

**Comment by iTrooz** [comment]
Hey, please provide your plateform, installation type, and logs. Do you have a GPU ?

**Comment by yeetdomain93** [comment]
@iTrooz 
imhex version - 1.28.0
Platform - Windows 11
Installation Type - .msi ,
GPU - Yes. NVIDIA RTX A2000 8GB Laptop GPU

Logs: Log file is empty

**Comment by iTrooz** [comment]
Could you run imhex from the command line ? Sometimes it shows more logs

**Comment by yeetdomain93** [comment]
> Could you run imhex from the command line ? Sometimes it shows more logs

PS C:\Program Files\ImHex> [14:47:57] [INFO]  [main] Native scaling set to: 2.5
[14:47:57] [INFO]  [main] Task 'Setting up environment' finished in 0 ms
[14:47:57] [INFO]  [main] Task 'Creating directories' finished in 1 ms
[14:47:57] [INFO]  [main] Task 'Loading settings' finished in 0 ms
[14:47:57] [WARN]  [builtin] Intel GPU detected! Intel's OpenGL driver has bugs that can cause issues when using ImHex. If you experience any rendering bugs, please try the Mesa3D Software Renderer
[14:47:57] [INFO]  [main] Task 'Loading plugins' finished in 15 ms
[14:47:57] [INFO]  [main] Task 'Checking for updates' finished in 0 ms
[14:47:59] [INFO]  [main] Task 'Loading fonts' finished in 1435 ms

Just left hanging and the ImHex application display with a blacked out screen.

**Comment by WerWolv** [comment]
> Intel GPU detected! Intel's OpenGL driver has bugs that can cause issues when using ImHex. If you experience any rendering bugs, please try the Mesa3D Software Renderer

Looks like even though you have a NVIDIA graphics card built into your Laptop, Windows decided to use the integrated Intel HD GPU instead. These Intel GPUs and especially their drivers have TONS of bugs and don't work well. Also it probably doesn't have enough VRAM available to load the fonts. Try forcing your OS to use the NVIDIA GPU instead

**Comment by yeetdomain93** [comment]
> > Intel GPU detected! Intel's OpenGL driver has bugs that can cause issues when using ImHex. If you experience any rendering bugs, please try the Mesa3D Software Renderer
> 
> Looks like even though you have a NVIDIA graphics card built into your Laptop, Windows decided to use the integrated Intel HD GPU instead. These Intel GPUs and especially their drivers have TONS of bugs and don't work well. Also it probably doesn't have enough VRAM available to load the fonts. Try forcing your OS to use the NVIDIA GPU instead

YES! That worked for me. Thank you for the support, this save it for me. Product looks nice

**Comment by ArtemiiKravchuk** [comment]
Had similar problem, but not due to graphic drivers
If ImHex boots up for the first time, but then you accidentally close it and cant open again (black screen appears) - you probably messed up your config.
So I just removed `.config/imhex` directory, and it started working again (posting if you have a similar story)

**Comment by paxcut** [comment]
In at least one occasion, the only way I could get ImHex to start in a working condition was to remove the entire `%APPDATA%\..\Local\imhex` folder. Other times removing the file `%APPDATA%\..\Local\config\interface.ini` is all I needed to remove since this controls the layout. Yet other times restarting Imhex did the trick.
