### ISSUE TITLE
[Bug] Bad first time user experience on Linux

### ISSUE THREAD

**Issue by StephenWassell** [WerWolv/ImHex#730]
### Operating System

Linux

### What's the issue you encountered?

These are my first impressions of ImHex on Linux (Kubuntu x64 over RDP), after being recommended it by a colleague who'd used it on Windows.

I installed the .deb and ran imhex from the command line, with a file in the current directory as the argument. When it started it opened many windows of different sizes, mostly empty. None of them seemed to contain the hex contents of the file. I closed them one by one until the only window left was one the height of the screen and about 8 pixels wide.

I resized the tall thin window and found the hex dump (for some reason I could make it wider but it was stuck at the full screen height). Immediately my system became laggy and the CPU monitor showed all the cores over 50% use. The frame rate showed about 4fps (what is this, a desktop app or a game?).

At that point I gave up because it was too slow to be useable. This isn't a brand new machine but it has no trouble running VS Code.

I didn't get as far as checking if it was possible to use a normal antialiased system font instead of the default which looked very blocky on my monitor.

### How can the issue be reproduced?

Install on Linux (I was using Kubuntu over an RDP connection, 1920x1200) and open a file.

### ImHex Version

1.22.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occurred.

**Comment by WerWolv** [comment]
Hey
I'm very sorry that you had a bad experience. I personally never experienced any issues like that and I'm using ImHex almost daily at my job on both Windows 10/11 and Linux (Ubuntu and Arch).

Could you provide some more information about your system? What kind of WM and DM do you use? Does your system have a GPU? Have you tried running it without RDP on a local machine? I often use ImHex over RDP on a Windows machine at it works perfectly fine there but Linux's implementation probably works differently and might cause these issues

**Comment by StephenWassell** [comment]
Hi, me too because it sounds like it's got some really useful features! The Linux machine is running up to date KDE and I'm connecting via RDP from Windows 10. I'm not sure about the GPU situation on the Linux side and I suspect it wouldn't help xrdp anyway.

I've just tried running it again: selecting Layout - Default has fixed the window layout, now everything is neatly embedded in the main window. It's saying 50 FPS but now taking 90% CPU on all cores when fullscreen.

**Comment by WerWolv** [comment]
Regular usage looks like this for me: 
![image](https://user-images.githubusercontent.com/10835354/188505737-3081007b-8e0a-4f1c-aba7-91fb020c857c.png)

The FPS displaying 4 to 5 FPS is alright when you're not interacting with the application. It automatically lowers the framerate if nothing has changed to reduce CPU and GPU usage. However it using 90% either means your system is _really really_ bad or something went terribly wrong. Please try if you can replicate the same behaviour without RDP

**Comment by nonchip** [comment]
i (using KDE Plasma on void linux / X11) didn't notice any lag, but this is how ImHex greets me every time i open it with a file as an argument (until i then manually drag away all the overlapping windows, and select layout->default (even though it's already ticked) from the menu bar):
![image](https://user-images.githubusercontent.com/601018/196722685-c8372686-9451-4a66-a996-a33e26824bdf.png)

**Comment by WerWolv** [comment]
I still feel like this issue has somehow to do with the Window Manager / Composer you're using. I've never been able to replicate the windows appearring like that. The default layout automatically docks them onto the Window so it looks right for me both on Windows and various Linux distros.

@iTrooz Do you have an idea maybe or are you available to look into this issue?

**Comment by nonchip** [comment]
> The default layout automatically docks them onto the Window so it looks right for me both on Windows and various Linux distros.

oh yeah, it just doesn't do that when the windows *open*. as soon as i explicitly reload the default layout everything is correct.
same for when opening the application without a file argument and get that "get started" widget.
but if i provide one, it opens like in the screenshot. essentially everything seems to try to float at (0,0) of the "main window", but not *inside* the main window, but as individual (though undecorated) ones, that then get shoved outside of it by the WM if they're too tall by the looks of it.

**Comment by iTrooz** [comment]
I have no idea what could cause it, I can't reproduce it myself (ArchLinux KDE with X11 using the 1.24.3 release AppImage)

Do you mind testing with other configurations ? (Others DEs, Wayland instead of X11... You should use a separate user to do that, to not mess with your current config files)

Also, could you make a screenshot of the whole app ? I have trouble understanding what I am seeing

**Comment by nonchip** [comment]
i'm afraid that *is* the whole app.
