### ISSUE TITLE
Remove python test package from releases

### ISSUE THREAD

**Issue by BlueAmulet** [WerWolv/ImHex#74]
A lot of the file size in the newest release is bloated by the python test package, it may be a good idea to exclude the tests from the release distribution. Python's documentation says that "The test package is meant for internal use by Python only."

For example ImHex_1.5.0_Windows.zip is 15854KB, removing the test folder resulted in a 11719KB zip (~74%)

**Comment by WerWolv** [comment]
Oh damn I did not know about this. I'll remove them in the next release, thanks :)
