### ISSUE TITLE
[Bug] Opening diffing crash with strange graphic errors

### ISSUE THREAD

**Issue by nzaquini** [WerWolv/ImHex#741]
### Operating System

Windows

### What's the issue you encountered?

As shown in the following picture the graphic of ImHex gets corrupted when opening the diffing page

![image](https://user-images.githubusercontent.com/63739365/190211856-d1eda974-cdc6-453f-b6af-eca6a86960df.png)

Sometimes also the main page graphic is corrupted.

### How can the issue be reproduced?

- Open ImHex
- Open two similar files (I used two 256 KB .dat files)
- Open diffing page
- Bring diffing page to the second screen

### ImHex Version

1.21.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- using Windows 11 Pro; Version 21H2; OS build 22000.856
- problem occurs when the diffing page is outside the ImHex window (as floating popup)
- problem occurs when the floating diffing page is on a second screen

**Comment by WerWolv** [comment]
Hey
This is not an ImHex issue but usually caused by Intel's (but raraly also some other) horrible GPU drivers. Make sure to use a dedicated GPU to run ImHex if you can. If you don't have one, try updating your graphics drivers or use the NoGPU version of ImHex instead.

There's sadly not much we can do about it.

**Comment by nzaquini** [comment]
Thank you very much!
I updated ImHex to NoGPU version (v1.22.0) and problem seams fixed. I also updated Intel Iris Xe Graphics driver to the last release (from 30.0.101.1404 to 31.0.101.3413) but could not check if that helps. If you need I can rollback to v1.21.2 and check.
