### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Lwenkun** [WerWolv/ImHex#742]
### Operating System

MacOS

### What's the issue you encountered?

Pattern Data panel show nothing when I open a file though the pattern of the file downloaded
<img width="1438" alt="截屏2022-09-16 00 33 45" src="https://user-images.githubusercontent.com/15084367/190460825-349498d9-3e28-4385-ba0f-00161491eb94.png">
<img width="811" alt="截屏2022-09-16 00 34 20" src="https://user-images.githubusercontent.com/15084367/190460861-25559044-796f-44b7-85bd-8251e92b2e2b.png">

### How can the issue be reproduced?

Just open a file whose pattern has been already downloaded

### ImHex Version

1.23.0, 1.22.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- System details
<img width="285" alt="截屏2022-09-16 00 47 45" src="https://user-images.githubusercontent.com/15084367/190462297-37a6805a-94ca-49e2-a655-1c226553edfd.png">

**Comment by WerWolv** [comment]
Hey
For automatic pattern loading to work, you also need to download the libmagic database from the content store. If libmagic can figure out the MIME type of the Java class file you loaded, a popup should show up suggesting you to load the right pattern.

If this doesn't work, you need to load the pattern manually by selecting `File -> Load Pattern...` and select the relevant pattern in there.
