### ISSUE TITLE
ld problem for macos

### ISSUE THREAD

**Issue by vainPointer** [WerWolv/ImHex#75]
Hello, I am trying to build this project for macos. Here is my configure:
```
export CC=/usr/local/Cellar/gcc/10.2.0/bin/gcc-10
export CXX=/usr/local/Cellar/gcc/10.2.0/bin/g++-10
CMAKE_PREFIX_PATH=/usr/local/Cellar/llvm/10.0.1 cmake ..
export LIBRARY_PATH="/usr/local/Cellar/glfw/3.3.2/lib:/usr/local/Cellar/libmagic/5.39/lib:/usr/local/Cellar/openssl/1.0.2s/lib:/usr/local/Cellar/capstone/4.0.2/lib:/usr/local/Cellar/llvm/10.0.1/lib"
```
Then `make -j` turns to:
> [ 97%] Building CXX object CMakeFiles/ImHex.dir/libs/ImGui/source/imgui_impl_opengl3.cpp.o
[100%] Linking CXX executable ImHex
Undefined symbols for architecture x86_64:
  "__ZN4llvm8demangleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE", referenced from:
      __ZN3hex9ViewTools13drawDemanglerEv in view_tools.cpp.o
      __ZN3hex11ViewStrings23createStringContextMenuERKNS_11FoundStringE in view_strings.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status

May I ask what problem it can be? I also tried `LLVM_DIR=/usr/local/Cellar/llvm/10.0.1/lib/cmake/llvm/ cmake ..` and the result is:
> [  2%] Linking CXX executable ImHex
Undefined symbols for architecture x86_64:
  "__ZN4llvm8demangleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE", referenced from:
      __ZN3hex9ViewTools13drawDemanglerEv in view_tools.cpp.o
      __ZN3hex11ViewStrings23createStringContextMenuERKNS_11FoundStringE in view_strings.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status

**Comment by WerWolv** [comment]
Hi!
Please check the discussion in #32
