### ISSUE TITLE
[Bug] Unable to make #include work

### ISSUE THREAD

**Issue by MGilleronFJ** [WerWolv/ImHex#753]
### Operating System

Windows 11

### What's the issue you encountered?

I have a folder in which I have `.hexpat` files and wanted to `#include` one in a new project. So I added that folder to the `Folders` tab in settings, but no matter what, it keeps not finding the files.
```
// Tried this with an empty file, or a non-empy one, same thing
#include <empty.hexpat>
// Or this, same error
#include "empty.hexpat"
```
```
error[M0004]: No such file or directory
  --> <Source Code>:1:1
1 | #include <empty.hexpat>
    ^
    Path doesn't point to a valid file.
```
Am I missing something obvious? Because I don't see other issues mentionning that, and it seems like a common feature.

### How can the issue be reproduced?

1) Create an empty `.hexpat` file in any folder, in my case it was in `C:\Users\Marc\Doodle`
2) Open ImHex
3) Go to Help -> Settings, add the path to the folder
4) Type `#include <empty.hexpat>` in the pattern editor (or with quotes, same outcome, I don't know if it's supposed to be valid tho).
5) Press the arrow button to compile the pattern: observe error.

Restarting ImHex doesn't fix it either.

![image](https://user-images.githubusercontent.com/105369548/192530124-d08a0ae0-fd0f-42d9-855a-419c0a4f0e54.png)

### ImHex Version

1.23.2

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by WerWolv** [comment]
Hi!
Sorry, this might not be documented very well currently. The pattern language expects a `includes` or `patterns` folder inside of the folder you specify in this list. It will only search for includes inside of those.
