### ISSUE TITLE
[Bug] Order of bitfields reversed?

### ISSUE THREAD

**Issue by ntamas** [WerWolv/ImHex#756]
### Operating System

MacOS

### What's the issue you encountered?

It seems like the order in which the individual fields of a bitfield are parsed by ImHex is reversed compared to what is in the documentation. For instance, the documentation shows this as an example:

```
bitfield Permission {
  r : 1;
  w : 1;
  x : 1;
};
```

and the correspnding screenshot in the documentation indicates that `r` is treated as the LSB, so the parsing happens from right to left. (On that screenshot, 0x06 is mapped to w=1 and x=1). [(source)](https://imhex.werwolv.net/docs/core_language/data_types.html#bitfields)

Now, I have a similar construct in my pattern file:

<img width="490" alt="Screenshot 2022-09-29 at 12 20 00" src="https://user-images.githubusercontent.com/195637/193006447-758fae33-cf93-40d4-96c5-2cc34124092a.png">

and it is parsed like this (note the ordering; `use_yaw` appears first at the LSB even though it is listed second in the bitfield so it should be the `MSB`):

<img width="732" alt="Screenshot 2022-09-29 at 12 21 09" src="https://user-images.githubusercontent.com/195637/193006667-1685d0bf-f097-469b-87ca-f037ec66521d.png">

Am I misunderstanding something, is there a secret switch or pragma that controls the ordering, or is it a geniune bug? I remember that the same pattern file used to work correctly in some earlier version of ImHex, but I was not tracking the version numbers so I cannot tell exactly which version it was. Right now I'm on 1.23.2.

### How can the issue be reproduced?

Create a pattern field with the following contents, load it into ImHex and make it parse a file containing at least one byte:

```
bitfield Test {
    lsb : 1;
    mid : 6;
    msb : 1;
};

Test file @ 0;
```

On my machine `msb` is parsed as bit zero (rightmost bit) and `lsb` is parsed as bit 7 (leftmost bit). It should be the other way around.

### ImHex Version

1.23.2

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by galkinvv** [comment]
> Am I misunderstanding something, is there a secret switch or pragma that controls the ordering, or is it a geniune bug? I remember that the same pattern file used to work correctly in some earlier version of ImHex, but I was not tracking the version numbers so I cannot tell exactly which version it was. Right now I'm on 1.23.2.

I had the same problem. It seems that imhex accidently switch default bitfield_order several verisons ago.
I think by now the most straight-forward way to make a pattern that works for several last versions - are explicitely specifying pattern parameters, like

```
#pragma endian little
#pragma bitfield_order right_to_left
```

All pragmas are documented at https://imhex.werwolv.net/docs/core_language/preprocessor.html

**Comment by ntamas** [comment]
Thanks, this is helpful, I didn't know about the `bitfield_order` pragma.

Nevertheless, I think that the reversal of the default `bitfield_order` is still a bug as the page you linked explicitly declares that the default is `right_to_left`, which is apparently not the case.

**Comment by markhc** [comment]
From what I can tell from some quick debugging, the default for is RightToLeft, as you can see [here](https://github.com/WerWolv/PatternLanguage/blob/master/lib/include/pl/core/evaluator.hpp#L354), but ImHex also loads some pattern files by default when you open a file, one of them being [ip.hexpat](https://github.com/WerWolv/ImHex-Patterns/blob/master/patterns/ip.hexpat).

This file changes the bitfield order to LeftToRight, and this is the order that is used afterwards by the evaluator unless another `#pragma bitfield_order` were to change it back.

**Comment by galkinvv** [comment]
> Nevertheless, I think that the reversal of the default `bitfield_order` is still a bug as the page you linked explicitly declares that the default is `right_to_left`, which is apparently not the case.

I think that it is a bug, but since versions of both variants already has some circulation 'in the wild' - bitfield usage without pragmas is already a risk anyway.

Saying - "just use the latest version" maybe a good idea but I often need to rollback ImHex versions since new version often break something that I need...

I'd suggest documenting it as is "default was A before version X and B after version X. Use this pragma". Or even reject bitfields without pragma comment.

**Comment by WerWolv** [comment]
Thanks for investigating, The latest commit to the pattern language now correctly resets the bitfield order back to RightToLeft after every use.
