### ISSUE TITLE
[Bug] ASCII Table difficult to read on lighter themes

### ISSUE THREAD

**Issue by daliang20** [WerWolv/ImHex#757]
### Operating System

Windows

### What's the issue you encountered?

The ASCII table in tools has a fixed color for even and odd rows on the light and dark themes. The font color depends on the theme. The color combination of the background color and that of the font makes it hard to use the tool. 

## Light Theme
![Light Mode ASCII Table](https://user-images.githubusercontent.com/32944137/193115651-3b9354cd-e040-4cb1-87cd-79e3dc80518e.PNG)

## Dark Theme
![darktheme](https://user-images.githubusercontent.com/32944137/193115552-4d069dc8-038b-4f28-87f1-1eb7e75aa8d9.png)

### How can the issue be reproduced?

Open up the ASCII Table with different themes.

### ImHex Version

1.23.2

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by WerWolv** [comment]
Thanks a lot for the report!
This bug must have been there since the basically the first week when I started this project :D
Latest commit fixes it
