### ISSUE TITLE
[Bug] Cannot compile on windows with MSYS2

### ISSUE THREAD

**Issue by SigmaStar** [WerWolv/ImHex#769]
### Operating System

Windows

### What's the issue you encountered?

while executing make, it encounter error as "writing 1 byte into a region of size 0" .

### How can the issue be reproduced?

Just build the project at current release

### ImHex Version

1.23.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

- Additional information about your environment.
- If possible and useful, please upload the binary you've been editing when the bug occurred.

**Comment by WerWolv** [comment]
Could you please post the entire error message?

**Comment by SigmaStar** [comment]
If with modified plugins, when building libimhex,it shows errors as below:
`In file included from C:/msys64/mingw64/include/c++/12.2.0/atomic:41,
                 from C:/msys64/mingw64/include/c++/12.2.0/stop_token:34,
                 from C:/msys64/mingw64/include/c++/12.2.0/thread:40,
                 from C:/Users/sig/git/ImHex/lib/libimhex/include/hex/api/task.hpp:6,
                 from C:\Users\sig\git\ImHex\lib\libimhex\source\api\task.cpp:1:
In member function 'std::__atomic_base<_IntTp>::__int_type std::__atomic_base<_IntTp>::load(std::memory_order) const [with _ITp = bool]',
    inlined from 'std::atomic<bool>::operator bool() const' at C:/msys64/mingw64/include/c++/12.2.0/atomic:87:26,
    inlined from 'bool hex::Task::isFinished() const' at C:\Users\sig\git\ImHex\lib\libimhex\source\api\task.cpp:79:22,
    inlined from 'bool hex::TaskHolder::isRunning() const' at C:\Users\sig\git\ImHex\lib\libimhex\source\api\task.cpp:133:63:
C:/msys64/mingw64/include/c++/12.2.0/bits/atomic_base.h:488:31: error: 'unsigned char __atomic_load_1(const volatile void*, int)' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  488 |         return __atomic_load_n(&_M_i, int(__m));
      |                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/c++/12.2.0/bits/atomic_base.h:488:31: error: 'unsigned char __atomic_load_1(const volatile void*, int)' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
In member function 'std::__atomic_base<_IntTp>::__int_type std::__atomic_base<_IntTp>::load(std::memory_order) const [with _ITp = bool]',
    inlined from 'std::atomic<bool>::operator bool() const' at C:/msys64/mingw64/include/c++/12.2.0/atomic:87:26,
    inlined from 'bool hex::Task::hadException() const' at C:\Users\sig\git\ImHex\lib\libimhex\source\api\task.cpp:83:22,
    inlined from 'bool hex::TaskHolder::hadException() const' at C:\Users\sig\git\ImHex\lib\libimhex\source\api\task.cpp:137:63:
C:/msys64/mingw64/include/c++/12.2.0/bits/atomic_base.h:488:31: error: 'unsigned char __atomic_load_1(const volatile void*, int)' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  488 |         return __atomic_load_n(&_M_i, int(__m));
      |                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/c++/12.2.0/bits/atomic_base.h:488:31: error: 'unsigned char __atomic_load_1(const volatile void*, int)' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
In member function 'std::__atomic_base<_IntTp>::__int_type std::__atomic_base<_IntTp>::load(std::memory_order) const [with _ITp = bool]',
    inlined from 'std::atomic<bool>::operator bool() const' at C:/msys64/mingw64/include/c++/12.2.0/atomic:87:26,
    inlined from 'bool hex::Task::wasInterrupted() const' at C:\Users\sig\git\ImHex\lib\libimhex\source\api\task.cpp:87:22,
    inlined from 'bool hex::TaskHolder::wasInterrupted() const' at C:\Users\sig\git\ImHex\lib\libimhex\source\api\task.cpp:141:65:
C:/msys64/mingw64/include/c++/12.2.0/bits/atomic_base.h:488:31: error: 'unsigned char __atomic_load_1(const volatile void*, int)' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  488 |         return __atomic_load_n(&_M_i, int(__m));
      |                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/c++/12.2.0/bits/atomic_base.h:488:31: error: 'unsigned char __atomic_load_1(const volatile void*, int)' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
In member function 'void std::__atomic_base<_IntTp>::store(__int_type, std::memory_order) [with _ITp = bool]',
    inlined from 'std::__atomic_base<_IntTp>::__int_type std::__atomic_base<_IntTp>::operator=(__int_type) [with _ITp = bool]' at C:/msys64/mingw64/include/c++/12.2.0/bits/atomic_base.h:356:7,
    inlined from 'bool std::atomic<bool>::operator=(bool)' at C:/msys64/mingw64/include/c++/12.2.0/atomic:80:31,
    inlined from 'void hex::Task::interrupt()' at C:\Users\sig\git\ImHex\lib\libimhex\source\api\task.cpp:60:33,
    inlined from 'void hex::TaskHolder::interrupt()' at C:\Users\sig\git\ImHex\lib\libimhex\source\api\task.cpp:146:43:
C:/msys64/mingw64/include/c++/12.2.0/bits/atomic_base.h:464:25: error: 'void __atomic_store_1(volatile void*, unsigned char, int)' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  464 |         __atomic_store_n(&_M_i, __i, int(__m));
      |         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/c++/12.2.0/bits/atomic_base.h:464:25: error: 'void __atomic_store_1(volatile void*, unsigned char, int)' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
cc1plus.exe: all warnings being treated as errors
mingw32-make[2]: *** [lib\libimhex\CMakeFiles\libimhex.dir\build.make:121: lib/libimhex/CMakeFiles/libimhex.dir/source/api/task.cpp.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:1017: lib/libimhex/CMakeFiles/libimhex.dir/all] Error 2
mingw32-make: *** [Makefile:165: all] Error 2`

**Comment by WerWolv** [comment]
Oh this is actually my fault, the CI is failing too and I didn't notice it.

I'm working on a fix right now but in the mean time you might want to build the release version or commit b80517ab159277c360a38ee0220fb3022952b587 instead of the latest commit

**Comment by SigmaStar** [comment]
I also want to know that how to build plugins alone. I mean I just wanna build ImHex once and modify my plugin code and rebuild my plugin. Is that possible?

**Comment by WerWolv** [comment]
Of course yeah. The easiest way is by using the ImHex plugin template: https://github.com/WerWolv/ImHex-Cpp-Plugin-Template

ImHex is included there as a submodule and will just be compiled once at the start. Afterwards when you make changes to your own plugin, it will just recompile your plugin and use it in the pre-built ImHex version
