### ISSUE TITLE
OpenGL 3...

### ISSUE THREAD

**Issue by Microeinstein** [WerWolv/ImHex#77]
Honestly, this project could easily become one of the best hex editors around, but... OpenGL 3!?

Why not using another 2D [backend](https://github.com/ocornut/imgui/tree/master/backends) like SDL or allegro? _Or even OpenGL 2?_

At home I have just one notebook from 2010 that barely supports OpenGL 2.1, _and I really can't afford anything better..._
I sincerely don't understand what requires the usage of OpenGL 3

_...and I don't want to run an hex editor by setting_ `LIBGL_ALWAYS_SOFTWARE=1`

**Comment by Thog** [comment]
Hello,

It should be reminded that this project is being worked on during the free time of WerWolv and I would ask you to keep your manner and be nice.

On the issue itself, I think it's fairly possible to support OpenGL 2 or software rendering one if none is available and will look into it in the future.

Best regards.
