### ISSUE TITLE
[Bug] Modified timestamp not updated on save

### ISSUE THREAD

**Issue by W4RH4WK** [WerWolv/ImHex#778]
### Operating System

Windows

### What's the issue you encountered?

When saving a file, the modified timestamp is not updated.

### How can the issue be reproduced?

1. Take note of a file's timestamps
2. Modify the file using ImHex
3. Observe that the timestamps did not change

### ImHex Version

1.24.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Additional context?

Also happened in 1.23.2.

This is bug is pretty annoying since Git will not recognize changes to the file.

**Comment by iTrooz** [comment]
This seems to be be fixed in the latest nightly (and most probably the release), closing
