### ISSUE TITLE
Opening an empty file and analyzing it using "Analyze current page" crashes the program

### ISSUE THREAD

**Issue by SumanthMehatha** [WerWolv/ImHex#78]
Steps to replicate the crash:
1. Create an empty file. (In my case it was .txt file)
2. Open the ImHex program and then open the empty file using open dialogue within ImHex
3. Click "Analyze current page" to crash the program.

This is not a serious bug as there is no use case but I will let you decide if you want to fix it. 

![crash](https://user-images.githubusercontent.com/20770757/101631311-2785c080-3a4a-11eb-8f50-d004778b856f.gif)

**Comment by PunitSalian** [comment]
Is this issue taken care of ? If not I can take a look. I discovered this project today, it'll be helpful if you give certain pointers for this one.
