### ISSUE TITLE
[Bug] ImHex always says there are unsaved changes

### ISSUE THREAD

**Issue by iTrooz** [WerWolv/ImHex#785]
### Operating System

Linux

### What's the issue you encountered?

ImHex always tells me "You have unsaved changes made to this Provider" (or sometimes "To this project"), even though I saved the file, and it was written to disk

### How can the issue be reproduced?

- Open a file in your local filesystem
- Edit a byte
- Save it
- Try to close ImHex

### ImHex Version

v1.24.3

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by iTrooz** [comment]
Summary of the conversation on discord (https://discord.com/channels/789833418631675954/789833418631675957/1031530044406906891) :
This happens because ImHex uses a "dirty bit" to determine if you made changes, for example editing the file, but also adding patterns, bookmarks... (project related stuff)

A solution would be to create multiple dirty bits, at least one for editing the file, and one for project-related stuff

**Comment by galkinvv** [comment]
Similar problem arises after editing the pattern in Pattern Editor window. ImHex says that there are unsaved changes, but didn't remind that they are in the pattern editor and not in the file itself

**Comment by jakibaki** [comment]
could this be reopened this pretty please? This still appears to be an active issue ^^

**Comment by paxcut** [comment]
I tried the latest build and it seems that the system used to prevent the potential loss of work is working as expected. Each input file opened in ImHex has many associated parts that are too numerous to list so they are identified using the name of the input file as reference. Some of these associated parts are created automatically for you by ImHex, so even if you think you have saved all the changes you made to the project there may still be parts to save you are just unaware of. This issue mentions to such possible ways in which ImHex reminds you about possible loss of work when exiting the app.

In the first scenario, you open an input file, make some edits to the binary content and save the edits over the existing input file in the file system. the edits automatically create an associated patch that allows you to undo them when the patch is saved in the project file so even though the input file changes were saved ImHex will warn you about data loss if you try to exit without saving the project first.

The second scenario involves making changes to the associated pattern in the pattern editor. Each pattern associated with each of the input files is saved in the project so saving the pattern to the hard disk still leaves the project with unsaved changes. When you try to exit ImHex at this point, you will see a message that lists each input file that has changes to either itself or one or more of its associated files. Seeing the name of the input file you may think that Imhex is in error by warning of changes that don't  exist, but the possible associated files are too numerous to list explicitly so changes to them are grouped together using the name of the input file as a reference. 

You should always assume that any changes made during the use of ImHex needs to be saved in the project before exiting and a global shortcut ( Alt-S by default) is provided to save the project quickly which will eliminate any popup messages when you exit ImHex. To reopen this issue, please list the steps needed to reproduce the problem but please try to use the latest nightly build to make sure the problem hasn't been fixed already.

**Comment by iTrooz** [comment]
Can confirm the bug I opened is no longer reproducible on master (dd389db8af66a2128e227eb591bf2da55dec0d52)
@jakibaki Feel free to record a video **on latest nightly** showing the problem/a similar problem, in a short and reproducible way

**Comment by iTrooz** [comment]
Oh.. uh, my bad, I can now reproduce.

**Comment by paxcut** [comment]
I may have missed something because I can't find any description of the problem that hasn't been addressed. If I did, I apologize and please direct me to the place I missed. I'll summarize  what I already explained.

Saving the changes made to a byte in the file does not save the patches created for the modification, so Imhex warns you about that if you exit without saving the project. Making changes to the pattern and saving them to a file does not save the one stored in the project when you exit.

The messages are very explicit about the fact that it is the project that has unsaved changes. First popup is:

<img width="1407" height="423" alt="Image" src="https://github.com/user-attachments/assets/16a2922a-a5ec-40e3-9761-0a6f3c9c2a19" />

If you say yes, you get a second popup comes up:

<img width="1195" height="780" alt="Image" src="https://github.com/user-attachments/assets/cb6edcff-fca6-4b80-a03f-c34aaacde158" />

where the name is only used as a reference to explain that the data that hasn't been saved yet is data associated with that file. I have also verified that doing operations that don't generate any data, like searching or running patterns, allows you to exit ImHHex without popup messages.

**Comment by iTrooz** [comment]
@paxcut Check this PR description for more info: https://github.com/WerWolv/ImHex/pull/2789

But in short, yeah I didn't like prompting the users twice when closing ImHex (one popup should be enough for the user to express their intent). Also, if I just opened a file, edited some bytes, and hit Ctrl+S, I would expect ImHex to not show a confirmation popup at all

@jakibaki Can you give feedback on this PR plz ?

**Comment by paxcut** [comment]
@iTrooz the popups you get are not about saving the provider, they are for saving the project only. if you say yes to the first popup you don't get a second one. if you say you don't want to save the project then the second popup tells you which providers have associated files that are not saved so you can take proper measures. 

> if I just opened a file, edited some bytes, and hit Ctrl+S, I would expect ImHex to not show a confirmation popup at all

then you loose the patches associated with your edits that allows you to undo them later on. ImHex creates data that is stored in prohects automatically and thats what the prompts are about.
