### ISSUE TITLE
[Bug] Crash (stacksmash) when parsing recursive structs

### ISSUE THREAD

**Issue by nonchip** [WerWolv/ImHex#790]
### Operating System

Linux

### What's the issue you encountered?

When parsing a struct such as:
```C
struct Packet {
  u8 type;
  if(type == 10) { // array
    u8 count;
    Packet elements[count];
  }
};
```
the process gets killed (by the kernel? by libc? not sure) due to "stack smashing", i suspect an infinite recursion here:

```
[16:36:10] [INFO]  [main] Welcome to ImHex!
[16:36:11] [INFO]  [main] Native scaling set to: 1.0
*** stack smashing detected ***: terminated
[1]    19971 segmentation fault  imhex-1.24.3.AppImage
```

### How can the issue be reproduced?

1. paste the above struct in the editor.

there is no step 2.

### ImHex Version

1.24.3.AppImage

### ImHex Build Type

- [ ] Nightly or built from sources

**Comment by WerWolv** [comment]
Hi! Thanks for the report
I fixed a verry similar issue a few commits ago. Could you try if the latest nightly works for you? You can download it from the bottom of https://imhex.werwolv.net

**Comment by nonchip** [comment]
just downloaded the latest nightly appimage, which interestingly has the exact same version as far as i could tell, exact same crash:

1. i start `imhex-1.24.3.AppImage some_file.bin`
2. i get rid of all the bajillion windows it vomits over my screen (see https://github.com/WerWolv/ImHex/issues/730#issuecomment-1284126376) to load Layout -> Default
3. i paste the above script verbatim into the pattern editor
4. before even pressing anything like "execute", as soon as i let go of ctrl+v, it crashes:

* stderr:
```
*** stack smashing detected ***: terminated
[1]    31739 segmentation fault  imhex-1.24.3.AppImage some_file.bin
```

* because for some weird reason your nightlies are stripped, gdb only says:
```
Thread 9 "imhex" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 4598]
0x00007ffff64a3e6e in ?? ()
(gdb) bt
#0  0x00007ffff64a3e6e in ?? ()
#1  0x0000000000000000 in ?? ()
```

* strace sees pretty much only `poll`, `recvmsg` and `getpid` calls before just going "killed by SIGSEGV", though then again overflowing the stack wouldn't necessarily show up in the syscalls anyway.

**Comment by WerWolv** [comment]
Latest commit should fix this issue

**Comment by nonchip** [comment]
thanks, will test the new nightly and report back if it still happens tomorrow :P

**Comment by nonchip** [comment]
oh actually, i just realized that (at least since the nightly) actually the "stack smashing detected: terminated" stderr message happens *as soon as i start* ImHex, not when the actual SIGSEGV happens (which is when pasting the recursive struct, and hopefully what you just fixed).

so *something* still misbehaves, gets murderized by the client, and that then doesn't actually do anything bad?

also at various points `libimhex` complains about timing out net requests i never saw or allowed, soooo that's not gonna go well with GDPR, but seems to not be bug-related, just yknow secret telemetry in a project that doesn't even need to know what an IP stack is, always slightly unfun.

**Comment by WerWolv** [comment]
That "secret telemetry" is really just ImHex checking if there's a new update available and loading the latest data that's available on https://github.com/WerWolv/ImHex-Patterns.
If you're worried, the whole API is also open source and available on https://github.com/WerWolv/WerWolvAPI. There's absolutely zero data collection going on so GDPR should not be a concern.

There's probably gonna be a flag you can set to disable all network communication in the future but that's just not there yet.

**Comment by iTrooz** [comment]
@nonchip for the requests at startup stuff, you may want to look at https://github.com/WerWolv/ImHex/issues/794
