### ISSUE TITLE
GLFW Error [65544] : Wayland: Failed to connect to display

### ISSUE THREAD

**Issue by Cvar1984** [WerWolv/ImHex#804]
### Operating System

Artix Linux x86_64

### What's the issue you encountered?
```
[10:16:05] [INFO]  [main] Welcome to ImHex!
[10:16:05] [ERROR] [main] GLFW Error [65544] : Wayland: Failed to connect to display
[10:16:05] [FATAL] [main] Failed to initialize GLFW!
```
i can't connect to the display, and i think im not using wayland, i use **x11**

### ImHex Version

imhex-1.23.2.r28.g86274b8b-1

**Comment by WerWolv** [comment]
Hey!
I can't speak for Artrix but on Arch Linux there are two glfw packages. `glfw-x11` and `glfw-wayland`. If you installed ImHex through a package manager and just spammed through the prompts, it's very likely that you chose the wrong one there by accident. Make sure to uninstall the wayland version and install the x11 version instead
