### ISSUE TITLE
[Bug] Certain invalid keywords will render the pattern language engine unusable until restart

### ISSUE THREAD

**Issue by vulpes2** [WerWolv/ImHex#812]
### Operating System

Linux

### What's the issue you encountered?

Certain invalid keywords like `uint32_t` will render the pattern language engine unusable for the lifetime of that particular provider. The pattern language engine will keep reporting an error on line 1 regardless of the content in the pattern editor once it gets into this state. The only way to fix this is switching to a new provider by closing the file and re-opening it, or restart the application.

Screenshot of the errors:
![](https://user-images.githubusercontent.com/83679347/199275723-3a4a67b6-0d5a-45d7-9780-24f480f34721.png)

### How can the issue be reproduced?

1. Paste the following code block into the pattern editor:
```
#include <std/core.pat>

struct header {
	uint32_t	magic;	
};
```

2. Click on the evaluate button a few times quickly
3. Observe the error reported on line 1
4. Try changing `uint32_t` to `u32`, evaluate the pattern again
5. Observe the persistent error on line 1

### ImHex Version

1.24.3

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Flatpak

**Comment by WerWolv** [comment]
Hey! Thanks for the report

This has fortunately been fixed already in the latest nightly and will be in the next release soon. Until then you can use the latest nightly build from https://imhex.werwolv.net, all the way at the bottom.

**Comment by vulpes2** [comment]
Thanks, glad to see it's already fixed!
