### ISSUE TITLE
[Bug] type::time32_t is always invalid

### ISSUE THREAD

**Issue by vulpes2** [WerWolv/ImHex#813]
### Operating System

Linux

### What's the issue you encountered?

I'm trying to parse a unix timestamp (big endian) and it always shows up as invalid.

### How can the issue be reproduced?

1. Create a new file and type `63 49 E6 59` into the hex editor. This should be 1665787481 in decimal which converts to `2022-10-14 22:44:41`.
2. Try to parse the data with the following pattern snippet:
    ```
    #include <std/core.pat>
    #include <type/time.pat>
    
    std::core::set_endian(std::mem::Endian::Big);
    
    type::time32_t time @ 0x0;
    ```
3. Observe the invalid result

### ImHex Version

1.24.3

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Flatpak

**Comment by WerWolv** [comment]
Fixed in latest ImHex-Patterns commit
