### ISSUE TITLE
[Bug] Error caused by font

### ISSUE THREAD

**Issue by YuroGod** [WerWolv/ImHex#816]
### Operating System

Windows

### What's the issue you encountered?

The program gives an error when setting the font to some Chinese fonts.
Sometimes it makes the program unusable, or even crashes.

### How can the issue be reproduced?

set font to simhei.ttf or yahei consolas hybrid.ttf.
This is a Chinese font.

### ImHex Version

1.24.3

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

### Additional context?

[fonts.zip](https://github.com/WerWolv/ImHex/files/9915296/fonts.zip)

Here are the two fonts that are causing the problem.

**Comment by iTrooz** [comment]
The fonts seems to work now, closing
