### ISSUE TITLE
[Bug] Inconsistent evaluation of multibyte bitfields if marked as big endian

### ISSUE THREAD

**Issue by MmAaXx500** [WerWolv/ImHex#837]
### Operating System

Linux

### What's the issue you encountered?

If the bitfield marked as big endian the Pattern Data tab displays the filed `a` with value 1, but the pattern is evaluated as if the `i` field had the value of 1.

![image](https://user-images.githubusercontent.com/36025825/205174841-7c475850-543f-4bad-ae6e-d858e7f1d7e4.png)

### How can the issue be reproduced?

```
bitfield bf {
    a : 1;
    b : 1;
    c : 1;
    d : 1;
    e : 1;
    f : 1;
    g : 1;
    h : 1;
    i : 1;
    j : 1;
    k : 1;
    l : 1;
    m : 1;
    n : 1;
    o : 1;
    p : 1;
};

struct data {
    be bf q;
    
    if (q.a == 1) {
        u8 should_be_this;
    }
    else if (q.i == 1) {
        u16 not_that;
    }
};

data x @ 0x0;
```

### ImHex Version

1.25.0 453ddaf (github artifact appimage)

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

Appimage

**Comment by julee** [comment]
> ### Operating System
> Linux
> 
> ### What's the issue you encountered?
> If the bitfield marked as big endian the Pattern Data tab displays the filed `a` with value 1, but the pattern is evaluated as if the `i` field had the value of 1.
> 
> ![image](https://user-images.githubusercontent.com/36025825/205174841-7c475850-543f-4bad-ae6e-d858e7f1d7e4.png)
> 
> ### How can the issue be reproduced?
> ```
> bitfield bf {
>     a : 1;
>     b : 1;
>     c : 1;
>     d : 1;
>     e : 1;
>     f : 1;
>     g : 1;
>     h : 1;
>     i : 1;
>     j : 1;
>     k : 1;
>     l : 1;
>     m : 1;
>     n : 1;
>     o : 1;
>     p : 1;
> };
> 
> struct data {
>     be bf q;
>     
>     if (q.a == 1) {
>         u8 should_be_this;
>     }
>     else if (q.i == 1) {
>         u16 not_that;
>     }
> };
> 
> data x @ 0x0;
> ```
> 
> ### ImHex Version
> 1.25.0 [453ddaf](https://github.com/WerWolv/ImHex/commit/453ddaf0d6c87d9b818373cc895c84794dde1ab2) (github artifact appimage)
> 
> ### ImHex Build Type
> * [x]  Nightly or built from sources
> 
> ### Installation type
> Appimage
> 
> ### Additional context?
> _No response_

I tried with this sample, seems using  global big endian with `#pragma endian big` will avoid the bug.
