### ISSUE TITLE
[Bug] crash or exit after a while opening the setting window

### ISSUE THREAD

**Issue by frank-s-liu** [WerWolv/ImHex#846]
### Operating System

Windows

### What's the issue you encountered?

imhex.exe crash or exit 
windows 11 OS
built from sources:
master branch e3f2541fdeacdf36df83842eaad73dee5dc10766 commit

### How can the issue be reproduced?

![crash](https://user-images.githubusercontent.com/70690476/207275488-4f2a22f2-3f43-4cfb-a3b7-d136882397d0.png)
![version](https://user-images.githubusercontent.com/70690476/207276810-497dfe2d-7b19-4fef-a68d-2dd0143dec33.png)

I just want to set the "color theme"，
I found it has a high speed refresh of the settings window
and after a while, this imhex process exit.
i am not sure it is crashed or exit
i don't find a coredump on my pc

i.e. don't need do anything, just open settings window.
     if you put this progrom on background, it may be more easy to reproduce

### ImHex Version

built from sources  e3f2541fdeacdf36df83842eaad73dee5dc10766

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

 mingw32-make -j install

**Comment by WerWolv** [comment]
Hey
Could you provide some more context maybe? Did you have any files open? Did you use other features of ImHex before? How long did you leave it like that?
I left ImHex running in the background for a few hours now and it seems to work just fine for me (also Windows 11) not even the RAM usage changed.

**Comment by frank-s-liu** [comment]
Sent from my iPhoneOn Dec 13, 2022, at 21:36, Nik ***@***.***> wrote:﻿don’t open any files. I just compiled on windows, so the imhex.exe are put in path of $Imhex-src/build/install. So I can double click to run this editor. It works well until I open the “settings” window to set color scheme,  less than 1min can reproduce this issue . Open the setting window and don’t close it and then put it bg 
Hey
Could you provide some more context maybe? Did you have any files open? Did you use other features of ImHex before? How long did you leave it like that?
I left ImHex running in the background for a few hours now and it seems to work just fine for me (also Windows 11) not even the RAM usage changed.

**Comment by frank-s-liu** [comment]
When I open the settings window, this window has a very high/slow refreshing speed . (I mean that I can watch the refreshing. )This behavior is different with imhex-windowsSent from my iPhoneOn Dec 13, 2022, at 21:36, Nik ***@***.***> wrote:﻿
Hey
Could you provide some more context maybe? Did you have any files open? Did you use other features of ImHex before? How long did you leave it like that?
I left ImHex running in the background for a few hours now and it seems to work just fine for me (also Windows 11) not even the RAM usage changed.

**Comment by frank-s-liu** [comment]
I download from here https://github.com/WerWolv/ImHex/releases/tag/v1.25.0
and installed on my pc
it has the same issue.
I record the screen

https://user-images.githubusercontent.com/70690476/207483326-38e7ee51-b029-4166-834b-b153e807c6e4.mp4

today i can reproduce this issue very easy

**Comment by frank-s-liu** [comment]
if i open one file and then open the "setting" window, imhex will cost much gpu,  about 70% in my PC
![graphics](https://user-images.githubusercontent.com/70690476/207505975-d57b9a65-4735-44c6-a884-48c272961839.png)
my gpu has 8G memory, used about 2.3G

**Comment by frank-s-liu** [comment]
every time before running imhex.exe, i will delete this dir "C:\Users\lyysl\AppData\Local\imhex"

**Comment by frank-s-liu** [comment]
i download the release version without gpu, and delete the dir of "~/AppData\Local\imhex"
and run imhex.exe
![nogpu](https://user-images.githubusercontent.com/70690476/207540773-4112b892-7039-42d9-83e0-a5a8e7a2e166.png)

seems no tables/button can be shown

**Comment by WerWolv** [comment]
Okay that issue can happen when you're running out of graphics memory. An easy way to fix it is by disabling unicode support in the `~/AppData\Local\imhex\config\settings.json` file. Look for the `hex.builtin.setting.general.enable_unicode` key in there and change its value from `1` to `0`. Then it should load properly

**Comment by frank-s-liu** [comment]
yes, no GPU release-version works good, but it cost much more cpu (range in 20%~40%)I can not set the language to "Chinese".

**Comment by WerWolv** [comment]
Okay then this is indeed an issue with your GPU. 
ImHex requires proper support for OpenGL 3.0 to run properly. If you don't have a dedicated GPU installed, usually the integrated Intel HD graphics are being used and Intel's drivers for those are really just hit or miss. If you're lucky, everything works just fine, in some cases everything works but you get occasional graphics glitches and in some particulary unlucky cases, like yours here, they just don't work at all.

You can maybe try to update your graphics drivers and hope it fixes the issues partially but besides that, there's really not much I can do here, sorry.
