### ISSUE TITLE
[Bug] Disassembly doesn't start from base offset

### ISSUE THREAD

**Issue by luc0x61** [WerWolv/ImHex#848]
### Operating System

Windows

### What's the issue you encountered?

The disassembly doesn't start from the chosen base offset.
I opened a small Windows/PE .exe and I can't move the start of disassembly as below

![Image 2022-12-21 173308](https://user-images.githubusercontent.com/56227954/208957328-17a8dd14-bc2f-4d8a-9c92-4e7e345a5f78.png)

Note that however, with a 'Selection' the disassembly is **correct**

### How can the issue be reproduced?

1. Open an .exe
2. Select View, Disassembler
3. Enter a 'Position' different from zero
4. The disassembled data keep starting from 0x0

### ImHex Version

1.25.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable Windows package, just extracted

**Comment by WerWolv** [comment]
Hey
The naming of these fields might be a bit misleading. `Base address` referes to the address all addresses in the instructions will be relative to. This is for example useful if you know that a certain part of your binary will be loaded at a specific address into memory so the addresses displayed will be correct.
Instead what you want to do is select the range of bytes you want to disassemble and then check the `Selection` radio box. Currently it just starts to disassemble all instructions starting from address 0x00 of your binary.
I'll see if I can make this a bit more obvious in the UI.

**Comment by luc0x61** [comment]
Oh, I see... Sorry for the wrong report 😊
