### ISSUE TITLE
[Bug] Pattern's `ref` broken in 1.26 as compared to 1.25

### ISSUE THREAD

**Issue by Kein** [WerWolv/ImHex#853]
### Operating System

Windows

### What's the issue you encountered?

Consider this:
```
struct MyStruct {
    char magic[16];
}

fn Assert_Header(ref MyStruct hdr) {
  std::print("{}", hdr.magic); // prints gibberish
  std::assert(hdr.magic == "-==--==--==--==-", "Invalid Header - magic mismatch"); // fails on asserts
};

struct BODY {
	MyStruct Header;
	std::print("{}", Header.magic); // prints valid Magic
	Assert_Header(Header);
}; [[inline]];

BODY data @ 0x00;
```

For some reason structs passed as ref do not point to valid object data in 1.26.x?

### How can the issue be reproduced?

Any test case with `ref` I presume

### ImHex Version

1.26.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by WerWolv** [comment]
Thanks for the report! Latest commit should fix it
