### ISSUE TITLE
[Bug] GLX: Failed to create context: GLXBadFBConfig

### ISSUE THREAD

**Issue by pandasoli** [WerWolv/ImHex#865]
### Operating System

Linux

### What's the issue you encountered?

![image](https://user-images.githubusercontent.com/76575902/211609720-f7c4b7a7-c7c5-40ce-bcdd-86935ca988c7.png)

### How can the issue be reproduced?

I have no idea how to reproduce it, I just ran the program and it happened

### ImHex Version

1.26.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

From the .deb in the website

### Additional context?
My OS:
![image](https://user-images.githubusercontent.com/76575902/211610120-44a3e27c-e661-463a-b4f3-ffe7c2b5e76b.png)

_No response_

**Comment by WerWolv** [comment]
Hey
ImHex draws its entire UI using OpenGL 3.0. Make sure your system has support for this and that your graphics drivers are installed and work correctly.

I also found this workaround here online, no idea though if it works. You can try setting the following env var: `MESA_GL_VERSION_OVERRIDE=4.3`

**Comment by pandasoli** [comment]
@WerWolv I have no much idea about that. Ig OpenGL is installed 'cause I did [this test](https://stackoverflow.com/questions/17768008/how-to-build-install-glfw-3-and-use-it-in-a-linux-project#answer-17772217) and it's working very well.

And btw idk how to set that env var, I tried to put in the program arguments but it didn't work

**Comment by WerWolv** [comment]
Running `export MESA_GL_VERSION_OVERRIDE=4.3` before trying to start ImHex should do it

**Comment by pandasoli** [comment]
Done, it worked, thx! <3
