### ISSUE TITLE
[Bug] MacOS: App is not usable because the window/fonts are too small

### ISSUE THREAD

**Issue by spachner** [WerWolv/ImHex#867]
### Operating System

MacOS

### What's the issue you encountered?

Just installed imhex for the first time on my Mac and the app is not usable because the window/fonts are small

What to do?

spachner

### How can the issue be reproduced?

Install on MacOS

### ImHex Version

1.26

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

brew install --cask imhex

### Additional context?

MacOS 13.0.1

**Comment by WerWolv** [comment]
Hey
This has been a long standing issue that I just can't manage to resolve properly because I don't have a mac myself. 
If you manage to find your way into the Settings (`Help -> Settings -> Interface`), you can change the Window scaling from `Native` to `x2.0` which should make the window look normal.

**Comment by chippey** [comment]
I ran into this too, running OSX 10.15.7.  Had to set Interface to x1.0 to make it look right.

**Comment by WerWolv** [comment]
Yeah that's the exact issue. MacOS lies about the dispay scaling. If you got a retina display it reports twice the scaling as it should. And I have no idea how to detect that.

**Comment by thestumbler** [comment]
I can confirm same thing, but on Ventura 13.1. Setting to x1.0 makes is useable.

**Comment by mgerhardy** [comment]
https://github.com/mgerhardy/vengi/blob/master/src/modules/ui/IMGUIApp.cpp#L275

this might help to reproduce the issue on a linux system.

```sh
	# test dpi related issues on linux with
	xrandr | grep connected | grep -v disconnected | awk '{print $1}'
	xrandr --output <screen-name> --scale 1.6x1.6
```

**Comment by chippey** [comment]
What about for now on Mac, just not attempt to detect screen scaling, and default to 1x, and on the first launch dialog put a message in about changing interface settings if it looks wrong?

**Comment by WerWolv** [comment]
@chippey Doesn't work either sadly because non-retina macs would need 1x and retina macs 2x

**Comment by WerWolv** [comment]
That said, I made a change to ImHex a few days ago that may or may not fix this issue. If you could test the latest nightly, it would be very appreciated

**Comment by chippey** [comment]
> @chippey Doesn't work either sadly because non-retina macs would need 1x and retina macs 2x

Odd, I have a 2015 retina MacBook, but 2x is way too big.  1x looks correct on my retina screen.

**Comment by WerWolv** [comment]
@chippey Okay, then I have absolutely no idea according to what rules macOS reports wrong scaling values. 
Have you tried the latest nightly? Does that work for you?

**Comment by chippey** [comment]
Just tried nightly, still didn't work.  I zapped my preferences and launched, everything was tiny again.

**Comment by WerWolv** [comment]
Hey yeah sorry, somebody else tested my fix a bit earlier and it made things much much worse so I reverted it back again. 
So we're pretty much back on square one again, I have no idea what's happening.
