### ISSUE TITLE
windows release fail to start

### ISSUE THREAD

**Issue by MrdUkk** [WerWolv/ImHex#87]
ImHex_1.5.0_Windows failed to start with unknown exception. OS Windows10 x64 LTSC.

Faulting application name: ImHex.exe, version: 0.0.0.0, time stamp: 0x5fcd43e0
Faulting module name: ImHex.exe, version: 0.0.0.0, time stamp: 0x5fcd43e0
Exception code: 0x40000015
Fault offset: 0x00000000002cb56a
Faulting process id: 0x1b00
Faulting application start time: 0x01d6cf993f6915e6
Faulting application path: C:\ImHex_1.5.0_Windows\ImHex.exe
Faulting module path: C:\ImHex_1.5.0_Windows\ImHex.exe

**Comment by fenginsc** [comment]
Windows7 x64 also fails to start, indicating that this application has requested the runtime to terminate it in an unused way.please contact the aplication's support team for more information.
version:ImHex_1.5.0

**Comment by CoderWannabe** [comment]
I don't want to bother you with a new issue, so I'll append my ImHex starting problem here.
When I double click on the imhex.exe file (release windows 1.6.1, portable folder) I get an error on the ScriptFreeCache entry point of the dynamic link GDI32.dll.
The same error occur after installing the msi of the same package.
My OS is windows 7 64bit. I can provide more infos if someone need it.

**Comment by huettenhain** [comment]
I have installed this in a clean Windows 10 VM for testing, via chocolatey. When launching `imhex.exe`, it does not launch and no errors are displayed; nothing happens. I decided to install Python 3 on the machine. Installing Python 3 lead to installing the VC runtime 2015, v14.0.24215.20170201. After having installed those, launching `imhex.exe` now displays an error message:

![image](https://user-images.githubusercontent.com/11869704/105580589-877fbe80-5d8d-11eb-9083-a70527aff7a2.png)

**Comment by sam9130** [comment]
I actually don't know but there are some reasons .
If you don't use windows 10 original version .
Change you bios setting .
You switch 32 bit to 64 bit but doesn't change bios setting.
Your CMD is not run properly.

**Comment by charlie-x** [comment]
had same issue with the windows build linked from main github page, removing pluginexample.dll and pluginbuilt.dll from plugins folder let imhex load properly

**Comment by WerWolv** [comment]
Something currently is really weird about the plugins. It crashes before my code even ever runs so I suspect Windows is somehow finding those dlls and tries to load them. Of course failing at it. I'll look into it.

@charlie-x It's enough to just delete the example plugin. Deleting pluginbuiltin.dll will remove basically all functionality from ImHex lol

**Comment by WerWolv** [comment]
Okay. The problem was that for whatever reason the plugin was loaded, immediately closed again and then tried to be initialized by ImHex. This only happened when two or more plugins were loaded.
It should be fixed now in the latest commit
