### ISSUE TITLE
[Bug] Can't import Intel Hex File?

### ISSUE THREAD

**Issue by thestumbler** [WerWolv/ImHex#871]
### Operating System

MacOS

### What's the issue you encountered?

Trying to "open other" to read an intel hex file. A file selection dialogue opens up, but I can't select any of my hex files. In fact, I can't select any file, only a directory. I'm afraid to click the whole directory, since I don't know what's going to happen.

### How can the issue be reproduced?

Open Providers
  Intel Hex Provider

Observe file selection window grays out all files, meaning you cannot select an intel hex file.

### ImHex Version

v1.26.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

DMG (building from source failed)

**Comment by WerWolv** [comment]
Hey
Looks like macOS doesn't like wildcard characters in the file picker? The latest commit now manually lists many of the intel hex extensions so it should hopefully work fine now

**Comment by thestumbler** [comment]
Solved my compilation issues. Most was needing to update various libraries on my system. One dependency apparently not pulled in by the process outlined in the instructions was to install `glfw`, which I did using `brew install glfw`. Previous commit I had pulled at the time of my initial post now builds okay ( 03d216f1 or b1cab5cc )

The latest commit 1f6acc10 fails to build with these errors:

```
...
[100%] Building CXX object plugins/builtin/CMakeFiles/builtin.dir/source/ui/hex_editor.cpp.o
[100%] Building CXX object plugins/builtin/CMakeFiles/builtin.dir/source/ui/pattern_drawer.cpp.o
/files/tools/imhex/plugins/builtin/source/ui/pattern_drawer.cpp: In member function 'void hex::plugin::builtin::ui::PatternDrawer::drawArray(pl::ptrn::Pattern&, pl::ptrn::Iteratable&, bool)':
/files/tools/imhex/plugins/builtin/source/ui/pattern_drawer.cpp:636:49: error: 'class pl::ptrn::Pattern' has no member named 'getAttributeArguments'; did you mean 'getAttributeValue'?
  636 |             if (const auto &arguments = pattern.getAttributeArguments("hex::visualize"); !arguments.empty()) {
      |                                                 ^~~~~~~~~~~~~~~~~~~~~
      |                                                 getAttributeValue
/files/tools/imhex/plugins/builtin/source/ui/pattern_drawer.cpp: At global scope:
/files/tools/imhex/plugins/builtin/source/ui/pattern_drawer.cpp:114:14: error: 'void hex::plugin::builtin::ui::{anonymous}::drawVisualizer(const std::vector<std::variant<char, bool, __int128 unsigned, __int128, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, pl::ptrn::Pattern*> >&, pl::ptrn::Pattern&, pl::ptrn::Iteratable&)' defined but not used [-Werror=unused-function]
  114 |         void drawVisualizer(const std::vector<pl::core::Token::Literal> &arguments, pl::ptrn::Pattern &pattern, pl::ptrn::Iteratable &iteratable) {
      |              ^~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [plugins/builtin/CMakeFiles/builtin.dir/source/ui/pattern_drawer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [plugins/builtin/CMakeFiles/builtin.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by WerWolv** [comment]
Make sure to properly update all git submodules. In this case here you forgot to pull the latest changes from the Pattern Language submodule

**Comment by thestumbler** [comment]
Weird, a message I posted here last night has disappeared. Anyway, it is a separate matter, so I will post it as a new issue. Once this new issue is solved, I will be able to confirm this is working on my Mac.

**Comment by thestumbler** [comment]
I can confirm this now works. Running the nightly 1f6acc10 on MacOs Ventura 13.1, I can now see and open Intel hex files. Thanks.
