### ISSUE TITLE
[Bug] No colorized regions in the File view despite using a pattern

### ISSUE THREAD

**Issue by hypercube-software** [WerWolv/ImHex#872]
### Operating System

Windows

### What's the issue you encountered?

I don't see any coloring in the file view depsite the "Pattern Data" view is perflectly working.
The file view remains black and white, I'm using the dark Theme.
Since I saw in the Readme.md the file view is intended to display colorized regions, I think I missed something here, may be a shortcut or something...

### How can the issue be reproduced?

I load any WAV file, load the pattern wav.hexpat, Evaluate and... no colors in the file view.

### ImHex Version

1.26.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by WerWolv** [comment]
That is very strange. It works perfectly fine here
![image](https://user-images.githubusercontent.com/10835354/212063933-d1dad1fb-edd2-41f7-955d-68f1d64a6ea0.png)

Did you modify anything else? Set a base address or changed any settings?

**Comment by hypercube-software** [comment]
![image](https://user-images.githubusercontent.com/8677100/212067559-1f8a9a1e-e3db-479d-a304-fc530d8e03f7.png)

as you can see, nothing. I tried to click on chunkId, the region is selected, but still not colorized

**Comment by WerWolv** [comment]
Oh! Try going into the Settings again. `Help -> Settings -> Hex Editor`. Then click on the color button next to `Selection highlight color`. In there drag the alpha bar (the vertical one at the far right) to about the middle. That should fix it

**Comment by hypercube-software** [comment]
Oh gosh, thanks a lot, I messed around with this at some point :-) My alpha channel was set to 0 !
By the way, thanks for this wonderdfull piece of software man, this is just impressive.

**Comment by WerWolv** [comment]
You're very welcome! Glad it worked :)
