### ISSUE TITLE
[Bug] include with relative files not working for yara files

### ISSUE THREAD

**Issue by PlasmaHH** [WerWolv/ImHex#875]
### Operating System

Linux

### What's the issue you encountered?

When loading yara files that use include directives, relative includes are not processed as relative ones.

### How can the issue be reproduced?

Easiest is possibly: Download official yara rules from the content store. Open yara rules view, select any of the indices, e.g. "offiicial_rules/webshells_index.yar"  click on "match rules" and then you get the error:

`
Error: callback failed to provide include resource: ./webshells/Wshell_fire2013.yar
`

strace -eopenat,chdir shows:

```
[pid 15708] openat(AT_FDCWD, "/home/plasmahh/.local/share/imhex/yara/official_rules/webshells_index.yar", O_RDONLY) = 14
[pid 15708] openat(AT_FDCWD, "./webshells/WShell_APT_Laudanum.yar", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 15708] openat(AT_FDCWD, "./webshells/WShell_ASPXSpy.yar", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 15708] openat(AT_FDCWD, "./webshells/WShell_ChinaChopper.yar", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 15708] openat(AT_FDCWD, "./webshells/WShell_Drupalgeddon2_icos.yar", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 15708] openat(AT_FDCWD, "./webshells/WShell_PHP_Anuna.yar", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 15708] openat(AT_FDCWD, "./webshells/WShell_PHP_in_images.yar", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 15708] openat(AT_FDCWD, "./webshells/WShell_THOR_Webshells.yar", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 15708] openat(AT_FDCWD, "./webshells/Wshell_ChineseSpam.yar", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 15708] openat(AT_FDCWD, "./webshells/Wshell_fire2013.yar", O_RDONLY) = -1 ENOENT (No such file or directory)
```

### ImHex Version

1.26.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

OpenSUSE Tumbleweed

### Additional context?

The error "callback failed to provide include resource:" seems to indicate that the yara compiler was provided an include callback. This seems to be done in view_yara.cpp:194 and the function tries to assemble the filename.

However, upon breaking there, it seems to expect the current filename in userdata, but  inspecting it this is not the case:

![image](https://user-images.githubusercontent.com/1965659/212188514-259b2370-64b2-4f74-871b-ac4c74a39676.png)

I would have expected the string to be "/home/plasmahh/.local/share/imhex/yara/official_rules/webshells_index.yar" ... if you have a look at the hexdump, it looks like the first 16 bytes have been overwritten.

I think the problem is that in the call of yr_compiler_set_include_callback the hex::toUTF8String(...).data() is being passed as the userdata. However toUTF8String returns a temporary std::string which is out of scope after the call. It should probably be a string local to the applyRules function.

**Comment by WerWolv** [comment]
Thank you for the report and looking into it! The latest commit should fix this now

**Comment by PlasmaHH** [comment]
Fastest fix ever, well done.
