### ISSUE TITLE
[Bug] Crash on window resize

### ISSUE THREAD

**Issue by corybsa** [WerWolv/ImHex#883]
### Operating System

Windows 11

### What's the issue you encountered?

ImHex will crash if you resize the window. Only crashes when you resize by grabbing a corner of the window.

### How can the issue be reproduced?

Click and hold any corner of the window and move the mouse around.

### ImHex Version

1.26.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by WerWolv** [comment]
Can't reproduce this myself. Do you have any window managing tools installed that could mess with ImHex?
Also do you have any crash logs you could upload?

**Comment by corybsa** [comment]
The only programs I could think that would be messing with the ImHex process is PowerToys, MSI Afterburner, or RTSS. I can close them and see if that fixes it. In the mean time, I uploaded a log file. There are multiple log files but they all essentially have the same content.

[20230113_160159.log](https://github.com/WerWolv/ImHex/files/10415453/20230113_160159.log)

**Comment by corybsa** [comment]
Rebooted my PC, closed every program that was open and it still happens. I know the exception in the log is not the most helpful, but maybe I can dive into this deeper this weekend.

**Comment by WerWolv** [comment]
If you can attach a debugger and check where exactly it's crashing, I could probably figure out what happened yeah

**Comment by corybsa** [comment]
Welp... I attached a debugger and now it's not crashing anymore lol. I'll close this issue for now. If it crops up again I'll try to get more detailed info before I create an issue. Thanks for the super cool hex editor!

**Comment by WerWolv** [comment]
Well rip. Let's hope it was just some Windows weirdness.
You're very welcome :)
