### ISSUE TITLE
[Bug] Font size slider is greyed out / can't modify

### ISSUE THREAD

**Issue by pcgeek86** [WerWolv/ImHex#885]
### Operating System

Windows

### What's the issue you encountered?

- I've installed ImHex version 1.26.1 on Windows 11 Dev Preview, using the Scoop CLI package manager.
- When I open the **Settings ➡️ Font** tab, the **Font Size** option is greyed out. I can't move the slider.

![image](https://user-images.githubusercontent.com/466713/212571376-5243206d-c3c1-40d0-be93-1528c29ac897.png)

### How can the issue be reproduced?

- Install ImHex on Windows 11, with Scoop package manager
- Open ImHex and try to modify the Font Size option

### ImHex Version

1.26.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Scoop package manager

**Comment by WerWolv** [comment]
Hey
ImHex uses a pixel perfect bitmap font by default. Trying to scale this font would result in it just turning blurry and ugly which is why the font size slider is grayed out by default. To use it you must first select a custom font with the widget above, then you can change it's scaling

**Comment by pcgeek86** [comment]
Thank you for the crazy-quick response, and the awesome software! Maybe consider adding a hover tool-tip, to indicate why the option is greyed out?

**Comment by WerWolv** [comment]
Yeah sure an info tooltip would certainly be nice

**Comment by pcgeek86** [comment]
FYI I tested this out with a custom "Nerd Fonts" font, and it worked great!

```
scoop bucket add nerd-fonts
scoop install sudo
sudo scoop install -g SourceCodePro-NF-Mono
```

![image](https://user-images.githubusercontent.com/466713/212572709-8bc5fbb2-b5d1-41ed-bccc-2fc0f3a091db.png)

**Comment by dshirron2** [comment]
On windows you can use monospace font (https://en.wikipedia.org/wiki/Monospaced_font).
For example Consolas.ttf worked great for me.
