### ISSUE TITLE
[Bug] dnf install imhex => DeprecationWarning: The distutils package is deprecated

### ISSUE THREAD

**Issue by mi-hol** [WerWolv/ImHex#887]
### Operating System

Linux

### What's the issue you encountered?

I tried to install on Ubuntu 22.04.1 LTS (in WSL)

```
dnf install imhex
/usr/lib/python3/dist-packages/dnf/const.py:22: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.sysconfig
/usr/lib/python3/dist-packages/dnf/const.py:22: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  import distutils.sysconfig
Unable to detect release version (use '--releasever' to specify release version)
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".

python3 --version
Python 3.10.6
```

### How can the issue be reproduced?

run above command on a "virgin" install of Ubuntu only with addl installed package dnf

### ImHex Version

1.26.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

dnf package

**Comment by WerWolv** [comment]
Hey
The Fedora packages have been completely revamped since. Could you test the latest build from here?
https://github.com/WerWolv/ImHex/actions/runs/3925476528

Though I can't promise that they will actually work on your setup. They've been built specifically for Fedora 36 and 37 so you should probably use the deb package instead

**Comment by mi-hol** [comment]
> so you should probably use the deb package instead

don't see a deb package mentioned in[ Install.md](https://github.com/WerWolv/ImHex/blob/master/INSTALL.md)
What command would I use?

![image](https://user-images.githubusercontent.com/22799428/212667703-f38c1efb-1d34-439c-bf1e-0f9d06e6ae04.png)

**Comment by WerWolv** [comment]
Same as any other .deb package too. `sudo apt install imhex.deb`

**Comment by mi-hol** [comment]
not that simple :(

```
sudo apt install imhex.deb
[sudo] password for mholzer:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package imhex.deb
E: Couldn't find any package by glob 'imhex.deb'
```

**Comment by WerWolv** [comment]
Basically all these questions you asked are general Linux knowledge and can be easily found through Google. This is not really a help forum for that, it's a bug tracker.
Try following the instructions I gave you and if after that something with ImHex itself still doesn't work, feel free to open a new issue.

**Comment by mi-hol** [comment]
Someone with interest in a good user experience would enhance [Install.md](https://github.com/WerWolv/ImHex/blob/master/INSTALL.md) instead of just closing

**Comment by WerWolv** [comment]
I don't mind adding more information to the install guide but at some point I just need to assume that people already have some knowledge about their system. Especially if the information can easily be found online, the existing sources are absolutely gonna be more helpful than whatever I'd write here. The equivalent to that on Windows would be be having to write a guide on how to open a browser, download a file and double click it which I don't think is particularly useful for anybody.
