### ISSUE TITLE
Split View Multi-File Comparison

### ISSUE THREAD

**Issue by mathaou** [WerWolv/ImHex#89]
I found myself with a corrupted and known good file, and I wanted an easy way to compare them side by side. Opening two files at once and comparing their hex view would be nice. Opening two instances of the program seems a bit clunky.

**Comment by MaybeNotABob** [comment]
I support this idea and would find it useful as well. The ability to sync or unsync panels during the comparison, in addition to differences highlighted in a different colour would be awesome.

**Comment by WerWolv** [comment]
This has been implemented in the `Diff` view
