### ISSUE TITLE
[Bug] Crashes when evaluating pattern with incomplete struct attribute

### ISSUE THREAD

**Issue by mia-is-baka** [WerWolv/ImHex#894]
### Operating System

Windows

### What's the issue you encountered?

If you specify struct attribute without arguments and round brackets and try to evaluate the pattern, ImHex just crashes

### How can the issue be reproduced?

1. Open any file
2. Write pattern like:
```c
struct Test {

} [[format]];

Test test @ 0;
```
3. Try to evaluate it

### ImHex Version

1.26.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI Installer

#### Log

```
[11:51:13] [FATAL] [main] Exception raised: 0xC0000005
Segmentation fault
```

#### Tested on

- Windows 11 22H2
- Windows 10 21H2

**Comment by WerWolv** [comment]
Hey
Thanks for the report! I think I fixed this bug already, could you try downloading the latest nightly release from my website and see if it still happens?
https://imhex.werwolv.net

**Comment by mia-is-baka** [comment]
> Hey Thanks for the report! I think I fixed this bug already, could you try downloading the latest nightly release from my website and see if it still happens? https://imhex.werwolv.net

Oh, that doesn't happen in the latest nightly release. Thanks and sorry!

**Comment by WerWolv** [comment]
Awesome, no problem! Glad it works :)
