### ISSUE TITLE
[Bug] data visualizer only have little endian result

### ISSUE THREAD

**Issue by zzzh** [WerWolv/ImHex#899]
### Operating System

Windows

### What's the issue you encountered?

The result should change by endian setting, as data inspector do, but not.

### How can the issue be reproduced?

Input some hex data and change data visualizer format, change the endian setting ( at bottom of data inspector, which is weird, apparently it should be a switch button in toolbar ), and compare the result with that on data inspector for some format.

### ImHex Version

1.25.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

msi

**Comment by WerWolv** [comment]
This has been implemented since. There's a toggle at the bottom of the hex editor view now

**Comment by lenrik1589** [comment]
As far as I can see, you are using one-byte data type, endianness only applies to multi-byte values, such as u16, float values, etc. as such the toggle is greyed out for you in that ScreenShot, Little/Big-endian does not affect interpretation of individual bits.
