### ISSUE TITLE
RISC-V Support

### ISSUE THREAD

**Issue by kevenv** [WerWolv/ImHex#9]
It would be great if you could support RISC-V.

**Comment by WerWolv** [comment]
Hi. I'm using the Capstone library for disassembling right now. When it adds RISC-V support, I will absolutely add it to ImHex

**Comment by kevenv** [comment]
Ah I see thanks!

**Comment by vazhnov** [comment]
RISCV now is in list of supported architectures in https://github.com/capstone-engine/capstone , probably since 2019: https://github.com/capstone-engine/capstone/pull/1401

**Comment by WerWolv** [comment]
It's been supported for a while, however it never ended up in an official release which would mean bundling and manually compiling it with ImHex which I'd rather avoid to not increase the build time even more
