### ISSUE TITLE
missing function from libpng on windows with MSYS2 build

### ISSUE THREAD

**Issue by vyrus001** [WerWolv/ImHex#90]
Used the MSYS2 dist command for deps, compiled using the MSYS2 makepkg-mingw build script. Exe appears to build find but produces an error about a missing function within libpng upon attempted execution and then promptly crashes.

![t](https://user-images.githubusercontent.com/3194872/101978928-b4c54280-3c0d-11eb-866e-94dc19701cf6.png)

WindowsBuildLabEx                      : 18362.1.amd64fre.19h1_release.190318-1202
WindowsCurrentVersion               : 6.3
WindowsEditionId                         : Professional
WindowsInstallationType              : Client
WindowsInstallDateFromRegistry : 6/19/2020 10:40:53 PM
WindowsProductName                 : Windows 10 Pro

**Comment by Tey** [comment]
You need to copy all the DLL files from the MSYS2 installation which was used to build the application, not just re-using the DLL files that are shipped with the official release (which is built with a non-up-to-date version of MSYS2 it seems). Using the `ntldd` tool, it is possible to find the required DLL files and their location.

For instance, I've used the following commands to put all the required DLL files in the `dist/msys2/pkg/mingw-w64-x86_64-ImHex/mingw64` folder after building the application:
````bash
pacman -S mingw-w64-x86_64-ntldd-git
cd pkg/mingw-w64-x86_64-ImHex/mingw64/
ntldd -R imhex.exe | grep msys64 | sed -E 's/^.*=> ([^ ]+) .*$/\1/' | sort -u | cygpath -f - | xargs -I dll cp -n dll ./
````
(it only works if MSYS2 install path contains the "msys64" string and there is no space character in this path)

On a side note, the original LICENSE file path is wrong in `PKGBUILD`, so `makepkg-mingw -s` ends with an error (although the package folder already contains all the built files when the package build aborts).

**Comment by WerWolv** [comment]
All dlls should be correctly copied over in the releases now
