### ISSUE TITLE
[Bug] Unable to open Motorola S-Record file using Motorola S-Record provider

### ISSUE THREAD

**Issue by KhazAkar** [WerWolv/ImHex#906]
### Operating System

Linux

### What's the issue you encountered?

When I've tried to open s19/srec file, ImHex shows "Failed to open file!'

### How can the issue be reproduced?

1. Generate S19/Srec file
2. Try to load it using S-Record provider in ImHex.

One thing - I'm unable to provide any s19 file for now to give some more info what's going on, but I can say that it was generated using some 'automotive-grade' compiler to compile stuff like vector microsar etc.

### ImHex Version

1.26.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Flatpak (linux) / Portable zip (Windows)

**Comment by WerWolv** [comment]
Hey! I just fixed a bug regarding that, please try if it works now.
Previously ImHex would throw an error if there are any new lines at the end of the file

**Comment by KhazAkar** [comment]
@WerWolv Thanks, now it opens the file, but now what I can see is just quote marks
![image](https://user-images.githubusercontent.com/12693890/214849284-c343eb86-f91e-4488-b4ce-d407d4b7c015.png)

**Comment by WerWolv** [comment]
Quote marks mean that the file didn't specify any bytes for that location. You might need to scroll down or switch the current page at the bottom of the hex editor to see where bytes got written to

**Comment by KhazAkar** [comment]
Thanks a lot for your patience, buddy! :)
