### ISSUE TITLE
Build fails in macOS Ventura

### ISSUE THREAD

**Issue by ghmanoj** [WerWolv/ImHex#910]
### Operating System

MacOS

### What's the issue you encountered?

CMake is identifying the compiler as ``AppleClang`` causing the build to fail.

``
CMake Error at cmake/build_helpers.cmake:339 (message):
  ImHex can only be compiled with GCC or Clang.  AppleClang is not supported.
Call Stack (most recent call first):
  CMakeLists.txt:28 (verifyCompiler)
``

### How can the issue be reproduced?

Build fails when compiling in macOS Ventura.
$ mkdir _build && cd _build
$ cmake ..

### ImHex Version

master 

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

From Git Clone

### Additional context?

Last commit hash 434ced44f068008116647f15df561457b9de3219

**Comment by WerWolv** [comment]
As mentioned in #911, Apple's clang is multiple versions outdated and doesn't support many of the latest C++ features ImHex is using. GCC can however be installed on macOS through homebrew which is able to compile ImHex successfully.

**Comment by gtackett** [comment]
> As mentioned in #911, Apple's clang is multiple versions outdated and doesn't support many of the latest C++ features ImHex is using. GCC can however be installed on macOS through homebrew which is able to compile ImHex successfully.

Hmm. My problem seems to be similar to that of @ghmanoj, although I'm trying to build on Big Sur, and I do have `gcc` et al. installed through **homebrew**. I followed the MacOS build instructions at (https://github.com/WerWolv/ImHex/tree/master/dist/compiling/macos.md). CMake is nevertheless identifying the compiler as AppleClang causing the build to fail.
1. Cloned the repo using git clone https://github.com/WerWolv/ImHex --recurse-submodules
2. Installed all the dependencies using brew bundle --no-lock --file dist/Brewfile
3. Tried to build ImHex itself using the following commands:
cd ImHex
mkdir -p build
cd build
CC=$(brew --prefix llvm)/bin/clang        \
CXX=$(brew --prefix llvm)/bin/clang++     \
OBJC=$(brew --prefix llvm)/bin/clang      \
OBJCXX=$(brew --prefix llvm)/bin/clang++  \
cmake -G "Ninja"                          \
  -DCMAKE_BUILD_TYPE=Release              \
  -DCMAKE_INSTALL_PREFIX="./install"      \
  -DIMHEX_GENERATE_PACKAGE=ON             \
  ..
ninja install
-- Configuring ImHex v1.33.0
CMake Error at cmake/build_helpers.cmake:421 (message):
  ImHex can only be compiled with GCC or Clang.  AppleClang is not supported.
Call Stack (most recent call first):
  CMakeLists.txt:49 (verifyCompiler)

**Comment by gtackett** [comment]
I wonder if [this post](https://stackoverflow.com/q/69957879/8539388 ) on **stackoverflow** explains the problem?

**Comment by gtackett** [comment]
I just needed to `rm CMakeCache.`
