### ISSUE TITLE
[Bug] Simple actions causes ImHex to constantly crash on Windows 10

### ISSUE THREAD

**Issue by ValeriiKim** [WerWolv/ImHex#921]
### Operating System

Windows

### What's the issue you encountered?

Deleting some lines in loaded pattern and evaluation of pattern code after that causes ImHex to crash.

### How can the issue be reproduced?

1. Open the file with HEX data (hexdata.sbd)
2. Load custom pattern `custom_pattern.hexpat`.
3. Delete lines from 47 to 74 in `Pattern Editor`.
4. Click `Auto evaluate` or manually evaluate the pattern.
5. After that the program crashes.

Also this happens not only with the file that attached to this issue.
This bug was also encountered in latest version 1.26.2.
[File and pattern.zip](https://github.com/WerWolv/ImHex/files/10663223/File.and.pattern.zip)

### ImHex Version

1.25.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

### Additional context?

Windows 10 Home edition, 22H2, build 19045.2486.

**Comment by WerWolv** [comment]
Hey! Thanks for the report. 
I can reproduce the crash on the latest release but not on the current dev build. 
Could you try downloading the latest nightly from here and see if it still happens to you? https://github.com/WerWolv/ImHex/actions/runs/4100899156

**Comment by ValeriiKim** [comment]
> Hey! Thanks for the report. I can reproduce the crash on the latest release but not on the current dev build. Could you try downloading the latest nightly from here and see if it still happens to you? https://github.com/WerWolv/ImHex/actions/runs/4100899156

Thanks for quick reply. Currently I have 1.26.2 MSI version, should I uninstall it before installing nightly build?

**Comment by WerWolv** [comment]
No you should be able to just run the MSI installer of the nightly and replace the current version with it

**Comment by ValeriiKim** [comment]
Hmm, it seems like with this nightly build these crashes don't occur, at least I tested with several similar files with data.

**Comment by WerWolv** [comment]
Cool. I fixed various issues with the pattern language and the drawing since so I assume I fixed it with those.
If you still encounter any more issues, let me know.

**Comment by ValeriiKim** [comment]
> Cool. I fixed various issues with the pattern language and the drawing since so I assume I fixed it with those. If you still encounter any more issues, let me know.
Thanks!
So I just can stay now with this nightly build for a while?

**Comment by WerWolv** [comment]
Yeah. I consider the nightlies to usually be at least as stable as the releases, I rarely push unfinished or completely broken changes. 
Once the next version gets released, you will just be able to download that and replace the currently installed nightly with the release
