### ISSUE TITLE
[Bug] Drag Select scrolling to top

### ISSUE THREAD

**Issue by daliang20** [WerWolv/ImHex#924]
### Operating System

Windows

### What's the issue you encountered?

When I try to drag select more than 1 bytes when the start of address is past `0x00000120`, the selection jumps back to near the beginning of the file to where the cursor ends. 

If the address is less than `0x00000120` there is no jump in the selection. 
![StartOfAddress](https://user-images.githubusercontent.com/32944137/217670866-99e805ec-3b94-4efa-99f2-66ef0d96196d.PNG)

Here I started the selection at `0x00000393` and tried to select a few bytes.
![TableJump](https://user-images.githubusercontent.com/32944137/217671027-ce0958de-4499-44ce-b297-c298e14956a4.PNG)

While I'm not sure if this is intended; holding shift at the start and end locations work fine. 

### How can the issue be reproduced?

1. Create a new file
2. Insert at address 0x00; size=0x400;
3. Scroll down near the bottom of the file.
4. Select a data point
5. Drag to next byte

### ImHex Version

1.26.2

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by sehnryr** [comment]
Same issue with the flapak version 1.26.2 on fedora 37.

**Comment by daliang20** [comment]
I think this was fixed with the 1.27.1. 

> Fixed the editing cursor not advancing automatically after the first page of data

**Comment by jozefizso** [comment]
Happens to me on Windows with v1.27.1

**Comment by bg5hfc** [comment]
Happens to me on Windows with v1.27.1
