### ISSUE TITLE
manage to compile and run on MacOS but GUI looks a little weird.

### ISSUE THREAD

**Issue by 7heaven** [WerWolv/ImHex#93]
Characters are way too big for retina display and there's aliasing
![20201213212534](https://user-images.githubusercontent.com/172270/102013227-c59ac300-3d89-11eb-93d5-113b92400f89.jpg)

Operating System: BigSur(11.0.1)
Resolution: default
Hardware: Macbook pro 15"  with touch bar (late 2018)

**Comment by Calinou** [comment]
Maybe it's because ImHex is considered a loDPI application, causing macOS to scale everything by a 2× factor?

**Comment by the-wondersmith** [comment]
For anyone that would like them, I've uploaded the required patches as well as a script to apply them [here](https://gofile.io/d/HXDPsm). Just extract the archive in the same directory as your local copy of the ImHex repo and then run `apply_patches.sh` from the terminal. You should be able to compile as normal after that.

**Comment by viecks** [comment]
> For anyone that would like them, I've uploaded the required patches as well as a script to apply them [here](https://gofile.io/d/HXDPsm). Just extract the archive in the same directory as your local copy of the ImHex repo and then run `apply_patches.sh` from the terminal. You should be able to compile as normal after that.

the patch is broken on the latest master HEAD. maybe a PR is needed for later build.

patching file ./CMakeLists.txt
Hunk #1 FAILED at 10.
Hunk #2 FAILED at 24.
Hunk #3 succeeded at 52 (offset 3 lines).
Hunk #4 FAILED at 99.
3 out of 4 hunks FAILED -- saving rejects to file ./CMakeLists.txt.rej
patching file ./include/helpers/utils.hpp
Hunk #1 succeeded at 88 (offset 27 lines).
patching file ./source/helpers/utils.cpp
patching file ./source/providers/file_provider.cpp
patching file ./source/views/view_strings.cpp
patching file ./source/views/view_tools.cpp
patching file ./source/views/view_hexeditor.cpp
patching file ./source/lang/evaluator.cpp

**Comment by Thog** [comment]
> > For anyone that would like them, I've uploaded the required patches as well as a script to apply them [here](https://gofile.io/d/HXDPsm). Just extract the archive in the same directory as your local copy of the ImHex repo and then run `apply_patches.sh` from the terminal. You should be able to compile as normal after that.
> 
> the patch is broken on the latest master HEAD. maybe a PR is needed for later build.
> 
> patching file ./CMakeLists.txt
> Hunk #1 FAILED at 10.
> Hunk #2 FAILED at 24.
> Hunk #3 succeeded at 52 (offset 3 lines).
> Hunk #4 FAILED at 99.
> 3 out of 4 hunks FAILED -- saving rejects to file ./CMakeLists.txt.rej
> patching file ./include/helpers/utils.hpp
> Hunk #1 succeeded at 88 (offset 27 lines).
> patching file ./source/helpers/utils.cpp
> patching file ./source/providers/file_provider.cpp
> patching file ./source/views/view_strings.cpp
> patching file ./source/views/view_tools.cpp
> patching file ./source/views/view_hexeditor.cpp
> patching file ./source/lang/evaluator.cpp

As of https://github.com/WerWolv/ImHex/commit/310059f2740ccc85333dc77380993631a5d91b49, build on macOS is officially supported, see the README for build instructions.

**Comment by WerWolv** [comment]
This has been improved
