### ISSUE TITLE
[Bug] building with no stacktrace/execinfo fails

### ISSUE THREAD

**Issue by nekopsykose** [WerWolv/ImHex#932]
### Operating System

Linux

### What's the issue you encountered?

building on alpine linux (no backtrace.h, execinfo.h,) fails

### How can the issue be reproduced?

build imhex on a musl-based platform (no execinfo.h in libc) without libexecinfo or similar to provide it

### ImHex Version

1.27.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

self-built

### Additional context?

```
/home/demon/src/aports/testing/imhex/src/ImHex/lib/libimhex/source/helpers/stacktrace.cpp:97:50: error: operator "__has_include" requires a header-name
   97 | #elif defined(HEX_HAS_EXECINFO) && __has_include(BACKTRACE_HEADER)
      |                                                  ^~~~~~~~~~~~~~~~
/home/demon/src/aports/testing/imhex/src/ImHex/lib/libimhex/source/helpers/stacktrace.cpp:125:51: error:operator "__has_include" requires a header-name
  125 | #elif defined(HEX_HAS_BACKTRACE) && __has_include(BACKTRACE_HEADER)
      |                                                   ^~~~~~~~~~~~~~~~
ninja: subcommand failed
```

this happens because these conditionals don't short circuit. so, in the event `defined(HEX_HAS_BACKTRACE)` is false, it still evaluates the `__has_include` and fails because that's not defined.

doing:

```
#elif defined(HEX_HAS_EXECINFO)
#if __has_include(BACKTRACE_HEADER)
```

works

**Comment by nekopsykose** [comment]
(terrible formatting) sample patch that works for me:

```diff
diff --git a/lib/libimhex/source/helpers/stacktrace.cpp b/lib/libimhex/source/helpers/stacktrace.cpp
index b6ee42a..bfc5826 100644
--- a/lib/libimhex/source/helpers/stacktrace.cpp
+++ b/lib/libimhex/source/helpers/stacktrace.cpp
@@ -94,7 +94,8 @@
 
     }
 
-#elif defined(HEX_HAS_EXECINFO) && __has_include(BACKTRACE_HEADER)
+#elif defined(HEX_HAS_EXECINFO)
+    #if __has_include(BACKTRACE_HEADER)
 
     #include BACKTRACE_HEADER
     #include <llvm/Demangle/Demangle.h>
@@ -121,8 +122,10 @@
         }
 
     }
+    #endif
 
-#elif defined(HEX_HAS_BACKTRACE) && __has_include(BACKTRACE_HEADER)
+#elif defined(HEX_HAS_BACKTRACE) 
+    #if __has_include(BACKTRACE_HEADER)
 
     #include BACKTRACE_HEADER
     #include <llvm/Demangle/Demangle.h>
@@ -163,6 +166,7 @@
         }
 
     }
+    #endif
 
 #else
 
```

**Comment by nekopsykose** [comment]
i can just MR that if it's convenient for you

**Comment by WerWolv** [comment]
Huh very interesting that it doesn't short circuit. Thanks for letting me know though, I'll fix in a bit

**Comment by nekopsykose** [comment]
funnily it's touched on in the common case for __has_include: https://gcc.gnu.org/onlinedocs/cpp/_005f_005fhas_005finclude.html

thanks a lot!
