### ISSUE TITLE
[Bug] Bookmark color does not match selected color

### ISSUE THREAD

**Issue by enekochan** [WerWolv/ImHex#934]
### Operating System

MacOS

### What's the issue you encountered?

The color in the bookmark list does not match the color selected in the color picker, it's darker.

![Screenshot-2023-02-14-at-02 36 31](https://user-images.githubusercontent.com/1836845/218616310-7f370fe1-a5e0-4ef6-a894-c8cac564178e.png)

### How can the issue be reproduced?

Create a bookmark and select a color for it in the color picker.

### ImHex Version

1.27.0

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Release dmg file

**Comment by WerWolv** [comment]
This could be an Alpha thing. I think by default, ImGui renders these headers slightly transparent which would cause them to become a bit darker. 
Could you check if they get slightly lighter when switching the theme to Light mode?

**Comment by WerWolv** [comment]
Actually looking at the code again, this was deliberate. The default alpha value is 0.7 and the hover color is slightly lighter so there's an actual distinction between the two. 
So this is more of a styling / usability thing which in my opinion is nice. Does it really matter if the color matches exactly to what you specify? It will greatly reduce the title readability if this was changed.
