### ISSUE TITLE
Example pattern

### ISSUE THREAD

**Issue by Mailaender** [WerWolv/ImHex#94]
Despite the cheat sheet I am not able to write a pattern that actually works. None of the screenshots show a complete one. I would love to contribute some examples for common file formats such as BMP or DOS MZ executable, but I need help.

It seems every line not starting with `#` results in an error:
![image](https://user-images.githubusercontent.com/756669/102024659-97ba7c00-3d93-11eb-959e-f9771d55180f.png)

**Comment by WerWolv** [comment]
Hi! Check out https://github.com/WerWolv/ImHex-Patterns
It has a few patterns to look at available
