### ISSUE TITLE
[Bug]  Window scaling issue after upgrade to 1.27

### ISSUE THREAD

**Issue by ojg78** [WerWolv/ImHex#942]
### Operating System

Windows

### What's the issue you encountered?

After installing the msi update package on Windows 11 the app launches with what looks like low resolution screen settings. Everything is very oversized. I tried to correct by adjusting the scaling in settings to .5 and it made it to small to use and too small to revert the scaling setting. Uninstall and re-install does not change the now tiny window. I tried using the portable package with the same results. Is there a config file or a reg key that can be changed to go back to the defaults so I can at least use the menus to troubleshoot?

Cheers.

### How can the issue be reproduced?

Install 1.2.7 on Windows 11 to update a previous version. Previous version was not uninstalled first.

![Screenshot_20230219_074703](https://user-images.githubusercontent.com/34142206/219948924-a34e8bac-3b8a-4da5-9c0d-ff461bc83ec0.png)

### ImHex Version

1.27

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

MSI

**Comment by WerWolv** [comment]
Hey, could you please try the latest nightly version from https://imhex.werwolv.net? That should have this issue corrected

**Comment by ojg78** [comment]
Updated to the nightly 1.27.1. The display was clear enough to be able to locate the scaling settings and revert to default. It displays fine now but this version until you open the dissembler when it distorts the window and then freezes not allowing any further control. Closing and re-opening resolves the hang and not opening the dissembler keeps it responsive. Seems like maybe a frame rate issue? I will play around with that and see what happens. Maybe we close this and open a new bug for the display distortion issue?

![IMHex_artifacts](https://user-images.githubusercontent.com/34142206/220491322-5e7a124d-8c76-4b35-8fe9-382ec70c1441.png)

**Comment by oladoga** [comment]
i set the scaling to 5X and remove the release and reinstall by your nightly build , the  old config always hold on,  i can't find any config file or item in regedit,  could you tell me how to restore the scaling to normal ,thanks a lot!

**Comment by WerWolv** [comment]
@oladoga It's in `%localappdata%/imhex` on Windows.

That said the latest nightly removed the x3.0 and x4.0 options because they only ever caused issues

**Comment by GitUser200607** [comment]
Is there a way to set scaling like x1.25? Or do I need to open a new issue?
