### ISSUE TITLE
[Bug] patterns do not auto-load

### ISSUE THREAD

**Issue by alphaqueueop** [WerWolv/ImHex#949]
### Operating System

Windows

### What's the issue you encountered?

Patterns do not auto-load; tried `png, pcap, zip`, and do not auto-load when either drag-and-drop file or load via menus. Using `File->Load Pattern` though works fine

### How can the issue be reproduced?

1. boot up imhex
2. drag and drop a file
3. does pattern autoload for extension?

### ImHex Version

1.21.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

portable

### Additional context?

win64 home

**Comment by manokara** [comment]
I think patterns were supposed to be loaded automatically based on their libmagic identification (in `<imhex data folder>/magic`). The mimetype defined in the magic file had to match a `#pragma MIME` in a pattern file. But apparently that is indeed not working, as loading an .exe file doesn't automatically load the `pe` pattern.

**Comment by WerWolv** [comment]
Works fine here.
Make sure to install the default magic file through the Content Store (`Help -> Content Store`) and also please update to a version of ImHex that's not a year old

**Comment by manokara** [comment]
Ah, right. I had the older magic files without extension, that's why ImHex wasn't picking them up.

**Comment by alphaqueueop** [comment]
Ok, I update from pattern repo, not much work still, `DLL` at least worked. Seems to be hexpat file issue. After messing around with Content Store and update everything, reloaded and can no longer type in the hex editor panel? Can only viewing is available
