### ISSUE TITLE
[Bug] can not write in hex editor panel

### ISSUE THREAD

**Issue by alphaqueueop** [WerWolv/ImHex#951]
### Operating System

Windows

### What's the issue you encountered?

can not write bytes in hex editor panel, only way to edit bytes is to use data inspector panel.
 Cant push `0-9` or `A-F` to write any bytes in hex editor panel

### How can the issue be reproduced?

1. drag and drop file
2. type either hex/ascii sides
3. no bytes insert/overwrite, nothing happens

### ImHex Version

1.27.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

portable

### Additional context?

is imhex even an editor or just a data viewer

**Comment by WerWolv** [comment]
Double click a byte cell to enter editing mode
