### ISSUE TITLE
[Bug] The starting position of the struct array is offset by 1

### ISSUE THREAD

**Issue by Demonese** [WerWolv/ImHex#960]
### Operating System

Windows

### What's the issue you encountered?

![image](https://user-images.githubusercontent.com/57629614/222462182-1dcdf417-f47b-4946-ac37-ff4936eb44dd.png)
![image](https://user-images.githubusercontent.com/57629614/222461568-4ea55d63-9087-4b17-b9bc-1101c5925114.png)
![image](https://user-images.githubusercontent.com/57629614/222461850-ddfc680a-104a-432f-9b23-b170e198ff85.png)

### How can the issue be reproduced?

![image](https://user-images.githubusercontent.com/57629614/222463558-0cfd55e5-827c-4853-8cc4-d0364d9bbafa.png)
![image](https://user-images.githubusercontent.com/57629614/222463942-e439488c-09de-481c-8e93-a00ef7959345.png)

### ImHex Version

1.27.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by milochristiansen** [comment]
I also ran into this issue.

Some more information:

* The array I am having trouble with is dynamically sized using `valueOfASizeField / sizeof(theStructType)`. This calculation is working correctly as the next point will demonstrate.
* The array has the correct offsets listed in the Pattern Data pane, and clicking on these offsets will select the correct data region in the hex editor.
* *However* index 0 as listed in the Pattern Data pane is actually index 1, and the final index is past the end of the array data *and* past the reported end offset.
* And, of course, the highlighted fields in the hex editor display the same offset data that the Pattern Data pane does.

**Comment by WerWolv** [comment]
Hey, sorry for the late response. The latest commit should fix this issue
