### ISSUE TITLE
[Bug] Incorrect CRC32 output using std::hash::crc32

### ISSUE THREAD

**Issue by AdrianCassar** [WerWolv/ImHex#961]
### Operating System

Windows

### What's the issue you encountered?

`std::hash::crc32` produces an incorrect CRC32 checksum for a given pattern.

### How can the issue be reproduced?

Pattern

`Data = "123456789"`

```c++
#include <std/io.pat>
#include <std/hash.pat>

u8 Data[9] @ 0x0;

u32 CRC32 = std::hash::crc32(Data, 0xFFFFFFFF, 0x04C11DB7);
std::print("{:x}", CRC32);
```

Output: `0xFC4F2BE9`
Expected: `0xCBF43926`

I'm using [crccalc.com](https://crccalc.com/?crc=123456789&method=crc32&datatype=ascii&outtype=0) to validate the expected result.

### ImHex Version

1.27.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Windows-x86_64.msi

**Comment by john2ksonn** [comment]
Same issue here! ([Screenshot](https://i.imgur.com/JZOmLtD.png))

v1.27.1 on Manjaro Linux

**Comment by WerWolv** [comment]
Latest commit should correct this behaviour and add three new parameters to the `std::hash::crc32` function.

`std::hash::crc32(pattern, 0xFFFFFFFF, 0x4C11DB7, 0xFFFFFFFF, true, true)` now returns the same results as the hash view
