### ISSUE TITLE
[Bug] imhex quit unexpectedly

### ISSUE THREAD

**Issue by zhuher** [WerWolv/ImHex#964]
### Operating System

MacOS

### What's the issue you encountered?

App dies upon being launched.

### How can the issue be reproduced?

1. Follow macos compiling guide
2. Try launching the app
3. ???
4. PROFIT

### ImHex Version

1.27.1

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

git clone this repo + follow macos compiling guide

### Additional context?

<img width="603" alt="image" src="https://user-images.githubusercontent.com/58177432/222971934-e314ede0-90d5-4007-99b2-cfc58602d80f.png">

Process:               imhex [95972]
Path:                  /Applications/imhex.app/Contents/MacOS/imhex
Identifier:            net.WerWolv.ImHex
Version:               1.27 (1.27.1)
Code Type:             ARM-64 (Native)
Parent Process:        zsh [95869]
Responsible:           wezterm-gui [95868]
User ID:               501

Date/Time:             2023-03-05 19:08:27.4818 +0300
OS Version:            macOS 13.2.1 (22D68)
Report Version:        12
Anonymous UUID:        5C1802F0-4AB0-0300-7AA5-10DC21632257

Sleep/Wake UUID:       941CC818-DFDA-4F15-8E99-66B399B058DD

Time Awake Since Boot: 270000 seconds
Time Since Wake:       9379 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Codes:       UNKNOWN_0x32 at 0x00000001009c0000
Exception Codes:       0x0000000000000032, 0x00000001009c0000

Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page

VM Region Info: 0x1009c0000 is in 0x1009c0000-0x100a60000;  bytes after start: 0  bytes before end: 655359
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      dyld private memory         100980000-1009c0000    [  256K] rw-/rwx SM=PRV  
--->  mapped file                 1009c0000-100a60000    [  640K] r--/rwx SM=COW  ...t_id=d02a7a4f
      GAP OF 0x19a4000 BYTES
      mapped file                 102404000-103470000    [ 16.4M] r-x/rwx SM=COW  ...t_id=cee9184f

Thread 0 Crashed:
0   dyld                          	       0x19b3123b0 dyld3::MachOFile::hasMachOMagic() const + 0
1   dyld                          	       0x19b2e96c4 dyld4::SyscallDelegate::mapFileReadOnly(Diagnostics&, char const*, unsigned long*, dyld4::FileID*, bool*, char*) const + 228
2   dyld                          	       0x19b2e9028 dyld4::SyscallDelegate::withReadOnlyMappedFile(Diagnostics&, char const*, bool, void (void const*, unsigned long, bool, dyld4::FileID const&, char const*) block_pointer) const + 88
3   dyld                          	       0x19b2e2184 dyld4::JustInTimeLoader::makeJustInTimeLoaderDisk(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*) + 208
4   dyld                          	       0x19b2d910c invocation function for block in dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&) + 1260
5   dyld                          	       0x19b2d8604 dyld4::Loader::forEachResolvedAtPathVar(dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, dyld4::ProcessConfig::PathOverrides::Type, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) + 776
6   dyld                          	       0x19b2c69b4 dyld4::ProcessConfig::PathOverrides::forEachPathVariant(char const*, dyld3::Platform, bool, bool, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) const + 688
7   dyld                          	       0x19b2d813c dyld4::Loader::forEachPath(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) + 248
8   dyld                          	       0x19b2d888c dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&) + 584
9   dyld                          	       0x19b2e0174 invocation function for block in dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&) + 408
10  dyld                          	       0x19b312b64 invocation function for block in dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const + 148
11  dyld                          	       0x19b2c02d8 dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 296
12  dyld                          	       0x19b3129ac dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const + 172
13  dyld                          	       0x19b2dfec0 dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&) + 164
14  dyld                          	       0x19b2c4500 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 1236
15  dyld                          	       0x19b2c3dc4 start + 2404

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x00000001009c0000   x1: 0x0000000000000000   x2: 0x000000016f6dd2d8   x3: 0x0000000000040002
    x4: 0x0000000000000003   x5: 0x0000000000000000   x6: 0x000000016f6dd2d8   x7: 0x0000000000000860
    x8: 0x000000016f6dd170   x9: 0x000000016f6dd178  x10: 0x000000000100000e  x11: 0x0000000000000001
   x12: 0x000000016f6dd902  x13: 0x0000000000000000  x14: 0x0000000238a1c12a  x15: 0x0000000000008000
   x16: 0x000000000000005c  x17: 0x000000019b2c1e7c  x18: 0x0000000000000000  x19: 0x000000016f6dd800
   x20: 0x0000000000000003  x21: 0x000000016f6dd2af  x22: 0x00000001009c0000  x23: 0x000000016f6dd2d8
   x24: 0x000000016f6dd2b0  x25: 0x000000016f6dd2d0  x26: 0x000000016f6dd770  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016f6dd290   lr: 0x000000019b2e96c4
    sp: 0x000000016f6dd170   pc: 0x000000019b3123b0 cpsr: 0x80001000
   far: 0x00000001009c0000  esr: 0x92000007 (Data Abort) byte read Translation fault

Binary Images:
       0x19b2be000 -        0x19b348ba3 dyld (*) <191e84f1-4b95-39c8-b253-1c1ef56c0fa8> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 4
    thread_create: 0
    thread_set_state: 282

**Comment by WerWolv** [comment]
Hey
I don't think this has anything to do with ImHex but rather something going wrong with your compilation. The instructions for macOS are only for x86 machines so it's possible that you need to do more on ARM computers. I know other people got it to work on ARM before, maybe check the existing issues for more information.
