### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by rajhlinux** [WerWolv/ImHex#968]
### Operating System

Linux

### What's the issue you encountered?

I use Freebsd 13.1

When I set scaling to x5, I'm unable to reset the settings via GUI because it's scaled at x5 and can not locate the drop down menu. It covers the entire display window...

Uninstalling and reinstalling seems to preserve the settings... hence I need to figure out a way to remove the cached settings.

### How can the issue be reproduced?

Set the scaling to x5

### ImHex Version

1.27.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

pkg install imhex

**Comment by WerWolv** [comment]
Hey
The latest nightly of ImHex removes these over-the-top scaling values so that shouldn't happen again. The settings, at least on regular Linux, follow your XDG path settings. So by default they are in `~/.config/imhex/config/settings.json`. Deleting that file should reset it
