### ISSUE TITLE
About string search PR

### ISSUE THREAD

**Issue by qux-bbb** [WerWolv/ImHex#971]
Hi, I found that the last string will not be listed when searching for strings. I modified it, but it was not merged. Is there any problem?  
The PR is https://github.com/WerWolv/ImHex/pull/963  

And if that PR is merged, I can do another fix like this:  
```cpp
-                (settings.m_spaces              && std::isspace(byte))  ||
+                (settings.m_spaces              && (byte == ' ' || byte == '\t'))  ||
                 (settings.m_underscores         && byte == '_')             ||
-                (settings.m_symbols             && std::ispunct(byte))  ||
-                (settings.m_lineFeeds           && byte == '\n');
+                (settings.m_symbols             && std::ispunct(byte) && byte != '\r' && byte != '\n')  ||
+                (settings.m_lineFeeds           && (byte == '\r' || byte == '\n'));
```
`isspace` is not just space  
https://en.cppreference.com/w/cpp/string/byte/isspace  
`ispunct` contains lineFeeds  
https://en.cppreference.com/w/cpp/string/byte/ispunct

**Comment by WerWolv** [comment]
Hey, sorry I thought I merged it yesterday. It looks good to me.

Feel free to make another PR with those suggestions, For spaces though, maybe \v and \f should still count? \n and \r definitely shouldn't though
