### ISSUE TITLE
[Bug] x64 set big endian , leb128 goes wrong

### ISSUE THREAD

**Issue by viruscamp** [WerWolv/ImHex#979]
### Operating System

Windows

### What's the issue you encountered?

The data is `0xbe 0x02`, with native endian little, read it as leb128, I got `318 0x013E`.

After set big endian, I got `18446744073709551678 0x_01_00000000_0000003Eu128` in value column, I think it should only a display error, the actual value is 62, because the next `char str[last_leb128]` looks like be 62 as length. 

### How can the issue be reproduced?

1. Make a 0x140 sized buffer, set first two bytes as `0xbe 0x02`.  
2. Run the pattern:
```cpp
#include <type/leb128.pat>
#include <std/io.pat>
#include <std/string.pat>

#pragma endian big
struct F {
    type::LEB128 len;
    std::print("len={}", len);
    char s[len];
    std::print("length={}", std::string::length(s));
};

F f @ 0;
```
3. You got a wrong output
```
len=18446744073709551678
length=62
```
4. comment out `#pragma endian big`, run again, you will get the right output
```
len=318
length=318
```

### ImHex Version

1.27.1

### ImHex Build Type

- [ ] Nightly or built from sources

### Installation type

Portable

**Comment by viruscamp** [comment]
Yes, I can confirm that `0xbe 0x02` read as leb128 , real value is `62`, display value is `18446744073709551678 `.

**Comment by viruscamp** [comment]
I think that the source reason; Casting Operator does do things right when endian set different to native.
```cpp
#include <std/io.pat>

#pragma endian big

u8 u8_2 = 2;
u64 u64_2 = 2;
u64 u64_2_from_u8 = u64(u8_2);

std::print("u8_2 = {}, u64_2 = {}, u64_2_from_u8 = {}",u8_2, u64_2 , u64_2_from_u8);
```
The output
```
u8_2 = 2, u64_2 = 2, u64_2_from_u8 = 144115188075855872
```

**Comment by WerWolv** [comment]
Thanks for the report! The latest commit should fix the casting issue
