### ISSUE TITLE
using section memory to allocate dynamic arrays fails.

### ISSUE THREAD

**Issue by paxcut** [WerWolv/ImHex#983]
I have some patterns that are not present in file to analyze but their creation can make the parsing so much easier. The patterns have a simple structure, but the main problem is they have an array of integers which varies in size across an array of said structures. I created pattern structures that include the variable number of elements that the particular pattern should have as the first member of the structure. 

I am trying to use sections by allocating space on them, assigning the allocated space the desired values of the patterns and finally placing the array of structures on the assigned allocated space. This appears to work except the actual sizes of the arrays are taken from the values of the file being analyzed even though I am placing the pattern on the section. 

Other than that all the values on the section are transferred to the pattern correctly and if a new input file is used that has the right values where the sizes of the arrays are located then it all works the first time it is run. Further attempts cause immediate CTD with no errors. I am on a windows 10 pc running the latest stable release if ImHex (1.27.1). 

I have created a test pattern file but beware that it must be run on a file that only contains zeroes or you risk freezing your pc for long periods of time or worse. Don't try to run this if you are not sure what it is doing. I have placed comments to explain it the best I can but I will happily answer any questions or comments. 

First, the pattern file. Before you load it open a new file in ImHex, resize it to 0x40 bytes and leave the values as zero. The input file or the pattern file don't need to be saved to disk for this to work.

```c++
#include <std/mem.pat>

// This is what I am trying to implement. the value of n is known only at runtime. 
// The idea is to create a layout of what the structures would look like in memory using 
//  Sections since this pattern never actually occurs in the input file.

struct DynamicArray
{
    u32 n;                        // We will read the values from the section memory
    u32 id;                      // So we create an array of u32's and fill it with the
    u32 array[n];          // values we want them to have including the arrays 
};

// As a test we create two instances of the pattern structure, one with 3 and 
// the other with 8 elements. The first one is 5 u32's (20 bytes) long and the
// second 10 u32's (40 bytes) for  a total of 15 u32's or 60 bytes.

std::mem::Section provider = std::mem::create_section("Memory provider");

u32 allocate[15] @0x00  in provider;

// Fill in the data
// First structure

allocate[0] = 3;
allocate[1] = 0; // index sequentially from zero

//first array

allocate[2]=0x44F8; //random numbers
allocate[3]=0xBE33; allocate[4]=0x54C7;

//Second structure
allocate[5] = 8;
allocate[6] = 1; 

//Second array

allocate[7]=0x7853;    allocate[8]=0xCA67;   allocate[9]=0xE458;  allocate[10]=0x5338;
allocate[11]=0x5677; allocate[12]=0xAE68; allocate[13]=0x0430; allocate[14]=0x0009;

// this is where it all occurs. We create an array of two structures
// and place them on the section that was just created.
DynamicArray test[2] @0x00 in provider;
```
The documentation talks little about whether this can work. After running it i get
![image](https://user-images.githubusercontent.com/53811119/226184114-4f68f5da-0468-4b4b-9517-f908228ee981.png)
It starts off well it reads two double words correctly but sets the sizes of the arrays to zero, so the values of the first array are used as entries of the second structure. That was obtained if the input file is all zeros. If we change the first byte of the input file to be 3 and the 20th byte (at 0x14) to be 8 we get
![image](https://user-images.githubusercontent.com/53811119/226185212-337da395-0c1e-421e-b530-88aa62fe47c4.png)
Now it all appears to work. Clicking run again cause ImHex to crash to desktop very fast. If this is the intended behavior and not a bug maybe drop a few words to explain what I am doing wrong or just not getting at all. What would really help is some way to implement this using ImHex. I can't praise this tool enough, Having only been acquainted with it recently I have seen very quickly how great its design is and I also like what I have seen on how it is implemented although i confess I havent had the chance to look at but a small fraction of the source code. In my opinion this is the best open software i have seen in recent times if not ever. Thank you for your time and kudos to the author for creating it and making it available to all.

-Paxcut

**Comment by paxcut** [comment]
I posted this message for two main reasons.
1) To find how section memory really works. I am still not sure if the current behavior is correct (except the CTD ) or maybe there a bug?
2) To get some tips on how to implement dynamic allocation with things like insert or variable redefinition. Other then non type template parameters i don't see how size value other than zero (the default) can be set and changed at  will. I didn't realize until recently that i could use linked lists if the array sizes are small. Another possibility is to restrict the numeric valuers to consecutive integers  and use base 64 to encode them into strings dynamically. 
peace
Paxcut.

I will keep this open in case there is a bug and I will report back once I get the pattern working.

**Comment by WerWolv** [comment]
Hi! Thanks a lot for the kind words and the report!
I managed to successfully reproduce the issue and I think I fixed it in the latest commit now. Please check if it works better now

**Comment by paxcut** [comment]
thanks for the quick reply. I'm trying to pay in kind but am having issues with the build. it fails on the part that makes the certs. I noticed you changed some code to allow custom certs. do we need to do anything to get the build to complete?
I don't know how else to test your fixes. i am building using msys2 on windows 10 with the latest compilers and tools installed (12.2.0). I'll test it when i get a hold of an updated working build.
Paxcut

**Comment by WerWolv** [comment]
The certificate is normally just bundled into ImHex, you don't need to do anything special besides what you can find in the compile guide under /dist/compiling.

If you just want to test the changes though, you can download pre-built nightly builds on GitHub Actions. There's also links for it at the very bottom of https://imhex.werwolv.net

**Comment by WerWolv** [comment]
It will, yes
