### ISSUE TITLE
[Bug] Files are truncated if you use Save As on themselves

### ISSUE THREAD

**Issue by the-blank-x** [WerWolv/ImHex#987]
### Operating System

Linux

### What's the issue you encountered?

Whenever I try to save a file I opened to itself with Save As, it gets truncated

### How can the issue be reproduced?

1. Open a file
2. Go to FIle > Save As
3. Save to the file you just opened

### ImHex Version

1.27.1 (53afa6ea430bfe1c1bba0e66b5530773e9b4acc4)

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

`imhex-bin` AUR package, but with [the nightly Arch Linux build artifact](https://nightly.link/WerWolv/ImHex/actions/runs/4469256630/ArchLinux%20.pkg.tar.zst%20x86_64.zip) supplied for the PKGBUILD

### Additional context?

Window Manager: sway 1.8.1

https://user-images.githubusercontent.com/45762106/226623494-27f41755-cab6-4bb7-ad28-e4c7b50b4d85.mp4

**Comment by WerWolv** [comment]
Thanks for the report! The latest commit should fix this
