### ISSUE TITLE
Some usability suggestions and questions

### ISSUE THREAD

**Issue by naikrovek** [WerWolv/ImHex#99]
This is such a great tool, and it could be EVEN MORE GREATERER.

1. when I click in the Hex Editor to view some data in the Data Inspector, the Data Inspector updates with the data I selected, as expected.  When I use the arrow keys to move the cursor around, the Data Inspector does not update to display the data under the cursor, which is not expected.  Please update the Data Inspector whenever the cursor moves.
1. Clicking in the Hex Editor, in the ASCII view part should select the same byte in the hexadecimal view, and the Data Inspector should also update.
1. The About dialog doesn't include the version of the application!  This is where one goes to find that information, I thought.  Version, build date, build options (if applicable, a la ffmpeg)
1. The hyperlink in the About dialog isn't a hyperlink.
1. When I click and drag in the Hex Editor, I select the bytes that I've dragged over.  Somewhere there should be information on the offset and size of my selection, using zero-based offset.  If a pattern is recognized that wholly encapsulates the data I've selected, the offset within that pattern should also be displayed.
1. I can't find a way to save the pattern independently of the overall project.  Can that be added?  Sometimes I'm only trying to refine the pattern, and I am using the tool for that purpose only.

Questions:
1. Is your Discord the proper place to discuss this stuff?  I see no channels for this tool.
2. I have a file which is basically an array of Type Length Value (TLV) fields.  I can't find enough information in the cheat sheet in order to write a pattern to find the very first TLV element in the file, and I can't figure out how to define that the root structure of the file is an array of structs.  Can the cheat sheet be updated and/or can that functionality be added?

**Comment by WerWolv** [comment]
Hi! Thanks a lot for the suggestions!

#1 and #2 are actually bugs that I wasn't aware of yet. I'll fix them as soon as I have time.

For #3, you're right that didn't even come to my mind lol

For #4, what hyperlink do you mean? There isn't any afaik.

For #5, that's also a good point just need to find a good place to put it.


I just made a new discord where you can ask questions in, you can find it in the readme.
